Repository airqo-platform/AirQo-frontend, pull requests merged in 2020-09, with the labels that each got.

#124 removing web-admin directory and also the vscode config file
  .gitignore
  netmanager/.gitignore
  web-admin/sample.txt
Labels: chore, ready for review

#139 Changing the title of the Analytics dashboard
  netmanager/src/views/pages/Dashboard/Dashboard.js
Labels: enhancement, ready for review

#136 [NetManager] hotfix for resetting password
  netmanager/src/config/constants.js
Labels: bug, ready for review

#137 Platform landing page
  netmanager/package.json
  netmanager/public/images/auth.jpg
  netmanager/public/images/image-city.jpg
  netmanager/src/App.js
  netmanager/src/config/constants.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/utils/categories.js
  netmanager/src/views/components/SidebarOptions/SidebarOptions.js
  netmanager/src/views/layouts/Landing.js
  netmanager/src/views/layouts/Main/components/Sidebar/Sidebar.js
  netmanager/src/views/pages/SignIn/SignIn.js
  netmanager/src/views/pages/SignUp/Login.js
  netmanager/src/views/pages/SignUp/Register.js
  netmanager/src/views/pages/SignUp/SignUp.js
Labels: ready for review

#134 Adding the data export sidebar item
  netmanager/src/App.js
  netmanager/src/config/constants.js
  netmanager/src/views/layouts/Main/components/Sidebar/Sidebar.js
  netmanager/src/views/pages/Download/index.js
Labels: feature, ready for review

#149 [NetManager] Integrate auth service tenancy
  netmanager/src/App.js
  netmanager/src/redux/Dashboard/constants.js
  netmanager/src/redux/Dashboard/operations.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/redux/Join/reducers/errorReducer.js
  netmanager/src/redux/Join/reducers/orgReducer.js
  netmanager/src/redux/Join/types.js
  netmanager/src/views/layouts/Landing.js
  netmanager/src/views/pages/Dashboard/components/CustomisableChart/CustomisableChart.js
  netmanager/src/views/pages/SignUp/Login.js
  netmanager/src/views/pages/SignUp/Register.js
  netmanager/src/views/pages/SignUp/utils.js
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review
