Repository airqo-platform/AirQo-frontend, pull requests merged in 2021-12, with the labels that each got.

#482 [Website] Website Fixes
  web/application/views/airqo-faqs.php
  web/application/views/airqo-home.php
  web/application/views/lib/footer.php
  web/application/views/lib/header.php
  web/assets/update/css/faq.css
  web/assets/update/css/style-starter.css
Labels: ready for review

#483 [NetManager] Platform Fixes
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/assets/css/pollutant-category.css
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/utils/sites.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/DataDisplay/DeviceManagement.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceLocation.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceOverview.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceQRCode.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/SensorChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/UptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/VoltageChart.js
  netmanager/src/views/components/DataDisplay/Map/MapBoxMap.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Dashboard/components/PollutantCategory/PollutantCategory.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#487 Fix Netmanager Workflow
  .github/workflows/deploy-platform-production.yml
  .github/workflows/deploy-platform-staging.yml
  netmanager/app.yaml
Labels: ready for merge, ready for review

#484 App enhancements
  mobile/README.md
  mobile/assets/icon/onboarding_hash_tag.svg
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/constants/api.dart
  mobile/lib/constants/app_constants.dart
  mobile/lib/main.dart
  mobile/lib/models/email_auth_model.dart
  mobile/lib/models/email_auth_model.g.dart
  mobile/lib/models/historical_measurement.dart
  mobile/lib/models/insights_chart_data.dart
  mobile/lib/models/measurement.dart
  mobile/lib/models/predict.dart
  mobile/lib/models/site.dart
  mobile/lib/models/site.g.dart
  mobile/lib/on_boarding/email_auth_widget.dart
  mobile/lib/on_boarding/phone_auth_widget.dart
  mobile/lib/on_boarding/profile_setup_screen.dart
  mobile/lib/on_boarding/setup_complete_screeen.dart
  mobile/lib/on_boarding/spash_screen.dart
  mobile/lib/on_boarding/welcome_screen.dart
  mobile/lib/screens/change_email_screen.dart
  mobile/lib/screens/dashboard_view.dart
  mobile/lib/screens/email_reauthenticate_screen.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/insights_page.dart
  mobile/lib/screens/map_view.dart
  mobile/lib/screens/phone_reauthenticate_screen.dart
  mobile/lib/screens/settings_page.dart
  mobile/lib/screens/view_profile_page.dart
  mobile/lib/services/fb_notifications.dart
  mobile/lib/services/local_notifications.dart
  mobile/lib/services/local_storage.dart
  mobile/lib/services/native_api.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/share.dart
  mobile/lib/utils/string_extension.dart
  mobile/lib/widgets/analytics_card.dart
  mobile/lib/widgets/buttons.dart
  mobile/lib/widgets/custom_shimmer.dart
  mobile/lib/widgets/favourite_place_card.dart
  mobile/lib/widgets/insights_card.dart
  mobile/lib/widgets/insights_tab_view.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for merge, ready for review

#490 Update deploy-platform-production.yml
  .github/workflows/deploy-platform-production.yml
  .github/workflows/deploy-platform-staging.yml
  workflow-trigger.txt
Labels: ready for merge, ready for review

#492 [NetManager] D3 dashboard
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/public/index.html
  netmanager/src/assets/css/d3/brushed-timeseries.css
  netmanager/src/assets/css/d3/chart-container.scss
  netmanager/src/assets/css/d3/timeseries.css
  netmanager/src/config/urls/analytics.js
  netmanager/src/d3.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/components/d3/BrushedTimeSeries.js
  netmanager/src/views/components/d3/ChartContainer.js
  netmanager/src/views/components/d3/CustomisableChart.js
  netmanager/src/views/components/d3/TimeSeriesChart.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
Labels: work in progress
