Repository airqo-platform/AirQo-frontend, pull requests merged in 2021-07, with the labels that each got.

#282 [NetManager] Migrate to Site Registry
  netmanager/src/AppRoutes.js
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/redux/LocationRegistry/actions.js
  netmanager/src/redux/LocationRegistry/operations.js
  netmanager/src/redux/LocationRegistry/reducers/location.js
  netmanager/src/redux/LocationRegistry/selectors.js
  netmanager/src/redux/LocationRegistry/tests.js
  netmanager/src/redux/LocationRegistry/types.js
  netmanager/src/redux/LocationRegistry/utils.js
  netmanager/src/redux/SiteRegistry/actions.js
  netmanager/src/redux/SiteRegistry/index.js
  netmanager/src/redux/SiteRegistry/operations.js
  netmanager/src/redux/SiteRegistry/reducers/index.js
  netmanager/src/redux/SiteRegistry/reducers/sites.js
  netmanager/src/redux/SiteRegistry/selectors.js
  netmanager/src/redux/Urls/reducers.js
  netmanager/src/redux/Urls/selectors.js
  netmanager/src/redux/index.js
  netmanager/src/utils/dateTime.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceView.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/LocationList/LocationEdit.js
  netmanager/src/views/components/LocationList/LocationRegister.js
  netmanager/src/views/components/LocationList/LocationView.js
  netmanager/src/views/components/LocationList/index.js
  netmanager/src/views/components/Sites/SiteRegistry.js
  netmanager/src/views/components/Sites/SiteToolbar.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/components/Sites/index.js
  netmanager/src/views/components/Table/CustomMaterialTable.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#286 [NetManager] Airqo dashboard
  netmanager/src/config/urls/analytics.js
  netmanager/src/redux/Dashboard/actions.js
  netmanager/src/redux/Dashboard/operations.js
  netmanager/src/redux/Dashboard/reducers/dashboardReducer.js
  netmanager/src/redux/Dashboard/reducers/sitesReducer.js
  netmanager/src/redux/Dashboard/selectors.js
  netmanager/src/utils/categories.js
  netmanager/src/utils/charts.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Dashboard/components/CustomDisplayChart/CustomDisplayChart.js
  netmanager/src/views/pages/Dashboard/components/CustomisableChart/CustomisableChart.js
Labels: ready for review

#289 [NetManager] hottest fix - clashing redux actions
  netmanager/src/redux/Dashboard/actions.js
  netmanager/src/redux/Dashboard/operations.js
  netmanager/src/redux/Dashboard/reducers/sitesReducer.js
  netmanager/src/redux/MapData/operations.js
Labels: ready for review

#290 Website Updates PLAT-588
  web/app.yaml
  web/application/controllers/Apis.php
  web/application/views/airqo-faqs.php
  web/application/views/airqo-partnerships.php
  web/assets/update/js/bootstrap.min.js.map
  web/environments.php
Labels: airqo-website, ready for review

#291 [NetManager] Use device details location details
  netmanager/src/redux/MapData/operations.js
Labels: netmanager, ready for review

#302 [NetManager] Analytics Refactoring
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/config/urls/analytics.js
  netmanager/src/utils/dateTime.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Dashboard/components/CustomDisplayChart/CustomDisplayChart.js
  netmanager/src/views/pages/Dashboard/components/CustomisableChart/CustomisableChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#303 [NetManager] Enable editing site
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/Sites/SiteView.js
Labels: ready for review

#269 Add k8s secrets & Jenkinsfile
  jenkins/platform-prod/Jenkinsfile
  jenkins/platform-stage/Jenkinsfile
  k8s/nginx-ingress/prod-airqo-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-airqo-platform-ingress-resource.yaml
  k8s/platform/.helmignore
  k8s/platform/Chart.yaml
  k8s/platform/charts/.gitkeep
  k8s/platform/prod-airqo-platform-frontend.yaml
  k8s/platform/stage-airqo-platform-frontend.yaml
  k8s/platform/templates/NOTES.txt
  k8s/platform/templates/_helpers.tpl
  k8s/platform/templates/deployment.yaml
  k8s/platform/templates/service.yaml
  k8s/platform/templates/tests/test-connection.yaml
  k8s/platform/values-dev.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  k8s/prod-airqo-platform-frontend.yaml
  k8s/stage-airqo-platform-frontend.yaml
  netmanager/Dockerfile.prod
  netmanager/Dockerfile.stage
  netmanager/nginx.conf
Labels: devops, k8s, ready for review

#325 [NetManager] Enable data export
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Download/Download.js
Labels: ready for review

#324 [NetManager] Hotfix for device pre-deploy testing
  netmanager/src/assets/css/device-registry.css
  netmanager/src/redux/DeviceRegistry/operations.js
  netmanager/src/views/charts/ChartContainer.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceComponents.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceView.js
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#301 website fixes
  web/.gcloudignore
  web/.gitignore
  web/application/controllers/Apis.php
  web/application/views/admin/create-post.php
  web/application/views/admin/edit-post.php
  web/application/views/airqo-blog-single.php
  web/application/views/airqo-home.php
  web/application/views/lib/footer.php
  web/application/views/lib/header.php
  web/assets/ckeditor/css/content-styles.css
  web/assets/images/partners/wehubit.png
  web/docker-compose.yaml
  web/docker/apache/000-default.conf
  web/docker/apache/Dockerfile.dev
  web/docker/mysql/Dockerfile.dev
  web/docker/nginx/Dockerfile
  web/docker/nginx/default.conf
  web/docker/php/Dockerfile
  web/environments.php
  web/index.php
Labels: airqo-website, ready for review, work in progress

#337 [NetManager] Device monitor refactoring
  netmanager/src/config/urls/deviceMonitoring.js
  netmanager/src/redux/DeviceManagement/operations.js
  netmanager/src/redux/DeviceManagement/reducers/devicesUptime.js
  netmanager/src/redux/DeviceManagement/selectors.js
  netmanager/src/redux/DeviceRegistry/operations.js
  netmanager/src/utils/charts.js
  netmanager/src/utils/dateTime.js
  netmanager/src/views/apis/deviceMonitoring.js
  netmanager/src/views/charts/utils.js
  netmanager/src/views/components/DataDisplay/DeviceManagement.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceLocation.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceOverview.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/SensorChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/UptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/VoltageChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/index.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/util.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceView.js
Labels: ready for review

#339 [NetManager] Merge deploy and edit pages
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceToolBar.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceView.js
Labels: ready for review

#340 [NetManager] Fix Graphs not showing not initial load
  netmanager/src/redux/Dashboard/reducers/locationFilterReducer.js
  netmanager/src/redux/Dashboard/reducers/sitesReducer.js
  netmanager/src/redux/Dashboard/reducers/userDefaultGraphsReducer.js
  netmanager/src/redux/DeviceManagement/reducers/devicesStatus.js
  netmanager/src/redux/DeviceManagement/reducers/devicesUptime.js
  netmanager/src/redux/DeviceManagement/reducers/networkUptime.js
  netmanager/src/redux/Join/reducers/authReducer.js
  netmanager/src/redux/Join/reducers/errorReducer.js
  netmanager/src/redux/Join/reducers/orgReducer.js
  netmanager/src/redux/Join/reducers/userReducer.js
  netmanager/src/redux/Maps/reducers.js
  netmanager/src/views/pages/Dashboard/components/CustomisableChart/CustomisableChart.js
Labels: ready for review

#342 [NetManager] Hot fix leaderboard
  netmanager/src/utils/statistics.js
  netmanager/src/views/components/DataDisplay/DeviceManagement.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceOverview.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/SensorChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/UptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/util.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review
