Repository airqo-platform/AirQo-frontend, pull requests merged in 2021-09, with the labels that each got.

#417 [NetManager] GitHub issues 4
  netmanager/src/assets/scss/locate.sass
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/Map/Map.js
Labels: ready for review

#416 Frontend CICD fixes
  .github/workflows/deploy-platform-production.yml
  .github/workflows/deploy-platform-staging.yml
  .gitignore
  k8s/platform/prod-airqo-platform-frontend.yaml
  k8s/platform/stage-airqo-platform-frontend.yaml
  k8s/platform/templates/deployment.yaml
  k8s/platform/values-dev.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  netmanager/Dockerfile.stage
Labels: ready for review, k8s, devops

#415 [NetManager] Install hotjar
  netmanager/public/index.html
Labels: ready for review

#428 Inject frontend envs directly into the pipeline
  .github/workflows/deploy-platform-production.yml
  .github/workflows/deploy-platform-staging.yml
Labels: ready for merge, ready for review, devops

#425 [Website] Website boilerplate
  website/.babelrc
  website/.eslintrc.js
  website/.gitignore
  website/.prettierignore
  website/.prettierrc
  website/README.md
  website/backend/__init__.py
  website/backend/asgi.py
  website/backend/settings.py
  website/backend/urls.py
  website/backend/wsgi.py
  website/bin/functions/general.sh
  website/bin/prettier_fix.sh
  website/bin/tests/check_prettier_errors.sh
  website/frontend/__init__.py
  website/frontend/apps.py
  website/frontend/index.css
  website/frontend/index.js
  website/frontend/migrations/__init__.py
  website/frontend/standaloneIndex.html
  website/frontend/templates/index.html
  website/frontend/urls.py
  website/frontend/views.py
  website/manage.py
  website/package-lock.json
  website/package.json
  website/requirements.txt
  website/tasks/__init__.py
  website/tasks/dev.py
  website/tasks/testing.py
  website/webpack.config.js
  website/webpack.dev.config.js
  website/webpack.fullapp.config.js
Labels: ready for review

#429 [NetManager] GitHub issues 5
  netmanager/src/config/urls/deviceMonitoring.js
  netmanager/src/redux/DeviceManagement/actions.js
  netmanager/src/redux/DeviceManagement/operations.js
  netmanager/src/redux/DeviceManagement/reducers/index.js
  netmanager/src/redux/DeviceManagement/reducers/uptimeLeaderboard.js
  netmanager/src/redux/DeviceManagement/selectors.js
  netmanager/src/utils/customHooks/DeviceManagementHooks.js
  netmanager/src/utils/customHooks/index.js
  netmanager/src/views/apis/deviceMonitoring.js
  netmanager/src/views/components/Copy/Copyable.js
  netmanager/src/views/components/DataDisplay/DeviceManagement.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceLocation.js
  netmanager/src/views/components/DataDisplay/DeviceView/DevicePhotos.js
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#432 [NetManager] Hotfixes
  netmanager/src/redux/DeviceManagement/actions.js
  netmanager/src/redux/DeviceManagement/operations.js
  netmanager/src/redux/DeviceManagement/reducers/devicesUptime.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/charts/utils.js
  netmanager/src/views/components/DataDisplay/DeviceManagement.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceOverviewChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/SensorChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/UptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/VoltageChart.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/pages/ForgotPassword/ForgotPassword.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review

#450 [NetManager] GitHub Issues 6
  netmanager/src/views/components/CustomSelects/OutlinedSelect.js
  netmanager/src/views/components/Dashboard/Overview.js
  netmanager/src/views/components/DataDisplay/DeviceManagement.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
  netmanager/src/views/pages/Dashboard/components/index.js
  netmanager/src/views/pages/Download/Download.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#445 [Website] Backend implementation
  website/backend/FAQ/__init__.py
  website/backend/FAQ/admin.py
  website/backend/FAQ/apps.py
  website/backend/FAQ/migrations/0001_initial.py
  website/backend/FAQ/migrations/__init__.py
  website/backend/FAQ/models.py
  website/backend/FAQ/serializers.py
  website/backend/FAQ/tests.py
  website/backend/FAQ/views.py
  website/backend/career/__init__.py
  website/backend/career/admin.py
  website/backend/career/apps.py
  website/backend/career/migrations/__init__.py
  website/backend/career/models.py
  website/backend/career/serializers.py
  website/backend/career/tests.py
  website/backend/career/views.py
  website/backend/settings.py
  website/backend/team/__init__.py
  website/backend/team/admin.py
  website/backend/team/apps.py
  website/backend/team/migrations/0001_initial.py
  website/backend/team/migrations/0002_auto_20210914_1501.py
  website/backend/team/migrations/__init__.py
  website/backend/team/models.py
  website/backend/team/serializers.py
  website/backend/team/tests.py
  website/backend/team/views.py
  website/backend/urls.py
  website/requirements.txt
  website/webpack.config.js
  website/webpack.dev.config.js
Labels: ready for review

#414 Website Fixes
  web/application/config/routes.php
  web/application/controllers/Airqo.php
  web/application/views/airqo-blog.php
  web/application/views/lib/header.php
Labels: ready for merge, ready for review, airqo-website
