Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-02, with the labels that each got.

#495 Added cross-env pkg to enable cross-platform access of .env file
  netmanager/package-lock.json
  netmanager/package.json
Labels: ready for review

#496 Updated netmanager readme
  netmanager/README.md
Labels: ready for review

#494 [NetManager] D3 integration part 3
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/views/components/d3/BrushedBarChart.js
  netmanager/src/views/components/d3/BrushedTimeSeries.js
  netmanager/src/views/components/d3/ChartContainer.js
  netmanager/src/views/components/d3/CustomisableChart.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Dashboard/components/AddChart.js
Labels: ready for review

#499 Refactor CI/CD
  netmanager/app.yaml
  web/app.yaml
Labels: enhancement, ready for merge, ready for review

#507 Fixed Alignment of maintenance record table
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceLogs.js
Labels: ready for review

#510 Upgrading app dependencies
  mobile/ios/Podfile
  mobile/ios/Podfile.lock
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for merge, ready for review

#513 [NetManager] BigQuery Data Export
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/pages/Download/Download.js
Labels: ready for review
