Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-09, with the labels that each got.

#759 Ft next project init
  .github/dependabot.yml
  .github/workflows/deploy-frontend-to-preview-env.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  .github/workflows/run-tests.yml
  .pre-commit-config.yaml
  k8s/.gitignore
  k8s/netmanager/.helmignore
  k8s/netmanager/Chart.yaml
  k8s/netmanager/charts/.gitkeep
  k8s/netmanager/prod-airqo-platform-frontend.yaml
  k8s/netmanager/stage-airqo-platform-frontend.yaml
  k8s/netmanager/templates/NOTES.txt
  k8s/netmanager/templates/_helpers.tpl
  k8s/netmanager/templates/deployment.yaml
  k8s/netmanager/templates/service.yaml
  k8s/netmanager/templates/tests/test-connection.yaml
  k8s/netmanager/values-dev.yaml
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/prod-airqo-next-platform.yaml
  k8s/platform/stage-airqo-next-platform.yaml
  platform/.babelrc.js
  platform/.dockerignore
  platform/.env.example
  platform/.eslintrc.json
  platform/.gitignore
  platform/.prettierignore
  platform/Dockerfile
  platform/README.md
  platform/cypress.config.js
  platform/cypress/component/ComponentName.cy.js
  platform/cypress/e2e/1-getting-started/todo.cy.js
  platform/cypress/fixtures/example.json
  platform/cypress/plugins/e2e.js
  platform/cypress/spec.js
  platform/cypress/support/commands.js
  platform/cypress/support/component-index.html
  platform/cypress/support/component.js
  platform/cypress/support/e2e.js
  platform/next.config.js
  platform/package.json
  platform/prettier.config.js
  platform/public/.gitkeep
  platform/src/common/styles/global.scss
  platform/src/pages/index.js
  platform/yarn.lock
Labels: ready for merge, ready for review

#788 [Website] Design fixes and QA
  website/frontend/src/icons/press/VoiceOfAfrica.svg
  website/frontend/src/icons/press/WorldEconomicForum.svg
  website/frontend/src/icons/press/XinhuaNet.svg
  website/frontend/src/pages/Press/Press.js
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/AnalyticsSection.scss
  website/frontend/styles/TopBar.scss
Labels: ready for merge

#802 [Website] Update to first and last name values
  website/frontend/src/assets/svg/QR code.svg
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/styles/ExploreData.scss
  website/frontend/styles/Legal.scss
Labels: ready for review

#793 use correct image name
  .github/workflows/deploy-frontends-to-staging.yml
Labels: ready for merge, ready for review

#801 add python auto linter
  .pre-commit-config.yaml
Labels: enhancement, ready for merge, ready for review

#799 Ft absolute imports
  platform/.eslintrc.json
  platform/jsconfig.json
  platform/src/common/components/Footer/.gitkeep
  platform/src/common/components/SideBar/components/Profile/.gitkeep
  platform/src/core/.gitkeep
  platform/src/lib/.gitkeep
Labels: ready for merge, ready for review

#804 [Website] Thorough test of hotfix changes
  website/frontend/src/pages/ExploreData/index.js
Labels: ready for review

#806 disable dependabot updates
  .github/dependabot.yml
Labels: ready for merge, ready for review

#809 [Website] Updates to Highlights schema and frontend design
  website/backend/highlights/admin.py
  website/backend/highlights/migrations/0004_alter_highlight_options_highlight_link_title_and_more.py
  website/backend/highlights/migrations/0005_alter_highlight_options.py
  website/backend/highlights/models.py
  website/frontend/src/components/HighlightsSection/index.js
  website/frontend/src/components/HighlightsSection/post.js
  website/frontend/styles/HighlightsSection.scss
Labels: ready for merge, ready for review

#800 [Legacy Platform] Ft heatmap
  netmanager/src/App.js
  netmanager/src/config/urls/analytics.js
  netmanager/src/config/urls/predict.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/Map/paints.js
  netmanager/src/views/pages/Map/utils.js
Labels: ready for review, netmanager

#808 Sets and updates device deployment status
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#810 [Website] Code refactor
  website/backend/highlights/admin.py
  website/frontend/src/components/HighlightsSection/index.js
  website/frontend/styles/HighlightsSection.scss
Labels: ready for merge, ready for review

#813 [Calibrate x Website]Added api auth
  .github/workflows/deploy-frontend-to-preview-env.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  calibrate/src/views/apis/calibrateTool.js
  website/frontend/apis/index.js
Labels: ready for merge, ready for review

#816 [Calibrate x Website] Web api auth
  calibrate/src/views/apis/calibrateTool.js
  website/frontend/apis/index.js
Labels: ready for merge, ready for review

#811 Updating app versions
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/main.dart
  mobile/lib/models/enum_constants.dart
  mobile/pubspec.yaml
Labels: ready for merge

#818 [Legacy platform] Missing device status fields resolved
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for merge, ready for review

#819 move to production
  .github/workflows/deploy-frontend-to-preview-env.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  calibrate/src/views/apis/calibrateTool.js
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/main.dart
  mobile/lib/models/enum_constants.dart
  mobile/pubspec.yaml
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/components/DataDisplay/Devices.js
  website/frontend/apis/index.js
Labels: ready for review

#821 move to production
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#822 [Website] Partners schema
  website/backend/partners/__init__.py
  website/backend/partners/admin.py
  website/backend/partners/apps.py
  website/backend/partners/migrations/0001_initial.py
  website/backend/partners/migrations/0002_alter_partner_partner_image_alter_partner_type_and_more.py
  website/backend/partners/migrations/__init__.py
  website/backend/partners/models.py
  website/backend/partners/serializers.py
  website/backend/partners/tests.py
  website/backend/partners/views.py
  website/backend/settings.py
  website/backend/urls.py
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/src/pages/Legal/Terms.js
Labels: ready for merge, ready for review

#825 Updating app dependencies
  mobile/android/app/build.gradle
  mobile/android/build.gradle
  mobile/ios/Podfile
  mobile/ios/Podfile.lock
  mobile/lib/services/notification_service.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for merge, ready for review

#824 [Analytics x new] Tailwind css setup
  platform/.eslintrc.json
  platform/package.json
  platform/postcss.config.js
  platform/src/common/styles/global.scss
  platform/src/lib/envConstants.js
  platform/src/pages/_app.jsx
  platform/src/pages/index.js
  platform/src/pages/index.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for merge, ready for review
