Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-04, with the labels that each got.

#566 Changed order of lat/long fields
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/Sites/SiteToolbar.js
Labels: ready for review

#568 [Website] Add Reseacrh page
  website/frontend/App.js
  website/frontend/src/components/Footer.js
  website/frontend/src/icons/research/arrow-right.svg
  website/frontend/src/icons/research/background-shape.svg
  website/frontend/src/icons/research/consult-2.png
  website/frontend/src/icons/research/consult-long.png
  website/frontend/src/icons/research/consult.png
  website/frontend/src/pages/HomePage.js
  website/frontend/src/pages/Page.js
  website/frontend/src/pages/ResearchPage.js
  website/frontend/styles/Footer.scss
  website/frontend/styles/ResearchPage.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
  website/frontend/styles/lib/variables.scss
  website/frontend/utils/customHooks.js
  website/package-lock.json
  website/package.json
  website/webpack.config.js
Labels: ready for review

#562 [Website] Ft website press page
  website/frontend/App.js
  website/frontend/src/components/Footer.js
  website/frontend/src/icons/press/np.svg
  website/frontend/src/pages/Press/Article.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/styles/Press.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
  website/frontend/styles/lib/variables.scss
Labels: ready for review, ui, website-redesign

#564 [Website] Ft tos page
  website/frontend/App.js
  website/frontend/src/components/Footer.js
  website/frontend/src/pages/Legal/Terms.js
  website/frontend/styles/Legal.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review, ui, website-redesign

#570 [Website] Ft communities page
  website/frontend/App.js
  website/frontend/src/assets/img/community/AirQo_arrow_left.svg
  website/frontend/src/assets/img/community/AirQo_blob_fill.svg
  website/frontend/src/assets/img/community/AirQo_quotes.png
  website/frontend/src/assets/img/community/AirQommunities.png
  website/frontend/src/assets/img/community/Rectangle 406.png
  website/frontend/src/assets/img/community/Rectangle 408-1.png
  website/frontend/src/assets/img/community/Rectangle 408.png
  website/frontend/src/assets/img/community/Rectangle 409.png
  website/frontend/src/components/Footer.js
  website/frontend/src/pages/CommunityPage.js
  website/frontend/styles/CommunityPage.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review

#552 [Calibrate] Calibrate App
  calibrate/.eslintrc.js
  calibrate/.gitignore
  calibrate/README.md
  calibrate/package-lock.json
  calibrate/package.json
  calibrate/public/favicon-16x16.png
  calibrate/public/favicon-32x32.png
  calibrate/public/favicon-96x96.png
  calibrate/public/favicon.ico
  calibrate/public/index.html
  calibrate/public/logo192.png
  calibrate/public/logo512.png
  calibrate/public/manifest.json
  calibrate/public/robots.txt
  calibrate/src/App.css
  calibrate/src/App.js
  calibrate/src/App.test.js
  calibrate/src/configs/urls.js
  calibrate/src/configs/utils.js
  calibrate/src/index.css
  calibrate/src/index.js
  calibrate/src/logo.svg
  calibrate/src/reportWebVitals.js
  calibrate/src/setupTests.js
  calibrate/src/styles/calibrate.css
  calibrate/src/views/HomePage.js
  calibrate/src/views/apis/calibrateTool.js
  calibrate/src/views/components/Calibrate.js
  calibrate/src/views/components/TopBar.js
Labels: ready for review

#569 [NetManager] Add date string check
  netmanager/src/utils/dateTime.js
Labels: ready for review

#561 Locate Service Maintenance
  netmanager/src/config/urls/locate.js
  netmanager/src/views/components/Map/Map.js
Labels: ready for review, locate

#536 App refresh indicator
  mobile/.idea/modules.xml
  mobile/lib/screens/analytics_view.dart
  mobile/lib/screens/dashboard_view.dart
  mobile/lib/screens/favourite_places.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/notification_page.dart
  mobile/lib/screens/settings_page.dart
  mobile/lib/widgets/custom_shimmer.dart
  mobile/lib/widgets/insights_tab.dart
Labels: ready for merge

#571 [NetManager] Downgrade to url-loader
  website/webpack.config.js
Labels: ready for review

#575 Updating app packages
  mobile/ios/Podfile
  mobile/ios/Podfile.lock
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for merge, ready for review

#578 [Website] Redesigned API section
  website/frontend/src/assets/img/api-img.png
  website/frontend/src/assets/img/api-section-img.png
  website/frontend/src/components/ApiSection/ApiSection.js
  website/frontend/styles/ApiSection.scss
Labels: ready for review

#581 [Website] Ft contact us page
  website/frontend/App.js
  website/frontend/src/components/Footer.js
  website/frontend/src/pages/ContactUs/ContactForm.js
  website/frontend/src/pages/ContactUs/ContactUs.js
  website/frontend/src/pages/ContactUs/card.js
  website/frontend/src/pages/ContactUs/cards.js
  website/frontend/src/pages/ContactUs/index.js
  website/frontend/styles/ContactUs.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review, website-redesign

#582 [Website] Homepage components CSS refactor
  website/frontend/src/assets/svg/get-app.svg
  website/frontend/src/components/MapSection/MapSection.js
  website/frontend/src/components/get-app/GetApp.js
  website/frontend/styles/GetApp.scss
  website/frontend/styles/Legal.scss
  website/frontend/styles/MapSection.scss
Labels: ready for review, website-redesign

#585 [Website] African Cities Page
  website/frontend/App.js
  website/frontend/src/components/Footer.js
  website/frontend/src/icons/africanCities/background-shape.svg
  website/frontend/src/icons/africanCities/countries/burundi.svg
  website/frontend/src/icons/africanCities/countries/ghana.svg
  website/frontend/src/icons/africanCities/countries/kenya.svg
  website/frontend/src/icons/africanCities/countries/mozambique.svg
  website/frontend/src/icons/africanCities/countries/nigeria.svg
  website/frontend/src/icons/africanCities/countries/senegal.svg
  website/frontend/src/icons/africanCities/countries/uganda.svg
  website/frontend/src/pages/AfricanCitiesPage.js
  website/frontend/styles/AfricanCitiesPage.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review

#584 [Website] Homepage Footer And Hero Section Iteration
  website/frontend/src/components/Footer.js
  website/frontend/src/components/Hero.js
  website/frontend/src/icons/footer/ArrowDown.js
  website/frontend/src/icons/footer/Facebook.js
  website/frontend/src/icons/footer/Instagram.js
  website/frontend/src/icons/footer/Location.js
  website/frontend/src/icons/footer/Twitter.js
  website/frontend/src/icons/footer/Youtube.js
  website/frontend/src/icons/homepage/hero/arrow-down.svg
  website/frontend/src/icons/homepage/hero/location.svg
  website/frontend/src/icons/homepage/hero/reload.svg
  website/frontend/styles/Footer.scss
  website/frontend/styles/Hero.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
  website/frontend/styles/lib/variables.scss
Labels: ready for review

#589 [Website] Page mini component
  website/frontend/src/pages/ContactUs/index.js
  website/frontend/src/pages/PageMini.js
  website/frontend/styles/ContactUs.scss
  website/frontend/styles/index.scss
Labels: ready for merge, ready for review, website-redesign

#590 [Website] Navbar second iteration
  website/frontend/src/components/nav/TopBar.js
  website/frontend/styles/NavTab.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review

#579 [Website] Ft analytics section
  website/frontend/src/assets/img/analytics dashboard.svg
  website/frontend/src/assets/img/analytics-section-img.png
  website/frontend/src/components/AnalyticsSection/AnalyticsSection.js
  website/frontend/styles/AnalyticsSection.scss
Labels: ready for review

#591 Ft get involved
  website/frontend/App.js
  website/frontend/src/components/NotificationBanner.js
  website/frontend/src/components/nav/NavTab.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/GetInvolved/CheckMail.js
  website/frontend/src/pages/GetInvolved/Register.js
  website/frontend/src/pages/GetInvolved/index.js
  website/frontend/styles/GetInvolved.scss
  website/frontend/styles/NotificationBanner.scss
  website/frontend/styles/index.scss
Labels: ready for review

#577 [NetManager] Enable viewing and refreshing of Airqlouds
  netmanager/src/AppRoutes.js
  netmanager/src/assets/css/dropdown.css
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/redux/AirQloud/operations.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/AirQlouds/AirQloudRegistry.js
  netmanager/src/views/components/AirQlouds/AirQloudToolbar.js
  netmanager/src/views/components/AirQlouds/AirQloudView.js
  netmanager/src/views/components/AirQlouds/AirQloudsTable.js
  netmanager/src/views/components/AirQlouds/index.js
  netmanager/src/views/containers/AirQloudDropDown.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#576 App metrics
  mobile/analysis_options.yaml
  mobile/android/app/build.gradle
  mobile/android/build.gradle
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/ios/firebase_app_id_file.json
  mobile/lib/auth/phone_auth_widget.dart
  mobile/lib/constants/api.dart
  mobile/lib/constants/config.dart
  mobile/lib/firebase_options.dart
  mobile/lib/models/event.dart
  mobile/lib/models/user_details.dart
  mobile/lib/on_boarding/profile_setup_screen.dart
  mobile/lib/on_boarding/setup_complete_screeen.dart
  mobile/lib/screens/dashboard_view.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/profile_edit_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/native_api.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/widgets/buttons.dart
  mobile/lib/widgets/insights_tab.dart
  mobile/pubspec.yaml
Labels: ready for merge, ready for review

#596 [Website] Fix webpack staticfiles loading
  website/backend/settings.py
  website/package-lock.json
  website/package.json
  website/webpack.config.js
Labels: ready for review

#597 Fix deployment issue
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .pre-commit-config.yaml
  website/README.md
  website/docker/Dockerfile
  website/docker/docker-compose-dev.yml
  website/webpack.config.js
Labels: hotfix, airqo-website, devops, website-redesign
