Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-10, with the labels that each got.

#832 [website] add missing authorization + PR previews
  .github/workflows/deploy-frontend-to-preview-env.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  website/Dockerfile
  website/README.md
Labels: ready for merge, ready for review, hotfix, airqo-website

#834 Add all available docs
  .github/workflows/deploy-frontends-to-production.yml
  docs/.nojekyll
  docs/README.md
  docs/_coverpage.md
  docs/_media/analytics_customisable_charts_1.png
  docs/_media/analytics_customisable_charts_2.png
  docs/_media/analytics_customisable_charts_3.png
  docs/_media/analytics_customisable_charts_4.png
  docs/_media/analytics_customisable_charts_5.png
  docs/_media/analytics_customisable_charts_6.png
  docs/_media/analytics_download_data.png
  docs/_media/analytics_exceedances.png
  docs/_media/analytics_mean_daily_pm.png
  docs/_media/analytics_region_status_cards.png
  docs/_media/analytics_select_location_1.png
  docs/_media/analytics_select_location_2.png
  docs/_media/extras_account_settings.png
  docs/_media/extras_add_user.png
  docs/_media/extras_feedback_1.png
  docs/_media/extras_feedback_2.png
  docs/_media/extras_feedback_3.png
  docs/_media/extras_feedback_4.png
  docs/_media/extras_settings.png
  docs/_media/join_forgot_password.png
  docs/_media/join_request_access.png
  docs/_media/logo.png
  docs/_navbar.md
  docs/_sidebar.md
  docs/api/README.md
  docs/api/_sidebar.md
  docs/api/devices.md
  docs/api/measurements.md
  docs/api/release_notes.md
  docs/api/sites.md
  docs/api/users.md
  docs/devices.md
  docs/index.html
  docs/login.md
  docs/measurements.md
  docs/mobile_app/README.md
  docs/mobile_app/_sidebar.md
  docs/mobile_app/privacy_policy.md
  docs/mobile_app/release_notes.md
  docs/package.json
  docs/platform/README.md
  docs/platform/_sidebar.md
  docs/platform/analytics.md
  docs/platform/extras.md
  docs/platform/join.md
  docs/sites.md
  k8s/docs/prod-airqo-docs.yaml
  k8s/docs/stage-airqo-docs.yaml
Labels: ready for merge, ready for review

#831 [Legacy platform] Netmanager hotfixes
  netmanager/src/assets/css/copyable.css
  netmanager/src/views/components/Copy/Copyable.js
  netmanager/src/views/layouts/common/Footer.js
  netmanager/src/views/pages/Download/Download.js
Labels: ready for merge, ready for review

#836 [Analytics] Implement analytics navigation
  platform/.eslintrc.json
  platform/jsconfig.json
  platform/next.config.js
  platform/package.json
  platform/public/icons/airqo_logo.svg
  platform/public/icons/arrow_drop_down.svg
  platform/public/icons/bar_chart.svg
  platform/public/icons/help_center.svg
  platform/public/icons/menu_bar.js
  platform/public/icons/notifications.svg
  platform/src/common/components/Footer/.gitkeep
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/common/components/SideBar/components/Profile/.gitkeep
  platform/src/common/components/SideBar/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/lib/windowSize.js
  platform/src/pages/_app.jsx
  platform/src/pages/_document.jsx
  platform/src/pages/analytics/airqlouds.jsx
  platform/src/pages/index.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#837 [Mobile app] Fix feedback functionality
  mobile/lib/blocs/feedback/feedback_bloc.dart
  mobile/lib/blocs/feedback/feedback_event.dart
  mobile/lib/blocs/feedback/feedback_state.dart
  mobile/lib/main.dart
  mobile/lib/models/feedback.dart
  mobile/lib/screens/feedback/feedback_page.dart
  mobile/lib/screens/feedback/feedback_page_widgets.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/services/rest_api.dart
Labels: ready for merge, ready for review

#840 [Legacy platform] Ignores empty device keys
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
Labels: ready for merge, ready for review

#852 [Mobile app] Minor fix - feedback
  mobile/lib/blocs/feedback/feedback_bloc.dart
  mobile/lib/screens/feedback/feedback_page_widgets.dart
Labels: ready for merge

#838 Refactor deploy workflows
  .github/workflows/deploy-frontend-to-preview-env.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  .github/workflows/run-tests.yml
Labels: ready for merge, ready for review

#843 [Website] Ft Partners frontend
  website/backend/partners/serializers.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/Partners/actions.js
  website/frontend/reduxStore/Partners/operations.js
  website/frontend/reduxStore/Partners/reducers.js
  website/frontend/reduxStore/Partners/selectors.js
  website/frontend/reduxStore/index.js
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/src/pages/CareerDetailPage.js
  website/frontend/src/pages/Partners/index.js
  website/frontend/styles/AboutUsPage.scss
  website/frontend/styles/CareersDetailPage.scss
  website/frontend/styles/GetInvolvedModal.scss
  website/frontend/styles/index.scss
Labels: ready for merge, ready for review

#856 Resolved deployment bug
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
Labels: ready for merge, ready for review

#859 [Legacy platform] Added loaders to deploy and recall buttons
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
Labels: ready for merge, ready for review

#858 [Website] fix: members section css
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/styles/AboutUsPage.scss
Labels: ready for merge

#855 Minor fix to loader message #846
  docs/index.html
Labels: ready for review, hacktoberfest-2022, hactoberfest

#861 added favicon in docs
  docs/_media/favicon.png
  docs/index.html
Labels: enhancement, hacktoberfest-2022, hactoberfest

#827 Setting top most card to user's current location
  mobile/ios/Podfile.lock
  mobile/lib/blocs/blocs.dart
  mobile/lib/blocs/dashboard/dashboard_bloc.dart
  mobile/lib/blocs/dashboard/dashboard_event.dart
  mobile/lib/blocs/dashboard/dashboard_state.dart
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/blocs/nearby_location/nearby_location_event.dart
  mobile/lib/constants/api.dart
  mobile/lib/main.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/kya.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/map/map_view.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/on_boarding/welcome_screen.dart
  mobile/lib/screens/search/search_page.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/services/location_service.dart
  mobile/lib/services/native_api.dart
  mobile/lib/services/notification_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/exception.dart
  mobile/lib/widgets/dialogs.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for merge, ready for review

#864 Added Calibrate docs link
  calibrate/.eslintrc.js
  calibrate/src/icons/arrow_long_right.js
  calibrate/src/views/components/TopBar.js
Labels: ready for merge, ready for review

#868 Added favicon to the analytics platform
  platform/public/icons/android-chrome-192x192.png
  platform/public/icons/android-chrome-512x512.png
  platform/public/icons/apple-touch-icon.png
  platform/public/icons/favicon-16x16.png
  platform/public/icons/favicon-32x32.png
  platform/public/icons/favicon.ico
  platform/public/icons/site.webmanifest
  platform/src/pages/_document.jsx
Labels: good first issue, ready for merge, ready for review, hacktoberfest-2022, hacktoberfest

#869 docs : Calibration guide
  docs/_media/airqalibrate_1.png
  docs/_media/airqalibrate_2.png
  docs/_media/airqalibrate_3.png
  docs/_media/ml_based_approach_bam_1.png
  docs/_media/ml_based_approach_bam_2.png
  docs/_media/ml_based_approach_bam_3.png
  docs/_sidebar.md
  docs/api/README.md
  docs/api/release_notes.md
  docs/calibration/README.md
  docs/calibration/_sidebar.md
  docs/calibration/airqalibrate.md
  docs/calibration/ml_based_approach.md
  docs/index.html
  docs/platform/analytics.md
Labels: documentation, good first issue, ready for merge, ready for review, calibration, hacktoberfest-2022, hacktoberfest

#874 Fix Dashboard-Bloc-provider error and Code Cleanup
  mobile/lib/app_config.dart
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/main_dev.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/feedback/feedback_page.dart
  mobile/lib/screens/feedback/feedback_page_widgets.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/widgets/dialogs.dart
Labels: ready for review

#873 Added calibrate app mentions
  CONTRIBUTING.md
  README.md
Labels: documentation, good first issue, ready for merge, ready for review, hacktoberfest-2022, hacktoberfest

#877 [Legacy] Corrected aqi label
  netmanager/src/assets/css/overlay-map.css
  netmanager/src/views/pages/Map/OverlayMap.js
  platform/.gitignore
Labels: ready for merge, ready for review

#881 FIX api-authentication
  mobile/packages/airqo_api/lib/src/airqo_api_client.dart
Labels: ready for merge, ready for review

#883 Fixes deploy button issue
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
Labels: ready for merge, ready for review

#880 Add "Edit on GitHub" feature on the AirQo Docs
  docs/index.html
Labels: documentation, ready for merge, ready for review, hacktoberfest-2022, hacktoberfest

#892 [Website] Ft highlights loader
  website/frontend/src/components/HighlightsSection/index.js
  website/frontend/styles/Errors.scss
Labels: ready for merge, ready for review

#888 Deploy to production:manual workflow trigger
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-k8s-changes-to-production.yml
Labels: ready for merge, ready for review, devops

#895 Mob feedback endpoint
  mobile/lib/constants/api.dart
  mobile/lib/constants/config.dart
  mobile/lib/services/rest_api.dart
Labels: ready for merge, ready for review, mobile-app

#904 [Legacy Platform] Robust map views
  netmanager/.eslintrc.js
  netmanager/.eslintrc.json
  netmanager/.prettierrc.json
  netmanager/src/assets/css/overlay-map.css
  netmanager/src/assets/img/icons/airqo_logo.png
  netmanager/src/utils/setAuthToken.js
  netmanager/src/views/layouts/Landing.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/Map/utils.js
Labels: ready for merge, ready for review

#900 env file sample and readme changes
  website/.env.sample
  website/README.md
Labels: documentation, good first issue, ready for merge, ready for review, hacktoberfest-2022, hacktoberfest

#897 Fix Calibrate App .env.sample and update README.md
  calibrate/.env.sample
  calibrate/README.md
Labels: documentation, enhancement, good first issue, ready for merge, ready for review, hacktoberfest-2022, hacktoberfest

#898 move to production
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-k8s-changes-to-production.yml
  calibrate/.env.sample
  calibrate/README.md
  docs/index.html
  mobile/lib/constants/api.dart
  mobile/lib/constants/config.dart
  mobile/lib/services/rest_api.dart
  mobile/packages/airqo_api/lib/src/airqo_api_client.dart
  netmanager/.eslintrc.js
  netmanager/.eslintrc.json
  netmanager/.prettierrc.json
  netmanager/src/assets/css/overlay-map.css
  netmanager/src/assets/img/icons/airqo_logo.png
  netmanager/src/utils/setAuthToken.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/layouts/Landing.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/Map/utils.js
  website/.env.sample
  website/README.md
  website/frontend/src/components/HighlightsSection/index.js
  website/frontend/styles/Errors.scss
Labels: ready for review

#908 [Legacy Platform] Correct sensor validations and fixed deployment
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
Labels: ready for merge, ready for review

#907 Refactored service name and job name while removing netmanager preview
  .github/workflows/remove-deploy-previews.yml
Labels: ready for merge, ready for review, hotfix, hacktoberfest-2022, hacktoberfest

#899 fix: Fix GitHub workflows to upgrade deprecated set-output
  .github/workflows/dart-code-metrics.yaml
  .github/workflows/deploy-frontend-to-preview-env.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/deploy-k8s-changes-to-production.yml
  .github/workflows/deploy-k8s-changes-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  .github/workflows/run-tests.yml
Labels: good first issue, ready for merge, ready for review, devops, hacktoberfest-2022, hacktoberfest

#890 Update README.md with correct info
  README.md
Labels: enhancement, good first issue, hacktoberfest-2022, hacktoberfest
