Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-05, with the labels that each got.

#595 Ft get involved
  website/frontend/src/pages/GetInvolved/Register.js
  website/frontend/src/pages/GetInvolved/index.js
  website/frontend/styles/GetInvolved.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review

#598 Ft communities page
  website/frontend/src/assets/img/community/Communities Star.svg
  website/frontend/src/pages/CommunityPage.js
  website/frontend/styles/CommunityPage.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review

#602 [Website] Ft mega menu
  website/frontend/src/assets/svg/Close.svg
  website/frontend/src/assets/svg/Menu.svg
  website/frontend/src/components/NotificationBanner.js
  website/frontend/src/components/nav/NavTab.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/styles/NavTab.scss
  website/frontend/styles/NotificationBanner.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/lib/colors.scss
  website/webpack.config.js
Labels: ready for review

#601 App maintenance [Sprint 8]
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/constants/config.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/on_boarding/spash_screen.dart
  mobile/lib/screens/about_page.dart
  mobile/lib/screens/analytics_view.dart
  mobile/lib/screens/dashboard_view.dart
  mobile/lib/screens/favourite_places.dart
  mobile/lib/screens/insights_page.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/search_page.dart
  mobile/lib/screens/web_view_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/local_storage.dart
  mobile/lib/utils/data_formatter.dart
  mobile/lib/utils/dialogs.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/widgets/custom_shimmer.dart
  mobile/lib/widgets/insights_tab.dart
  mobile/pubspec.yaml
Labels: ready for merge, ready for review

#607 [Website] Home page iterations 2.0
  website/frontend/src/assets/svg/android_play_store.svg
  website/frontend/src/assets/svg/apple_app_store.svg
  website/frontend/src/components/ApiSection/ApiSection.js
  website/frontend/src/components/MapSection/MapSection.js
  website/frontend/src/components/get-app/GetApp.js
  website/frontend/styles/AirQommunitiesSection.scss
  website/frontend/styles/ApiSection.scss
  website/frontend/styles/GetApp.scss
  website/frontend/styles/MapSection.scss
  website/frontend/styles/NewsletterSection.scss
  website/frontend/styles/TopBar.scss
Labels: ready for review

#610 [Website] About Us Mobile responsive
  website/frontend/src/assets/img/about_us_vector_3.png
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/styles/AboutUsPage.scss
Labels: ready for review

#614 Home page fixes
  website/frontend/src/components/AirQommunitiesSection/AirQommunitiesSection.js
  website/frontend/src/components/AnalyticsSection/AnalyticsSection.js
  website/frontend/src/components/ApiSection/ApiSection.js
  website/frontend/src/components/MapSection/MapSection.js
  website/frontend/src/components/Monitor.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/Page.js
  website/frontend/src/pages/PageMini.js
  website/frontend/styles/AirQommunitiesSection.scss
  website/frontend/styles/AnalyticsSection.scss
  website/frontend/styles/NavTab.scss
  website/frontend/styles/TopBar.scss
Labels: ready for review

#613 [Website] Fixed image positioning for about-us mobile
  website/frontend/styles/AboutUsPage.scss
Labels: ready for review

#615 App maintenance [Sprint 9]
  mobile/assets/i18n/en.json
  mobile/assets/i18n/lug.json
  mobile/ios/Podfile
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/auth/email_auth_widget.dart
  mobile/lib/main.dart
  mobile/lib/screens/kya/kya_title_page.dart
  mobile/lib/screens/search_page.dart
  mobile/lib/services/native_api.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/utils/pm.dart
  mobile/lib/widgets/analytics_card.dart
  mobile/lib/widgets/buttons.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review

#609 [Calibrate] Integrate Calibrate tool API
  calibrate/package-lock.json
  calibrate/package.json
  calibrate/src/configs/urls.js
  calibrate/src/views/components/Calibrate.js
Labels: ready for review

#529 Ft device update errors
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/Sites/SiteView.js
Labels: ready for merge, ready for review, priority-high
