Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-06, with the labels that each got.

#612 [Website] Airqloud summary and Newsletter API integrations
  calibrate/public/index.html
  website/.babelrc
  website/backend/settings.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/assets/favicon-16x16.png
  website/frontend/assets/favicon-32x32.png
  website/frontend/assets/favicon-96x96.png
  website/frontend/assets/favicon.ico
  website/frontend/config/urls.js
  website/frontend/config/utils.js
  website/frontend/reduxStore/AirQlouds/actions.js
  website/frontend/reduxStore/AirQlouds/operations.js
  website/frontend/reduxStore/AirQlouds/reducers.js
  website/frontend/reduxStore/AirQlouds/selectors.js
  website/frontend/reduxStore/Newsletter/actions.js
  website/frontend/reduxStore/Newsletter/operations.js
  website/frontend/reduxStore/Newsletter/reducers.js
  website/frontend/reduxStore/Newsletter/selectors.js
  website/frontend/reduxStore/index.js
  website/frontend/reduxStore/utils.js
  website/frontend/src/components/Footer.js
  website/frontend/src/components/NewsletterSection/NewsletterSection.js
  website/frontend/src/icons/footer/cancel.svg
  website/frontend/store.js
  website/frontend/styles/Footer.scss
  website/frontend/styles/NewsletterSection.scss
  website/frontend/templates/index.html
  website/package-lock.json
  website/package.json
Labels: ready for review

#636 add new build variables
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .gitignore
  website/README.md
  website/docker/Dockerfile
  website/docker/docker-compose-dev.yml
Labels: ready for merge, ready for review, devops

#625 [Calibrate] Hotfix - Add standard pollutant mappers
  calibrate/src/views/components/Calibrate.js
Labels: ready for review

#641 Fix docker ENV typo
  website/README.md
  website/docker/Dockerfile
Labels: enhancement, ready for merge, ready for review, hotfix

#635 [Website] Mega menu
  website/frontend/src/components/nav/TopBar.js
  website/frontend/styles/NavTab.scss
  website/frontend/styles/TopBar.scss
  website/package-lock.json
Labels: ready for review

#637 [Website] hero section
  website/frontend/src/assets/img/hero-img.png
  website/frontend/src/components/Hero.js
  website/frontend/styles/Hero.scss
Labels: ready for review

#638 [Website] monitor section
  website/frontend/src/components/Monitor.js
Labels: ready for review

#639 [Website] analytics section
  website/frontend/src/components/AnalyticsSection/AnalyticsSection.js
Labels: ready for review

#647 [Website] - Homepage changes
  website/frontend/config/urls.js
  website/frontend/src/assets/img/Get-app.png
  website/frontend/src/assets/img/get-app.png
  website/frontend/src/components/MapSection/MapSection.js
  website/frontend/src/components/get-app/GetApp.js
  website/frontend/styles/GetApp.scss
Labels: ready for merge, website-redesign

#629 add resource limits and hpas
  k8s/calibrate/prod-airqo-calibrate-app.yaml
  k8s/calibrate/stage-airqo-calibrate-app.yaml
  k8s/platform/prod-airqo-platform-frontend.yaml
  k8s/platform/stage-airqo-platform-frontend.yaml
  k8s/website/prod-airqo-website.yaml
  k8s/website/stage-airqo-website.yaml
  workflow-trigger.txt
Labels: ready for merge, ready for review, devops

#655 [Website] Added Hover effects and app download links
  website/frontend/src/components/Footer.js
  website/frontend/src/components/get-app/GetApp.js
  website/frontend/src/icons/footer/LinkedIn.svg
  website/frontend/src/icons/homepage/partners/google.svg
  website/frontend/styles/ContactUs.scss
  website/frontend/styles/NewsletterSection.scss
Labels: ready for review

#654 [Website] Ft airquality section
  website/frontend/src/assets/img/AirQuality.png
  website/frontend/src/assets/img/Digitalplatforms.png
  website/frontend/src/assets/img/ForCommunities.png
  website/frontend/src/components/AirQuality/AfricanCities.js
  website/frontend/src/components/AirQuality/AirQuality.js
  website/frontend/src/components/AirQuality/Communities.js
  website/frontend/src/pages/HomePage.js
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/Partners.scss
  website/frontend/styles/index.scss
Labels: ready for merge, website-redesign

#660 [Website] Newsletter and footer changes
  website/frontend/src/components/Footer.js
  website/frontend/src/components/NewsletterSection/NewsletterSection.js
  website/frontend/styles/Footer.scss
  website/frontend/styles/NewsletterSection.scss
Labels: ready for review

#652 [Website] Homepage highlight section
  website/frontend/src/assets/img/highlights/engineer.png
  website/frontend/src/assets/img/highlights/google-org.svg
  website/frontend/src/components/Highlight.js
  website/frontend/src/pages/HomePage.js
  website/frontend/styles/Highlight.scss
  website/frontend/styles/index.scss
Labels: ready for review

#661 [Website] Update Profile endpoint
  website/backend/settings.py
  website/backend/team/admin.py
  website/backend/team/migrations/0003_alter_member_options_remove_member_created_at_and_more.py
  website/backend/team/migrations/0004_alter_member_linked_in_alter_member_twitter.py
  website/backend/team/migrations/0005_alter_member_linked_in_alter_member_twitter.py
  website/backend/team/migrations/0006_member_order.py
  website/backend/team/models.py
  website/backend/team/views.py
  website/requirements.txt
Labels: ready for review

#653 Added more instructions on how to run the app
  mobile/README.md
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/resources/android.png
  mobile/resources/ios.png
  mobile/resources/mobile.png
  mobile/resources/project-structure.png
Labels: ready for merge, ready for review

#666 Fix - App whatsapp feedback option
  mobile/android/app/src/main/AndroidManifest.xml
  mobile/ios/Runner/Info.plist
  mobile/lib/constants/config.dart
  mobile/lib/screens/feedback/feedback_page.dart
Labels: ready for merge, ready for review

#650 automatically use the browser IANA time zone
  netmanager/src/utils/dateTime.js
Labels: enhancement, ready for merge, ready for review, feature, hotfix, netmanager, feature-request

#665 Changing insights graph pm colours
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/insights/insights_tab.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/themes/app_theme.dart
  mobile/lib/widgets/custom_widgets.dart
Labels: ready for merge, ready for review

#669 Fix - share buttons don't work
  mobile/lib/constants/config.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/insights/insights_tab.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/services/native_api.dart
  mobile/lib/widgets/buttons.dart
  mobile/lib/widgets/custom_shimmer.dart
  mobile/lib/widgets/custom_widgets.dart
Labels: ready for review

#671 [Website] - Ft contact us
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/ContactUs/actions.js
  website/frontend/reduxStore/ContactUs/operations.js
  website/frontend/reduxStore/ContactUs/reducers.js
  website/frontend/reduxStore/ContactUs/selectors.js
  website/frontend/src/assets/img/Feedback.png
  website/frontend/src/icons/contactUs/Data.svg
  website/frontend/src/icons/contactUs/Feedback.svg
  website/frontend/src/icons/contactUs/Inquiry.svg
  website/frontend/src/icons/contactUs/Tools.svg
  website/frontend/src/pages/ContactUs/ContactForm.js
  website/frontend/src/pages/ContactUs/Feedback.js
  website/frontend/src/pages/ContactUs/card.js
  website/frontend/src/pages/ContactUs/cards.js
  website/frontend/src/pages/ContactUs/index.js
  website/frontend/styles/ContactUs.scss
Labels: ready for merge, ready for review, website-redesign

#680 [Website] Remove explore button
  website/frontend/src/components/AnalyticsSection/AnalyticsSection.js
  website/frontend/src/components/ApiSection/ApiSection.js
  website/frontend/src/components/Hero.js
  website/frontend/src/components/Highlight.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/styles/Hero.scss
  website/frontend/styles/Highlight.scss
Labels: ready for review

#670 Update insights_tab.dart
  mobile/lib/screens/insights/insights_tab.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/themes/colors.dart
Labels: ready for merge, ready for review

#684 MOB-88 - MOB-88-disable-fa-qs-on-mobile-app
  mobile/lib/screens/settings/settings_page.dart
Labels: ready for merge, ready for review, mobile-app

#686 Updated app versions
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/ios/Runner/Info.plist
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/auth/phone_auth_widget.dart
  mobile/lib/screens/insights/insights_tab.dart
  mobile/lib/widgets/dialogs.dart
  mobile/pubspec.yaml
Labels: ready for merge

#688 [Website] - Highlights section design
  website/frontend/src/assets/img/HighlightsSection/AirQoTeam.png
  website/frontend/src/assets/img/HighlightsSection/Feature.png
  website/frontend/src/components/HighlightsSection/index.js
  website/frontend/src/components/HighlightsSection/pagination.js
  website/frontend/src/components/HighlightsSection/post.js
  website/frontend/src/pages/HomePage.js
  website/frontend/styles/HighlightsSection.scss
  website/frontend/styles/index.scss
Labels: ready for review, website-redesign

#685 move to production
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/ios/Runner/Info.plist
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/auth/phone_auth_widget.dart
  mobile/lib/screens/insights/insights_tab.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/themes/colors.dart
  mobile/lib/widgets/dialogs.dart
  mobile/pubspec.yaml
  web/application/config/routes.php
  web/application/controllers/Airqo.php
  web/application/views/airqo-career-details2.php
  web/application/views/airqo-careers.php
  website/frontend/src/assets/img/HighlightsSection/AirQoTeam.png
  website/frontend/src/assets/img/HighlightsSection/Feature.png
  website/frontend/src/components/HighlightsSection/index.js
  website/frontend/src/components/HighlightsSection/pagination.js
  website/frontend/src/components/HighlightsSection/post.js
  website/frontend/src/pages/HomePage.js
  website/frontend/styles/HighlightsSection.scss
  website/frontend/styles/index.scss
Labels: ready for review

#695 [Website] Hotfix - update hero image
  website/frontend/src/assets/img/HeroKampala.jpeg
  website/frontend/src/assets/img/Hero_Kampala.jpeg
  website/frontend/src/components/Hero.js
Labels: ready for review
