Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-03, with the labels that each got.

#514 Add GCS as an option for storing static files
  website/.gitignore
  website/backend/settings.py
  website/requirements.txt
Labels: ready for review

#511 Mobile app v2.0.1 - User feedback
  mobile/lib/auth/email_auth_widget.dart
  mobile/lib/auth/login_screen.dart
  mobile/lib/auth/phone_auth_widget.dart
  mobile/lib/auth/signup_screen.dart
  mobile/lib/screens/dashboard_view.dart
  mobile/lib/screens/profile_view.dart
  mobile/lib/services/native_api.dart
  mobile/lib/widgets/buttons.dart
Labels: ready for merge, ready for review

#508 Added Loader to Registry page and maintenace logs page, average and exceedances charts
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceLogs.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#523 [Web] Add US embassy logo
  web/application/views/airqo-home.php
  web/application/views/airqo-partnerships.php
  web/assets/images/partners/us-mission-uganda-vertical.webp
  web/assets/images/partners/us-mission-uganda.webp
Labels: ready for review

#524 Restore app.yaml
  web/app.yaml
Labels: ready for merge

#518 update alert timeout
  netmanager/src/redux/MainAlert/operations.js
Labels: ready for merge, ready for review

#522 App site names and locations
  mobile/lib/models/json_parsers.dart
  mobile/lib/models/measurement.dart
  mobile/lib/models/measurement.g.dart
  mobile/lib/models/place_details.dart
  mobile/lib/models/place_details.g.dart
  mobile/lib/models/site.dart
  mobile/lib/models/site.g.dart
  mobile/lib/screens/map_view.dart
  mobile/lib/screens/search_page.dart
  mobile/lib/services/local_storage.dart
  mobile/lib/services/native_api.dart
  mobile/lib/widgets/analytics_card.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/favourite_place_card.dart
  mobile/lib/widgets/insights_tab.dart
Labels: ready for review

#519 [NetManager] Split Management Tab
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/AppRoutes.js
  netmanager/src/assets/css/manager-map.css
  netmanager/src/assets/scss/device-management.sass
  netmanager/src/utils/dateTime.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementMap.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Sidebar/components/SidebarNav/SidebarNav.js
Labels: ready for review

#520 Ft map filter enhancement
  netmanager/src/assets/css/map-filter.css
  netmanager/src/assets/scss/device-management.sass
  netmanager/src/index.css
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementMap.js
  netmanager/src/views/components/DataDisplay/Map/MapBoxMap.js
  netmanager/src/views/components/DataDisplay/Map/MapFilter.js
  netmanager/src/views/components/DataDisplay/Map/MapKey.js
Labels: ready for review, priority-medium

#466 Website maintenance
  web/README.md
  web/app-prod.yaml
  web/app-stage.yaml
Labels: ready for review, airqo-website

#526 App theming. Part 1
  mobile/lib/auth/change_email_screen.dart
  mobile/lib/auth/change_phone_screen.dart
  mobile/lib/auth/email_auth_widget.dart
  mobile/lib/auth/email_reauthenticate_screen.dart
  mobile/lib/auth/login_screen.dart
  mobile/lib/auth/phone_auth_widget.dart
  mobile/lib/auth/phone_reauthenticate_screen.dart
  mobile/lib/auth/signup_screen.dart
  mobile/lib/main.dart
  mobile/lib/on_boarding/location_setup_screen.dart
  mobile/lib/on_boarding/notifications_setup_screen.dart
  mobile/lib/on_boarding/profile_setup_screen.dart
  mobile/lib/on_boarding/setup_complete_screeen.dart
  mobile/lib/on_boarding/spash_screen.dart
  mobile/lib/on_boarding/welcome_screen.dart
  mobile/lib/screens/about_page.dart
  mobile/lib/screens/dashboard_view.dart
  mobile/lib/screens/favourite_places.dart
  mobile/lib/screens/feedback_page.dart
  mobile/lib/screens/for_you_page.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/insights_page.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/kya/kya_title_page.dart
  mobile/lib/screens/map_view.dart
  mobile/lib/screens/notification_page.dart
  mobile/lib/screens/profile_edit_page.dart
  mobile/lib/screens/profile_view.dart
  mobile/lib/screens/search_page.dart
  mobile/lib/screens/settings_page.dart
  mobile/lib/services/native_api.dart
  mobile/lib/themes/light_theme.dart
  mobile/lib/utils/date.dart
  mobile/lib/utils/dialogs.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/utils/pm.dart
  mobile/lib/widgets/analytics_card.dart
  mobile/lib/widgets/buttons.dart
  mobile/lib/widgets/custom_shimmer.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/favourite_place_card.dart
  mobile/lib/widgets/insights_tab.dart
  mobile/lib/widgets/recomendation.dart
  mobile/lib/widgets/text_fields.dart
  mobile/lib/widgets/tooltip.dart
Labels: ready for review

#531 Candidate request submission and reject dates
  netmanager/src/utils/dateTime.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
Labels: ready for merge, ready for review, priority-medium

#528 [NetManager] Platform fixes
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceQRCode.js
  netmanager/src/views/components/d3/BrushedTimeSeries.js
  netmanager/src/views/components/d3/CustomisableChart.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
Labels: ready for review

#533 fixed customisable date bug
  netmanager/src/views/components/d3/CustomisableChart.js
Labels: ready for review

#537 Website ingress resource
  k8s/.gitignore
  k8s/nginx-ingress/prod-frontend-ingress-resource.yaml
  k8s/nginx-ingress/stage-airqo-platform-ingress-resource.yaml
  k8s/nginx-ingress/stage-frontend-ingress-resource.yaml
Labels: ready for review

#544 [Website] Add Footer
  website/backend/settings.py
  website/frontend/App.js
  website/frontend/src/components/Footer.js
  website/frontend/src/pages/HomePage.js
  website/frontend/src/pages/Page.js
  website/frontend/styles/Footer.scss
  website/frontend/styles/NotificationBanner.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/variables.scss
Labels: ready for review

#538 Ft get app section
  website/frontend/src/assets/img/get-app-sm.png
  website/frontend/src/assets/img/get-app.png
  website/frontend/src/components/get-app/GetApp.js
  website/frontend/src/components/get-app/index.js
  website/frontend/src/icons/getapp/ios.js
  website/frontend/src/icons/getapp/play.js
  website/frontend/src/pages/HomePage.js
  website/frontend/styles/GetApp.scss
  website/frontend/styles/index.scss
Labels: ready for merge, ready for review, ui, priority-high, website-redesign

#540 Ft map section
  website/frontend/src/assets/img/homepage-map.png
  website/frontend/src/components/MapSection/MapSection.js
  website/frontend/src/components/MapSection/index.js
  website/frontend/src/icons/common/ArrowRight.js
  website/frontend/src/pages/HomePage.js
  website/frontend/styles/MapSection.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for merge, ready for review, ui, priority-high, website-redesign

#530 App sharing feature Enhancement
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/services/native_api.dart
  mobile/lib/widgets/analytics_card.dart
Labels: ready for merge

#541 ft-navbar
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/HomePage.js
  website/frontend/styles/NavTab.scss
  website/frontend/styles/TopBar.scss
  website/package-lock.json
  website/package.json
Labels: work in progress, ready for review

#542 Fix for wrong date bug
  netmanager/package-lock.json
  netmanager/src/utils/dateTime.js
Labels: hotfix, priority-high

#547 Added API section
  website/frontend/src/assets/img/api-section-img.png
  website/frontend/src/components/ApiSection/ApiSection.js
  website/frontend/src/components/ApiSection/index.js
  website/frontend/src/pages/HomePage.js
  website/frontend/styles/ApiSection.scss
  website/frontend/styles/index.scss
Labels: ready for review

#521 Update device 'status' and 'isActive' fields
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for merge, ready for review

#554 fix broken dependencies
  netmanager/package-lock.json
Labels: hotfix, priority-high

#532 KYA enhancements
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/auth/email_auth_widget.dart
  mobile/lib/auth/phone_auth_widget.dart
  mobile/lib/screens/dashboard_view.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/kya/kya_title_page.dart
  mobile/lib/screens/map_view.dart
  mobile/lib/screens/profile_edit_page.dart
  mobile/lib/screens/profile_view.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/native_api.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/utils/kya_utils.dart
  mobile/pubspec.yaml
Labels: ready for merge

#548 Added Analytics section
  website/frontend/src/assets/img/analytics-section-img.png
  website/frontend/src/components/AnalyticsSection/AnalyticsSection.js
  website/frontend/src/components/AnalyticsSection/index.js
  website/frontend/src/pages/HomePage.js
  website/frontend/styles/AnalyticsSection.scss
  website/frontend/styles/NewsletterSection.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/index.scss
Labels: ready for review
