Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-07, with the labels that each got.

#698 [Website] setup google analytics
  website/frontend/templates/index.html
Labels: ready for review

#700 [Website] fixed hero section buttons - overflow on mobile
  website/frontend/styles/Hero.scss
Labels: ready for review

#699 [Website] fixes mega menu
  website/frontend/styles/NavTab.scss
  website/frontend/styles/TopBar.scss
Labels: ready for review

#703 [Website] Homepage consistency and mobile responsiveness
  website/frontend/src/assets/img/ApiSection.png
  website/frontend/src/assets/img/MapWrapper.png
  website/frontend/src/components/AnalyticsSection/AnalyticsSection.js
  website/frontend/src/components/ApiSection/ApiSection.js
  website/frontend/src/components/MapSection/MapSection.js
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/AnalyticsSection.scss
  website/frontend/styles/ApiSection.scss
  website/frontend/styles/GetApp.scss
  website/frontend/styles/Hero.scss
  website/frontend/styles/Highlight.scss
  website/frontend/styles/HighlightsSection.scss
  website/frontend/styles/MapSection.scss
  website/frontend/styles/Monitor.scss
  website/frontend/styles/NewsletterSection.scss
  website/frontend/styles/index.scss
  website/frontend/templates/index.html
Labels: ready for merge, website-redesign

#644 Ft deploy previews
  .github/workflows/deploy-frontend-to-preview-env.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  website/.dockerignore
  website/README.md
  website/docker/Dockerfile
  website/docker/docker-compose-dev.yml
  website/docker/wsgi-entrypoint.sh
Labels: ready for merge, ready for review, devops

#628 airqalibrate subdomain
  k8s/nginx-ingress/prod-frontend-ingress-resource.yaml
  k8s/nginx-ingress/stage-frontend-ingress-resource.yaml
Labels: ready for merge, ready for review, devops

#708 Added Security guidelines to README
  mobile/README.md
Labels: ready for merge

#719 [Website] Ft Featured Stories interactions
  website/.gitignore
  website/frontend/src/assets/img/HighlightsSection/FortPortal.jpeg
  website/frontend/src/assets/img/HighlightsSection/SRI.jpeg
  website/frontend/src/components/HighlightsSection/index.js
  website/frontend/src/components/HighlightsSection/pagination.js
  website/frontend/src/components/HighlightsSection/post.js
  website/frontend/src/pages/Page.js
  website/frontend/src/pages/PageMini.js
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/AnalyticsSection.scss
  website/frontend/styles/GetApp.scss
  website/frontend/styles/HighlightsSection.scss
  website/frontend/styles/Monitor.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for merge, ready for review, website-redesign

#657 [Website] Implement explore data interactions
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/ExploreData/actions.js
  website/frontend/reduxStore/ExploreData/operations.js
  website/frontend/reduxStore/ExploreData/reducers.js
  website/frontend/reduxStore/ExploreData/selectors.js
  website/frontend/reduxStore/index.js
  website/frontend/src/assets/img/explore/get-started-explore.png
  website/frontend/src/assets/img/explore/man-download-app.png
  website/frontend/src/assets/svg/QR code.svg
  website/frontend/src/assets/svg/apple-btn.svg
  website/frontend/src/assets/svg/explore/air-quality-platform.svg
  website/frontend/src/assets/svg/explore/discover-air-quality.svg
  website/frontend/src/assets/svg/explore/registration_complete_svg.svg
  website/frontend/src/assets/svg/google-play-btn.svg
  website/frontend/src/components/Hero.js
  website/frontend/src/components/Highlight.js
  website/frontend/src/components/Partners.js
  website/frontend/src/components/nav/NavTab.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/styles/ExploreData.scss
  website/frontend/styles/index.scss
Labels: ready for review

#718 [Website] Ft loading page
  website/frontend/App.js
  website/frontend/src/components/LoadSpinner/index.js
  website/frontend/src/icons/loading/airqo.png
  website/frontend/standaloneIndex.html
  website/frontend/styles/Loadspinner.scss
  website/frontend/styles/index.scss
  website/frontend/templates/index.html
Labels: ready for merge, ready for review, website-redesign

#706 [Website] Ft partners section changes
  website/frontend/src/components/Partners.js
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/Partners.scss
Labels: ready for merge, ready for review

#694 Migrate new website to production
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .gitignore
  k8s/website/prod-airqo-website.yaml
  k8s/website/stage-airqo-website.yaml
  website/.dockerignore
  website/.gitignore
  website/Dockerfile
  website/README.md
  website/docker/Dockerfile
  website/docker/database/01-init.sh
  website/docker/docker-compose-dev.yml
  website/docker/wsgi-entrypoint.sh
  website/requirements.txt
Labels: ready for merge, ready for review, priority-high

#717 [Website] Add Careers Page
  website/backend/career/admin.py
  website/backend/career/migrations/0002_bulletdescription_alter_career_options_and_more.py
  website/backend/career/migrations/0003_rename_bullet_bulletpoint_bullet_and_more.py
  website/backend/career/migrations/0004_career_unique_title.py
  website/backend/career/migrations/0005_alter_bulletdescription_options_and_more.py
  website/backend/career/models.py
  website/backend/career/serializers.py
  website/backend/career/views.py
  website/backend/settings.py
  website/backend/urls.py
  website/backend/utils/__init__.py
  website/backend/utils/models.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/Careers/actions.js
  website/frontend/reduxStore/Careers/operations.js
  website/frontend/reduxStore/Careers/reducers.js
  website/frontend/reduxStore/Careers/selectors.js
  website/frontend/reduxStore/index.js
  website/frontend/src/components/Footer.js
  website/frontend/src/components/MiniHighlights.js
  website/frontend/src/icons/careers/careers.jpeg
  website/frontend/src/pages/CareerDetailPage.js
  website/frontend/src/pages/CareerPage.js
  website/frontend/src/pages/HomePage.js
  website/frontend/src/pages/Page.js
  website/frontend/styles/CareersDetailPage.scss
  website/frontend/styles/CareersPage.scss
  website/frontend/styles/index.scss
  website/frontend/utils/groupBy.js
  website/requirements.txt
Labels: ready for review

#728 http to https autoredirect
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: ready for merge, ready for review, hotfix

#726 [Website] Update partner logos
  website/frontend/src/assets/img/partners/Afriqair.png
  website/frontend/src/assets/img/partners/Development Impact lab.png
  website/frontend/src/assets/img/partners/Embassy of Sweden KLA.png
  website/frontend/src/assets/img/partners/Enabel Wehubit.png
  website/frontend/src/assets/img/partners/Fort Portal City.png
  website/frontend/src/assets/img/partners/Horizonte Ciudadano Foundation.png
  website/frontend/src/assets/img/partners/KCCA.png
  website/frontend/src/assets/img/partners/Kiira.png
  website/frontend/src/assets/img/partners/MLands.png
  website/frontend/src/assets/img/partners/MUK_Logo@4x 1.png
  website/frontend/src/assets/img/partners/Mapping for Change UK.png
  website/frontend/src/assets/img/partners/MoWT.png
  website/frontend/src/assets/img/partners/NEMA.png
  website/frontend/src/assets/img/partners/Sheffield University UK.png
  website/frontend/src/assets/img/partners/UNEP.png
  website/frontend/src/assets/img/partners/US Embassy UG.png
  website/frontend/src/assets/img/partners/University of Colorado Boulder US.png
  website/frontend/src/assets/img/partners/University of Florida US.png
  website/frontend/src/assets/img/partners/World Bank.png
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/styles/AboutUsPage.scss
Labels: ready for merge

#724 [Website] Ft Highlights Section Backend
  website/.gitignore
  website/backend/career/migrations/0006_auto_20220718_0617.py
  website/backend/highlights/__init__.py
  website/backend/highlights/admin.py
  website/backend/highlights/apps.py
  website/backend/highlights/migrations/0001_initial.py
  website/backend/highlights/migrations/0002_auto_20220718_0637.py
  website/backend/highlights/migrations/0003_auto_20220720_1057.py
  website/backend/highlights/migrations/__init__.py
  website/backend/highlights/models.py
  website/backend/highlights/serializers.py
  website/backend/highlights/tests.py
  website/backend/highlights/views.py
  website/backend/settings.py
  website/backend/team/migrations/0008_alter_member_options.py
  website/backend/urls.py
Labels: ready for merge, ready for review

#731 [Urban Better] Data export
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/pages/Download/Download.js
Labels: ready for review

#733 [Website] Dynamic explore data login url
  website/.gitignore
  website/frontend/config/urls.js
  website/frontend/src/pages/ExploreData/index.js
Labels: ready for review

#732 Remove handlers from app engine config
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  website/backend/settings.py
  workflow-trigger.txt
Labels: enhancement, ready for review

#580 Set up GitGaurdian pre-commit hook
  .gitguardian.yml
  .gitignore
Labels: enhancement, question, ready for review, security, request-access
