Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-12, with the labels that each got.

#973 update mobile app release notes
  docs/mobile_app/release_notes.md
Labels: good first issue, ready for review

#974 Side menu button functionality tests
  docs/cypress/e2e/tests/index.cy.js
Labels: enhancement, ready for review

#975 Search functionality tests
  docs/cypress/e2e/tests/index.cy.js
Labels: enhancement, ready for review

#981 [Website] Ft Privacy Policy
  website/frontend/App.js
  website/frontend/src/components/Footer.js
  website/frontend/src/pages/Legal/PrivacyPolicy.js
  website/frontend/src/pages/Legal/Terms.js
  website/frontend/src/pages/Legal/TermsOfService.js
  website/frontend/src/pages/Legal/index.js
  website/frontend/styles/Legal.scss
Labels: ready for review

#976 Edit on GitHub functionality tests
  docs/cypress.config.js
  docs/cypress/e2e/tests/index.cy.js
Labels: documentation, enhancement, ready for review

#960 Refine cd pipeline
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/platform/values-dev.yaml
Labels: ready for review, devops

#983 [Website] Ft team biographies
  website/backend/partners/migrations/0003_alter_partner_type.py
  website/backend/partners/models.py
  website/backend/team/admin.py
  website/backend/team/migrations/0009_memberbiography.py
  website/backend/team/models.py
  website/backend/team/serializers.py
  website/frontend/src/components/AirQuality/AfricanCities.js
  website/frontend/src/components/Modal/index.js
  website/frontend/src/components/Profile.js
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/styles/AboutUsPage.scss
  website/frontend/styles/Modal.scss
  website/frontend/styles/index.scss
Labels: ready for review

#988 Restrict production workflow actors
  .github/workflows/deploy-frontends-to-production.yml
Labels: enhancement, ready for review

#991 update file with retry
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: enhancement, ready for review

#992 [Mobile app] Adding Section for Contributors.
  mobile/README.md
  mobile/lib/constants/config.dart
Labels: work in progress

#995 [Website] Ft Board Members
  website/backend/board/__init__.py
  website/backend/board/admin.py
  website/backend/board/apps.py
  website/backend/board/migrations/0001_initial.py
  website/backend/board/migrations/__init__.py
  website/backend/board/models.py
  website/backend/board/serializers.py
  website/backend/board/tests.py
  website/backend/board/views.py
  website/backend/settings.py
  website/backend/urls.py
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/Board/actions.js
  website/frontend/reduxStore/Board/operations.js
  website/frontend/reduxStore/Board/reducers.js
  website/frontend/reduxStore/Board/selectors.js
  website/frontend/reduxStore/index.js
  website/frontend/src/pages/AboutUsPage.js
Labels: ready for review

#982 [Mobile app] Search feature redesign
  mobile/ios/Podfile.lock
  mobile/lib/blocs/dashboard/dashboard_bloc.dart
  mobile/lib/blocs/map/map_bloc.dart
  mobile/lib/blocs/search/search_bloc.dart
  mobile/lib/blocs/search/search_event.dart
  mobile/lib/blocs/search/search_state.dart
  mobile/lib/constants/config.dart
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/models/air_quality_reading.dart
  mobile/lib/models/air_quality_reading.g.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/hive_type_id.dart
  mobile/lib/models/models.dart
  mobile/lib/models/search_history.dart
  mobile/lib/models/search_history.g.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/search/search_page.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/location_service.dart
  mobile/lib/themes/app_theme.dart
  mobile/lib/utils/data_formatter.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/widgets/custom_shimmer.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/error_widgets.dart
  mobile/lib/widgets/icons.dart
  mobile/lib/widgets/widgets.dart
Labels: ready for review

#999 Ft docs enhancement
  docs/README.md
  docs/calibration/README.md
  docs/cypress/e2e/tests/index.cy.js
  docs/index.html
Labels: documentation, enhancement

#997 move to production
  docs/README.md
  docs/calibration/README.md
  docs/cypress/e2e/tests/index.cy.js
  docs/index.html
  mobile/README.md
  mobile/ios/Podfile.lock
  mobile/lib/blocs/dashboard/dashboard_bloc.dart
  mobile/lib/blocs/map/map_bloc.dart
  mobile/lib/blocs/search/search_bloc.dart
  mobile/lib/blocs/search/search_event.dart
  mobile/lib/blocs/search/search_state.dart
  mobile/lib/constants/config.dart
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/models/air_quality_reading.dart
  mobile/lib/models/air_quality_reading.g.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/hive_type_id.dart
  mobile/lib/models/models.dart
  mobile/lib/models/search_history.dart
  mobile/lib/models/search_history.g.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/search/search_page.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/location_service.dart
  mobile/lib/themes/app_theme.dart
  mobile/lib/utils/data_formatter.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/widgets/custom_shimmer.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/error_widgets.dart
  mobile/lib/widgets/icons.dart
  mobile/lib/widgets/widgets.dart
  website/backend/board/__init__.py
  website/backend/board/admin.py
  website/backend/board/apps.py
  website/backend/board/migrations/0001_initial.py
  website/backend/board/migrations/__init__.py
  website/backend/board/models.py
  website/backend/board/serializers.py
  website/backend/board/tests.py
  website/backend/board/views.py
  website/backend/settings.py
  website/backend/urls.py
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/Board/actions.js
  website/frontend/reduxStore/Board/operations.js
  website/frontend/reduxStore/Board/reducers.js
  website/frontend/reduxStore/Board/selectors.js
  website/frontend/reduxStore/index.js
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/styles/GetInvolvedModal.scss
Labels: ready for review
