Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-08, with the labels that each got.

#747 Delete Google.svg
  website/frontend/src/icons/homepage/partners/Google.svg
Labels: ready for review

#745 Ft website ssl redirect default
  website/README.md
  website/backend/settings.py
Labels: enhancement, ready for merge, ready for review, hotfix

#755 [Hotfix] Removed unused import
  website/frontend/styles/index.scss
Labels: ready for review

#757 [Website] Ft Homepage tabview PR clean up
  website/frontend/src/components/AnalyticsSection/AnalyticsSection.js
  website/frontend/src/components/Hero.js
  website/frontend/src/components/MapSection/MapSection.js
  website/frontend/src/components/Monitor.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/AnalyticsSection.scss
  website/frontend/styles/ApiSection.scss
  website/frontend/styles/GetApp.scss
  website/frontend/styles/Hero.scss
  website/frontend/styles/HighlightsSection.scss
  website/frontend/styles/MapSection.scss
  website/frontend/styles/Monitor.scss
  website/frontend/styles/NavTab.scss
  website/frontend/styles/Partners.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/lib/variables.scss
Labels: ready for merge, ready for review

#750 Update README.md
  website/README.md
Labels: ready for merge, ready for review

#761 [Website] Pages metadata
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/src/pages/CareerPage.js
  website/frontend/src/pages/ContactUs/index.js
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
  website/frontend/src/pages/OurSolutions/CommunityPage.js
  website/frontend/src/pages/OurSolutions/ResearchPage.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/utils/seo.js
  website/package-lock.json
  website/package.json
Labels: ready for merge, ready for review

#763 [Website] Ft tahmo logo
  website/frontend/src/assets/img/partners/MMU.jpg
  website/frontend/src/assets/img/partners/TAHMO.png
  website/frontend/src/pages/AboutUsPage.js
Labels: ready for merge

#758 Add next platform cicd
  .github/workflows/deploy-frontend-to-preview-env.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/.gitignore
  k8s/netmanager/.helmignore
  k8s/netmanager/Chart.yaml
  k8s/netmanager/charts/.gitkeep
  k8s/netmanager/prod-airqo-platform-frontend.yaml
  k8s/netmanager/stage-airqo-platform-frontend.yaml
  k8s/netmanager/templates/NOTES.txt
  k8s/netmanager/templates/_helpers.tpl
  k8s/netmanager/templates/deployment.yaml
  k8s/netmanager/templates/service.yaml
  k8s/netmanager/templates/tests/test-connection.yaml
  k8s/netmanager/values-dev.yaml
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/prod-airqo-next-platform.yaml
  k8s/platform/stage-airqo-next-platform.yaml
  platform/.dockerignore
  platform/.env.example
  platform/.gitignore
  platform/Dockerfile
  platform/README.md
  platform/next.config.js
  platform/public/.gitkeep
  platform/src/pages/index.js
Labels: ready for merge, ready for review

#760 [Website] Highlights section backend integration
  website/backend/highlights/serializers.py
  website/backend/highlights/views.py
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/Highlights/actions.js
  website/frontend/reduxStore/Highlights/operations.js
  website/frontend/reduxStore/Highlights/reducers.js
  website/frontend/reduxStore/Highlights/selectors.js
  website/frontend/reduxStore/index.js
  website/frontend/src/components/HighlightsSection/index.js
  website/frontend/src/components/HighlightsSection/pagination.js
  website/frontend/src/components/HighlightsSection/post.js
  website/frontend/src/components/LoadSpinner/ImageLoader.js
  website/frontend/src/components/LoadSpinner/SectionLoader.js
  website/frontend/src/pages/CareerPage.js
  website/frontend/styles/CareersPage.scss
  website/frontend/styles/HighlightsSection.scss
  website/frontend/styles/Loadspinner.scss
Labels: ready for merge, ready for review

#762 [Website] Removes duplicate metadata
  website/frontend/src/pages/HomePage.js
  website/frontend/standaloneIndex.html
  website/frontend/templates/index.html
  website/frontend/utils/seo.js
Labels: ready for review

#765 Ft secrets injection
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: enhancement, ready for merge, ready for review, devops

#768 [Website] Resolve CSS bugs
  website/frontend/src/pages/ContactUs/index.js
  website/frontend/styles/ContactUs.scss
  website/frontend/styles/Footer.scss
  website/frontend/styles/Highlight.scss
  website/frontend/styles/HomePage.scss
Labels: ready for merge, ready for review

#767 [Website] New partner logos and updated hierarchy
  website/frontend/src/assets/img/partners/Enabel Wehubit.png
  website/frontend/src/assets/img/partners/MLands.png
  website/frontend/src/assets/img/partners/MUK_Logo.png
  website/frontend/src/assets/img/partners/MakerereUniversity.png
  website/frontend/src/assets/img/partners/Ministries.png
  website/frontend/src/assets/img/partners/MoWT.png
  website/frontend/src/assets/img/partners/US Embassy UG.png
  website/frontend/src/assets/img/partners/USEmbassy.png
  website/frontend/src/assets/img/partners/WRI.png
  website/frontend/src/assets/img/partners/WeHubit.png
  website/frontend/src/components/Partners.js
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/styles/Partners.scss
Labels: ready for merge, ready for review

#764 remove obsolete jenkins folder
  jenkins/platform-prod/Jenkinsfile
  jenkins/platform-stage/Jenkinsfile
Labels: enhancement, ready for merge, ready for review

#770 Deactivate kenya tab
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
Labels: ready for merge

#772 [Website] Change link phrasing
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
  website/frontend/src/pages/OurSolutions/ResearchPage.js
Labels: ready for merge

#769 Progressively loads team profile images
  website/backend/settings.py
  website/frontend/src/components/Profile.js
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/styles/AboutUsPage.scss
  website/frontend/utils/customHooks.js
Labels: ready for merge, ready for review

#775 Ft new article
  website/frontend/src/icons/press/Lifewire-logo.svg
  website/frontend/src/icons/press/VoaLogo.svg
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
  website/frontend/src/pages/OurSolutions/CommunityPage.js
  website/frontend/src/pages/OurSolutions/ResearchPage.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/styles/Press.scss
  website/frontend/templates/index.html
Labels: ready for merge, ready for review

#774 Disabling WhatsApp feedback option
  mobile/lib/screens/feedback/feedback_page_widgets.dart
Labels: ready for review

#778 Add static code analysis and linting
  .pre-commit-config.yaml
  platform/.eslintrc.json
  platform/.prettierignore
  platform/README.md
  platform/next.config.js
  platform/package.json
  platform/prettier.config.js
  platform/src/pages/index.js
  platform/yarn.lock
Labels: enhancement, dependencies

#779 Add ui automated testing with Cypress, CI with GitHub Actions & Code coverage
  .github/dependabot.yml
  .github/workflows/run-tests.yml
  platform/.babelrc.js
  platform/.dockerignore
  platform/.gitignore
  platform/README.md
  platform/cypress.config.js
  platform/cypress/component/ComponentName.cy.js
  platform/cypress/e2e/1-getting-started/todo.cy.js
  platform/cypress/fixtures/example.json
  platform/cypress/plugins/e2e.js
  platform/cypress/spec.js
  platform/cypress/support/commands.js
  platform/cypress/support/component-index.html
  platform/cypress/support/component.js
  platform/cypress/support/e2e.js
  platform/package.json
  platform/yarn.lock
Labels: enhancement, devops

#773 fix - android cipher exception
  mobile/lib/services/hive_service.dart
  mobile/lib/services/secure_storage.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for merge, ready for review
