Repository airqo-platform/AirQo-frontend, pull requests merged in 2022-11, with the labels that each got.

#917 Creating .env.sample file and updating README.md according to it.
  netmanager/.env.sample
  netmanager/README.md
Labels: enhancement, good first issue, ready for merge, ready for review

#862 added back to top button
  docs/index.html
Labels: enhancement, ready for merge, ready for review

#923 [Mobile app] Fix - failure on startup
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/main_dev.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/secure_storage.dart
Labels: ready for merge, ready for review

#924 [Mobile app] - Refactoring authentication and onboarding screens
  mobile/lib/blocs/auth_code/auth_code_bloc.dart
  mobile/lib/blocs/auth_code/auth_code_event.dart
  mobile/lib/blocs/auth_code/auth_code_state.dart
  mobile/lib/blocs/blocs.dart
  mobile/lib/blocs/dashboard/dashboard_bloc.dart
  mobile/lib/blocs/email_auth/email_auth_bloc.dart
  mobile/lib/blocs/email_auth/email_auth_event.dart
  mobile/lib/blocs/email_auth/email_auth_state.dart
  mobile/lib/blocs/phone_auth/phone_auth_bloc.dart
  mobile/lib/blocs/phone_auth/phone_auth_event.dart
  mobile/lib/blocs/phone_auth/phone_auth_state.dart
  mobile/lib/blocs/settings/settings_bloc.dart
  mobile/lib/blocs/settings/settings_event.dart
  mobile/lib/blocs/settings/settings_state.dart
  mobile/lib/main_common.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/json_parsers.dart
  mobile/lib/models/profile.dart
  mobile/lib/screens/auth/auth_verification.dart
  mobile/lib/screens/auth/auth_widgets.dart
  mobile/lib/screens/auth/change_email_screen.dart
  mobile/lib/screens/auth/change_phone_screen.dart
  mobile/lib/screens/auth/email_auth_widget.dart
  mobile/lib/screens/auth/email_reauthenticate_screen.dart
  mobile/lib/screens/auth/phone_auth_widget.dart
  mobile/lib/screens/auth/phone_reauthenticate_screen.dart
  mobile/lib/screens/feedback/feedback_page.dart
  mobile/lib/screens/feedback/feedback_page_widgets.dart
  mobile/lib/screens/on_boarding/introduction_screen.dart
  mobile/lib/screens/on_boarding/location_setup_screen.dart
  mobile/lib/screens/on_boarding/notifications_setup_screen.dart
  mobile/lib/screens/on_boarding/on_boarding_widgets.dart
  mobile/lib/screens/on_boarding/profile_setup_screen.dart
  mobile/lib/screens/on_boarding/setup_complete_screeen.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/on_boarding/welcome_screen.dart
  mobile/lib/screens/profile/profile_view.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/themes/colors.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/text_fields.dart
  mobile/pubspec.yaml
Labels: ready for merge, ready for review

#926 [Mobile app] - Terms and Privacy
  mobile/lib/constants/config.dart
  mobile/lib/screens/settings/about_page.dart
  mobile/lib/screens/web_view_page.dart
Labels: ready for merge, ready for review

#928 [Mobile app] Enhancing the feedback feature
  mobile/lib/blocs/feedback/feedback_bloc.dart
  mobile/lib/blocs/feedback/feedback_event.dart
  mobile/lib/blocs/feedback/feedback_state.dart
  mobile/lib/main_common.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/screens/feedback/feedback_page.dart
  mobile/lib/screens/feedback/feedback_page_widgets.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
Labels: ready for merge, ready for review

#927 Proof-read App Privacy Policy
  docs/mobile_app/privacy_policy.md
Labels: documentation, ready for review

#915 reverting changes to the landing page
  netmanager/src/views/layouts/Landing.js
Labels: ready for review, netmanager

#933 [Website] Cameroon airqloud
  website/frontend/src/components/Footer.js
  website/frontend/src/icons/africanCities/countries/cameroon.svg
Labels: ready for merge, ready for review

#929 remove .idea folder from git cache
  .idea/.gitignore
  .idea/AirQo-frontend.iml
  .idea/modules.xml
  .idea/vcs.xml
  mobile/.idea/vcs.xml
Labels: good first issue, ready for merge, ready for review

#925 Add the Hardware guide to the AirQo docs
  docs/_media/monitor_1.png
  docs/_media/monitor_2.png
  docs/_media/monitor_3.png
  docs/_media/monitor_4.png
  docs/_sidebar.md
  docs/hardware/README.md
  docs/hardware/_sidebar.md
  docs/hardware/monitor.md
Labels: documentation, good first issue, ready for merge, ready for review

#932 [Legacy] Adds google analytics to netmanager
  .github/workflows/deploy-frontend-pr-previews.yml
  netmanager/.env.sample
  netmanager/public/index.html
Labels: ready for merge, ready for review

#935 update contribution guide to notify contributors they dont need to wait to be assigned issues
  CONTRIBUTING.md
Labels: good first issue, ready for merge, ready for review

#940 add requirements to pr checklist under pr status of maturity
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation, good first issue, ready for merge, ready for review

#947 [Mobile App]Fix Color of text on notifications page
  mobile/lib/screens/notification/notification_widgets.dart
  mobile/lib/themes/colors.dart
Labels: ready for review

#949 [Netmanager] Added category column to candidate column
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
Labels: ready for merge, ready for review

#950 [Netmanager] Decoupled rundevice test from deployment process
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
Labels: ready for merge, ready for review

#944 [CI/942]: Update actions checkout version from v2 to v3
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/deploy-k8s-changes-to-production.yml
  .github/workflows/deploy-k8s-changes-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  .github/workflows/run-tests.yml
Labels: good first issue, ready for merge, ready for review

#951 move to production
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/deploy-k8s-changes-to-production.yml
  .github/workflows/deploy-k8s-changes-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  .github/workflows/run-tests.yml
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
Labels: ready for review

#918 mobile-CI-CD
  .github/workflows/deploy-mobile-android-to-firebase-app-distribution.yml
  mobile/README.md
  mobile/android/Gemfile
  mobile/android/Gemfile.lock
  mobile/android/app/build.gradle
  mobile/android/fastlane/.gitignore
  mobile/android/fastlane/Appfile
  mobile/android/fastlane/Fastfile
  mobile/android/fastlane/Pluginfile
  mobile/android/fastlane/README.md
  mobile/android/release_notes.txt
Labels: ready for review

#937 Deleted Scooping Requirements
  docs/hardware/monitor.md
Labels: ready for merge, ready for review

#953 [Mobile app] New release
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/ios/Runner/Info.plist
  mobile/pubspec.yaml
Labels: ready for merge, ready for review

#954 [Mobile app] - hotfix search feature
  mobile/lib/models/models.dart
  mobile/lib/models/suggestion.dart
  mobile/lib/models/suggestion.g.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/packages/airqo_api/lib/src/models/prediction.dart
Labels: ready for review, priority-high

#941 Stop preview auto updates
  .github/workflows/deploy-frontend-pr-previews.yml
  k8s/calibrate/charts/.gitkeep
  k8s/calibrate/templates/tests/test-connection.yaml
  k8s/calibrate/values-dev.yaml
  k8s/docs/charts/.gitkeep
  k8s/docs/templates/tests/test-connection.yaml
  k8s/docs/values-dev.yaml
  k8s/docs/values-stage.yaml
  k8s/netmanager/values-dev.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/charts/.gitkeep
  k8s/platform/templates/tests/test-connection.yaml
  k8s/platform/values-dev.yaml
Labels: ready for review, devops

#934 Fix image registry
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/deploy-k8s-changes-to-production.yml
  .github/workflows/deploy-k8s-changes-to-staging.yml
  k8s/docs/values-stage.yaml
Labels: ready for merge, ready for review, devops

#956 platform terms and conditions
  docs/api/README.md
  docs/api/release_notes.md
  docs/api/users.md
  docs/calibration/airqalibrate.md
  docs/calibration/ml_based_approach.md
  docs/hardware/monitor.md
  docs/index.html
  docs/platform/_sidebar.md
  docs/platform/analytics.md
  docs/platform/extras.md
  docs/platform/join.md
  docs/platform/terms_and_conditions.md
Labels: documentation, enhancement, ready for merge, ready for review

#957 Allows admin to send user feedback on reject data access
  netmanager/src/config/urls/authService.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
Labels: ready for merge, ready for review

#946 [Netmanager] Updates polluntant concentration label on the map
  netmanager/src/utils/setAuthToken.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for merge, ready for review

#968 Fix the candidates and user tables date bug
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
Labels: bug, ready for merge, ready for review, hotfix

#969 Setup docs tests
  docs/cypress.config.js
  docs/cypress/e2e/tests/index.cy.js
  docs/cypress/fixtures/example.json
  docs/cypress/support/commands.js
  docs/cypress/support/e2e.js
  docs/package.json
  docs/yarn.lock
Labels: enhancement, ready for merge, ready for review

#959 Allows admin to send Candidates a message
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
Labels: ready for merge, ready for review

#971 docs tests CI
  .github/workflows/test-changes.yml
  docs/.dockerignore
  docs/cypress.config.js
  docs/cypress/e2e/tests/index.cy.js
  docs/cypress/support/index.js
  docs/index.html
  docs/package.json
Labels: enhancement, ready for review

#978 Increment app version android
  mobile/pubspec.yaml
Labels: ready for review

#977 Cover page tests
  docs/cypress/e2e/tests/index.cy.js
Labels: documentation, enhancement, ready for review

#967 [Mobile]Changing Health Tips messages to be dynamic.
  mobile/lib/screens/insights/insights_tab.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/services/native_api.dart
  mobile/lib/utils/pm.dart
  mobile/lib/widgets/health_tip.dart
  mobile/lib/widgets/widgets.dart
Labels: ready for review
