Repository airqo-platform/AirQo-frontend, pull requests merged in 2023-03, with the labels that each got.

#1074 [MOBILE] review application permissions
  mobile/android/app/src/main/AndroidManifest.xml
  mobile/ios/Podfile.lock
  mobile/ios/Runner/Info.plist
  mobile/pubspec.lock
Labels: mobile-app

#1045 remove unused files
  k8s/calibrate/prod-airqo-calibrate-app.yaml
  k8s/calibrate/stage-airqo-calibrate-app.yaml
  k8s/docs/prod-airqo-docs.yaml
  k8s/docs/stage-airqo-docs.yaml
  k8s/netmanager/prod-airqo-platform-frontend.yaml
  k8s/netmanager/stage-airqo-platform-frontend.yaml
  k8s/platform/prod-airqo-next-platform.yaml
  k8s/platform/stage-airqo-next-platform.yaml
Labels: ready for review, hotfix

#1082 [Website] Updated Explore data flow & user feedback
  website/backend/highlights/migrations/0006_alter_highlight_title.py
  website/backend/highlights/migrations/0007_alter_highlight_link_title.py
  website/backend/highlights/models.py
  website/backend/publications/migrations/0002_alter_publication_category.py
  website/backend/publications/models.py
  website/frontend/src/components/Tweets.js
  website/frontend/src/pages/CareerPage.js
  website/frontend/src/pages/ContactUs/card.js
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/src/pages/Publications/CardComponent.js
  website/frontend/src/pages/Publications/Pagination.js
  website/frontend/src/pages/Publications/Publications.js
  website/frontend/src/pages/Publications/ReportComponent.js
  website/frontend/styles/Press.scss
  website/frontend/styles/PublicationPage.scss
Labels: ready for review

#1067 [Collocation] Add Monitor Table Functionality
  platform/package.json
  platform/public/icons/Common/arrowLeft.svg
  platform/public/icons/Common/arrow_right_blue.svg
  platform/public/icons/arrow_right_alt_blue.svg
  platform/public/icons/check_circle.jsx
  platform/public/icons/ellipsis_horizontal_circle.jsx
  platform/src/common/components/AddMonitor/Calendar/index.jsx
  platform/src/common/components/AddMonitor/Skeletion/Calendar.jsx
  platform/src/common/components/AddMonitor/Skeletion/Table.jsx
  platform/src/common/components/AddMonitor/Skeletion/index.jsx
  platform/src/common/components/AddMonitor/Table/DataTable.jsx
  platform/src/common/components/AddMonitor/Table/Pagination.jsx
  platform/src/common/components/AddMonitor/Table/SearchBar.jsx
  platform/src/common/components/AddMonitor/Table/index.jsx
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Layout/content_box.jsx
  platform/src/common/components/Navigation/breadcrumb.jsx
  platform/src/common/components/Skeleton/index.jsx
  platform/src/common/components/Toast/error.jsx
  platform/src/common/components/Toast/index.jsx
  platform/src/common/components/Toast/success.jsx
  platform/src/common/components/Toast/warning.jsx
  platform/src/core/urls/deviceMonitoring.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/addMonitor/selectedCollocateDevicesSlice.js
  platform/src/lib/store/services/collocation/collocationDataSlice.js
  platform/src/lib/store/services/collocation/index.js
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1086 Ft scheduling collocate
  platform/package.json
  platform/public/icons/Common/arrowLeft.svg
  platform/public/icons/Common/arrow_right_blue.svg
  platform/public/icons/arrow_right_alt_blue.svg
  platform/public/icons/check_circle.jsx
  platform/public/icons/ellipsis_horizontal_circle.jsx
  platform/src/common/components/AddMonitor/Calendar/index.jsx
  platform/src/common/components/AddMonitor/Skeletion/Calendar.jsx
  platform/src/common/components/AddMonitor/Skeletion/Table.jsx
  platform/src/common/components/AddMonitor/Skeletion/index.jsx
  platform/src/common/components/AddMonitor/Table/DataTable.jsx
  platform/src/common/components/AddMonitor/Table/Pagination.jsx
  platform/src/common/components/AddMonitor/Table/SearchBar.jsx
  platform/src/common/components/AddMonitor/Table/index.jsx
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Layout/content_box.jsx
  platform/src/common/components/Navigation/breadcrumb.jsx
  platform/src/common/components/Skeleton/index.jsx
  platform/src/common/components/Toast/error.jsx
  platform/src/common/components/Toast/index.jsx
  platform/src/common/components/Toast/success.jsx
  platform/src/common/components/Toast/warning.jsx
  platform/src/core/urls/deviceMonitoring.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/addMonitor/selectedCollocateDevicesSlice.js
  platform/src/lib/store/services/collocation/collocationDataSlice.js
  platform/src/lib/store/services/collocation/index.js
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1088 [WEBSITE] Events page
  website/frontend/App.js
  website/frontend/reduxStore/EventsNav/NavigationSlice.js
  website/frontend/reduxStore/index.js
  website/frontend/src/assets/img/Events/banner.png
  website/frontend/src/assets/img/Events/event-placeholder.jpg
  website/frontend/src/assets/img/Events/participation.png
  website/frontend/src/assets/img/Events/programme-1.png
  website/frontend/src/assets/img/Events/programme-2.png
  website/frontend/src/components/Footer.js
  website/frontend/src/pages/Events/Details.js
  website/frontend/src/pages/Events/EventCard.js
  website/frontend/src/pages/Events/Header.js
  website/frontend/src/pages/Events/Navigation.js
  website/frontend/src/pages/Events/index.js
  website/frontend/styles/Events.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
  website/package-lock.json
  website/package.json
Labels: ready for review, airqo-website

#1089 [WEBSITE] Old career listing frontend delete
  website/backend/career/admin.py
  website/frontend/src/pages/CareerPage.js
Labels: ready for review, airqo-website

#1091 [WEBSITE] Monitor Page
  website/.env.sample
  website/frontend/App.js
  website/frontend/src/assets/docs/AirQoMonitorUserGuideV04.pdf
  website/frontend/src/assets/img/OurProducts/Monitor/Africa.png
  website/frontend/src/assets/img/OurProducts/Monitor/activate.png
  website/frontend/src/assets/img/OurProducts/Monitor/monitor.png
  website/frontend/src/assets/img/OurProducts/Monitor/section-1.png
  website/frontend/src/components/OurProducts/Header.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/src/pages/OurProducts/MonitorPage.js
  website/frontend/styles/NavTab.scss
  website/frontend/styles/Products.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review, airqo-website

#1092 move to production
  website/.env.sample
  website/frontend/App.js
  website/frontend/src/assets/docs/AirQoMonitorUserGuideV04.pdf
  website/frontend/src/assets/img/OurProducts/Monitor/Africa.png
  website/frontend/src/assets/img/OurProducts/Monitor/activate.png
  website/frontend/src/assets/img/OurProducts/Monitor/monitor.png
  website/frontend/src/assets/img/OurProducts/Monitor/section-1.png
  website/frontend/src/components/OurProducts/Header.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/Events/Details.js
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/src/pages/OurProducts/MonitorPage.js
  website/frontend/styles/NavTab.scss
  website/frontend/styles/Products.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review

#1094 Updating app packages
  mobile/ios/Podfile.lock
  mobile/pubspec.lock
Labels: ready for review, mobile-app

#1077 Mob 185 showcase design changes
  mobile/assets/icon/line.svg
  mobile/lib/constants/config.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/for_you_page.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/widgets/custom_widgets.dart
Labels: ready for review, mobile-app

#1095 Blocs for KYA, notifications, favourite places and analytics
  mobile/lib/blocs/account/account_bloc.dart
  mobile/lib/blocs/account/account_event.dart
  mobile/lib/blocs/analytics/analytics_bloc.dart
  mobile/lib/blocs/analytics/analytics_event.dart
  mobile/lib/blocs/analytics/analytics_state.dart
  mobile/lib/blocs/blocs.dart
  mobile/lib/blocs/favourite_place/favourite_place_bloc.dart
  mobile/lib/blocs/favourite_place/favourite_place_event.dart
  mobile/lib/blocs/favourite_place/favourite_place_state.dart
  mobile/lib/blocs/kya/kya_bloc.dart
  mobile/lib/blocs/kya/kya_event.dart
  mobile/lib/blocs/kya/kya_state.dart
  mobile/lib/blocs/notification/notification_bloc.dart
  mobile/lib/blocs/notification/notification_event.dart
  mobile/lib/blocs/notification/notification_state.dart
  mobile/lib/blocs/settings/settings_bloc.dart
  mobile/lib/main_common.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/hive_type_id.dart
  mobile/lib/models/kya.dart
  mobile/lib/models/kya.g.dart
  mobile/lib/screens/analytics/analytics_view.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/auth/auth_verification.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/favourite_places/favourite_places_page.dart
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/kya/kya_title_page.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/notification/notification_page.dart
  mobile/lib/screens/notification/notification_widgets.dart
  mobile/lib/screens/on_boarding/introduction_screen.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/native_api.dart
  mobile/lib/services/notification_service.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/error_widgets.dart
Labels: ready for review, mobile-app

#1022 [Netmanager] Landing Page Map Fixes & Logout bug
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/utils/setAuthToken.js
  netmanager/src/views/layouts/common/Topbar.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1100 [Netmanager] make tabs scrollable for mobile viewports
  netmanager/src/views/pages/Download/Download.js
Labels: ready for review

#1081 Insight Redesign
  mobile/assets/icon/good_emoji.svg
  mobile/assets/icon/hazardous_emoji.svg
  mobile/assets/icon/moderate_emoji.svg
  mobile/assets/icon/ufgs_emoji.svg
  mobile/assets/icon/unhealthy_emoji.svg
  mobile/assets/icon/very_unhealthy_emoji.svg
  mobile/lib/blocs/insights/insights_bloc.dart
  mobile/lib/blocs/insights/insights_event.dart
  mobile/lib/blocs/insights/insights_state.dart
  mobile/lib/constants/api.dart
  mobile/lib/main_common.dart
  mobile/lib/models/air_quality_reading.dart
  mobile/lib/models/chart_data.dart
  mobile/lib/models/chart_data.g.dart
  mobile/lib/models/database.dart
  mobile/lib/models/database.g.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/insight.dart
  mobile/lib/models/models.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
  mobile/lib/screens/insights/daily_insights_tab.dart
  mobile/lib/screens/insights/hourly_insights_tab.dart
  mobile/lib/screens/insights/insights_page.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/native_api.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/themes/colors.dart
  mobile/lib/utils/data_formatter.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/utils/pm.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/icons.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1105 [WEBSITE] Events Model and dynamic frontend
  website/backend/event/__init__.py
  website/backend/event/admin.py
  website/backend/event/apps.py
  website/backend/event/migrations/0001_initial.py
  website/backend/event/migrations/0002_session_order.py
  website/backend/event/migrations/__init__.py
  website/backend/event/models.py
  website/backend/event/serializers.py
  website/backend/event/tests.py
  website/backend/event/views.py
  website/backend/settings.py
  website/backend/urls.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/Events/EventSlice.js
  website/frontend/reduxStore/index.js
  website/frontend/src/assets/img/Events/banner.jpg
  website/frontend/src/assets/img/Events/banner.png
  website/frontend/src/assets/img/Events/event-placeholder.jpg
  website/frontend/src/pages/Events/Details.js
  website/frontend/src/pages/Events/EventCard.js
  website/frontend/src/pages/Events/Header.js
  website/frontend/src/pages/Events/Navigation.js
  website/frontend/src/pages/Events/index.js
  website/frontend/styles/Events.scss
  website/requirements.txt
Labels: ready for review

#1090 [Collocation] Ft device status table
  platform/public/icons/Actions/addBoxed.svg
  platform/public/icons/Actions/view_week.svg
  platform/public/icons/Common/more_horiz.svg
  platform/public/icons/pages.svg
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Collocation/AddMonitor/Calendar/index.jsx
  platform/src/common/components/Collocation/AddMonitor/Skeletion/Calendar.jsx
  platform/src/common/components/Collocation/AddMonitor/Skeletion/Table.jsx
  platform/src/common/components/Collocation/AddMonitor/Skeletion/index.jsx
  platform/src/common/components/Collocation/AddMonitor/Table/DataTable.jsx
  platform/src/common/components/Collocation/AddMonitor/Table/Pagination.jsx
  platform/src/common/components/Collocation/AddMonitor/Table/SearchBar.jsx
  platform/src/common/components/Collocation/AddMonitor/Table/index.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/SearchBar.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/Skeleton.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/index.jsx
  platform/src/common/components/Collocation/DeviceStatus/Tabs/Tab.jsx
  platform/src/common/components/Collocation/DeviceStatus/Tabs/index.jsx
  platform/src/common/components/Collocation/header.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/lib/store/index.js
  platform/src/lib/store/services/collocation/collocationDataSlice.js
  platform/src/lib/store/services/collocation/index.js
  platform/src/lib/store/services/collocation/selectedCollocateDevicesSlice.js
  platform/src/pages/analytics/airqlouds.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/collocate_success.jsx
  platform/src/pages/collocation/overview.jsx
  platform/src/pages/index.jsx
  platform/tailwind.config.js
Labels: ready for review

#1080 [Mobile App] Home page animations
  mobile/analysis_options.yaml
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/blocs/dashboard/dashboard_bloc.dart
  mobile/lib/blocs/dashboard/dashboard_event.dart
  mobile/lib/blocs/dashboard/dashboard_state.dart
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/blocs/nearby_location/nearby_location_state.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/screens/auth/auth_verification.dart
  mobile/lib/screens/auth/email_auth_widget.dart
  mobile/lib/screens/auth/phone_auth_widget.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_view_legacy.txt
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/favourite_places/favourite_places_page.dart
  mobile/lib/screens/feedback/feedback_page.dart
  mobile/lib/screens/for_you_page.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/insights/insights_page.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/notification/notification_page.dart
  mobile/lib/screens/on_boarding/introduction_screen.dart
  mobile/lib/screens/on_boarding/location_setup_screen.dart
  mobile/lib/screens/on_boarding/notifications_setup_screen.dart
  mobile/lib/screens/on_boarding/profile_setup_screen.dart
  mobile/lib/screens/on_boarding/setup_complete_screeen.dart
  mobile/lib/screens/profile/profile_view.dart
  mobile/lib/screens/search/search_page.dart
  mobile/lib/screens/settings/about_page.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/screens/web_view_page.dart
  mobile/lib/services/location_service.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/error_widgets.dart
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1108 [Netmanager] Fixed device deployment date in device table
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#1110 [Netmanager] add network field to sites and devices
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/Sites/SiteToolbar.js
  netmanager/src/views/components/Sites/SiteView.js
Labels: ready for review

#1111 move to production
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/Sites/SiteToolbar.js
  netmanager/src/views/components/Sites/SiteView.js
Labels: ready for review

#1107 MOB-194-Configure air Quality Messages
  mobile/lib/models/insight.dart
Labels: ready for review

#1112 Move to production
  mobile/lib/models/insight.dart
Labels: ready for review

#1113 [Collocation] Ft toast component
  platform/public/icons/Common/warning_circle.jsx
  platform/src/common/components/Toast/error.jsx
  platform/src/common/components/Toast/index.jsx
  platform/src/common/components/Toast/success.jsx
  platform/src/common/components/Toast/warning.jsx
  platform/src/lib/store/services/collocation/collocationDataSlice.js
  platform/src/lib/store/services/collocation/index.js
  platform/src/pages/_document.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
Labels: ready for review

#1114 [WEBSITE] Events Fixes
  website/backend/event/migrations/0003_alter_session_options.py
  website/backend/event/models.py
  website/frontend/src/pages/Events/Details.js
  website/frontend/styles/Events.scss
  website/frontend/styles/index.scss
Labels: ready for review

#1117 [Nemanager] add kcca logo to topbar of airqo dashboard
  netmanager/src/views/layouts/common/Topbar.js
Labels: ready for review

#1118 move to production
  netmanager/src/views/layouts/common/Topbar.js
Labels: ready for review

#1121 [Netmanager] remove kcca logo
  netmanager/src/views/layouts/common/Topbar.js
Labels: ready for review

#1122 move to production
  netmanager/src/views/layouts/common/Topbar.js
Labels: ready for review

#1104 Updating app versions for release to production
  mobile/android/Gemfile.lock
  mobile/android/fastlane/release_notes.txt
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/ios/Runner/Info.plist
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review

#1123 move to production
  mobile/android/Gemfile.lock
  mobile/android/fastlane/release_notes.txt
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/ios/Runner/Info.plist
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review

#1124 [WEBSITE] Monitor Page
  website/.env.sample
  website/frontend/App.js
  website/frontend/src/assets/docs/AirQoMonitorUserGuideV04.pdf
  website/frontend/src/assets/docs/Binos-Maintenance-Manual.pdf
  website/frontend/src/assets/img/OurProducts/Monitor/Africa.png
  website/frontend/src/assets/img/OurProducts/Monitor/activate.png
  website/frontend/src/assets/img/OurProducts/Monitor/monitor.png
  website/frontend/src/assets/img/OurProducts/Monitor/section-1.png
  website/frontend/src/assets/img/OurProducts/Monitor/section-2.png
  website/frontend/src/components/OurProducts/Header.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/Events/Details.js
  website/frontend/src/pages/Events/EventCard.js
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/src/pages/OurProducts/MonitorPage.js
  website/frontend/styles/Events.scss
  website/frontend/styles/Products.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
Labels: ready for review

#1055 MOB-164 Mobile Dynamic Health Tips
  mobile/assets/images/child.png
  mobile/assets/images/family.png
  mobile/assets/images/old_man.png
  mobile/assets/images/pregnant_woman.png
  mobile/lib/models/air_quality_reading.dart
  mobile/lib/models/air_quality_reading.g.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/health_tip.dart
  mobile/lib/models/health_tip.g.dart
  mobile/lib/models/insight.dart
  mobile/lib/models/models.dart
  mobile/lib/utils/pm.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/health_tip.dart
  mobile/lib/widgets/widgets.dart
Labels: ready for review, mobile-app

#1128 move to production
  mobile/assets/images/child.png
  mobile/assets/images/family.png
  mobile/assets/images/old_man.png
  mobile/assets/images/pregnant_woman.png
  mobile/lib/models/air_quality_reading.dart
  mobile/lib/models/air_quality_reading.g.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/health_tip.dart
  mobile/lib/models/health_tip.g.dart
  mobile/lib/models/insight.dart
  mobile/lib/models/models.dart
  mobile/lib/utils/pm.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/health_tip.dart
  mobile/lib/widgets/widgets.dart
Labels: ready for review

#1130 [Mobile app] Hotfix health tips
  mobile/ios/Podfile.lock
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/health_tip.dart
  mobile/lib/models/health_tip.g.dart
  mobile/lib/models/hive_type_id.dart
  mobile/lib/services/hive_service.dart
Labels: ready for review

#1131 [WEBSITE] Analytics Page
  website/frontend/App.js
  website/frontend/src/assets/img/OurProducts/Analytics/analytics-dashboard.png
  website/frontend/src/assets/img/OurProducts/Analytics/analytics-header.png
  website/frontend/src/assets/img/OurProducts/Analytics/section-1-overlap.png
  website/frontend/src/assets/img/OurProducts/Analytics/section-1.png
  website/frontend/src/assets/img/OurProducts/Analytics/section-2.png
  website/frontend/src/components/Footer.js
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/OurProducts/AnalyticsPage.js
  website/frontend/src/pages/OurProducts/MonitorPage.js
  website/frontend/styles/Footer.scss
  website/frontend/styles/Products.scss
Labels: ready for review
