Repository airqo-platform/AirQo-frontend, pull requests merged in 2023-01, with the labels that each got.

#910 [Mobile] Create ios flavours
  mobile/README.md
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/ios/Runner.xcodeproj/xcshareddata/xcschemes/airqo.xcscheme
  mobile/ios/Runner.xcodeproj/xcshareddata/xcschemes/airqodev.xcscheme
  mobile/ios/Runner/Base.lproj/Main.storyboard
  mobile/ios/Runner/Info.plist
  mobile/ios/config/airqo/.gitignore
  mobile/ios/config/airqodev/.gitignore
Labels: ready for review

#1001 [Legacy Platform] Ft load map nodes
  netmanager/src/App.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/SignUp/Login.js
Labels: ready for review

#1002 [Website] Ft tweets on homepage
  website/frontend/src/components/Tweets.js
  website/frontend/src/pages/HomePage.js
Labels: ready for review

#989 [MOBILE] Fix Firebase Crashlytics issues
  mobile/lib/blocs/account/account_bloc.dart
  mobile/lib/screens/analytics/analytics_view.dart
Labels: ready for review

#993 [Mobile App] Error and empty state widgets
  mobile/assets/icon/loader.svg
  mobile/assets/icon/no_analytics_icon.svg
  mobile/assets/icon/no_favorite_places_icon.svg
  mobile/assets/icon/no_kya_icon.svg
  mobile/lib/blocs/dashboard/dashboard_bloc.dart
  mobile/lib/blocs/dashboard/dashboard_event.dart
  mobile/lib/blocs/dashboard/dashboard_state.dart
  mobile/lib/blocs/map/map_bloc.dart
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/blocs/nearby_location/nearby_location_event.dart
  mobile/lib/blocs/nearby_location/nearby_location_state.dart
  mobile/lib/blocs/search/search_bloc.dart
  mobile/lib/blocs/search/search_event.dart
  mobile/lib/constants/config.dart
  mobile/lib/models/air_quality_reading.dart
  mobile/lib/models/analytics.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/screens/analytics/analytics_view.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/favourite_places/favourite_places_page.dart
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
  mobile/lib/screens/feedback/feedback_page.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/location_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/widgets/custom_shimmer.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/dialogs.dart
  mobile/lib/widgets/error_widgets.dart
  mobile/packages/airqo_api/lib/src/airqo_api_client.dart
  mobile/packages/airqo_api/lib/src/models/measurement.dart
  mobile/packages/airqo_api/lib/src/models/measurement.g.dart
  mobile/packages/airqo_api/lib/src/models/measurement_value.dart
  mobile/packages/airqo_api/lib/src/models/measurement_value.g.dart
  mobile/packages/airqo_api/lib/src/models/models.dart
  mobile/packages/airqo_api/lib/src/models/prediction.dart
  mobile/packages/airqo_api/lib/src/search_api_client.dart
  mobile/packages/airqo_api/lib/src/utils.dart
  mobile/packages/app_repository/lib/src/models/models.dart
  mobile/packages/app_repository/lib/src/models/region.dart
  mobile/packages/app_repository/lib/src/models/site_reading.dart
Labels: ready for review

#1000 Reset Network Uptime Period from 28 days to 1 day
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
Labels: ready for review

#1005 [Netmanager] Changed Leaderboard time period
  netmanager/src/views/charts/ChartContainer.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
Labels: ready for review

#1006 [Mobile app] Updating dependency packages
  mobile/android/app/build.gradle
  mobile/android/build.gradle
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/main_common.dart
  mobile/lib/models/database.g.dart
  mobile/lib/screens/web_view_page.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#743 Mob 44 interactions design
  mobile/lib/blocs/account/account_bloc.dart
  mobile/lib/blocs/account/account_event.dart
  mobile/lib/blocs/account/account_state.dart
  mobile/lib/blocs/blocs.dart
  mobile/lib/blocs/kya/kya_bloc.dart
  mobile/lib/blocs/kya/kya_event.dart
  mobile/lib/blocs/kya/kya_state.dart
  mobile/lib/main_common.dart
  mobile/lib/models/kya.dart
  mobile/lib/models/kya.g.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/kya/kya_title_page.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1008 [Mobile app] new release
  mobile/android/release_notes.txt
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/blocs/kya/kya_state.dart
  mobile/lib/constants/config.dart
  mobile/lib/main_common.dart
  mobile/lib/models/database.dart
  mobile/lib/models/database.g.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/hive_type_id.dart
  mobile/lib/models/json_parsers.dart
  mobile/lib/models/kya.dart
  mobile/lib/models/kya.g.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.yaml
Labels: mobile-app

#1011 Fix Broken link in mobile README file #1010
  mobile/README.md
Labels: ready for review, mobile-app

#1009 [Website] Publications
  website/backend/publications/__init__.py
  website/backend/publications/admin.py
  website/backend/publications/apps.py
  website/backend/publications/migrations/0001_initial.py
  website/backend/publications/migrations/__init__.py
  website/backend/publications/models.py
  website/backend/publications/serializers.py
  website/backend/publications/tests.py
  website/backend/publications/views.py
  website/backend/settings.py
  website/backend/urls.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/Publications/actions.js
  website/frontend/reduxStore/Publications/operations.js
  website/frontend/reduxStore/Publications/reducers.js
  website/frontend/reduxStore/Publications/selectors.js
  website/frontend/reduxStore/index.js
  website/frontend/src/components/Footer.js
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
  website/frontend/src/pages/OurSolutions/ResearchPage.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/src/pages/Publications/CardComponent.js
  website/frontend/src/pages/Publications/Pagination.js
  website/frontend/src/pages/Publications/Publications.js
  website/frontend/src/pages/Publications/ReportComponent.js
  website/frontend/styles/Press.scss
  website/frontend/styles/PublicationPage.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/index.scss
Labels: ready for review

#1014 Update old versions of GitHub actions
  .github/workflows/dart-code-metrics.yaml
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  .github/workflows/test-changes.yml
Labels: enhancement, ready for review, devops

#1020 [Website] Get Involved button
  website/frontend/src/components/GetInvolvedModal.js
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/src/pages/GetInvolved/CheckMail.js
  website/frontend/src/pages/GetInvolved/Register.js
  website/frontend/src/pages/GetInvolved/index.js
  website/frontend/styles/GetInvolved.scss
  website/frontend/styles/GetInvolvedModal.scss
  website/frontend/styles/index.scss
Labels: ready for review

#1021 [Mobile app] data serialisation and map hot fixes.
  mobile/analysis_options.yaml
  mobile/ios/Podfile.lock
  mobile/lib/models/air_quality_reading.dart
  mobile/lib/models/air_quality_reading.g.dart
  mobile/lib/screens/analytics/analytics_view.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/auth/auth_verification.dart
  mobile/lib/screens/auth/auth_widgets.dart
  mobile/lib/screens/auth/email_auth_widget.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/favourite_places/favourite_places_page.dart
  mobile/lib/screens/insights/daily_insights_tab.dart
  mobile/lib/screens/insights/hourly_insights_tab.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/map/map_view.dart
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/notification/notification_page.dart
  mobile/lib/screens/on_boarding/on_boarding_widgets.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/utils/data_formatter.dart
  mobile/lib/utils/date.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/utils/utils.dart
  mobile/lib/widgets/custom_widgets.dart
Labels: ready for review, hotfix, mobile-app

#707 Fault detection frontend
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/AppRoutes.js
  netmanager/src/redux/FaultDetection/actions.js
  netmanager/src/redux/FaultDetection/operations.js
  netmanager/src/redux/FaultDetection/reducers.js
  netmanager/src/redux/FaultDetection/selectors.js
  netmanager/src/views/apis/faultDetection.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementFaults.js
  netmanager/src/views/components/Table/ColumnGroupingTable.js
  netmanager/src/views/components/Table/CustomMaterialTable.js
  netmanager/src/views/components/Table/Table.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: work in progress

#1026 [Website] Hotjar setup
  website/frontend/templates/index.html
Labels: ready for review

#1007 CI-CD-production-android
  .github/workflows/deploy-android-to-firebase-app-distribution.yml
  .github/workflows/deploy-android-to-play-console.yml
  .github/workflows/deploy-mobile-android-to-firebase-app-distribution.yml
  mobile/android/Gemfile.lock
  mobile/android/app/build.gradle
  mobile/android/fastlane/.gitignore
  mobile/android/fastlane/Appfile
  mobile/android/fastlane/Fastfile
  mobile/android/fastlane/Pluginfile
  mobile/android/fastlane/README.md
  mobile/android/fastlane/metadata/android/en-US/full_description.txt
  mobile/android/fastlane/metadata/android/en-US/images/featureGraphic.jpeg
  mobile/android/fastlane/metadata/android/en-US/images/icon.jpeg
  mobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.jpeg
  mobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.jpeg
  mobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/3_en-US.
  mobile/android/fastlane/metadata/android/en-US/short_description.txt
  mobile/android/fastlane/metadata/android/en-US/title.txt
  mobile/android/fastlane/metadata/android/en-US/video.txt
  mobile/android/fastlane/release_notes.txt
  mobile/android/release_notes.txt
Labels: ready for review, mobile-app

#1029 [MOBILE] Move to production
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/ios/Runner/Info.plist
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#882 Showcase/ Tutorial for the mobile app features
  mobile/lib/constants/config.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/for_you_page.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1017 [Website] Impact Numbers
  website/frontend/src/assets/svg/ImpactNumbers/Community.svg
  website/frontend/src/assets/svg/ImpactNumbers/Monitor.svg
  website/frontend/src/assets/svg/ImpactNumbers/Network.svg
  website/frontend/src/assets/svg/ImpactNumbers/Partners.svg
  website/frontend/src/assets/svg/ImpactNumbers/Publications.svg
  website/frontend/src/assets/svg/ImpactNumbers/Records.svg
  website/frontend/src/components/AirQuality/AirQuality.js
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/src/pages/HomePage.js
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
  website/frontend/src/pages/OurSolutions/CommunityPage.js
  website/frontend/src/pages/OurSolutions/ResearchPage.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/ImpactNumbers.scss
  website/frontend/styles/Monitor.scss
  website/frontend/styles/index.scss
  website/frontend/styles/lib/colors.scss
  website/frontend/templates/index.html
  website/frontend/utils/seo.js
Labels: ready for review

#1024 added a line break under basic maintenance
  docs/hardware/monitor.md
Labels: ready for review
