Repository airqo-platform/AirQo-frontend, pull requests merged in 2023-02, with the labels that each got.

#1033 [Urgent] add MIT license
  LICENSE
Labels: ready for review, priority-high

#1023 [Platform] Collocation pages
  platform/.eslintrc.json
  platform/.vscode/extensions.json
  platform/.vscode/launch.json
  platform/.vscode/settings.json
  platform/package.json
  platform/prettier.config.js
  platform/public/icons/Actions/addBoxed.svg
  platform/public/icons/Actions/upload.svg
  platform/public/icons/Collocation/collocate.svg
  platform/public/icons/Collocation/collocation.svg
  platform/public/icons/Collocation/overview.svg
  platform/src/common/components/Collocation/header.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1028 [MOBILE] CI/CD Fix ruby installation path - production
  .github/workflows/deploy-android-to-play-store.yml
Labels: ready for review, mobile-app, devops

#1027 [MOBILE] CI/CD Fix ruby installation path - staging
  .github/workflows/deploy-android-to-firebase-app-distribution.yml
Labels: ready for review, mobile-app, devops

#1031 [MOBILE APP] codebase cleanup
  mobile/README.md
  mobile/lib/blocs/dashboard/dashboard_bloc.dart
  mobile/lib/blocs/dashboard/dashboard_event.dart
  mobile/lib/blocs/feedback/feedback_bloc.dart
  mobile/lib/blocs/feedback/feedback_event.dart
  mobile/lib/blocs/insights/insights_event.dart
  mobile/lib/main.dart
  mobile/lib/screens/auth/auth_verification.dart
  mobile/lib/screens/auth/auth_widgets.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/feedback/feedback_page_widgets.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/notification/notification_widgets.dart
  mobile/lib/screens/on_boarding/introduction_screen.dart
  mobile/lib/screens/on_boarding/location_setup_screen.dart
  mobile/lib/screens/on_boarding/notifications_setup_screen.dart
  mobile/lib/screens/on_boarding/on_boarding_widgets.dart
  mobile/lib/screens/on_boarding/profile_setup_screen.dart
  mobile/lib/screens/on_boarding/setup_complete_screeen.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/profile/profile_view.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/screens/settings/about_page.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/location_service.dart
  mobile/lib/themes/app_theme.dart
  mobile/lib/widgets/error_widgets.dart
  mobile/lib/widgets/health_tip.dart
  mobile/lib/widgets/text_fields.dart
  mobile/lib/widgets/tooltip.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1030 Change image host to eu.gcr.io
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  k8s/calibrate/prod-airqo-calibrate-app.yaml
  k8s/calibrate/stage-airqo-calibrate-app.yaml
  k8s/calibrate/values-dev.yaml
  k8s/calibrate/values-prod.yaml
  k8s/calibrate/values-stage.yaml
  k8s/docs/prod-airqo-docs.yaml
  k8s/docs/stage-airqo-docs.yaml
  k8s/docs/values-dev.yaml
  k8s/docs/values-prod.yaml
  k8s/docs/values-stage.yaml
  k8s/netmanager/prod-airqo-platform-frontend.yaml
  k8s/netmanager/stage-airqo-platform-frontend.yaml
  k8s/netmanager/values-dev.yaml
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/prod-airqo-next-platform.yaml
  k8s/platform/stage-airqo-next-platform.yaml
  k8s/platform/values-dev.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
Labels: enhancement, ready for review, devops

#1040 [Netmanager] Remove loader from Maintenance logs table
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceLogs.js
Labels: ready for review

#1050 use env value for registry
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: ready for review, hotfix

#1042 [Netmanager] Soft add device support
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#1037 [Netmanager] Add country field to request data access form
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
  netmanager/src/views/pages/SignUp/Register.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
Labels: ready for review

#1059 [Website] Addressing User Feedback
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/styles/GetInvolvedModal.scss
Labels: ready for review

#1060 move to production
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/styles/GetInvolvedModal.scss
Labels: ready for review

#1063 [Platform] Add Monitor Skeleton
  platform/package.json
  platform/public/icons/Common/arrowLeft.svg
  platform/public/icons/Common/arrow_right_blue.svg
  platform/src/common/components/Layout/content_box.jsx
  platform/src/common/components/Navigation/breadcrumb.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1056 [MOBILE APP] updating app versions
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/constants/config.dart
  mobile/lib/screens/map/map_view.dart
  mobile/lib/screens/search/search_page.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1065 Revert "[Platform] Add Monitor Skeleton"
  platform/package.json
  platform/public/icons/Common/arrowLeft.svg
  platform/public/icons/Common/arrow_right_blue.svg
  platform/src/common/components/Layout/content_box.jsx
  platform/src/common/components/Navigation/breadcrumb.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1057 [Collocation] Add Monitor Table UI
  platform/package.json
  platform/public/icons/Actions/filter_alt.svg
  platform/public/icons/Actions/search.svg
  platform/public/icons/Actions/sort_by_alpha.svg
  platform/public/icons/arrow_drop_down.js
  platform/public/icons/arrow_drop_down.svg
  platform/public/icons/keyboard_arrow_left.svg
  platform/public/icons/keyboard_arrow_right.svg
  platform/public/icons/keyboard_backspace.svg
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/common/components/Skeleton/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/urls/deviceRegistry.js
  platform/src/core/utils/dateTime.js
  platform/src/core/utils/strings.js
  platform/src/lib/envConstants.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/deviceRegistry.js
  platform/src/pages/_app.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1062 [Netmanager] Export data options
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/pages/Download/Download.js
Labels: ready for review

#1061 [Website] Ft upgrade packages
  website/Dockerfile
  website/frontend/index.js
  website/frontend/src/components/nav/NavTab.js
  website/package-lock.json
  website/package.json
Labels: ready for review

#1054 MOB-171-Improvements to the showcase
  mobile/lib/constants/config.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/for_you_page.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/pubspec.lock
Labels: ready for review, mobile-app

#1070 Fix firebase options filename
  .github/workflows/deploy-android-to-play-store.yml
Labels: mobile-app

#1072 Hotfix for showcase package upgrade
  mobile/lib/screens/dashboard/dashboard_view.dart
Labels: ready for review, hotfix, mobile-app

#1058 only pull images when they are not present locally
  k8s/calibrate/prod-airqo-calibrate-app.yaml
  k8s/calibrate/stage-airqo-calibrate-app.yaml
  k8s/docs/prod-airqo-docs.yaml
  k8s/docs/stage-airqo-docs.yaml
  k8s/netmanager/prod-airqo-platform-frontend.yaml
  k8s/netmanager/stage-airqo-platform-frontend.yaml
  k8s/platform/prod-airqo-next-platform.yaml
  k8s/platform/stage-airqo-next-platform.yaml
Labels: enhancement, ready for review

#1076 Correct metadata path, cleanup
  .github/workflows/deploy-android-to-play-store.yml
  mobile/android/fastlane/Appfile
  mobile/android/fastlane/Fastfile
  mobile/android/fastlane/metadata/android/en-US/full_description.txt
  mobile/android/fastlane/metadata/android/en-US/images/featureGraphic.jpeg
  mobile/android/fastlane/metadata/android/en-US/images/icon.jpeg
  mobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/1_en-US.jpeg
  mobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/2_en-US.jpeg
  mobile/android/fastlane/metadata/android/en-US/images/phoneScreenshots/3_en-US.
  mobile/android/fastlane/metadata/android/en-US/short_description.txt
  mobile/android/fastlane/metadata/android/en-US/title.txt
  mobile/android/fastlane/metadata/android/en-US/video.txt
Labels: mobile-app, devops

#1071 MOB-175-remove unused svgs and replace with Material icons
  mobile/assets/icon/chart.svg
  mobile/assets/icon/cog.svg
  mobile/assets/icon/home_icon.svg
  mobile/assets/icon/kya_stars.svg
  mobile/assets/icon/location.svg
  mobile/assets/icon/more_arrow.svg
  mobile/assets/icon/profile.svg
  mobile/assets/icon/search.svg
  mobile/assets/icon/valid_input_icon.svg
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/auth/auth_verification.dart
  mobile/lib/screens/auth/auth_widgets.dart
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/icons.dart
Labels: ready for review, mobile-app

#1069 [MOBILE APP] update screen
  mobile/assets/icon/update_icon.svg
  mobile/lib/blocs/dashboard/dashboard_bloc.dart
  mobile/lib/blocs/dashboard/dashboard_event.dart
  mobile/lib/blocs/dashboard/dashboard_state.dart
  mobile/lib/constants/api.dart
  mobile/lib/models/app_store_version.dart
  mobile/lib/models/app_store_version.g.dart
  mobile/lib/models/models.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/on_boarding/introduction_screen.dart
  mobile/lib/screens/settings/update_screen.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/widgets/icons.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
  mobile/test/extensions_test.dart
Labels: ready for review, mobile-app

#1073 [MOBILE APP] location air quality error messages
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/blocs/nearby_location/nearby_location_event.dart
  mobile/lib/blocs/nearby_location/nearby_location_state.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/services/location_service.dart
Labels: ready for review, mobile-app

#1078 use python 3.10
  website/Dockerfile
Labels: enhancement, ready for review, hotfix
