Repository airqo-platform/AirQo-frontend, pull requests merged in 2023-08, with the labels that each got.

#1386 [WEBSITE] Content Update
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/src/components/nav/TopBar.js
Labels: ready for review

#1385 move to production
  k8s/netmanager/values-prod.yaml
  mobile/lib/constants/api.dart
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/src/components/nav/TopBar.js
Labels: ready for review

#1374 Utilising search history endpoints within the mobile app
  mobile/README.md
  mobile/lib/blocs/blocs.dart
  mobile/lib/blocs/search/search_bloc.dart
  mobile/lib/blocs/search/search_event.dart
  mobile/lib/blocs/search/search_state.dart
  mobile/lib/blocs/search_history/search_history_bloc.dart
  mobile/lib/blocs/search_history/search_history_event.dart
  mobile/lib/blocs/search_history/search_history_state.dart
  mobile/lib/constants/api.dart
  mobile/lib/main_common.dart
  mobile/lib/models/hive_type_id.dart
  mobile/lib/models/search_history.dart
  mobile/lib/models/search_history.g.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/search/search_page.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/location_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/utils/rating.dart
  mobile/test/api/search_history_test.dart
Labels: ready for review, mobile-app

#1383 Location History Bug fixes
  mobile/lib/models/favourite_place.dart
  mobile/lib/models/location_history.dart
  mobile/lib/services/rest_api.dart
  mobile/test/api/location_history_test.dart
Labels: ready for review, mobile-app

#1388 [Nemanager] Migrate analytics apis
  netmanager/src/config/urls/analytics.js
  netmanager/src/config/urls/authService.js
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/config/urls/locationRegistry.js
  netmanager/src/config/urls/metaData.js
  netmanager/src/redux/Dashboard/actions.js
  netmanager/src/redux/Dashboard/operations.js
  netmanager/src/redux/Dashboard/reducers/dashboardReducer.js
  netmanager/src/redux/Dashboard/reducers/locationFilterReducer.js
  netmanager/src/redux/Dashboard/selectors.js
  netmanager/src/redux/DeviceRegistry/actions.js
  netmanager/src/redux/DeviceRegistry/operations.js
  netmanager/src/redux/DeviceRegistry/reducers/components.js
  netmanager/src/redux/DeviceRegistry/reducers/index.js
  netmanager/src/redux/DeviceRegistry/selectors.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceComponents.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceOverview.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/CustomisableChart/CustomisableChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#1355 hotfix - home screen widget errors
  mobile/android/app/src/main/kotlin/com/airqo/app/AirQoCircularWidget.kt
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/services/widget_service.dart
Labels: ready for review, mobile-app

#1393 [NETMANAGER] Generating access tokens
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/__tests__/GenerateToken.test.js
  netmanager/src/__tests__/__snapshots__/GenerateToken.test.js.snap
  netmanager/src/config/urls/analytics.js
  netmanager/src/setupTests.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/pages/Settings/Settings.js
  netmanager/src/views/pages/Settings/components/GenerateToken/GenerateToken.js
Labels: ready for review

#1371 Kya Bug Fixes
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/services/rest_api.dart
Labels: ready for review, mobile-app

#1398 [WEB] Adding Jest Test Library
  website/.babelrc
  website/package-lock.json
  website/package.json
Labels: ready for review

#1399 Minor improvements to the Widget
  mobile/android/app/src/main/kotlin/com/airqo/app/AirQoCircularWidget.kt
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/services/widget_service.dart
Labels: ready for review, mobile-app

#1401 [Netmanager] Modified logs page
  netmanager/src/AppRoutes.js
  netmanager/src/__tests__/Logs/logs.test.js
  netmanager/src/redux/Logs/actions.js
  netmanager/src/redux/Logs/operations.js
  netmanager/src/redux/Logs/reducer.js
  netmanager/src/redux/index.js
  netmanager/src/setupTests.js
  netmanager/src/views/components/Table/CustomMaterialTable.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Logs/BreadCrumb/index.js
  netmanager/src/views/pages/Logs/DataExport/index.js
  netmanager/src/views/pages/Logs/ServiceDropdown/index.js
  netmanager/src/views/pages/Logs/index.js
  netmanager/src/views/pages/Logs/logs_table.js
Labels: ready for review

#1397 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  mobile/android/app/src/main/kotlin/com/airqo/app/AirQoCircularWidget.kt
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/email_authentication/email_auth_widgets.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/phone_authentication/phone_auth_widgets.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/services/widget_service.dart
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/AppRoutes.js
  netmanager/src/__tests__/GenerateToken.test.js
  netmanager/src/__tests__/Logs/logs.test.js
  netmanager/src/__tests__/__snapshots__/GenerateToken.test.js.snap
  netmanager/src/config/urls/analytics.js
  netmanager/src/redux/Logs/actions.js
  netmanager/src/redux/Logs/operations.js
  netmanager/src/redux/Logs/reducer.js
  netmanager/src/redux/index.js
  netmanager/src/setupTests.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/components/Table/CustomMaterialTable.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Logs/BreadCrumb/index.js
  netmanager/src/views/pages/Logs/DataExport/index.js
  netmanager/src/views/pages/Logs/ServiceDropdown/index.js
  netmanager/src/views/pages/Logs/index.js
  netmanager/src/views/pages/Logs/logs_table.js
  netmanager/src/views/pages/Settings/Settings.js
  netmanager/src/views/pages/Settings/components/GenerateToken/GenerateToken.js
  website/.babelrc
  website/package-lock.json
  website/package.json
Labels: ready for review

#1403 removing date from insights
  mobile/lib/screens/insights/insights_widgets.dart
Labels: ready for review, mobile-app

#1406 Updated Translation for Modified Text
  mobile/lib/screens/dashboard/dashboard_widgets.dart
Labels: ready for review, mobile-app

#1414 [Netmanager] Switch device monitoring apis to v2
  netmanager/src/config/urls/deviceMonitoring.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceOverviewChart.js
Labels: ready for review

#1415 [Netmanager] Device recallType implementations
  netmanager/src/__tests__/RecallDevice.test.js
  netmanager/src/__tests__/__snapshots__/RecallDevice.test.js.snap
  netmanager/src/assets/css/dropdown.css
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceLogs.js
Labels: ready for review

#1417 [WEBSITE] API V2 Configuration
  website/frontend/apis/index.js
Labels: ready for review

#1418 [WEBSITE] Adjust Partners' image onClick Handler
  website/frontend/src/pages/AboutUsPage.js
Labels: ready for review

#1420 [Analytics] added page titles to collocation pages
  platform/src/pages/analytics/collocation/add_monitor.jsx
  platform/src/pages/analytics/collocation/collocate.jsx
  platform/src/pages/analytics/collocation/overview.jsx
  platform/src/pages/analytics/collocation/reports/[device].jsx
  platform/src/pages/analytics/collocation/reports/index.jsx
  platform/src/pages/analytics/collocation/reports/monitor_report/[device].jsx
Labels: ready for review

#1419 [WEBSITE] Dynamic Impact numbers
  website/backend/impact/__init__.py
  website/backend/impact/admin.py
  website/backend/impact/apps.py
  website/backend/impact/migrations/0001_initial.py
  website/backend/impact/migrations/__init__.py
  website/backend/impact/models.py
  website/backend/impact/serializers.py
  website/backend/impact/tests.py
  website/backend/impact/views.py
  website/backend/settings.py
  website/backend/urls.py
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/ImpactNumbers/ImpactSlice.js
  website/frontend/reduxStore/index.js
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/src/components/__tests__/HomepageTests/Homepage.test.js
Labels: ready for review

#1314 [NETMANAGER] Heatmap Reconfiguration
  netmanager/src/__tests__/OverlayMap/OverlayMap.test.js
  netmanager/src/config/urls/predict.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/redux/MapData/reducers.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/Map/paints.js
  netmanager/src/views/pages/Map/utils.js
Labels: ready for review

#1416 [Netmanager] Sessions Timeout For user login
  netmanager/src/AppRoutes.js
  netmanager/src/__tests__/TimeSession.test.js
  netmanager/src/__tests__/__snapshots__/TimeSession.test.js.snap
Labels: ready for review, netmanager

#1421 [WEBSITE] Broken CSS fix
  website/frontend/src/components/AirQuality/AfricanCities.js
  website/frontend/src/components/AirQuality/Communities.js
  website/frontend/src/components/Hero.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/Hero.scss
  website/frontend/styles/NavTab.scss
  website/frontend/styles/TopBar.scss
Labels: ready for review

#1427 [WEBSITE] Missing API link on topbar
  website/frontend/App.js
  website/frontend/src/components/nav/TopBar.js
Labels: ready for review

#1428 Add Data provider to Insights card
  mobile/lib/models/air_quality_reading.dart
  mobile/lib/models/air_quality_reading.g.dart
  mobile/lib/screens/insights/insights_widgets.dart
Labels: ready for review

#1433 [Hotfix] Commented out the heatmap render functions
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1437 Mobile App fixes
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/widgets/dialogs.dart
Labels: ready for review

#1438 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/widgets/dialogs.dart
Labels: ready for review

#1423 [WEBSITE] Calibration Page
  website/frontend/App.js
  website/frontend/src/assets/img/OurProducts/Calibration/calibration-header.png
  website/frontend/src/assets/img/OurProducts/Calibration/section-1.jpg
  website/frontend/src/assets/img/OurProducts/Calibration/section-2.jpg
  website/frontend/src/assets/img/OurProducts/Calibration/section-3.png
  website/frontend/src/components/Footer.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/OurProducts/CalibrationPage.js
  website/frontend/styles/Products.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/lib/colors.scss
  website/package-lock.json
Labels: ready for review, airqo-website

#1439 move to production
  website/frontend/App.js
  website/frontend/src/assets/img/OurProducts/Calibration/calibration-header.png
  website/frontend/src/assets/img/OurProducts/Calibration/section-1.jpg
  website/frontend/src/assets/img/OurProducts/Calibration/section-2.jpg
  website/frontend/src/assets/img/OurProducts/Calibration/section-3.png
  website/frontend/src/components/Footer.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/OurProducts/CalibrationPage.js
  website/frontend/styles/Products.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/lib/colors.scss
  website/package-lock.json
Labels: ready for review

#1410 [NET] Adding feature to add new device hosts, and send them mobile money
  netmanager/src/AppRoutes.js
  netmanager/src/__tests__/DataDisplay/DeviceHosts.test.js
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceHosts.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceToolBar.js
  netmanager/src/views/components/Hosts/HostRegistry.js
  netmanager/src/views/components/Hosts/HostView.js
  netmanager/src/views/components/Hosts/HostsTable.js
  netmanager/src/views/components/Hosts/Table.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/ExportData/index.js
Labels: ready for review

#1444 [WEBSITE - DEVOP] Triggering new ENV Variable
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  website/.env.sample
  website/README.md
Labels: ready for review

#1446 [NET] Responsiveness and UI improvement on host addition
  netmanager/src/views/components/Hosts/HostView.js
  netmanager/src/views/components/Hosts/HostsTable.js
Labels: ready for review

#1447 [WEBSITE] Triggering ENV Variable
  website/README.md
Labels: ready for review

#1450 [Netmanager] Candidates request access for organisations functionality
  netmanager/src/redux/Join/actions.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/components/AirQlouds/AirQloudRegistry.js
  netmanager/src/views/components/AirQlouds/AirQloudsTable.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/Sites/SiteRegistry.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/layouts/common/Sidebar/components/SidebarNav/SidebarNav.js
  netmanager/src/views/pages/CandidateList/CandidateList.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
  netmanager/src/views/pages/Roles/index.js
  netmanager/src/views/pages/SignUp/Register.js
  netmanager/src/views/stateConnectors/usersStateConnector.js
Labels: ready for review

#1453 [Netmanager] hides network monitoring sidebar item for other orgs
  netmanager/src/views/layouts/common/Sidebar/components/SidebarNav/SidebarNav.js
Labels: ready for review

#1456 mobile test coverage
  .github/workflows/mobile-app-tests.yaml
  mobile/README.md
Labels: work in progress, ready for review

#1458 [HOTFIX] Fix netmanager landing page bug
  netmanager/src/views/layouts/common/Sidebar/components/SidebarNav/SidebarNav.js
Labels: ready for review

#1457 move to production
  .github/workflows/mobile-app-tests.yaml
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  mobile/README.md
  netmanager/src/views/layouts/common/Sidebar/components/SidebarNav/SidebarNav.js
Labels: ready for review

#1461 Incrementing Version Number for Android
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1430 [WEBSITE] Content and UI improvement
  website/frontend/src/components/AirQuality/AfricanCities.js
  website/frontend/src/components/AirQuality/Communities.js
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/styles/ImpactNumbers.scss
Labels: ready for review

#1452 [NETMANAGER] Access Token Management
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/pages/Settings/Settings.js
  netmanager/src/views/pages/Settings/components/GenerateToken/GenerateToken.js
  netmanager/src/views/pages/Settings/components/GenerateToken/Table.js
Labels: ready for review

#1462 [WEBSITE] Broken Analytics URL Link
  website/frontend/config/urls.js
Labels: ready for review

#1459 move to production
  .github/workflows/test-changes.yml
  README.md
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  mobile/pubspec.yaml
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/pages/Settings/Settings.js
  netmanager/src/views/pages/Settings/components/GenerateToken/GenerateToken.js
  netmanager/src/views/pages/Settings/components/GenerateToken/Table.js
  platform/README.md
  website/frontend/config/urls.js
  website/frontend/src/components/AirQuality/AfricanCities.js
  website/frontend/src/components/AirQuality/Communities.js
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/styles/ImpactNumbers.scss
Labels: ready for review

#1464 [Hotfix] Makes airqo deafult request access org
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/pages/SignUp/Register.js
Labels: ready for review

#1460 [WEBSITE] Clean-Air Page Skeleton
  website/frontend/App.js
  website/frontend/src/components/CleanAir/HomePage/Header.js
  website/frontend/src/components/CleanAir/TopBarNav/index.js
  website/frontend/src/components/Footer.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/CleanAirPress.js
  website/frontend/src/pages/CleanAir/GetInvolved.js
  website/frontend/src/pages/CleanAir/Page.js
  website/frontend/src/pages/CleanAir/index.js
  website/frontend/styles/CleanAirPage.scss
  website/frontend/styles/index.scss
Labels: ready for review

#1466 [Hotfix] fetch user roles and permissions directly from user info api
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1467 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1441 Cancel button kya
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/pubspec.lock
Labels: ready for review, mobile-app
