Repository airqo-platform/AirQo-frontend, pull requests merged in 2023-07, with the labels that each got.

#1313 Updating android and iOS versions
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1302 [Netmanager]Making the Dashboard charts to look better
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/views/components/d3/CustomisableChart.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review, netmanager

#1316 Ft docs to wiki
  calibrate/.env.sample
  calibrate/README.md
  mobile/README.md
  website/README.md
Labels: documentation, ready for review

#1324 [WEBSITE] Remove tweets components
  website/frontend/src/pages/HomePage.js
Labels: ready for review

#1325 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
Labels: ready for review

#1308 Reimplement favorite Places using Api.
  mobile/lib/blocs/favourite_place/favourite_place_bloc.dart
  mobile/lib/constants/api.dart
  mobile/lib/constants/config.dart
  mobile/lib/models/favourite_place.dart
  mobile/lib/models/favourite_place.g.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/widgets/dialogs.dart
Labels: ready for review, mobile-app

#1334 Adding error handling for iOS
  mobile/lib/constants/api.dart
  mobile/lib/constants/config.dart
  mobile/lib/main_common.dart
  mobile/lib/models/app_store_version.dart
  mobile/lib/models/app_store_version.g.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/on_boarding/introduction_screen.dart
  mobile/lib/screens/settings/about_page.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/notification_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/exception.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/error_widgets.dart
  mobile/test/api/check_if_user_exists_test.dart
  mobile/test/api/check_if_user_exists_test.mocks.dart
  mobile/test/api/fetch_air_quality_readings_test.dart
  mobile/test/api/get_app_version_test.dart
  mobile/test/api/get_app_version_test.mocks.dart
  mobile/test/api/get_mobile_carrier_test.dart
  mobile/test/api/get_mobile_carrier_test.mocks.dart
  mobile/test/api/send_email_verification_test.dart
  mobile/test/api/send_email_verification_test.mocks.dart
  mobile/test/api/send_feedback_test.dart
  mobile/test/api/send_feedback_test.mocks.dart
  mobile/test/screens/insights/insights_widgets_test.dart
  mobile/test/utils/extensions/primitive_data_types_test.dart
  mobile/test/utils/extensions_test.dart
Labels: ready for review, mobile-app

#1337 [Netmanager] Responsiveness of the y-axis on the Exceedance chart
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#1340 [NetManager] Renaming of the title from NetManager to AirQo Analytics
  netmanager/public/index.html
Labels: ready for review

#1338 [WEBSITE] Redirect Users to Specific app stores
  website/frontend/App.js
  website/frontend/src/pages/ExploreData/Redirect.js
  website/package-lock.json
  website/package.json
Labels: ready for review

#1343 [PLAT] Added 404 page
  platform/public/icons/Errors/Oops.svg
  platform/src/pages/404.jsx
Labels: ready for review

#1330 [PLAT] Sidebar and Topbar Redesign
  platform/public/icons/Actions/Notification.svg
  platform/public/icons/Actions/search_md.svg
  platform/public/icons/Home/Hello.png
  platform/public/icons/Home/illustration.jpg
  platform/public/icons/SideBar/Collapse.svg
  platform/public/icons/SideBar/Hello.png
  platform/public/icons/SideBar/Sites.svg
  platform/public/icons/SideBar/announcement_card.svg
  platform/public/icons/SideBar/bar_chart.svg
  platform/public/icons/SideBar/book_open_01.svg
  platform/public/icons/SideBar/grid_01.svg
  platform/public/icons/SideBar/home-smile.svg
  platform/public/icons/SideBar/home_smile.svg
  platform/public/icons/SideBar/illustration.jpg
  platform/public/icons/SideBar/life_buoy_02.svg
  platform/public/icons/SideBar/notification_box.svg
  platform/public/icons/SideBar/profile.svg
  platform/public/icons/SideBar/settings_02.svg
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/SideBar/AnnouncementCard.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/common/components/TopBar/TopBarItem.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/common/styles/global.scss
  platform/src/pages/Home/index.jsx
  platform/src/pages/index.jsx
Labels: ready for review, analytics

#1310 [Netmanager] Fix network uptime graph time & update battery voltage chart
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/assets/css/chart-container.css
  netmanager/src/config/urls/deviceMonitoring.js
  netmanager/src/redux/DeviceRegistry/operations.js
  netmanager/src/redux/DeviceRegistry/reducers/batteryVoltage.js
  netmanager/src/views/charts/ApexChart.js
  netmanager/src/views/charts/ChartContainer.js
  netmanager/src/views/charts/utils.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceOverviewChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/SensorChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/UptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/VoltageChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/util.js
  netmanager/src/views/containers/PageAccess.js
Labels: ready for review

#1346 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/assets/css/chart-container.css
  netmanager/src/config/urls/deviceMonitoring.js
  netmanager/src/redux/DeviceRegistry/operations.js
  netmanager/src/redux/DeviceRegistry/reducers/batteryVoltage.js
  netmanager/src/views/charts/ApexChart.js
  netmanager/src/views/charts/ChartContainer.js
  netmanager/src/views/charts/utils.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceOverviewChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/SensorChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/UptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/VoltageChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/util.js
  netmanager/src/views/containers/PageAccess.js
  platform/public/icons/Actions/Notification.svg
  platform/public/icons/Actions/search_md.svg
  platform/public/icons/Errors/Oops.svg
  platform/public/icons/Home/Hello.png
  platform/public/icons/Home/illustration.jpg
  platform/public/icons/SideBar/Collapse.svg
  platform/public/icons/SideBar/Hello.png
  platform/public/icons/SideBar/Sites.svg
  platform/public/icons/SideBar/announcement_card.svg
  platform/public/icons/SideBar/bar_chart.svg
  platform/public/icons/SideBar/book_open_01.svg
  platform/public/icons/SideBar/grid_01.svg
  platform/public/icons/SideBar/home-smile.svg
  platform/public/icons/SideBar/home_smile.svg
  platform/public/icons/SideBar/illustration.jpg
  platform/public/icons/SideBar/life_buoy_02.svg
  platform/public/icons/SideBar/notification_box.svg
  platform/public/icons/SideBar/profile.svg
  platform/public/icons/SideBar/settings_02.svg
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/SideBar/AnnouncementCard.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/common/components/TopBar/TopBarItem.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/common/styles/global.scss
  platform/src/pages/404.jsx
  platform/src/pages/Home/index.jsx
  platform/src/pages/index.jsx
Labels: ready for review

#1326 Adding deletion param to emailAuth endpoint.
  mobile/lib/services/rest_api.dart
Labels: ready for review, mobile-app

#1347 move to production
  k8s/netmanager/values-prod.yaml
  k8s/platform/values-prod.yaml
  mobile/lib/services/rest_api.dart
Labels: ready for review

#1348 [Netmanager] AirQloud based data summary reports (calibrated data availabilty for customisable time period)
  netmanager/src/config/urls/analytics.js
  netmanager/src/config/urls/deviceMonitoring.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/deviceMonitoring.js
  netmanager/src/views/components/AirQlouds/AirQloudView.js
Labels: ready for review

#1332 Rating feature
  mobile/lib/blocs/profile/profile_bloc.dart
  mobile/lib/models/app_store_version.g.dart
  mobile/lib/models/profile.dart
  mobile/lib/models/profile.g.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/utils/rating.dart
  mobile/lib/utils/utils.dart
  mobile/lib/widgets/dialogs.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1353 [Netmanager] Added editable site name and site description
  netmanager/src/views/components/Sites/SiteView.js
Labels: ready for review

#1345 [NetManager] Site activities visualization
  netmanager/src/AppRoutes.js
  netmanager/src/redux/ActivityLogs/actions.js
  netmanager/src/redux/ActivityLogs/index.js
  netmanager/src/redux/ActivityLogs/operations.js
  netmanager/src/redux/ActivityLogs/reducers/activities.js
  netmanager/src/redux/ActivityLogs/reducers/activityOptions.js
  netmanager/src/redux/ActivityLogs/reducers/activitySummary.js
  netmanager/src/redux/ActivityLogs/reducers/index.js
  netmanager/src/redux/ActivityLogs/selectors.js
  netmanager/src/redux/index.js
  netmanager/src/utils/sites.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/Activities/ActivitiesRegistry.js
  netmanager/src/views/components/Activities/ActivitiesTable.js
  netmanager/src/views/components/Activities/index.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1333 [WEBSITE] Refactor Press View to display data from the database
  website/backend/press/models.py
  website/backend/press/serializers.py
  website/backend/settings.py
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/Press/PressSlice.js
  website/frontend/reduxStore/index.js
  website/frontend/src/pages/Press/Article.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/styles/Press.scss
Labels: ready for review

#1356 [Ntmanager] Make device details view scrollable
  netmanager/src/assets/css/chart-container.css
  netmanager/src/views/charts/ChartContainer.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
Labels: ready for review

#1358 [WEBSITE] Resource Devops hack
  website/backend/event/admin.py
Labels: ready for review

#1298 [Netmanager] Tutorials on features for new users
  netmanager/src/views/components/TutorialTooltip/Tutorial.css
  netmanager/src/views/components/TutorialTooltip/Tutorial.js
  netmanager/src/views/pages/ExportData/index.js
Labels: work in progress

#1362 [PLATFORM] Account routes
  platform/src/common/components/SideBar/AnnouncementCard.jsx
  platform/src/pages/account/creation/index.jsx
Labels: ready for review

#1357 [Netmanager] Responsiveness of the Average Chart Modal header
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
Labels: ready for review

#1365 [WEB] API page implementation
  website/frontend/App.js
  website/frontend/src/assets/img/OurProducts/Api/HeaderImage.png
  website/frontend/src/assets/img/OurProducts/Api/section-1.jpg
  website/frontend/src/assets/img/OurProducts/Api/section-2.png
  website/frontend/src/assets/img/OurProducts/Api/section-3.png
  website/frontend/src/components/Footer.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/OurProducts/ApiPage.js
  website/frontend/styles/Products.scss
Labels: ready for review

#1368 [WEBSITE] Resource Fixes
  website/backend/event/admin.py
  website/frontend/src/pages/Press/Press.js
  website/frontend/src/pages/Publications/CardComponent.js
  website/frontend/src/pages/Publications/Publications.js
  website/frontend/src/pages/Publications/ReportComponent.js
  website/frontend/styles/Press.scss
  website/frontend/styles/PublicationPage.scss
Labels: ready for review

#1369 [Collocation] Status summary report
  platform/public/icons/Common/info_circle.svg
  platform/src/common/components/Collocation/AddMonitor/Calendar/index.jsx
  platform/src/common/components/Collocation/AddMonitor/Table/DataTable.jsx
  platform/src/common/components/Collocation/DeviceStatus/ReportDetailPopup/detail_card.jsx
  platform/src/common/components/Collocation/DeviceStatus/ReportDetailPopup/index.jsx
  platform/src/common/components/Collocation/DeviceStatus/ResetThreshold/index.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/index.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/common/components/Toast/index.jsx
  platform/src/core/apis/Collocation.js
  platform/src/lib/store/services/collocation/selectedCollocateDevicesSlice.js
  platform/src/pages/Home/index.jsx
  platform/src/pages/analytics/collocation/add_monitor.jsx
  platform/src/pages/analytics/collocation/collocate.jsx
  platform/src/pages/analytics/collocation/collocate_success.jsx
  platform/src/pages/analytics/collocation/overview.jsx
  platform/src/pages/analytics/collocation/reports/[device].jsx
  platform/src/pages/analytics/collocation/reports/index.jsx
  platform/src/pages/analytics/collocation/reports/monitor_report/[device].jsx
Labels: ready for review

#1351 Mob-245 Utilise kya endpoints in the mobile app
  mobile/lib/blocs/kya/kya_bloc.dart
  mobile/lib/blocs/kya/kya_bloc.g.dart
  mobile/lib/blocs/kya/kya_event.dart
  mobile/lib/blocs/kya/kya_state.dart
  mobile/lib/constants/api.dart
  mobile/lib/constants/config.dart
  mobile/lib/main_common.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/kya.dart
  mobile/lib/models/kya.g.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/kya/kya_title_page.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/native_api.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/utils/rating.dart
  mobile/test/api/kya_lessons_test.dart
  mobile/test/api/kya_lessons_test.mocks.dart
  mobile/test/cubics/kya_progress_cubic_test.dart
  mobile/test/utils/extensions/kya_test.dart
  mobile/test/utils/extensions/primitive_data_types_test.dart
Labels: ready for review, mobile-app

#1373 Using location history APIs in the mobile app.
  mobile/README.md
  mobile/lib/blocs/location_history/location_history_bloc.dart
  mobile/lib/constants/api.dart
  mobile/lib/constants/config.dart
  mobile/lib/models/location_history.dart
  mobile/lib/models/location_history.g.dart
  mobile/lib/screens/analytics/analytics_view.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/rest_api.dart
Labels: ready for review

#1380 Icon bug fix
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
Labels: ready for review, mobile-app

#1350 Mob 253 swipe to remove favourite
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
  mobile/lib/widgets/custom_widgets.dart
Labels: ready for review, mobile-app
