Repository airqo-platform/AirQo-frontend, pull requests merged in 2023-11, with the labels that each got.

#1618 [ANALYTICS] Axios instance implementation and top-tab bug fix
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/apis/Collocation.js
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/apis/Settings.js
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/index.jsx
Labels: ready for review

#1621 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/apis/Collocation.js
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/apis/Settings.js
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/index.jsx
Labels: ready for review

#1608 Inventory setup
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/inventory/.helmignore
  k8s/inventory/Chart.yaml
  k8s/inventory/templates/NOTES.txt
  k8s/inventory/templates/_helpers.tpl
  k8s/inventory/templates/deployment.yaml
  k8s/inventory/templates/hpa.yaml
  k8s/inventory/templates/service.yaml
  k8s/inventory/templates/tests/test-connection.yaml
  k8s/inventory/values-dev.yaml
  k8s/inventory/values-prod.yaml
  k8s/inventory/values-stage.yaml
Labels: ready for review

#1625 [ANALYTICS] Home page implementation
  platform/public/icons/SideBar/BarChartIcon.js
  platform/public/icons/SideBar/CollocateIcon.js
  platform/public/icons/SideBar/HomeIcon.js
  platform/public/icons/SideBar/SettingsIcon.js
  platform/public/icons/SideBar/collocation.svg
  platform/public/icons/SideBar/home_smile.svg
  platform/public/icons/SideBar/settings_02.svg
  platform/public/icons/bar_chart.svg
  platform/public/images/Home/analyticsImage.png
  platform/public/images/Home/playIcon.svg
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/pages/Home/index.jsx
Labels: ready for review

#1623 Update Mobile App Android Version
  mobile/pubspec.yaml
Labels: ready for review

#1620 Shorebird-setup
  mobile/README.md
  mobile/pubspec.lock
  mobile/pubspec.yaml
  mobile/shorebird.yaml
Labels: ready for review, mobile-app

#1626 [ANALYTICS] Responsiveness and tooltip addition to charts legend
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/Charts.js
  platform/src/pages/Home/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: ready for review

#1630 [Hotfixes] analytics UI
  platform/src/common/components/Settings/Teams/table.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/settings/Tabs/Team.jsx
Labels: ready for review

#1631 [Hotfix] Fix user details api name bug
  platform/src/pages/settings/Tabs/Profile.jsx
Labels: ready for review

#1609 Sync Mobile User and Platform Accouts
  mobile/lib/constants/api.dart
  mobile/lib/models/profile.dart
  mobile/lib/models/profile.g.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/rest_api.dart
  mobile/test/api/check_if_user_exists_test.mocks.dart
  mobile/test/api/kya_lessons_test.mocks.dart
  mobile/test/api/quiz_test.mocks.dart
  mobile/test/api/send_email_verification_test.mocks.dart
Labels: ready for review

#1600 [WEBSITE] Clean-air Network (Partners page implementation)
  website/frontend/src/__tests__/CleanAirTests/PartnersPage.test.js
  website/frontend/src/assets/img/cleanAir/acronym.jpg
  website/frontend/src/assets/img/cleanAir/clean.jpeg
  website/frontend/src/assets/img/cleanAir/goals.JPG
  website/frontend/src/assets/img/cleanAir/hero.jpg
  website/frontend/src/assets/img/cleanAir/mission.jpeg
  website/frontend/src/assets/img/cleanAir/partners-sec1.png
  website/frontend/src/assets/img/cleanAir/partners-sec2.png
  website/frontend/src/assets/img/cleanAir/partners-sec3.png
  website/frontend/src/assets/img/cleanAir/synergy.jpg
  website/frontend/src/components/CleanAir/CTAs/BottomCTAs.js
  website/frontend/src/components/CleanAir/CTAs/ButtonCTA.js
  website/frontend/src/components/CleanAir/HomePage/Header.js
  website/frontend/src/components/CleanAir/SecondaryNav/index.js
  website/frontend/src/components/CleanAir/Sections/Section.js
  website/frontend/src/components/CleanAir/Sections/SingleSection.js
  website/frontend/src/components/CleanAir/Sections/SplitSection.js
  website/frontend/src/components/CleanAir/index.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/Page.js
  website/frontend/styles/CleanAirPage.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/lib/colors.scss
  website/package-lock.json
Labels: ready for review

#1632 [Hotfix] Use axios instance for candidates and user apis
  netmanager/src/config/urls/authService.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
Labels: ready for review

#1633 [Hotfix] Candidate request fix
  netmanager/src/redux/Join/actions.js
Labels: ready for review

#1634 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  netmanager/src/redux/Join/actions.js
Labels: ready for review

#1636 [analytics] userDefaults implementation on charts
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/lib/store/services/charts/userDefaultsSlice.js
  platform/src/pages/_app.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: ready for review

#1637 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/lib/store/services/charts/userDefaultsSlice.js
  platform/src/pages/_app.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: ready for review

#1638 [analytics] code optimization for loading issue
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Layout/index.jsx
  platform/src/core/apis/Account.js
Labels: ready for review

#1639 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Layout/index.jsx
  platform/src/core/apis/Account.js
Labels: ready for review

#1640 [Netmanager] Host Registry functionality enhancement
  netmanager/src/views/components/Hosts/HostView.js
  netmanager/src/views/components/Hosts/HostsTable.js
  netmanager/src/views/components/Hosts/Table.js
Labels: ready for review

#1642 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  netmanager/src/views/components/Hosts/HostView.js
  netmanager/src/views/components/Hosts/HostsTable.js
  netmanager/src/views/components/Hosts/Table.js
Labels: ready for review

#1635 inventory-fix
  .github/workflows/deploy-frontend-pr-previews.yml
  inventory/.dockerignore
  inventory/.env.sample
  inventory/Dockerfile
  inventory/Inventory/settings.py
  inventory/README.md
  k8s/inventory/values-dev.yaml
Labels: ready for review

#1646 Inventory-url
  inventory/Inventory/settings.py
  inventory/Inventory/urls.py
  inventory/README.md
  inventory/dashboard/urls.py
  inventory/user/urls.py
Labels: work in progress, ready for review

#1648 distinguish login url
  inventory/Inventory/urls.py
Labels: ready for review

#1651 [Analytics] QA feedback and Export chart implementation
  platform/package.json
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/yarn.lock
Labels: ready for review

#1649 inventory url fix
  inventory/Inventory/settings.py
  inventory/Inventory/urls.py
  inventory/README.md
Labels: ready for review

#1652 [WEBSITE] Clean Air Resources model
  website/backend/README.md
  website/backend/cleanair/admin.py
  website/backend/cleanair/migrations/0003_cleanairresource_author_title_and_more.py
  website/backend/cleanair/migrations/0004_cleanairresource_resource_authors.py
  website/backend/cleanair/models.py
Labels: ready for review

#1658 [Analytics] Export Data & Print Report UI and functionality
  platform/package.json
  platform/public/icons/Analytics/download.svg
  platform/public/icons/Analytics/share.svg
  platform/public/icons/Common/download.svg
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Modal/ExportDataModal.jsx
  platform/src/common/components/Modal/ExportModalWrapper.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/core/apis/Analytics.js
  platform/src/core/urls/analytics.js
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
  platform/yarn.lock
Labels: ready for review

#1655 Grids cohorts feedback
  netmanager/src/AppRoutes.js
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/layouts/Landing.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Analytics/components/AirqloudDropdown.jsx
  netmanager/src/views/pages/Analytics/components/Breadcrumb.jsx
  netmanager/src/views/pages/Analytics/components/CohortsDashboard.jsx
  netmanager/src/views/pages/Analytics/components/GridsDashboard.jsx
  netmanager/src/views/pages/Analytics/index.js
  netmanager/src/views/pages/Dashboard/components/AddChart.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
  netmanager/src/views/pages/Dashboard/components/PollutantCategory/PollutantCategory.js
  netmanager/src/views/pages/NotFound/NotFound.js
  netmanager/src/views/pages/PermissionDenied/index.js
  netmanager/src/views/pages/SignUp/FunctionalLogin.js
  netmanager/src/views/pages/SignUp/Login.js
  netmanager/src/views/pages/SignUp/Register.js
Labels: ready for review

#1660 Mobile App minor Fixes and Top Card alternatives for nearest Location
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/services/app_service.dart
  mobile/lib/widgets/auth_widgets.dart
Labels: ready for review

#1661 move to production
  k8s/netmanager/values-prod.yaml
  k8s/platform/values-prod.yaml
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/services/app_service.dart
  mobile/lib/widgets/auth_widgets.dart
Labels: ready for review

#1664 move to production
  inventory/README.md
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
Labels: ready for review

#1669 [PLATFORM] Create and Update User Preferences
  platform/public/icons/Actions/bin_icon.svg
  platform/public/icons/Actions/drag_icon.svg
  platform/public/icons/Actions/drag_icon_light.svg
  platform/public/icons/Actions/star_icon.svg
  platform/public/icons/Actions/star_icon_light.svg
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/account/CreationSlice.js
  platform/src/lib/store/services/account/UserDefaultsSlice.js
  platform/src/pages/account/creation/individual/interest/[id]/[token].jsx
  platform/src/pages/account/creation/individual/register.jsx
  platform/src/pages/account/creation/organisation/verify-email.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/[token].jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/tailwind.config.js
Labels: ready for review

#1675 [Analytics] Added organization dropdown and page access control
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/pages/settings/index.jsx
Labels: ready for review

#1678 [Analytics] Organization profile page
  platform/public/icons/Common/copy.svg
  platform/public/icons/Settings/globe.svg
  platform/src/common/components/TextInputField/index.jsx
  platform/src/core/apis/Account.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/groups/GroupInfoSlice.js
  platform/src/pages/settings/Tabs/OrganizationProfile.jsx
  platform/src/pages/settings/index.jsx
Labels: ready for review

#1671 [Analytics] Code refactoring and UI improvements
  platform/public/icons/circleTick.js
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Modal/ExportModalWrapper.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/common/components/Modal/videoModals/CustomModal.jsx
  platform/src/common/components/skeletons/HomeSkeleton.jsx
  platform/src/common/components/steppers/CircularStepper.jsx
  platform/src/core/apis/Account.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/charts/ChartData.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/lib/store/services/charts/userDefaultsSlice.js
  platform/src/pages/Home/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: work in progress

#1673 move to production
  inventory/Inventory/settings.py
  inventory/requirements.txt
  k8s/inventory/values-prod.yaml
  k8s/inventory/values-stage.yaml
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  netmanager/README.md
  platform/public/icons/Common/copy.svg
  platform/public/icons/Settings/globe.svg
  platform/public/icons/circleTick.js
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Modal/ExportModalWrapper.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/common/components/Modal/videoModals/CustomModal.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/TextInputField/index.jsx
  platform/src/common/components/skeletons/HomeSkeleton.jsx
  platform/src/common/components/steppers/CircularStepper.jsx
  platform/src/core/apis/Account.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/charts/ChartData.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/lib/store/services/charts/userDefaultsSlice.js
  platform/src/lib/store/services/groups/GroupInfoSlice.js
  platform/src/pages/Home/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
  platform/src/pages/settings/Tabs/OrganizationProfile.jsx
  platform/src/pages/settings/index.jsx
Labels: ready for review

#1650 [Analytics] Air quality cards UI and functionality
  platform/public/icons/Common/wind.svg
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/common/components/Layout/borderless_content_box.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Tooltip/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/apis/DeviceRegistry.js
  platform/src/lib/constants.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/deviceRegistry/RecentMeasurementsSlice.js
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/tailwind.config.js
Labels: ready for review

#1681 [Analytics] custom datepicker
  platform/package.json
  platform/src/common/components/Calendar/Calendar.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Calendar/components/CalendarHeader.jsx
  platform/src/common/components/Calendar/components/Footer.jsx
  platform/src/common/components/Calendar/components/ShortCuts.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/yarn.lock
Labels: ready for review

#1680 move to production
  k8s/inventory/values-prod.yaml
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/package.json
  platform/public/icons/Common/wind.svg
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/common/components/Calendar/Calendar.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Calendar/components/CalendarHeader.jsx
  platform/src/common/components/Calendar/components/Footer.jsx
  platform/src/common/components/Calendar/components/ShortCuts.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Layout/borderless_content_box.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Tooltip/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/apis/DeviceRegistry.js
  platform/src/lib/constants.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/deviceRegistry/RecentMeasurementsSlice.js
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1682 [Analytics] Chart and Custom datepicker improvements
  platform/src/common/components/Calendar/Calendar.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: ready for review

#1683 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Calendar/Calendar.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: ready for review

#1576 Kya quiz progress fix
  mobile/lib/blocs/kya/kya_bloc.dart
  mobile/lib/blocs/kya/kya_bloc.g.dart
  mobile/lib/blocs/kya/kya_state.dart
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_fr.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/kya.dart
  mobile/lib/models/kya.g.dart
  mobile/lib/models/quiz.dart
  mobile/lib/models/quiz.g.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/kya/kya_lessons_page.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/quiz/quiz_final_page.dart
  mobile/lib/screens/quiz/quiz_title_page.dart
  mobile/lib/screens/quiz/quiz_view.dart
  mobile/lib/screens/quiz/quiz_widgets.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.lock
  mobile/test/utils/extensions/kya_test.dart
Labels: ready for review, mobile-app

#1685 [PLATFORM] Customise Locations
  platform/.env.example
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/apis/DeviceRegistry.js
  platform/src/lib/store/services/account/UserDefaultsSlice.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/pages/account/creation/index.jsx
  platform/src/pages/account/creation/individual/verify-email.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/tailwind.config.js
Labels: ready for review

#1688 [Hotfixes] Display Collocation only for user with right permissions
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/core/utils/protectedRoute.js
  platform/src/lib/store/services/account/CreationSlice.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/pages/analytics/index.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/src/pages/permission-denied.jsx
Labels: ready for review

#1689 [PLATFORM] Error handling bugs
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
Labels: ready for review

#1690 [analytics] Export and share functionality
  platform/.env.example
  platform/package.json
  platform/public/icons/Topbar/userIcon.js
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/core/apis/Analytics.js
  platform/src/core/urls/analytics.js
  platform/src/pages/Home/index.jsx
  platform/src/pages/_app.jsx
  platform/src/pages/account/creation/individual/interest/[id]/[token].jsx
  platform/src/pages/account/creation/individual/register.jsx
  platform/src/pages/account/creation/individual/verify-email.jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify-email.jsx
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/src/pages/collocation/reports/[device].jsx
  platform/src/pages/collocation/reports/index.jsx
  platform/src/pages/collocation/reports/monitor_report/[device].jsx
  platform/src/pages/settings/index.jsx
  platform/yarn.lock
Labels: ready for review

#1691 Push Notifications: Mobile App
  mobile/lib/constants/config.dart
  mobile/lib/main.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/on_boarding/notifications_setup_screen.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/notification_service.dart
Labels: ready for review

#1692 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  mobile/lib/constants/config.dart
  mobile/lib/main.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/on_boarding/notifications_setup_screen.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/notification_service.dart
  platform/.env.example
  platform/package.json
  platform/public/icons/Topbar/userIcon.js
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/core/apis/Analytics.js
  platform/src/core/urls/analytics.js
  platform/src/pages/Home/index.jsx
  platform/src/pages/_app.jsx
  platform/src/pages/account/creation/individual/interest/[id]/[token].jsx
  platform/src/pages/account/creation/individual/register.jsx
  platform/src/pages/account/creation/individual/verify-email.jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify-email.jsx
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/src/pages/collocation/reports/[device].jsx
  platform/src/pages/collocation/reports/index.jsx
  platform/src/pages/collocation/reports/monitor_report/[device].jsx
  platform/src/pages/settings/index.jsx
  platform/yarn.lock
Labels: ready for review

#1654 Translated healthtips for forecast
  mobile/lib/services/rest_api.dart
Labels: ready for review

#1693 move to production
  k8s/platform/values-prod.yaml
  mobile/lib/services/rest_api.dart
Labels: ready for review

#1694 [Hotfix] Using editable location names
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#1695 move to production
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#1696 [PLATFORM] Button styling
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
Labels: ready for review

#1698 [Hotfix] org dropdown
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
Labels: ready for review

#1697 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
Labels: ready for review

#1701 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/core/utils/protectedRoute.js
  platform/src/pages/account/creation/individual/interest/[id]/[token].jsx
Labels: ready for review

#1702 [Netmanager] Enhancing Security Measures
  netmanager/.env.sample
  netmanager/src/App.js
Labels: ready for review

#1703 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  netmanager/.env.sample
  netmanager/src/App.js
Labels: ready for review

#1705 [WEBSITE] deployment error
  website/backend/settings.py
Labels: ready for review

#1706 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  website/backend/settings.py
Labels: ready for review

#1707 [WEBSITE] Data loading issue
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
Labels: ready for review

#1708 move to production
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
Labels: ready for review

#1676 Mobile_fixes
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_fr.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
  mobile/lib/main.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/email_authentication/email_auth_screen.dart
  mobile/lib/screens/email_authentication/email_verification_screen.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/on_boarding/introduction_screen.dart
  mobile/lib/screens/on_boarding/location_setup_screen.dart
  mobile/lib/screens/on_boarding/notifications_setup_screen.dart
  mobile/lib/screens/on_boarding/profile_setup_screen.dart
  mobile/lib/screens/on_boarding/setup_complete_screen.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/phone_authentication/phone_auth_screen.dart
  mobile/lib/screens/phone_authentication/phone_verification_screen.dart
  mobile/lib/screens/settings/update_screen.dart
  mobile/lib/services/notification_service.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1710 move to production
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_fr.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
  mobile/lib/main.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/email_authentication/email_auth_screen.dart
  mobile/lib/screens/email_authentication/email_verification_screen.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/on_boarding/introduction_screen.dart
  mobile/lib/screens/on_boarding/location_setup_screen.dart
  mobile/lib/screens/on_boarding/notifications_setup_screen.dart
  mobile/lib/screens/on_boarding/profile_setup_screen.dart
  mobile/lib/screens/on_boarding/setup_complete_screen.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/phone_authentication/phone_auth_screen.dart
  mobile/lib/screens/phone_authentication/phone_verification_screen.dart
  mobile/lib/screens/settings/update_screen.dart
  mobile/lib/services/notification_service.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review

#1674 [Netmanager] Added grid uptime reports section to grid details page
  netmanager/src/redux/Analytics/operations.js
  netmanager/src/redux/DeviceManagement/operations.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/deviceMonitoring.js
  netmanager/src/views/components/AirQlouds/AirQloudView.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/AirqloudUptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/AirqloudUptimeLeaderboard.js
  netmanager/src/views/pages/GridsRegistry/AddGridForm.jsx
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
Labels: ready for review

#1712 move to production
  k8s/netmanager/values-stage.yaml
  netmanager/src/redux/Analytics/operations.js
  netmanager/src/redux/DeviceManagement/operations.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/deviceMonitoring.js
  netmanager/src/views/components/AirQlouds/AirQloudView.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/AirqloudUptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/AirqloudUptimeLeaderboard.js
  netmanager/src/views/pages/GridsRegistry/AddGridForm.jsx
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
Labels: ready for review

#1711 Fix favourites
  mobile/lib/blocs/favourite_place/favourite_place_bloc.dart
  mobile/lib/blocs/kya/kya_bloc.dart
  mobile/lib/constants/config.dart
  mobile/lib/constants/constants.dart
  mobile/lib/constants/language_constants.dart
  mobile/lib/main_common.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/quiz/quiz_view.dart
  mobile/lib/screens/quiz/quiz_widgets.dart
  mobile/lib/screens/settings/language_switch.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1713 move to production
  k8s/netmanager/values-prod.yaml
  mobile/lib/blocs/favourite_place/favourite_place_bloc.dart
  mobile/lib/blocs/kya/kya_bloc.dart
  mobile/lib/constants/config.dart
  mobile/lib/constants/constants.dart
  mobile/lib/constants/language_constants.dart
  mobile/lib/main_common.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/quiz/quiz_view.dart
  mobile/lib/screens/quiz/quiz_widgets.dart
  mobile/lib/screens/settings/language_switch.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review

#1709 [Analytics] Implement Checklist Completion Logic and Refactor Site Selection
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/pages/Home/index.jsx
  platform/src/pages/analytics/index.jsx
Labels: ready for review

#1714 [WEBSITE] Cleanair Feedback
  website/frontend/src/components/CleanAir/Hightlights/MainHighlight.js
  website/frontend/src/components/CleanAir/SecondaryNav/index.js
  website/frontend/src/components/CleanAir/Sections/SplitSection.js
  website/frontend/src/components/Footer.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
  website/frontend/src/pages/CleanAir/EventDetails.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1718 [Platform] Save user's active organization to preferences
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/pages/account/login/index.jsx
Labels: ready for review

#1715 [Analytics] Data Export
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Calendar/components/ShortCuts.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
Labels: ready for review

#1717 [PLATFORM] Customise location using PATCH endpoint
  platform/package.json
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/core/apis/Account.js
  platform/src/lib/store/services/account/UserDefaultsSlice.js
  platform/yarn.lock
Labels: ready for review

#1720 [analytics] Custom dropdown style issues
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Layout/index.jsx
Labels: ready for review

#1721 [Analytics] Customization and preferences issue
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/pages/_app.jsx
  platform/src/pages/analytics/index.jsx
Labels: ready for review

#1716 move to production
  k8s/platform/values-stage.yaml
  platform/package.json
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Calendar/components/ShortCuts.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/core/apis/Account.js
  platform/src/lib/store/services/account/UserDefaultsSlice.js
  platform/src/pages/Home/index.jsx
  platform/src/pages/_app.jsx
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/yarn.lock
  website/frontend/src/components/CleanAir/Hightlights/MainHighlight.js
  website/frontend/src/components/CleanAir/SecondaryNav/index.js
  website/frontend/src/components/CleanAir/Sections/SplitSection.js
  website/frontend/src/components/Footer.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
  website/frontend/src/pages/CleanAir/EventDetails.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1719 Language-fix
  mobile/lib/blocs/favourite_place/favourite_place_bloc.dart
  mobile/lib/constants/language_constants.dart
  mobile/lib/main.dart
  mobile/lib/main_dev.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/for_you_page.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/settings/language_switch.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/screens/settings/update_screen.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/local_storage.dart
  mobile/lib/services/notification_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/widgets/error_widgets.dart
Labels: ready for review, mobile-app

#1726 move to production
  k8s/platform/values-prod.yaml
  mobile/lib/blocs/favourite_place/favourite_place_bloc.dart
  mobile/lib/constants/language_constants.dart
  mobile/lib/main.dart
  mobile/lib/main_dev.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/for_you_page.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/settings/language_switch.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/screens/settings/update_screen.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/local_storage.dart
  mobile/lib/services/notification_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/widgets/error_widgets.dart
Labels: ready for review

#1727 move to production
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/utils/protectedRoute.js
  platform/src/lib/store/services/account/UserDefaultsSlice.js
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#1728 [Analytics] Collocation updates
  platform/src/common/components/Collocation/AddMonitor/Overview/graph_card.jsx
  platform/src/common/components/Collocation/AddMonitor/Table/DataTable.jsx
  platform/src/common/components/Collocation/DeviceStatus/ReportDetailPopup/index.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/index.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/IntraCorrelation/custom_legend.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/IntraCorrelation/index.jsx
  platform/src/common/components/Modal/Modal.jsx
  platform/src/core/apis/Collocation.js
  platform/src/core/urls/deviceMonitoring.js
  platform/src/core/utils/protectedRoute.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/collocation/index.js
  platform/src/lib/store/services/deviceRegistry.js
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/src/pages/collocation/reports/[device].jsx
  platform/src/pages/collocation/reports/monitor_report/[device].jsx
Labels: ready for review

#1729 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Collocation/AddMonitor/Overview/graph_card.jsx
  platform/src/common/components/Collocation/AddMonitor/Table/DataTable.jsx
  platform/src/common/components/Collocation/DeviceStatus/ReportDetailPopup/index.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/index.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/IntraCorrelation/custom_legend.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/IntraCorrelation/index.jsx
  platform/src/common/components/Modal/Modal.jsx
  platform/src/core/apis/Collocation.js
  platform/src/core/urls/deviceMonitoring.js
  platform/src/core/utils/protectedRoute.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/collocation/index.js
  platform/src/lib/store/services/deviceRegistry.js
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/src/pages/collocation/reports/[device].jsx
  platform/src/pages/collocation/reports/monitor_report/[device].jsx
Labels: ready for review

#1730 Fix localization issue in AirQoApp
  mobile/lib/main_common.dart
Labels: ready for review, mobile-app

#1722 [WEBSITE] Image and section update on About page
  website/frontend/src/assets/img/cleanAir/acronym3.png
  website/frontend/src/assets/img/cleanAir/clean1.jpg
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
Labels: ready for review

#1732 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  mobile/lib/main_common.dart
  website/frontend/src/assets/img/cleanAir/acronym3.png
  website/frontend/src/assets/img/cleanAir/clean1.jpg
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
Labels: ready for review

#1731 [Analytics] Analytic Chart Card Improvements and Optimization
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#1733 move to production
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#1734 Update README.md
  platform/README.md
Labels: ready for review

#1736 [WEBSITE] Clean-Air Feedback
  website/frontend/src/components/CleanAir/Sections/SingleSection.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/EventDetails.js
  website/frontend/styles/CleanAirPage.scss
  website/frontend/styles/Events.scss
Labels: ready for review

#1741 Added measurements api section for user to copy
  netmanager/src/assets/css/copyable.css
  netmanager/src/views/components/Copy/Copyable.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/components/HowToApiModal/index.js
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
Labels: ready for review

#1738 Fix for Syncing Mobile and Platform account
  mobile/lib/services/rest_api.dart
Labels: ready for review

#1740 [Analytics] Customization repetition issue and Account creation fix
  platform/public/icons/Alerts/Info_circle.js
  platform/public/icons/LocationIcon.js
  platform/public/icons/close_icon.js
  platform/public/images/Account/analyticsImage.png
  platform/src/common/components/Account/CheckComponent.jsx
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Account/RadioComponent.jsx
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/pages/account/creation/index.jsx
  platform/src/pages/account/creation/individual/interest/[id]/[token].jsx
  platform/src/pages/account/creation/individual/register.jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/src/pages/account/login/index.jsx
Labels: ready for review

#1742 Navigate to Favorites from Notification
  mobile/lib/main.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/services/notification_service.dart
Labels: ready for review

#1744 [Hotfix] Use cohorts summary api on cohorts registry
  netmanager/src/redux/Analytics/actions.js
  netmanager/src/redux/Analytics/operations.js
  netmanager/src/redux/Analytics/reducer.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/pages/CohortsRegistry/index.js
Labels: ready for review

#1739 move to production
  .github/workflows/deploy-frontends-to-staging.yml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  mobile/lib/main.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/services/notification_service.dart
  mobile/lib/services/rest_api.dart
  mobile/pubspec.yaml
  netmanager/README.md
  netmanager/src/assets/css/copyable.css
  netmanager/src/redux/Analytics/actions.js
  netmanager/src/redux/Analytics/operations.js
  netmanager/src/redux/Analytics/reducer.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/AirQlouds/AirQloudView.js
  netmanager/src/views/components/Copy/Copyable.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/components/HowToApiModal/index.js
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/CohortsRegistry/index.js
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
  netmanager/src/views/pages/Settings/components/GenerateToken/GenerateToken.js
  platform/public/icons/Alerts/Info_circle.js
  platform/public/icons/LocationIcon.js
  platform/public/icons/close_icon.js
  platform/public/images/Account/analyticsImage.png
  platform/src/common/components/Account/CheckComponent.jsx
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Account/RadioComponent.jsx
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/pages/account/creation/index.jsx
  platform/src/pages/account/creation/individual/interest/[id]/[token].jsx
  platform/src/pages/account/creation/individual/register.jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/src/pages/account/login/index.jsx
  website/frontend/src/components/CleanAir/Sections/SingleSection.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/EventDetails.js
  website/frontend/src/pages/Events/Details.js
  website/frontend/styles/CleanAirPage.scss
  website/frontend/styles/Events.scss
Labels: ready for review
