Repository airqo-platform/AirQo-frontend, pull requests merged in 2023-10, with the labels that each got.

#1521 Update mobile app version details
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1525 [NET] Host registry modifications
  netmanager/src/__tests__/DataDisplay/HostRegistry.test.js
  netmanager/src/views/components/Hosts/HostView.js
  netmanager/src/views/components/Hosts/HostsTable.js
Labels: ready for review

#1524 [NET] Removed the distance and bearing to kampala fields (site Registry)
  netmanager/src/__tests__/DataDisplay/sitesView.test.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/containers/PageAccess.js
Labels: ready for review

#1531 [WEBSITE] clean air loading issue
  website/frontend/src/components/CleanAir/Hightlights/MainHighlight.js
  website/frontend/src/components/CleanAir/Hightlights/NewArticle.js
  website/frontend/src/components/CleanAir/Sections/Section.js
  website/frontend/src/pages/CleanAir/Page.js
Labels: ready for review

#1532 [Netmanager] Added health status chart to network stats page
  netmanager/jsconfig.json
  netmanager/src/App.test.js
  netmanager/src/__tests__/DataDisplay/AirqloudUptimeChart.test.js
  netmanager/src/__tests__/test_utils.js
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/redux/AirQloud/actions.js
  netmanager/src/redux/AirQloud/operations.js
  netmanager/src/redux/AirQloud/reducers.js
  netmanager/src/redux/AirQloud/selectors.js
  netmanager/src/redux/DeviceManagement/actions.js
  netmanager/src/redux/DeviceManagement/operations.js
  netmanager/src/redux/DeviceManagement/reducers/airqloudUptime.js
  netmanager/src/redux/DeviceManagement/reducers/index.js
  netmanager/src/redux/DeviceManagement/selectors.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/charts/ApexChart.js
  netmanager/src/views/charts/ChartContainer.js
  netmanager/src/views/components/AirQlouds/AirQloudsTable.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/AirqloudUptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/SensorChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/UptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/VoltageChart.js
  netmanager/src/views/containers/AirQloudDropDown.js
Labels: ready for review

#1528 [Netmanager] Optimizing autocomplete function call
  netmanager/src/views/components/AirqualitySearch/index.js
Labels: ready for review

#1535 Fixing forecast issues on Insights page
  mobile/lib/services/hive_service.dart
Labels: ready for review, mobile-app

#1534 [website] Fix on clean air page loading
  website/frontend/src/components/CleanAir/Hightlights/MainHighlight.js
Labels: ready for review

#1523 animations and transitions
  mobile/lib/screens/analytics/analytics_view.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/email_authentication/email_verification_screen.dart
  mobile/lib/screens/favourite_places/favourite_places_page.dart
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
  mobile/lib/screens/feedback/feedback_page_widgets.dart
  mobile/lib/screens/for_you_page.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/kya/kya_final_page.dart
  mobile/lib/screens/kya/kya_title_page.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/notification/notification_page.dart
  mobile/lib/screens/notification/notification_widgets.dart
  mobile/lib/screens/offline_banner.dart
  mobile/lib/screens/phone_authentication/phone_auth_widgets.dart
  mobile/lib/screens/phone_authentication/phone_verification_screen.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/quiz/quiz_final_page.dart
  mobile/lib/screens/quiz/quiz_title_page.dart
  mobile/lib/screens/quiz/quiz_view.dart
  mobile/lib/screens/search/search_widgets.dart
Labels: ready for review, mobile-app

#1522 Enabling Translations for KYA and Quiz
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/quiz/quiz_title_page.dart
  mobile/lib/screens/quiz/quiz_widgets.dart
  mobile/lib/services/rest_api.dart
  mobile/test/api/kya_lessons_test.dart
  mobile/test/api/quiz_test.dart
Labels: ready for review

#1537 [NETMANAGER] Refactored sidebar and implemented Teams view
  netmanager/src/AppRoutes.js
  netmanager/src/__tests__/Teams/Teams.test.js
  netmanager/src/config/urls/analytics.js
  netmanager/src/redux/AccessControl/actions.js
  netmanager/src/redux/AccessControl/operations.js
  netmanager/src/redux/AccessControl/reducers.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/components/Hosts/HostsTable.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
  netmanager/src/views/pages/Teams/Table.js
  netmanager/src/views/pages/Teams/Teams.js
  netmanager/src/views/pages/Teams/TeamsView.js
Labels: ready for review

#1539 [Netmanager] Hotfixes and refactorings
  netmanager/src/AppRoutes.js
  netmanager/src/redux/Analytics/actions.js
  netmanager/src/redux/Analytics/operations.js
  netmanager/src/redux/Analytics/reducer.js
  netmanager/src/redux/Dashboard/operations.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/apis/deviceMonitoring.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/apis/location.js
  netmanager/src/views/apis/metaData.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceToolBar.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/components/d3/CustomisableChart.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Analytics/components/CohortsDashboard.jsx
  netmanager/src/views/pages/Analytics/components/GridsDashboard.jsx
  netmanager/src/views/pages/Analytics/index.js
  netmanager/src/views/pages/CohortsRegistry/AddCohortForm.jsx
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/CohortsRegistry/CohortsTable.js
  netmanager/src/views/pages/CohortsRegistry/DevicesTable.jsx
  netmanager/src/views/pages/CohortsRegistry/breadcrumb.js
  netmanager/src/views/pages/CohortsRegistry/index.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Dashboard/components/AddChart.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
  netmanager/src/views/pages/GridsRegistry/AddGridForm.jsx
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
  netmanager/src/views/pages/GridsRegistry/GridsTable.jsx
  netmanager/src/views/pages/GridsRegistry/PolygonMap.jsx
  netmanager/src/views/pages/GridsRegistry/SitesTable.jsx
  netmanager/src/views/pages/GridsRegistry/breadcrumb.js
  netmanager/src/views/pages/GridsRegistry/index.js
Labels: ready for review

#1541 [Netmanager] added airqloud uptime leaderboard
  netmanager/src/views/components/DataDisplay/DeviceManagement/AirqloudUptimeLeaderboard.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
Labels: ready for review

#1542 [Hotfix] jwt config
  netmanager/src/redux/Join/actions.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/CustomisableChart/CustomisableChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#1540 included currentUserRoles to localstorage and implemented Sim Registry
  netmanager/src/AppRoutes.js
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/components/SIM/SimRegistry.js
  netmanager/src/views/components/SIM/Table.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
Labels: ready for review

#1543 Log KYA completion events
  mobile/lib/blocs/kya/kya_bloc.dart
  mobile/lib/models/enum_constants.dart
Labels: ready for review, mobile-app

#1536 Mobile CI/CD updates
  .github/workflows/deploy-android-to-firebase-app-distribution.yml
  .github/workflows/deploy-android-to-play-store.yml
  mobile/android/Gemfile.lock
  mobile/android/fastlane/Fastfile
  mobile/android/fastlane/README.md
  mobile/pubspec.lock
Labels: ready for review, mobile-app

#1544 [NETMANAGER] Switch between Networks and Teams
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/Sites/SiteToolbar.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
  netmanager/src/views/pages/Teams/Teams.js
Labels: ready for review

#1545 [netmanager] reversed changes
  netmanager/src/views/components/Sites/SiteToolbar.js
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
Labels: ready for review

#1547 [NETMANAGER] App Crash on Login Page
  netmanager/src/redux/AirQloud/operations.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/pages/SignUp/Register.js
Labels: ready for review

#1546 Fix delay in KYA and Quiz translation
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/services/firebase_service.dart
Labels: ready for review, mobile-app

#1551 Added REACT_APP_OPENCAGE_API_KEY env
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  website/Dockerfile
  website/README.md
Labels: ready for review

#1550 [NETMANAGER] Bug Fix on Teams View plus additional modifications
  netmanager/src/AppRoutes.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/views/components/SIM/SimRegistry.js
  netmanager/src/views/components/SIM/Table.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Teams/Teams.js
Labels: ready for review

#1552 [Hotfixes] Grids and cohorts
  netmanager/package.json
  netmanager/src/__tests__/GridsCohorts/CohortsRegistry.test.js
  netmanager/src/__tests__/GridsCohorts/GridsRegistry.test.js
  netmanager/src/redux/Analytics/actions.js
  netmanager/src/redux/Analytics/operations.js
  netmanager/src/redux/Analytics/reducer.js
  netmanager/src/setupTests.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/pages/Analytics/components/CohortsDashboard.jsx
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/CohortsRegistry/index.js
  netmanager/src/views/pages/GridsRegistry/AddGridForm.jsx
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
  netmanager/src/views/pages/GridsRegistry/index.js
Labels: ready for review

#1553 Disable calling the Places API in tests
  mobile/test/api/search_test.dart
Labels: ready for review, mobile-app

#1548 [WEBSITE] Filtering data for Press and Events Pages
  website/frontend/src/pages/Events/Details.js
  website/frontend/src/pages/Events/index.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1549 [WEBSITE] Display AirQlouds based on Users country/location
  website/frontend/__tests__/locationtracker/Locationtracker.test.js
  website/frontend/config/urls.js
  website/frontend/config/utils.js
  website/frontend/reduxStore/AirQlouds/operations.js
  website/frontend/src/components/Footer.js
  website/frontend/src/components/LoctionTracker/LocationTracker.js
Labels: ready for review

#1555 [Analytics] Settings page skeleton
  platform/cypress/e2e/pages/settings.cy.js
  platform/public/icons/Common/chevron_down.svg
  platform/public/icons/Common/search_md.svg
  platform/public/icons/Topbar/avatar.svg
  platform/src/common/components/Collocation/DeviceStatus/Tabs/index.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/common/components/Tabs/Tab.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/common/components/TopBar/TopBarItem.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/pages/analytics/collocation/collocate.jsx
  platform/src/pages/analytics/collocation/overview.jsx
  platform/src/pages/analytics/collocation/reports/[device].jsx
  platform/src/pages/analytics/collocation/reports/index.jsx
  platform/src/pages/analytics/collocation/reports/monitor_report/[device].jsx
  platform/src/pages/settings/index.jsx
  platform/tailwind.config.js
Labels: ready for review

#1558 [NETMANAGER] UI Enhancement and Transition from Organisations to Networks(sidebar)
  netmanager/src/AppRoutes.js
  netmanager/src/views/components/Hosts/HostRegistry.js
  netmanager/src/views/components/SIM/SimRegistry.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Topbar.js
Labels: ready for review

#1565 [WEBSITE] Adding Variable to .env.sample file
  website/.env.sample
Labels: ready for review

#1563 [ANALYTICS] Password reset
  platform/cypress/e2e/pages/settings.cy.js
  platform/public/icons/Actions/close.svg
  platform/public/icons/Actions/info-alert.svg
  platform/public/icons/Settings/lock.svg
  platform/src/common/components/AlertBox/index.jsx
  platform/src/core/apis/Settings.js
  platform/src/core/urls/authentication.js
  platform/src/pages/settings/Tabs/Password.jsx
  platform/src/pages/settings/index.jsx
Labels: ready for review

#1569 [PLATFORM] Individual Account Creation Refactor
  platform/jsconfig.json
  platform/public/icons/Account/visibility_off.svg
  platform/public/icons/Account/visibility_on.svg
  platform/public/icons/Actions/exclamation.svg
  platform/public/images/Account/SideQuote.png
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Account/RadioComponent.jsx
  platform/src/common/components/Toast/index.jsx
  platform/src/common/styles/global.scss
  platform/src/lib/store/services/account/CreationSlice.js
  platform/src/pages/account/creation/index.jsx
  platform/src/pages/account/creation/step2.jsx
  platform/src/pages/account/creation/step3.jsx
  platform/tailwind.config.js
Labels: ready for review

#1567 [Netmanager] Hide Sim Registry and included JWT to heatmap and sites API headers
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/apis/location.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1562 [ANALYTICS] Login Functionality and Protected routes
  platform/cypress/e2e/pages/login.cy.js
  platform/package.json
  platform/src/common/components/AuthenticatedLayout/index.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/common/components/Spinner/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/apis/Settings.js
  platform/src/core/utils/protectedRoute.js
  platform/src/core/utils/setAuthToken.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/account/LoginSlice.js
  platform/src/pages/Home/index.jsx
  platform/src/pages/_app.jsx
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/airqlouds.jsx
  platform/src/pages/analytics/collocation/add_monitor.jsx
  platform/src/pages/analytics/collocation/collocate.jsx
  platform/src/pages/analytics/collocation/collocate_success.jsx
  platform/src/pages/analytics/collocation/overview.jsx
  platform/src/pages/analytics/collocation/reports/[device].jsx
  platform/src/pages/analytics/collocation/reports/index.jsx
  platform/src/pages/analytics/collocation/reports/monitor_report/[device].jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/index.jsx
  platform/src/pages/settings/Tabs/Password.jsx
  platform/src/pages/settings/index.jsx
  platform/yarn.lock
Labels: ready for review

#1570 [WEBSITE] updated mobile app QR code
  website/frontend/src/assets/img/QR_code.jpg
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/ExploreData/index.js
Labels: ready for review

#1571 [Analytics] Implemented Session Timeout and Dropdown UI enhancement.
  platform/cypress/component/Topbar.cy.js
  platform/package.json
  platform/src/common/components/TopBar/TopBarItem.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/utils/protectedRoute.js
  platform/yarn.lock
Labels: ready for review

#1572 Enable Favorites Page to open Using dynamic Links
  mobile/lib/services/native_api.dart
Labels: ready for review

#1574 [PLATFORM] Organisation Creation Flow
  platform/public/icons/Account/verified.svg
  platform/public/icons/Common/edit-pencil.svg
  platform/public/images/Account/OrganisationSideQuote.png
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Account/ProgressComponent.jsx
  platform/src/common/components/Account/RadioComponent.jsx
  platform/src/common/styles/global.scss
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/pages/account/creation/index.jsx
  platform/src/pages/account/creation/individual/interest/[id]/[token].jsx
  platform/src/pages/account/creation/individual/register.jsx
  platform/src/pages/account/creation/individual/verify-email.jsx
  platform/src/pages/account/creation/organisation/create-org/details.jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify-email.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/[token].jsx
  platform/src/pages/account/creation/step4.jsx
  platform/tailwind.config.js
Labels: ready for review

#1564 [Analytics] Invite user to join org team functionality
  platform/cypress/e2e/pages/settings.cy.js
  platform/cypress/fixtures/users.json
  platform/public/icons/Actions/plus.svg
  platform/public/icons/Settings/mail.svg
  platform/public/icons/Settings/person.svg
  platform/public/icons/Settings/plus.svg
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Layout/content_box.jsx
  platform/src/common/components/Settings/Teams/InviteForm.jsx
  platform/src/common/components/Settings/Teams/table.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/collocation/overview.jsx
  platform/src/pages/settings/Tabs/Password.jsx
  platform/src/pages/settings/Tabs/Team.jsx
  platform/src/pages/settings/index.jsx
  platform/tailwind.config.js
Labels: ready for review

#1575 [Netmanager] loading & No data issue for Device Registry
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceHosts.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/SIM/SimRegistry.js
  netmanager/src/views/components/Sites/SiteToolbar.js
  netmanager/src/views/components/Sites/SitesTable.js
Labels: ready for review

#1578 [Hotfix] Pass jwt token directly to get user details api
  platform/src/core/apis/Account.js
  platform/src/pages/account/login/index.jsx
Labels: ready for review

#1577 [NETMANAGER] replacing left distance_to_kampala on site Registry
  netmanager/src/views/components/Sites/SitesTable.js
Labels: ready for review

#1585 [NETMANAGER] fix loading issues
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/Activities/ActivitiesTable.js
  netmanager/src/views/components/AirQlouds/AirQloudsTable.js
  netmanager/src/views/components/Hosts/HostsTable.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/pages/GridsRegistry/index.js
  netmanager/src/views/pages/Teams/Teams.js
Labels: ready for review

#1589 [PLATFORM] Visibility of Logout Option on Mobile and Tablet Views
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/TopBar/index.jsx
Labels: ready for review

#1588 [Netmanager] HeatMap Refactoring and New Feature intro tags added
  netmanager/src/redux/MapData/operations.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Sidebar/components/SidebarNav/SidebarNav.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
Labels: ready for review

#1587 Add release notes updates for new releases
  .github/workflows/deploy-android-to-play-store.yml
  mobile/android/fastlane/release_notes.txt
Labels: ready for review, mobile-app

#1590 move to production
  .github/workflows/deploy-android-to-play-store.yml
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  mobile/android/fastlane/release_notes.txt
  netmanager/src/redux/MapData/operations.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Sidebar/components/SidebarNav/SidebarNav.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/TopBar/index.jsx
Labels: ready for review

#1591 [WEBSITE] Failed AirQloud load
  website/frontend/config/urls.js
Labels: ready for review

#1592 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  website/frontend/config/urls.js
Labels: ready for review

#1593 [Netmanager] Included Missing new feature tags
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1594 move to production
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1554 [WEBSITE] Homepage French translation
  website/frontend/App.js
  website/frontend/i18n.js
  website/frontend/index.js
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/reduxStore/EventsNav/NavigationSlice.js
  website/frontend/src/__tests__/Locale/locale.test.js
  website/frontend/src/__tests__/locationtracker/Locationtracker.test.js
  website/frontend/src/components/AirQuality/AfricanCities.js
  website/frontend/src/components/AirQuality/AirQuality.js
  website/frontend/src/components/AirQuality/Communities.js
  website/frontend/src/components/AnalyticsSection/AnalyticsSection.js
  website/frontend/src/components/ApiSection/ApiSection.js
  website/frontend/src/components/Footer.js
  website/frontend/src/components/Hero.js
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/src/components/MapSection/MapSection.js
  website/frontend/src/components/MiniHighlights.js
  website/frontend/src/components/Monitor.js
  website/frontend/src/components/NewsletterSection/NewsletterSection.js
  website/frontend/src/components/Partners.js
  website/frontend/src/components/get-app/GetApp.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/AnalyticsSection.scss
  website/frontend/styles/Footer.scss
  website/frontend/styles/Hero.scss
  website/frontend/styles/ImpactNumbers.scss
  website/frontend/styles/MapSection.scss
  website/frontend/styles/Monitor.scss
  website/frontend/styles/NewsletterSection.scss
  website/frontend/styles/TopBar.scss
  website/package-lock.json
  website/package.json
Labels: ready for review

#1598 [Hotfix] Dashboard charts
  netmanager/src/views/components/d3/CustomisableChart.js
  netmanager/src/views/pages/Analytics/components/CohortsDashboard.jsx
  netmanager/src/views/pages/Analytics/components/GridsDashboard.jsx
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#1597 [WEBSITE] Translation Documentation
  website/frontend/locales/README.md
Labels: ready for review

#1599 [Analytics] Analytics page UI skeleton
  platform/cypress/e2e/collocation/device_status_table.cy.js
  platform/public/icons/SideBar/bar_chart.svg
  platform/public/icons/SideBar/collocation.svg
  platform/src/common/components/Collocation/DeviceStatus/ReportDetailPopup/index.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/IntraCorrelation/index.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/pages/Home/index.jsx
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/airqlouds.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/collocate_success.jsx
  platform/src/pages/collocation/overview.jsx
  platform/src/pages/collocation/reports/[device].jsx
  platform/src/pages/collocation/reports/index.jsx
  platform/src/pages/collocation/reports/monitor_report/[device].jsx
  platform/tailwind.config.js
Labels: ready for review

#1603 Swahili support
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/email_authentication/email_auth_widgets.dart
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
Labels: ready for review, mobile-app

#1581 [PLATFORM] Organisation Creation
  platform/src/common/components/Account/Layout.jsx
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/lib/store/services/account/CreationSlice.js
  platform/src/pages/account/creation/individual/register.jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/[token].jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/src/pages/account/login/index.jsx
  platform/tailwind.config.js
Labels: ready for review

#1605 [netmanager] Code Refactoring
  netmanager/src/App.js
  netmanager/src/redux/Dashboard/operations.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/utils/charts.js
  netmanager/src/utils/setAuthToken.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/apis/axiosConfig.js
  netmanager/src/views/apis/deviceMonitoring.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/apis/location.js
  netmanager/src/views/apis/metaData.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/DataDisplay/Dialogs/DeleteDialog.js
  netmanager/src/views/components/Map/Map.js
  netmanager/src/views/components/SIM/SimRegistry.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/CustomisableChart/CustomisableChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
  netmanager/src/views/pages/Dashboard/components/Map/Map.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Reports/graph.js
  netmanager/src/views/pages/Teams/Teams.js
  netmanager/src/views/pages/UserList/AvailableUserList.js
  netmanager/src/views/pages/UserList/components/UsersTable/AvailableUsersTable.js
Labels: ready for review

#1601 move to production
  inventory/.dockerignore
  inventory/Dockerfile
  inventory/Inventory/settings.py
  inventory/Inventory/urls.py
  k8s/netmanager/values-prod.yaml
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/email_authentication/email_auth_widgets.dart
  mobile/lib/screens/favourite_places/favourite_places_widgets.dart
  netmanager/src/App.js
  netmanager/src/redux/Dashboard/operations.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/utils/charts.js
  netmanager/src/utils/setAuthToken.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/apis/axiosConfig.js
  netmanager/src/views/apis/deviceMonitoring.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/apis/location.js
  netmanager/src/views/apis/metaData.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/DataDisplay/Dialogs/DeleteDialog.js
  netmanager/src/views/components/Map/Map.js
  netmanager/src/views/components/SIM/SimRegistry.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/CustomisableChart/CustomisableChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
  netmanager/src/views/pages/Dashboard/components/Map/Map.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Reports/graph.js
  netmanager/src/views/pages/Teams/Teams.js
  netmanager/src/views/pages/UserList/AvailableUserList.js
  netmanager/src/views/pages/UserList/components/UsersTable/AvailableUsersTable.js
  platform/src/common/components/Account/Layout.jsx
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/lib/store/services/account/CreationSlice.js
  platform/src/pages/account/creation/individual/register.jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/[token].jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/src/pages/account/login/index.jsx
  platform/tailwind.config.js
Labels: ready for review

#1602 [WEBSITE] Addressing User Feedback
  website/backend/partners/migrations/0006_alter_partner_type.py
  website/backend/partners/migrations/0007_alter_partner_type.py
  website/backend/partners/migrations/0008_alter_partner_type.py
  website/backend/partners/models.py
  website/frontend/locales/en/translation.json
  website/frontend/src/components/CleanAir/Hightlights/MainHighlight.js
  website/frontend/src/components/CleanAir/SecondaryNav/index.js
  website/frontend/src/components/CleanAir/Sections/Section.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/styles/TopBar.scss
Labels: ready for review

#1507 in app language switch
  mobile/assets/images/english_flag.png
  mobile/assets/images/france_flag.png
  mobile/assets/images/portugal_flag.png
  mobile/assets/images/swahili_flag.png
  mobile/lib/constants/constants.dart
  mobile/lib/constants/language_contants.dart
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_fr.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/main_dev.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/settings/language_switch.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/widgets/buttons.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1607 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  mobile/assets/images/english_flag.png
  mobile/assets/images/france_flag.png
  mobile/assets/images/portugal_flag.png
  mobile/assets/images/swahili_flag.png
  mobile/lib/constants/constants.dart
  mobile/lib/constants/language_contants.dart
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_fr.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/main_dev.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/settings/language_switch.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/widgets/buttons.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
  platform/public/images/EventHandling/congratulations.svg
  platform/src/core/apis/Account.js
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/urls/deviceRegistry.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/account/CreationSlice.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/pages/account/creation/get-started.jsx
  platform/src/pages/account/creation/individual/interest/[id]/[token].jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/[token].jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/src/pages/account/login/index.jsx
  website/backend/partners/migrations/0006_alter_partner_type.py
  website/backend/partners/migrations/0007_alter_partner_type.py
  website/backend/partners/migrations/0008_alter_partner_type.py
  website/backend/partners/models.py
  website/frontend/locales/en/translation.json
  website/frontend/src/components/CleanAir/Hightlights/MainHighlight.js
  website/frontend/src/components/CleanAir/SecondaryNav/index.js
  website/frontend/src/components/CleanAir/Sections/Section.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/styles/TopBar.scss
Labels: ready for review

#1610 [Hotfixes] Netmanager hotfixes
  netmanager/src/App.js
  netmanager/src/redux/MapData/actions.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/redux/MapData/reducers.js
  netmanager/src/redux/MapData/selectors.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/pages/GridsRegistry/AddGridForm.jsx
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1611 move to production
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  netmanager/src/App.js
  netmanager/src/redux/MapData/actions.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/redux/MapData/reducers.js
  netmanager/src/redux/MapData/selectors.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/pages/GridsRegistry/AddGridForm.jsx
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1612 [PLATFORM] Organisation Creation
  platform/package.json
  platform/src/common/components/Account/Layout.jsx
  platform/src/core/apis/Account.js
  platform/src/core/apis/DeviceRegistry.js
  platform/src/lib/store/services/account/CreationSlice.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify-email.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/yarn.lock
Labels: ready for review

#1614 [Analytics] Analytics Charts implementation
  platform/public/icons/Actions/three-dots-menu.svg
  platform/public/icons/Charts/GoodAir.js
  platform/public/icons/Charts/Hazardous.js
  platform/public/icons/Charts/Moderate.js
  platform/public/icons/Charts/Unhealthy.js
  platform/public/icons/Charts/UnhealthySG.js
  platform/public/icons/Charts/VeryUnhealthy.js
  platform/public/icons/Charts/bar-chart.svg
  platform/public/icons/Charts/line-chart-up.svg
  platform/public/icons/Common/chevron_down.svg
  platform/public/icons/calendar.svg
  platform/public/icons/settings.svg
  platform/public/icons/tickIcon.js
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/common/styles/global.scss
  platform/src/core/apis/Account.js
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/apis/axiosConfig.js
  platform/src/core/urls/deviceRegistry.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/yarn.lock
Labels: work in progress, ready for review

#1613 move to production
  k8s/netmanager/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/package.json
  platform/public/icons/Actions/three-dots-menu.svg
  platform/public/icons/Charts/GoodAir.js
  platform/public/icons/Charts/Hazardous.js
  platform/public/icons/Charts/Moderate.js
  platform/public/icons/Charts/Unhealthy.js
  platform/public/icons/Charts/UnhealthySG.js
  platform/public/icons/Charts/VeryUnhealthy.js
  platform/public/icons/Charts/bar-chart.svg
  platform/public/icons/Charts/line-chart-up.svg
  platform/public/icons/Common/chevron_down.svg
  platform/public/icons/calendar.svg
  platform/public/icons/settings.svg
  platform/public/icons/tickIcon.js
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/common/styles/global.scss
  platform/src/core/apis/Account.js
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/apis/axiosConfig.js
  platform/src/core/urls/deviceRegistry.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/account/CreationSlice.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify-email.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/src/pages/account/login/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/yarn.lock
Labels: ready for review

#1615 [Analytics] Ft profile page
  platform/package.json
  platform/public/icons/Settings/clock.svg
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Layout/borderless_content_box.jsx
  platform/src/common/components/Layout/content_box.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/common/components/TextInputField/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/apis/Cloudinary.js
  platform/src/pages/account/login/index.jsx
  platform/src/pages/settings/Tabs/Profile.jsx
  platform/src/pages/settings/index.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1616 move to production
  k8s/platform/values-prod.yaml
  platform/package.json
  platform/public/icons/Settings/clock.svg
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Layout/borderless_content_box.jsx
  platform/src/common/components/Layout/content_box.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/common/components/TextInputField/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/core/apis/Account.js
  platform/src/core/apis/Cloudinary.js
  platform/src/pages/account/login/index.jsx
  platform/src/pages/settings/Tabs/Profile.jsx
  platform/src/pages/settings/index.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1617 [Netmanager] utilize new map events api
  netmanager/src/__tests__/OverlayMap/OverlayMap.test.js
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1619 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  netmanager/src/__tests__/OverlayMap/OverlayMap.test.js
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review
