Repository airqo-platform/AirQo-frontend, pull requests merged in 2023-06, with the labels that each got.

#1177 Updating dependencies
  .github/workflows/dart-code-metrics.yaml
  mobile/ios/Podfile.lock
  mobile/lib/blocs/favourite_place/favourite_place_bloc.dart
  mobile/lib/blocs/phone_auth/phone_auth_state.dart
  mobile/lib/screens/auth/auth_widgets.dart
  mobile/lib/screens/auth/phone_auth_widget.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
  mobile/test/api/check_if_user_exists_test.mocks.dart
  mobile/test/api/get_app_version_test.mocks.dart
  mobile/test/api/get_mobile_carrier_test.mocks.dart
  mobile/test/api/send_email_verification_test.mocks.dart
  mobile/test/api/send_feedback_test.mocks.dart
  mobile/upgrade-dependencies.sh
Labels: ready for review, mobile-app

#1207 move to production
  .github/workflows/dart-code-metrics.yaml
  mobile/ios/Podfile.lock
  mobile/lib/blocs/favourite_place/favourite_place_bloc.dart
  mobile/lib/blocs/phone_auth/phone_auth_state.dart
  mobile/lib/screens/auth/auth_widgets.dart
  mobile/lib/screens/auth/phone_auth_widget.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
  mobile/test/api/check_if_user_exists_test.mocks.dart
  mobile/test/api/get_app_version_test.mocks.dart
  mobile/test/api/get_mobile_carrier_test.mocks.dart
  mobile/test/api/send_email_verification_test.mocks.dart
  mobile/test/api/send_feedback_test.mocks.dart
  mobile/upgrade-dependencies.sh
  netmanager/src/assets/css/overlay-map.css
  website/backend/africancities/__init__.py
  website/backend/africancities/admin.py
  website/backend/africancities/apps.py
  website/backend/africancities/migrations/0001_initial.py
  website/backend/africancities/migrations/__init__.py
  website/backend/africancities/models.py
  website/backend/africancities/serializers.py
  website/backend/africancities/views.py
  website/backend/settings.py
  website/backend/urls.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/AfricanCities/CitiesSlice.js
  website/frontend/reduxStore/index.js
  website/frontend/src/components/Footer.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
  website/frontend/styles/AfricanCitiesPage.scss
Labels: ready for review

#1195 [Netmanager] Predict and display air quality for a given location
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/public/images/emojis/good_emoji.svg
  netmanager/public/images/emojis/hazardous_emoji.svg
  netmanager/public/images/emojis/moderate_emoji.svg
  netmanager/public/images/emojis/ufgs_emoji.svg
  netmanager/public/images/emojis/unhealthy_emoji.svg
  netmanager/public/images/emojis/very_unhealthy_emoji.svg
  netmanager/public/index.html
  netmanager/src/assets/css/aq_search.css
  netmanager/src/config/urls/metaData.js
  netmanager/src/config/urls/predict.js
  netmanager/src/redux/GooglePlaces/actions.js
  netmanager/src/redux/GooglePlaces/operations.js
  netmanager/src/redux/GooglePlaces/reducer.js
  netmanager/src/redux/index.js
  netmanager/src/views/apis/metaData.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/AirqualitySearch/aq_data.js
  netmanager/src/views/components/AirqualitySearch/index.js
  netmanager/src/views/layouts/common/Topbar.js
Labels: ready for review

#1208 Sort Filter's activation
  platform/src/common/components/Collocation/AddMonitor/Table/index.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/index.jsx
Labels: ready for review

#1209 [Website] Toggle topbar nav menus
  website/frontend/src/components/nav/NavTab.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/styles/NavTab.scss
  website/frontend/styles/TopBar.scss
Labels: ready for review

#1223 [Netmanager] User feedback
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/assets/css/chart-container.css
  netmanager/src/redux/DeviceOverview/OverviewSlice.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/redux/index.js
  netmanager/src/views/charts/ApexChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceOverview.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceQRCode.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/VoltageChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceView.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/Sites/SiteToolbar.js
  netmanager/src/views/pages/Account/components/AccountDetails/AccountDetails.js
  netmanager/src/views/pages/Devices/.gitkeep
  netmanager/src/views/pages/LocationList/.gitkeep
  netmanager/src/views/pages/LocationList/LocationList.js
  netmanager/src/views/pages/LocationList/index.js
  netmanager/src/views/pages/UserList/components/Breadcrumb/index.js
  netmanager/src/views/pages/UserList/components/UsersTable/AvailableUsersTable.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
Labels: ready for review

#1220 [Analytics] Table interactivity(States: Default, Hover, Focused)
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
Labels: ready for review, analytics, Quality Assurance

#1212 [Analytics] Added dropdown menu to device Status table
  platform/flowbite.d.ts
  platform/public/icons/Actions/close.svg
  platform/public/icons/Actions/exclamation.svg
  platform/src/common/components/Collocation/AddMonitor/Table/DataTable.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Dropdowns/Dropdown.jsx
  platform/src/common/components/Modal/Modal.jsx
  platform/src/core/urls/deviceMonitoring.js
  platform/src/pages/collocation/collocate.jsx
Labels: ready for review

#1228 [WEBSITE] User Documents
  website/frontend/App.js
  website/frontend/src/assets/docs/AirQoAnalyticsPlatformUserGuide.pdf
  website/frontend/src/assets/docs/Binos-Maintenance-Manual.pdf
  website/frontend/src/assets/img/explore/man-download-app.png
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/src/pages/OurProducts/AnalyticsPage.js
  website/frontend/src/pages/OurProducts/MonitorPage.js
  website/frontend/styles/ExploreData.scss
Labels: ready for review

#1229 [Netmanager] Loading state in Device Registry view
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#1230 [Netmanager] Search functionality for country input field
  netmanager/src/views/pages/SignUp/Register.js
Labels: ready for review

#1231 worked on network statistics view
  netmanager/src/views/charts/ApexChart.js
  netmanager/src/views/components/Sites/SiteView.js
Labels: ready for review

#1222 Restructure the airqlouds dropdown
  netmanager/src/assets/css/dropdown.css
  netmanager/src/views/containers/AirQloudDropDown.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
Labels: ready for review, netmanager

#1235 [Netmanager] dropdown-improvement
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/layouts/common/Topbar.js
  netmanager/src/views/pages/Organisation/components/toolbar.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review

#1233 [Netmanager] Map style component restructure
  netmanager/src/assets/css/overlay-map.css
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review, netmanager

#1232 [Netmanager] Redirects to 404 page when path doesn't exist
  netmanager/public/images/AccessDenied.svg
  netmanager/public/images/Oops.svg
  netmanager/public/images/undraw_page_not_found_su7k.svg
  netmanager/src/AppRoutes.js
  netmanager/src/views/pages/NotFound/NotFound.js
  netmanager/src/views/pages/PermissionDenied/index.js
Labels: ready for review

#1236 [Netmanager] Fixing the "Invalid date" text issue On loading.
  netmanager/src/views/layouts/common/Topbar.js
Labels: ready for review

#1237 [Netmanager] Search hotfix
  netmanager/src/views/components/AirqualitySearch/dashboard_searchbar.js
  netmanager/src/views/components/AirqualitySearch/index.js
  netmanager/src/views/containers/AirQloudDropDown.js
  netmanager/src/views/layouts/common/Topbar.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
Labels: ready for review

#1240 [Netmanager] Hotfix candidates table error message
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
Labels: ready for review

#1242 [Netmanager] set default network to airqo when user logins
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1048 [Netmanager] fix add image functionality
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/views/apis/cloudinary.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/DataDisplay/DeviceView/DevicePhotos.js
Labels: ready for review

#1247 [Netmanager] HotFix - empty sidebar
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1246 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/views/apis/cloudinary.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/DataDisplay/DeviceView/DevicePhotos.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1251 [NETMANAGER] Error on the device registry screen
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#1249 [Netmanager] Ft export logs page
  netmanager/src/AppRoutes.js
  netmanager/src/config/urls/authService.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Logs/BreadCrumb/index.js
  netmanager/src/views/pages/Logs/DataExport/index.js
  netmanager/src/views/pages/Logs/DataExport/logs_table.js
Labels: ready for review

#1253 [Netmanager] Shows add device button only within the airqo organisation
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#1255 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#1256 [Netmanager]Resizing of the Airqlouds dropdown and the Dashboard Searchbar
  netmanager/src/views/pages/Dashboard/Dashboard.js
Labels: ready for review

#1257 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/src/views/pages/Dashboard/Dashboard.js
Labels: ready for review

#1259 [Netmanager] Assign Users table refresh issue on delete of user
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
Labels: ready for review

#1260 [Netmanager] unable to select country on the add user modal
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review

#1261 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review

#1262 [Netmanager] Fix issue with missing uuid package in netmanager
  netmanager/package-lock.json
  netmanager/package.json
Labels: ready for review

#1267 [Netmanager] fixing issues from previous PRs
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/pages/UserList/components/HorizontalLoader/HorizontalLoader.js
  netmanager/src/views/pages/UserList/components/HorizontalLoader/loader.css
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review

#1270 [Netmanager] unable to select country in the add user modal
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review

#1277 downgrade github action version
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: good first issue, ready for review, devops

#1241 Authentication bugs
  mobile/lib/blocs/auth_code/auth_code_bloc.dart
  mobile/lib/blocs/auth_code/auth_code_event.dart
  mobile/lib/blocs/auth_code/auth_code_state.dart
  mobile/lib/blocs/blocs.dart
  mobile/lib/blocs/email_auth/email_auth_bloc.dart
  mobile/lib/blocs/email_auth/email_auth_event.dart
  mobile/lib/blocs/email_auth/email_auth_state.dart
  mobile/lib/blocs/email_verification/email_verification_bloc.dart
  mobile/lib/blocs/email_verification/email_verification_event.dart
  mobile/lib/blocs/email_verification/email_verification_state.dart
  mobile/lib/blocs/phone_auth/phone_auth_bloc.dart
  mobile/lib/blocs/phone_auth/phone_auth_event.dart
  mobile/lib/blocs/phone_auth/phone_auth_state.dart
  mobile/lib/blocs/phone_verification/phone_verification_bloc.dart
  mobile/lib/blocs/phone_verification/phone_verification_event.dart
  mobile/lib/blocs/phone_verification/phone_verification_state.dart
  mobile/lib/blocs/profile/profile_bloc.dart
  mobile/lib/main_common.dart
  mobile/lib/models/email_auth_model.dart
  mobile/lib/models/email_auth_model.g.dart
  mobile/lib/models/enum_constants.dart
  mobile/lib/models/phone_auth_model.dart
  mobile/lib/models/profile.dart
  mobile/lib/screens/auth/auth_verification.dart
  mobile/lib/screens/auth/auth_widgets.dart
  mobile/lib/screens/auth/email_auth_widget.dart
  mobile/lib/screens/auth/phone_auth_widget.dart
  mobile/lib/screens/email_authentication/email_auth_screen.dart
  mobile/lib/screens/email_authentication/email_auth_widgets.dart
  mobile/lib/screens/email_authentication/email_verification_screen.dart
  mobile/lib/screens/on_boarding/introduction_screen.dart
  mobile/lib/screens/on_boarding/splash_screen.dart
  mobile/lib/screens/phone_authentication/phone_auth_screen.dart
  mobile/lib/screens/phone_authentication/phone_auth_widgets.dart
  mobile/lib/screens/phone_authentication/phone_verification_screen.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/settings/account_deletion_widgets.dart
  mobile/lib/screens/settings/delete_account_screen.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/app_service.dart
  mobile/lib/themes/app_theme.dart
  mobile/lib/utils/extensions.dart
  mobile/lib/widgets/auth_widgets.dart
  mobile/lib/widgets/buttons.dart
  mobile/lib/widgets/dialogs.dart
  mobile/lib/widgets/text_fields.dart
Labels: bug, ready for review, mobile-app, authentication

#1278 Net refresh issue
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/pages/UserList/components/HorizontalLoader/HorizontalLoader.js
  netmanager/src/views/pages/UserList/components/HorizontalLoader/loader.css
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review

#1275 [WEBSITE] Update Monitor page map
  website/frontend/src/assets/img/OurProducts/Monitor/Africa.png
  website/frontend/styles/Products.scss
Labels: ready for review

#1273 [Netmanager]Improving on the Organization Selection
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
Labels: ready for review

#1286 [Netmanager] Improving Network map overview card responsiveness on Mobile view
  netmanager/src/assets/scss/device-management.sass
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementMap.js
  netmanager/src/views/components/Sites/SiteToolbar.js
Labels: ready for review

#1285 [Netmanager]Restructure overview charts
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/SensorChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/UptimeChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/VoltageChart.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/util.js
Labels: ready for review

#1280 Mobile app release.
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/pubspec.yaml
Labels: ready for review

#1290 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/pubspec.yaml
  netmanager/src/AppRoutes.js
  netmanager/src/assets/css/manager-map.css
  netmanager/src/assets/css/map-download.css
  netmanager/src/assets/css/map-filter.css
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/components/DataDisplay/Map/MapFilter.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Download/index.js
  netmanager/src/views/pages/ExportData/components/BreadCrumb.js
  netmanager/src/views/pages/ExportData/downloads.js
  netmanager/src/views/pages/ExportData/index.js
Labels: ready for review

#1292 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/redux/MapData/operations.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review, analytics

#1295 [Netmanager] Candidates table fixes
  netmanager/src/views/components/Table/CustomMaterialTable.js
  netmanager/src/views/pages/CandidateList/components/CandidateDrawer/index.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
Labels: ready for review

#1297 [WEB] Add pagination and message in case of no events
  website/frontend/src/pages/Events/index.js
  website/frontend/styles/Events.scss
Labels: ready for review

#1213 [MOBILE] Setup Firebase Crashlytics
  mobile/android/app/build.gradle
  mobile/android/build.gradle
  mobile/lib/utils/exception.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1299 Upgrading mobile app dependencies
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/blocs/settings/settings_bloc.dart
  mobile/lib/services/location_service.dart
  mobile/lib/services/notification_service.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1300 Replacing geocoding package with a custom API call.
  mobile/ios/Podfile.lock
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/models/address.dart
  mobile/lib/models/address.g.dart
  mobile/lib/models/models.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/location_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1303 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  mobile/android/app/build.gradle
  mobile/android/build.gradle
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/blocs/settings/settings_bloc.dart
  mobile/lib/models/address.dart
  mobile/lib/models/address.g.dart
  mobile/lib/models/models.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/location_service.dart
  mobile/lib/services/notification_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/exception.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
  website/frontend/src/pages/Events/index.js
  website/frontend/styles/Events.scss
Labels: ready for review

#1304 [Analytics] Add collocation error report card
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/IntraCorrelation/index.jsx
  platform/src/common/components/Modal/Modal.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/reports/[device].jsx
Labels: ready for review

#1305 move to production
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/IntraCorrelation/index.jsx
  platform/src/common/components/Modal/Modal.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/reports/[device].jsx
Labels: ready for review

#1309 [Netmanager] Implement a horizontal loader
  netmanager/src/views/components/AirQlouds/AirQloudToolbar.js
  netmanager/src/views/components/AirQlouds/AirQloudsTable.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceComponents.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceLogs.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/HorizontalLoader/HorizontalLoader.js
  netmanager/src/views/components/HorizontalLoader/loader.css
  netmanager/src/views/components/Sites/SiteToolbar.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/pages/UserList/components/HorizontalLoader/HorizontalLoader.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
Labels: ready for review

#1306 caching images(loading indicator)
  mobile/lib/widgets/custom_widgets.dart
Labels: ready for review, mobile-app

#1289 Retries
  mobile/lib/services/rest_api.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1248 Fix code to handle invalid emails
  mobile/lib/utils/extensions.dart
  mobile/test/utils/extensions/primitive_data_types_test.dart
Labels: ready for review, mobile-app

#1312 [Netmanager] adds access token to events & sites api routes
  netmanager/src/utils/envVariables.js
  netmanager/src/views/apis/deviceRegistry.js
Labels: ready for review

#1180 [PLATFORM] Google auth
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/pages/account/creation/index.jsx
Labels: ready for review

#1315 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/pages/account/creation/index.jsx
Labels: ready for review

#1318 [WEBSITE] Updated images
  website/frontend/src/assets/img/AirQuality.png
  website/frontend/src/assets/img/OurProducts/Analytics/section-1-overlap.png
  website/frontend/src/assets/img/monitor.png
  website/frontend/styles/Products.scss
Labels: ready for review
