Repository airqo-platform/AirQo-frontend, pull requests merged in 2023-05, with the labels that each got.

#1156 [MOBILE APP] hotfix - iOS failure on startup
  mobile/README.md
  mobile/android/app/build.gradle
  mobile/android/build.gradle
  mobile/build.yaml
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/ios/Runner/AppDelegate.swift
  mobile/ios/Runner/Info.plist
  mobile/lib/main.dart
  mobile/lib/main_dev.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/services/firebase_service.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/location_service.dart
  mobile/lib/themes/colors.dart
  mobile/lib/utils/exception.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
  mobile/test/profile_widgets_test.dart
  mobile/upgrade-dependencies.sh
Labels: ready for review, mobile-app

#1159 [Mobile app] resolving flutter linter issues.
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/web_view_page.dart
  mobile/lib/services/local_storage.dart
  mobile/lib/utils/data_formatter.dart
  mobile/lib/utils/network.dart
  mobile/lib/widgets/error_widgets.dart
Labels: ready for review, mobile-app

#1157 [Netmanager] LOGGING USERS WHO PERFORM DATA EXPORTS
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/analytics.js
Labels: ready for review

#1162 [Collocation] added collocation overview skeleton ui
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Collocation/AddMonitor/Skeletion/GraphCard.jsx
  platform/src/common/components/Collocation/AddMonitor/Skeletion/Overview.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/pages/index.jsx
  platform/tailwind.config.js
Labels: ready for review

#1164 move to production
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/analytics.js
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Collocation/AddMonitor/Skeletion/GraphCard.jsx
  platform/src/common/components/Collocation/AddMonitor/Skeletion/Overview.jsx
  platform/src/common/components/SideBar/index.jsx
  platform/src/pages/index.jsx
  platform/tailwind.config.js
Labels: ready for review

#1160 [PLATFORM] Platform Account Verification
  platform/.env.example
  platform/package.json
  platform/src/common/components/Account/RadioComponent.jsx
  platform/src/common/styles/global.scss
  platform/src/core/apis/Account.js
  platform/src/core/urls/authentication.js
  platform/src/lib/envConstants.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/account/CreationSlice.js
  platform/src/pages/account/creation/index.jsx
  platform/src/pages/account/creation/step2.jsx
  platform/src/pages/account/creation/step3.jsx
  platform/src/pages/account/creation/step4.jsx
  platform/tailwind.config.js
  platform/yarn.lock
Labels: ready for review

#1165 [Collocation] Display collocation periods and respective scheduled devices from api
  platform/package.json
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Collocation/AddMonitor/Overview/graph_card.jsx
  platform/src/common/components/Collocation/AddMonitor/Skeletion/Overview.jsx
  platform/src/common/components/Collocation/Collocate/empty_state.jsx
  platform/src/common/components/Collocation/Overview/empty_state.jsx
  platform/src/core/utils/matchingDevices.js
  platform/src/lib/store/services/collocation/collocationDataSlice.js
  platform/src/lib/store/services/collocation/index.js
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/yarn.lock
Labels: ready for review

#1168 [Netmanager] Apply airqlouds summary api to airqloud registry
  netmanager/src/redux/AirQloud/actions.js
  netmanager/src/redux/AirQloud/operations.js
  netmanager/src/redux/AirQloud/reducers.js
  netmanager/src/redux/AirQloud/selectors.js
  netmanager/src/views/components/AirQlouds/AirQloudView.js
  netmanager/src/views/components/AirQlouds/AirQloudsTable.js
Labels: ready for review

#1155 [Netmanager] Access control
  netmanager/src/AppRoutes.js
  netmanager/src/config/urls/analytics.js
  netmanager/src/config/urls/authService.js
  netmanager/src/redux/AccessControl/actions.js
  netmanager/src/redux/AccessControl/operations.js
  netmanager/src/redux/AccessControl/reducers.js
  netmanager/src/redux/Dashboard/operations.js
  netmanager/src/redux/DeviceRegistry/operations.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/redux/SiteRegistry/operations.js
  netmanager/src/redux/index.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementMap.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceView.js
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/Map/Map.js
  netmanager/src/views/components/Sites/SiteRegistry.js
  netmanager/src/views/components/Sites/SiteToolbar.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/components/Table/UserList/UserList.js
  netmanager/src/views/components/Table/UserList/components/UsersTable/UsersTable.js
  netmanager/src/views/components/Table/UserList/containers/UserList.js
  netmanager/src/views/containers/PageAccess.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
  netmanager/src/views/layouts/common/Sidebar/components/SidebarNav/SidebarNav.js
  netmanager/src/views/layouts/common/Topbar.js
  netmanager/src/views/pages/Account/components/AccountDetails/AccountDetails.js
  netmanager/src/views/pages/CandidateList/CandidateList.js
  netmanager/src/views/pages/Download/Download.js
  netmanager/src/views/pages/PermissionDenied/index.js
  netmanager/src/views/pages/Roles/components/RolesTable.js
  netmanager/src/views/pages/Roles/components/RolesToolbar.js
  netmanager/src/views/pages/Roles/components/UserPopupTable.js
  netmanager/src/views/pages/Roles/index.js
  netmanager/src/views/pages/UserList/UserList.js
  netmanager/src/views/pages/UserList/components/UsersTable/UsersTable.js
  netmanager/src/views/pages/UserList/components/UsersToolbar/UsersToolbar.js
  netmanager/src/views/stateConnectors/usersStateConnector.js
Labels: ready for review

#1171 [MOBILE] Rename search bar widget
  mobile/android/build.gradle
  mobile/ios/Podfile.lock
  mobile/lib/screens/feedback/feedback_page.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/screens/search/search_page.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/widgets/tooltip.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1163 [Mobile app] Enhancements to Insights
  mobile/lib/models/enum_constants.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/insights/insights_page.dart
  mobile/lib/screens/insights/insights_widgets.dart
  mobile/lib/screens/map/map_view_widgets.dart
  mobile/lib/screens/search/search_widgets.dart
  mobile/lib/themes/app_theme.dart
  mobile/lib/widgets/custom_widgets.dart
  mobile/lib/widgets/dialogs.dart
  mobile/test/api/fetch_air_quality_readings_test.dart
  mobile/test/api/get_app_version_test.dart
  mobile/test/screens/insights/insights_widgets_test.dart
Labels: ready for review

#1174 Website Domains: Explicit URLs
  website/backend/settings.py
Labels: ready for review

#1173 [Netmanager] Loads sites pages fasters
  netmanager/src/redux/SiteRegistry/actions.js
  netmanager/src/redux/SiteRegistry/operations.js
  netmanager/src/redux/SiteRegistry/reducers/index.js
  netmanager/src/redux/SiteRegistry/reducers/siteDetails.js
  netmanager/src/redux/SiteRegistry/reducers/sitesSummary.js
  netmanager/src/redux/SiteRegistry/selectors.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/components/Sites/SitesTable.js
Labels: ready for review

#1170 [Netmanager] Run device test
  netmanager/src/utils/dateTime.js
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
Labels: ready for review

#1178 remove flutter localisation package
  mobile/pubspec.lock
  mobile/pubspec.yaml
Labels: ready for review, mobile-app

#1172 Kya Unit tests
  mobile/lib/blocs/kya/kya_bloc.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/utils/extensions.dart
  mobile/test/utils/extensions/kya/kya_test.dart
Labels: ready for review, mobile-app

#1176 [Mobile app] Hotfixes
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/services/rest_api.dart
Labels: ready for review, mobile-app

#1161 Add unit tests for primitive extensions
  mobile/lib/screens/on_boarding/on_boarding_widgets.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.yaml
  mobile/test/utils/extensions_test.dart
Labels: ready for review, mobile-app

#1175 [Netmanager] Assigns available users to network
  netmanager/src/AppRoutes.js
  netmanager/src/redux/AccessControl/actions.js
  netmanager/src/redux/AccessControl/operations.js
  netmanager/src/redux/AccessControl/reducers.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
  netmanager/src/views/pages/UserList/AvailableUserList.js
  netmanager/src/views/pages/UserList/components/UsersTable/AvailableUsersTable.js
Labels: ready for review

#1181 [WEBSITE] Dynamic African cities section
  website/backend/africancities/__init__.py
  website/backend/africancities/admin.py
  website/backend/africancities/apps.py
  website/backend/africancities/migrations/0001_initial.py
  website/backend/africancities/migrations/0002_remove_content_description_description.py
  website/backend/africancities/migrations/__init__.py
  website/backend/africancities/models.py
  website/backend/africancities/serializers.py
  website/backend/africancities/views.py
  website/backend/event/admin.py
  website/backend/event/models.py
  website/backend/settings.py
  website/backend/urls.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/AfricanCities/CitiesSlice.js
  website/frontend/reduxStore/Events/EventSlice.js
  website/frontend/reduxStore/index.js
  website/frontend/src/components/Footer.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
  website/frontend/styles/AfricanCitiesPage.scss
Labels: ready for review

#1182 [Mobile app] location fixes
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/blocs/nearby_location/nearby_location_event.dart
  mobile/lib/blocs/nearby_location/nearby_location_state.dart
  mobile/lib/constants/config.dart
  mobile/lib/models/current_location.dart
  mobile/lib/models/location_history.dart
  mobile/lib/models/models.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/on_boarding/location_setup_screen.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/location_service.dart
  mobile/lib/utils/extensions.dart
  mobile/test/utils/extensions/kya/kya_test.dart
Labels: ready for review, mobile-app

#1184 [Netmanager] reduce network uptime time interval to 7 days
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
Labels: ready for review

#1186 [Hotfix] Loads the right site details
  netmanager/src/redux/SiteRegistry/operations.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/components/Sites/SitesTable.js
Labels: ready for review

#1185 New release updates
  mobile/android/Gemfile.lock
  mobile/android/fastlane/release_notes.txt
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/blocs/nearby_location/nearby_location_state.dart
  mobile/lib/constants/config.dart
  mobile/lib/models/current_location.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/services/location_service.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
  mobile/test/utils/extensions/kya/primitive_data_types_test.dart
  mobile/test/utils/extensions_test.dart
Labels: ready for review, mobile-app

#1187 [Collocation] Reports pages & updating api version
  platform/cypress.config.js
  platform/cypress/e2e/collocation/collocation.cy.js
  platform/src/common/components/Collocation/AddMonitor/Overview/graph_card.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  platform/src/common/components/Collocation/Report/Charts/CorrelationBarChart.jsx
  platform/src/common/components/Collocation/Report/Charts/CorrelationLineChart.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/DataCompletenessTable/DataTable.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/DataCompletenessTable/index.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/InterCorrelation/index.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/IntraCorrelation/custom_legend.jsx
  platform/src/common/components/Collocation/Report/MonitorReport/IntraCorrelation/index.jsx
  platform/src/common/components/Collocation/Report/box.jsx
  platform/src/common/components/Layout/header.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Navigation/breadcrumb.jsx
  platform/src/common/components/Table/index.jsx
  platform/src/core/urls/deviceMonitoring.js
  platform/src/core/utils/colors.js
  platform/src/core/utils/matchingDevices.js
  platform/src/lib/store/services/collocation/index.js
  platform/src/lib/store/services/deviceRegistry.js
  platform/src/pages/collocation/add_monitor.jsx
  platform/src/pages/collocation/collocate.jsx
  platform/src/pages/collocation/overview.jsx
  platform/src/pages/collocation/reports/[device].jsx
  platform/src/pages/collocation/reports/monitor_report/[device].jsx
  platform/tailwind.config.js
Labels: ready for review, resolved

#1202 Restoring mobile app folder
  mobile/android/Gemfile.lock
  mobile/android/fastlane/release_notes.txt
  mobile/ios/Podfile.lock
  mobile/ios/Runner.xcodeproj/project.pbxproj
  mobile/lib/blocs/kya/kya_bloc.dart
  mobile/lib/blocs/nearby_location/nearby_location_bloc.dart
  mobile/lib/blocs/nearby_location/nearby_location_event.dart
  mobile/lib/blocs/nearby_location/nearby_location_state.dart
  mobile/lib/constants/config.dart
  mobile/lib/models/current_location.dart
  mobile/lib/models/location_history.dart
  mobile/lib/models/models.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/screens/dashboard/dashboard_widgets.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/on_boarding/location_setup_screen.dart
  mobile/lib/screens/on_boarding/on_boarding_widgets.dart
  mobile/lib/screens/settings/settings_page.dart
  mobile/lib/services/hive_service.dart
  mobile/lib/services/location_service.dart
  mobile/lib/services/rest_api.dart
  mobile/lib/utils/extensions.dart
  mobile/pubspec.lock
  mobile/pubspec.yaml
  mobile/test/utils/extensions/kya_test.dart
  mobile/test/utils/extensions/primitive_data_types_test.dart
  mobile/test/utils/extensions_test.dart
Labels: ready for review, mobile-app

#1203 [Netmanager] Adds available users page
  netmanager/src/AppRoutes.js
  netmanager/src/redux/AccessControl/actions.js
  netmanager/src/redux/AccessControl/operations.js
  netmanager/src/redux/AccessControl/reducers.js
  netmanager/src/views/apis/accessControl.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Sidebar/components/NetworkDropdown.js
  netmanager/src/views/pages/UserList/AvailableUserList.js
  netmanager/src/views/pages/UserList/components/UsersTable/AvailableUsersTable.js
Labels: ready for review

#1204 [Netmanager] Reduce network uptime interval to 7 days
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementStats.js
Labels: ready for review

#1205 [Netmanager] Loads the right site details
  netmanager/src/redux/SiteRegistry/operations.js
  netmanager/src/views/components/Sites/SiteView.js
  netmanager/src/views/components/Sites/SitesTable.js
Labels: ready for review

#1188 [Netmanager] reduce size of map markers
  netmanager/src/assets/css/overlay-map.css
Labels: ready for review

#1214 [WEBSITE] African Cities Implementation
  website/backend/africancities/__init__.py
  website/backend/africancities/admin.py
  website/backend/africancities/apps.py
  website/backend/africancities/migrations/0001_initial.py
  website/backend/africancities/migrations/__init__.py
  website/backend/africancities/models.py
  website/backend/africancities/serializers.py
  website/backend/africancities/views.py
  website/backend/settings.py
  website/backend/urls.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/AfricanCities/CitiesSlice.js
  website/frontend/reduxStore/index.js
  website/frontend/src/components/Footer.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
  website/frontend/styles/AfricanCitiesPage.scss
Labels: ready for review
