Repository airqo-platform/AirQo-frontend, pull requests merged in 2024-05, with the labels that each got.

#1993 [website] Addressed QA feedback and content update.
  website/backend/cleanair/migrations/0035_alter_program_program_details.py
  website/backend/cleanair/migrations/0036_alter_program_program_details.py
  website/backend/cleanair/migrations/0037_remove_program_program_details_program_sub_text.py
  website/backend/cleanair/migrations/0038_forumevent_schedule_details.py
  website/backend/cleanair/migrations/0039_rename_sponsorship_details_forumevent_sponsorship_opportunities_and_more.py
  website/backend/cleanair/migrations/0040_rename_sponsorship_opportunities_forumevent_sponsorship_opportunities_about_and_more.py
  website/backend/cleanair/migrations/0041_forumevent_partners_text_section_and_more.py
  website/backend/cleanair/migrations/0042_rename_travel_logistics_forumevent_travel_logistics_vaccination_details_and_more.py
  website/backend/cleanair/migrations/0043_forumevent_glossary_details.py
  website/backend/cleanair/migrations/0044_alter_partner_category.py
  website/backend/cleanair/migrations/0045_forumevent_travel_logistics_accommodation_details.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/components/CleanAir/profile/Profile.js
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/CommitteePage.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Glossary.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Partners.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Schedule.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Travel.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1994 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  website/backend/cleanair/migrations/0035_alter_program_program_details.py
  website/backend/cleanair/migrations/0036_alter_program_program_details.py
  website/backend/cleanair/migrations/0037_remove_program_program_details_program_sub_text.py
  website/backend/cleanair/migrations/0038_forumevent_schedule_details.py
  website/backend/cleanair/migrations/0039_rename_sponsorship_details_forumevent_sponsorship_opportunities_and_more.py
  website/backend/cleanair/migrations/0040_rename_sponsorship_opportunities_forumevent_sponsorship_opportunities_about_and_more.py
  website/backend/cleanair/migrations/0041_forumevent_partners_text_section_and_more.py
  website/backend/cleanair/migrations/0042_rename_travel_logistics_forumevent_travel_logistics_vaccination_details_and_more.py
  website/backend/cleanair/migrations/0043_forumevent_glossary_details.py
  website/backend/cleanair/migrations/0044_alter_partner_category.py
  website/backend/cleanair/migrations/0045_forumevent_travel_logistics_accommodation_details.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/components/CleanAir/profile/Profile.js
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/CommitteePage.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Glossary.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Partners.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Schedule.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Travel.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1997 [website] Event details content and style Updates
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
  website/frontend/styles/Events.scss
Labels: ready for review

#1996 [Analytics] Displays suggested locations by country on map sidebar
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/map/index.jsx
Labels: ready for review

#2000 [platform] Map optimization and improvements (QA Feedback)
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/map/index.jsx
Labels: ready for review

#1992 [platform] Side Bar collapse and mobile view Inconsistency fix
  platform/public/icons/Settings/PersonIcon.js
  platform/public/icons/SideBar/LogoutIcon.js
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/MapLayout.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/SideBar/CollapsedSidebar.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/lib/store/index.js
  platform/src/lib/store/services/sideBar/SideBarSlice.js
Labels: ready for review

#1999 Added netmanager to AppRoutes.js
  netmanager/src/AppRoutes.js
Labels: work in progress, ready for review

#1998 move to production
  k8s/platform/values-stage.yaml
  netmanager/src/AppRoutes.js
  platform/public/icons/Settings/PersonIcon.js
  platform/public/icons/SideBar/LogoutIcon.js
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/MapLayout.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/SideBar/CollapsedSidebar.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/lib/store/index.js
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/lib/store/services/sideBar/SideBarSlice.js
  platform/src/pages/map/index.jsx
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
  website/frontend/styles/Events.scss
Labels: ready for review

#2002 retrigger frontends
  netmanager/README.md
  platform/README.md
Labels: ready for review

#2003 move to production
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  netmanager/README.md
  platform/README.md
Labels: ready for review

#2001 Disabling the inital implementation of Account Linking
  mobile/lib/screens/email_authentication/email_verification_screen.dart
  mobile/lib/screens/email_link/confirm_account_details.dart
  mobile/lib/screens/email_link/email_link_page.dart
  mobile/lib/screens/email_link/email_link_widgets.dart
  mobile/lib/screens/email_link/link_verification_screen.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/profile/profile_edit_page.dart
  mobile/lib/screens/profile/profile_view.dart
  mobile/lib/screens/profile/profile_widgets.dart
Labels: ready for review, mobile-app

#2004 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  mobile/lib/screens/email_authentication/email_verification_screen.dart
  mobile/lib/screens/email_link/confirm_account_details.dart
  mobile/lib/screens/email_link/email_link_page.dart
  mobile/lib/screens/email_link/email_link_widgets.dart
  mobile/lib/screens/email_link/link_verification_screen.dart
  mobile/lib/screens/home_page.dart
  mobile/lib/screens/profile/profile_edit_page.dart
  mobile/lib/screens/profile/profile_view.dart
  mobile/lib/screens/profile/profile_widgets.dart
Labels: ready for review

#2006 [netmanager] chore: Adjust loading state to MapContainer
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#2005 [platform] chore: Map node updates
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Cities.js
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/api/proxy.js
Labels: ready for review

#2008 [platform] Sidebar collapse map route Fix
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
Labels: ready for review

#2007 move to production
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  netmanager/src/views/pages/Map/OverlayMap.js
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Cities.js
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/api/proxy.js
Labels: ready for review

#2009 [Analytics] Modified customise feature search functionality
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/search/SearchField.jsx
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/urls/deviceRegistry.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/pages/_document.jsx
Labels: ready for review

#2010 move to production
  k8s/netmanager/values-prod.yaml
  k8s/platform/values-prod.yaml
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/search/SearchField.jsx
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/urls/deviceRegistry.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/pages/_document.jsx
Labels: ready for review

#2011 [platform] Update layout component to fix UI glitches
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/pages/Home/index.jsx
  platform/src/pages/analytics/index.jsx
Labels: ready for review

#2012 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/Tabs/index.jsx
  platform/src/pages/Home/index.jsx
  platform/src/pages/analytics/index.jsx
Labels: ready for review

#2013 [platform] Analytics Cards and Chart alignments
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#2014 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#1995 Adjusted request access url to point to analytics
  netmanager/src/views/pages/SignUp/Login.js
  netmanager/src/views/pages/SignUp/Register.js
Labels: ready for review

#2015 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  netmanager/src/views/pages/SignUp/Login.js
  netmanager/src/views/pages/SignUp/Register.js
Labels: ready for review

#2016 [platform] Chore: Improve UI, Optimize Images, and Refactor Code
  platform/public/images/Account/OrganisationSideQuote.png
  platform/public/images/Account/SideQuote.png
  platform/public/images/Account/analyticsImage.png
  platform/public/images/Account/analyticsImage.webp
  platform/public/images/Home/analytics.png
  platform/public/images/Home/analyticsImage.png
  platform/public/images/Home/analyticsImage.webp
  platform/public/images/Home/export.png
  platform/public/images/Home/settings.png
  platform/public/images/map/Emoji.png
  platform/public/images/map/Emoji.webp
  platform/public/images/map/Heatmap.png
  platform/public/images/map/Heatmap.webp
  platform/public/images/map/Node.png
  platform/public/images/map/Node.webp
  platform/public/images/map/Node_number.png
  platform/public/images/map/Node_number.webp
  platform/public/images/map/dark.png
  platform/public/images/map/dark.webp
  platform/public/images/map/light.png
  platform/public/images/map/light.webp
  platform/public/images/map/satellite.png
  platform/public/images/map/satellite.webp
  platform/public/images/map/street.png
  platform/public/images/map/street.webp
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/components/index.jsx
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/MapLayout.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/LayerModal.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/search/SearchField.jsx
  platform/src/common/styles/global.scss
  platform/src/pages/Home/index.jsx
  platform/src/pages/account/creation/individual/verify-email.jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify-email.jsx
Labels: ready for review

#2017 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  platform/public/images/Account/OrganisationSideQuote.png
  platform/public/images/Account/SideQuote.png
  platform/public/images/Account/analyticsImage.png
  platform/public/images/Account/analyticsImage.webp
  platform/public/images/Home/analytics.png
  platform/public/images/Home/analyticsImage.png
  platform/public/images/Home/analyticsImage.webp
  platform/public/images/Home/export.png
  platform/public/images/Home/settings.png
  platform/public/images/map/Emoji.png
  platform/public/images/map/Emoji.webp
  platform/public/images/map/Heatmap.png
  platform/public/images/map/Heatmap.webp
  platform/public/images/map/Node.png
  platform/public/images/map/Node.webp
  platform/public/images/map/Node_number.png
  platform/public/images/map/Node_number.webp
  platform/public/images/map/dark.png
  platform/public/images/map/dark.webp
  platform/public/images/map/light.png
  platform/public/images/map/light.webp
  platform/public/images/map/satellite.png
  platform/public/images/map/satellite.webp
  platform/public/images/map/street.png
  platform/public/images/map/street.webp
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Button/TabButtons.jsx
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/components/index.jsx
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/MapLayout.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/LayerModal.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/search/SearchField.jsx
  platform/src/common/styles/global.scss
  platform/src/pages/Home/index.jsx
  platform/src/pages/account/creation/individual/verify-email.jsx
  platform/src/pages/account/creation/organisation/register.jsx
  platform/src/pages/account/creation/organisation/verify-email.jsx
Labels: ready for review

#2018 [analytics] Calendar and Chart Updates
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Calendar/Calendar.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/components/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: ready for review

#2019 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Button/index.jsx
  platform/src/common/components/Calendar/Calendar.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/components/index.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: ready for review

#2022 [website] bug fixes
  website/backend/settings.py
  website/frontend/App.js
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/src/icons/careers/careers.webp
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/src/pages/CareerPage.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
  website/frontend/src/pages/Events/index.js
  website/frontend/src/pages/OurProducts/CalibrationPage.js
  website/frontend/src/pages/Partners/index.js
  website/frontend/styles/CareersPage.scss
Labels: ready for review

#2023 move to production
  website/backend/settings.py
  website/frontend/App.js
  website/frontend/src/components/ImpactNumbers/index.js
  website/frontend/src/icons/careers/careers.webp
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/src/pages/CareerPage.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
  website/frontend/src/pages/Events/index.js
  website/frontend/src/pages/OurProducts/CalibrationPage.js
  website/frontend/src/pages/Partners/index.js
  website/frontend/styles/CareersPage.scss
Labels: ready for review

#2024 [netmanager] Revert changes to routes
  netmanager/src/AppRoutes.js
Labels: ready for review

#2026 [Platform] Data export checks
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Modal/ExportDataModal.jsx
  platform/src/common/components/Modal/ExportModalWrapper.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: ready for review

#2028 move to production
  k8s/netmanager/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/ChartContainer.js
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Modal/ExportDataModal.jsx
  platform/src/common/components/Modal/ExportModalWrapper.jsx
  platform/src/common/components/Modal/PrintReportModal.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/pages/analytics/index.jsx
  platform/src/pages/analytics/tabs/Explore.jsx
Labels: ready for review

#2030 updating the README
  netmanager/README.md
Labels: ready for review

#2031 move to production
  k8s/platform/values-prod.yaml
  netmanager/README.md
Labels: ready for review

#2027 [Analytics] Location naming alignment and modified map search logic
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/core/utils/strings.js
  platform/src/lib/store/services/charts/ChartData.js
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#2035 [Analytics] Update Profile and checklist bug fixes
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/SideBar/SideBarDrawer.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/common/styles/global.scss
  platform/src/pages/settings/Tabs/Profile.jsx
Labels: ready for review

#2036 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Dropdowns/CustomDropdown.jsx
  platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/SideBarDrawer.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/common/styles/global.scss
  platform/src/core/utils/strings.js
  platform/src/lib/store/services/charts/ChartData.js
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/src/pages/settings/Tabs/Profile.jsx
Labels: ready for review

#2037 [Hotfix] Usage of one name for location names
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/core/utils/strings.js
  platform/src/pages/analytics/index.jsx
  platform/src/pages/settings/Tabs/Profile.jsx
Labels: ready for review

#2039 [Analytics] Fix issue of empty suggestions under map side panel
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/pages/map/index.jsx
Labels: ready for review

#2040 [analytics] Added auto-logout feature for inactivity
  platform/src/common/components/Layout/index.jsx
  platform/src/pages/settings/Tabs/Profile.jsx
Labels: ready for review

#2042 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Layout/index.jsx
  platform/src/pages/settings/Tabs/Profile.jsx
Labels: ready for review

#2043 [Analytics] Fix Data Splitting Issue for Map Sidebar Display
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
Labels: ready for review

#2044 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
Labels: ready for review

#2045 [Hotfix] Chart loading behavior and bug fixes
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/core/utils/LogoutUser.jsx
  platform/src/core/utils/SetChartDetails.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#2046 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/core/utils/LogoutUser.jsx
  platform/src/core/utils/SetChartDetails.jsx
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#2048 [Analytics] Map sidebar QA improvements
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapControls.js
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/styles/global.scss
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/map/index.jsx
Labels: ready for review

#2049 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapControls.js
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/styles/global.scss
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/map/index.jsx
Labels: ready for review

#2050 [analytics] Map client side error fix
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/lib/store/services/map/MapSlice.js
Labels: ready for review

#2051 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/lib/store/services/map/MapSlice.js
Labels: ready for review

#2047 [Hotfix] Analytics chart loading fix
  platform/public/icons/Charts/Invalid.js
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Layout/index.jsx
  platform/src/core/utils/SetChartDetails.jsx
  platform/src/lib/store/index.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#2052 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/public/icons/Charts/Invalid.js
  platform/src/common/components/AQNumberCard/index.jsx
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Layout/index.jsx
  platform/src/core/utils/SetChartDetails.jsx
  platform/src/lib/store/index.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/pages/analytics/tabs/OverView.jsx
Labels: ready for review

#2053 [Hotfix] Analytics chart loading
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Layout/index.jsx
  platform/src/pages/Home/index.jsx
Labels: ready for review

#2054 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Calendar/CustomCalendar.jsx
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Layout/index.jsx
  platform/src/pages/Home/index.jsx
Labels: ready for review

#2055 [Hotfix] Locations search fix
  platform/src/common/components/Customise/LocationsContentComponent.jsx
Labels: ready for review

#2056 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Customise/LocationsContentComponent.jsx
Labels: ready for review
