Repository airqo-platform/AirQo-frontend, pull requests merged in 2024-07, with the labels that each got.

#2079 (Analytics) chore: Add disabled state to account creation roles
  platform/src/common/components/Account/CheckComponent.jsx
  platform/src/pages/account/creation/index.jsx
Labels: ready for review

#2080 move to production
  platform/src/common/components/Account/CheckComponent.jsx
  platform/src/pages/account/creation/index.jsx
Labels: ready for review

#2081 (Website) chore: Update event views and frontend API to retrieve event details
  website/backend/event/views.py
  website/frontend/apis/index.js
  website/frontend/src/pages/CleanAir/EventDetails.js
  website/frontend/src/pages/Events/Details.js
Labels: ready for review

#2082 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  website/backend/event/views.py
  website/frontend/apis/index.js
  website/frontend/src/pages/CleanAir/EventDetails.js
  website/frontend/src/pages/Events/Details.js
Labels: ready for review

#2078 [Analytics] Map SideBar code refactor and fix
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/Map/components/sidebar/components/CountryList.jsx
  platform/src/common/components/Map/components/sidebar/components/LocationAlertCard.jsx
  platform/src/common/components/Map/components/sidebar/components/LocationCards.jsx
  platform/src/common/components/Map/components/sidebar/components/PollutantCard.jsx
  platform/src/common/components/Map/components/sidebar/components/Predictions.jsx
  platform/src/common/components/Map/components/sidebar/components/TabSelector.jsx
  platform/src/common/components/Map/components/sidebar/index.jsx
  platform/src/common/components/Map/data/Cities.js
  platform/src/common/components/Map/data/countries.json
  platform/src/core/apis/DeviceRegistry.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/lib/store/services/deviceRegistry/RecentMeasurementsSlice.js
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/src/pages/map/index.jsx
Labels: ready for review

#2083 move to production
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/Map/components/sidebar/components/CountryList.jsx
  platform/src/common/components/Map/components/sidebar/components/LocationAlertCard.jsx
  platform/src/common/components/Map/components/sidebar/components/LocationCards.jsx
  platform/src/common/components/Map/components/sidebar/components/PollutantCard.jsx
  platform/src/common/components/Map/components/sidebar/components/Predictions.jsx
  platform/src/common/components/Map/components/sidebar/components/TabSelector.jsx
  platform/src/common/components/Map/components/sidebar/index.jsx
  platform/src/common/components/Map/data/Cities.js
  platform/src/common/components/Map/data/countries.json
  platform/src/core/apis/DeviceRegistry.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/lib/store/services/deviceRegistry/RecentMeasurementsSlice.js
  platform/src/pages/analytics/tabs/OverView.jsx
  platform/src/pages/map/index.jsx
Labels: ready for review

#2088 (reports) Charts and report
  .github/workflows/deploy-frontend-pr-previews.yml
  reports/Dockerfile
  reports/src/app/NetworkIssues.tsx
  reports/src/app/SessionAndThemeProvider.tsx
  reports/src/app/api/auth/[...nextauth]/options.ts
  reports/src/app/api/auth/[...nextauth]/route.ts
  reports/src/app/error.tsx
  reports/src/app/favicon.ico
  reports/src/app/files/page.tsx
  reports/src/app/layout.tsx
  reports/src/app/login/page.tsx
  reports/src/app/not-found.tsx
  reports/src/app/report/[reportID]/page.tsx
  reports/src/app/report/_sections/ReportForm.tsx
  reports/src/app/report/_sections/SkeletonLoader.tsx
  reports/src/app/report/page.tsx
  reports/src/app/settings/page.tsx
  reports/src/components/authForm/index.tsx
  reports/src/components/forms/reportForm/index.tsx
  reports/src/components/header/Header.tsx
  reports/src/components/reportTemplates/graphs/index.tsx
  reports/src/components/reportTemplates/template1/index.tsx
  reports/src/layout/MainLayout.tsx
  reports/src/lib/hooks.ts
  reports/src/lib/loginCheck.tsx
  reports/src/lib/reduxSlices/gridSlice.tsx
  reports/src/lib/store.tsx
  reports/src/lib/utils.ts
  reports/src/services/sessionProvider/index.tsx
  reports/src/services/themeProvider/ThemeProvider.tsx
  reports/tsconfig.json
Labels: ready for review

#2090 move to production
  .github/workflows/deploy-frontend-pr-previews.yml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  mobile/lib/blocs/insights/insights_bloc.dart
  mobile/lib/main.dart
  mobile/lib/screens/dashboard/dashboard_view.dart
  mobile/lib/services/location_service.dart
  mobile/lib/services/rest_api.dart
  reports/Dockerfile
  reports/src/app/NetworkIssues.tsx
  reports/src/app/SessionAndThemeProvider.tsx
  reports/src/app/api/auth/[...nextauth]/options.ts
  reports/src/app/api/auth/[...nextauth]/route.ts
  reports/src/app/error.tsx
  reports/src/app/favicon.ico
  reports/src/app/files/page.tsx
  reports/src/app/layout.tsx
  reports/src/app/login/page.tsx
  reports/src/app/not-found.tsx
  reports/src/app/report/[reportID]/page.tsx
  reports/src/app/report/_sections/ReportForm.tsx
  reports/src/app/report/_sections/SkeletonLoader.tsx
  reports/src/app/report/page.tsx
  reports/src/app/settings/page.tsx
  reports/src/components/authForm/index.tsx
  reports/src/components/forms/reportForm/index.tsx
  reports/src/components/header/Header.tsx
  reports/src/components/reportTemplates/graphs/index.tsx
  reports/src/components/reportTemplates/template1/index.tsx
  reports/src/layout/MainLayout.tsx
  reports/src/lib/hooks.ts
  reports/src/lib/loginCheck.tsx
  reports/src/lib/reduxSlices/gridSlice.tsx
  reports/src/lib/store.tsx
  reports/src/lib/utils.ts
  reports/src/services/sessionProvider/index.tsx
  reports/src/services/themeProvider/ThemeProvider.tsx
  reports/tsconfig.json
Labels: ready for review

#2091 [Analytics] Update README.md to trigger new ENVS
  platform/README.md
Labels: ready for review

#2092 move to production
  k8s/reports/values-prod.yaml
  k8s/reports/values-stage.yaml
  platform/README.md
Labels: ready for review

#2093 Modify ports for Reports Service
  k8s/reports/values-dev.yaml
  k8s/reports/values-prod.yaml
  k8s/reports/values-stage.yaml
Labels: ready for review

#2094 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  k8s/reports/values-dev.yaml
  k8s/reports/values-prod.yaml
  k8s/reports/values-stage.yaml
Labels: ready for review

#2097 (Analytics) feat: Upgrade to Node.js 18.x - 20.x and Next ^14.2.5
  platform/.babelrc.js
  platform/.eslintrc.json
  platform/.gitignore
  platform/Dockerfile
  platform/next.config.js
  platform/package.json
  platform/src/common/components/SideBar/SideBarItem.jsx
  platform/src/core/utils/protectedRoute.js
  platform/src/lib/store/services/account/UserDefaultsSlice.js
  platform/src/pages/Home/index.jsx
  platform/src/pages/_document.jsx
  platform/yarn.lock
Labels: enhancement, ready for review

#2100 (reports) chore: Update Node.js version to 20.x in Dockerfile
  .github/workflows/deploy-frontend-pr-previews.yml
  reports/Dockerfile
  reports/next.config.mjs
  reports/package-lock.json
  reports/package.json
  reports/src/app/SessionAndThemeProvider.tsx
  reports/src/app/api/auth/[...nextauth]/options.ts
  reports/src/components/authForm/index.tsx
  reports/src/components/reportTemplates/template1/index.tsx
Labels: ready for review, deployments

#2101 Refactor file paths and imports for reports feature
  reports/src/app/api/auth/[...nextauth]/options.ts
  reports/src/app/not-found.tsx
  reports/src/app/page.tsx
  reports/src/app/reports/files/page.tsx
  reports/src/app/reports/login/page.tsx
  reports/src/app/reports/report/[reportID]/page.tsx
  reports/src/app/reports/report/_sections/ReportForm.tsx
  reports/src/app/reports/report/_sections/SkeletonLoader.tsx
  reports/src/app/reports/report/page.tsx
  reports/src/app/reports/settings/page.tsx
  reports/src/components/authForm/index.tsx
  reports/src/components/header/Header.tsx
  reports/src/components/sidebar/SideBar.tsx
  reports/src/middleware.ts
Labels: ready for review, deployments

#2102 refactor:(charts) Add WHO standard reference line
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Charts/components/index.jsx
Labels: enhancement, ready for review

#2103 [Netmanager] Remove unused features/pages
  netmanager/src/AppRoutes.js
  netmanager/src/__tests__/faultyDevices/ManageFaults.test.js
  netmanager/src/config/urls/authService.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/redux/Join/reducers/userReducer.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/components/AirqualitySearch/aq_data.js
  netmanager/src/views/components/AirqualitySearch/dashboard_searchbar.js
  netmanager/src/views/components/AirqualitySearch/index.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementFaults.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Topbar.js
  netmanager/src/views/pages/Analytics/components/Breadcrumb.jsx
  netmanager/src/views/pages/CandidateList/CandidateList.js
  netmanager/src/views/pages/CandidateList/components/CandidateDrawer/index.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/index.js
  netmanager/src/views/pages/CandidateList/components/CandidatesToolbar/CandidatesToolbar.js
  netmanager/src/views/pages/CandidateList/components/CandidatesToolbar/index.js
  netmanager/src/views/pages/CandidateList/components/UserEditForm/UserEditForm.js
  netmanager/src/views/pages/CandidateList/components/UserEditForm/index.js
  netmanager/src/views/pages/CandidateList/components/index.js
  netmanager/src/views/pages/CandidateList/data.js
  netmanager/src/views/pages/CandidateList/index.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/UserStats/UserStats.js
  netmanager/src/views/stateConnectors/usersStateConnector.js
Labels: ready for review

#2104 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  k8s/reports/values-prod.yaml
  netmanager/src/AppRoutes.js
  netmanager/src/__tests__/faultyDevices/ManageFaults.test.js
  netmanager/src/config/urls/authService.js
  netmanager/src/redux/Join/actions.js
  netmanager/src/redux/Join/reducers/userReducer.js
  netmanager/src/views/apis/authService.js
  netmanager/src/views/components/AirqualitySearch/aq_data.js
  netmanager/src/views/components/AirqualitySearch/dashboard_searchbar.js
  netmanager/src/views/components/AirqualitySearch/index.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementFaults.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/layouts/common/Topbar.js
  netmanager/src/views/pages/Analytics/components/Breadcrumb.jsx
  netmanager/src/views/pages/CandidateList/CandidateList.js
  netmanager/src/views/pages/CandidateList/components/CandidateDrawer/index.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/index.js
  netmanager/src/views/pages/CandidateList/components/CandidatesToolbar/CandidatesToolbar.js
  netmanager/src/views/pages/CandidateList/components/CandidatesToolbar/index.js
  netmanager/src/views/pages/CandidateList/components/UserEditForm/UserEditForm.js
  netmanager/src/views/pages/CandidateList/components/UserEditForm/index.js
  netmanager/src/views/pages/CandidateList/components/index.js
  netmanager/src/views/pages/CandidateList/data.js
  netmanager/src/views/pages/CandidateList/index.js
  netmanager/src/views/pages/Dashboard/Dashboard.js
  netmanager/src/views/pages/UserStats/UserStats.js
  netmanager/src/views/stateConnectors/usersStateConnector.js
Labels: ready for review

#2105 [Hotfix] Add missing client page route
  netmanager/src/AppRoutes.js
Labels: ready for review

#2106 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/src/AppRoutes.js
Labels: ready for review

#2114 fix : Refactor Customize Component styling and Enhance WHO Reference Line in Chart
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Charts/components/index.jsx
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
Labels: bug, ready for review

#2115 chore: Update with New (AQI) index on AirQo Map for PM2.5 Pollutant
  platform/src/common/components/Map/components/Legend.js
  platform/src/common/components/Map/components/MapNodes.js
Labels: ready for review

#2116 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Charts/Charts.js
  platform/src/common/components/Charts/components/index.jsx
  platform/src/common/components/Customise/LocationsContentComponent.jsx
  platform/src/common/components/Customise/index.jsx
  platform/src/common/components/Map/components/Legend.js
  platform/src/common/components/Map/components/MapNodes.js
Labels: ready for review

#2117 Fix Deprecated Python runtime version for Website
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: ready for review

#2118 move to production
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
Labels: ready for review

#2107 feat: Upgraded Website Performance via Dependency Updates and webpack Enhancements
  website/Dockerfile
  website/backend/settings.py
  website/frontend/src/assets/img/ApiSection.png
  website/frontend/src/assets/img/QR_code.webp
  website/frontend/src/assets/img/about-us-vector-1.png
  website/frontend/src/assets/img/analytics dashboard.svg
  website/frontend/src/assets/img/analytics_dashboard_mob.svg
  website/frontend/src/assets/img/community/Rectangle 406.webp
  website/frontend/src/assets/img/community/Rectangle 408-1.webp
  website/frontend/src/assets/img/community/Rectangle 409.webp
  website/frontend/src/assets/img/partners/USEmbassy.png
  website/frontend/src/assets/img/partners/WeHubit.png
  website/frontend/src/assets/svg/QR code.svg
  website/frontend/src/assets/svg/errors/AccessDenied.svg
  website/frontend/src/assets/svg/errors/InternalServerError.svg
  website/frontend/src/assets/svg/explore/download.svg
  website/frontend/src/components/Tweets.js
  website/frontend/src/icons/careers/careers.jpeg
  website/frontend/src/icons/common/ArrowRight.js
  website/frontend/src/icons/footer/Instagram.js
  website/frontend/src/icons/getapp/ios.js
  website/frontend/src/icons/getapp/play.js
  website/frontend/src/icons/homepage/hero/arrow-down.svg
  website/frontend/src/icons/homepage/hero/location.svg
  website/frontend/src/icons/homepage/hero/reload.svg
  website/frontend/src/icons/press/Lifewire-logo.svg
  website/frontend/src/icons/press/VoaLogo.svg
  website/frontend/src/icons/press/VoiceOfAfrica.svg
  website/frontend/src/icons/press/WorldEconomicForum.svg
  website/frontend/src/icons/press/XinhuaNet.svg
  website/frontend/src/icons/press/devex.svg
  website/frontend/src/icons/press/pml-daily.svg
  website/frontend/src/icons/press/the-conversation.svg
  website/frontend/src/icons/press/zindi.svg
  website/frontend/src/icons/research/consult.webp
  website/frontend/src/pages/ErrorPages/Error403.js
  website/frontend/src/pages/ErrorPages/Error500.js
  website/frontend/src/pages/ErrorPages/ErrorPageComponent.js
  website/frontend/styles/AfricanCitiesPage.scss
  website/frontend/styles/AirQuality.scss
  website/frontend/styles/AnalyticsSection.scss
  website/frontend/styles/ApiSection.scss
  website/frontend/styles/CommunityPage.scss
  website/frontend/styles/ContactUs.scss
  website/frontend/styles/Footer.scss
  website/frontend/styles/GetApp.scss
  website/frontend/styles/Hero.scss
  website/frontend/styles/HighlightsSection.scss
  website/frontend/styles/MapSection.scss
  website/frontend/styles/Monitor.scss
  website/frontend/utilities/groupBy.js
  website/package-lock.json
  website/package.json
  website/requirements.txt
  website/webpack.config.js
  website/webpack.fullapp.config.js
Labels: enhancement, ready for review

#2120 chore: Update Customise component styles and structure
  platform/src/common/components/Customise/index.jsx
Labels: ready for review

#2121 feat: Add prettier, routes configurations and deployment fix
  reports/.eslintrc.json
  reports/.prettierignore
  reports/.prettierrc
  reports/README.md
  reports/components.json
  reports/next.config.mjs
  reports/package-lock.json
  reports/package.json
  reports/src/app/AppProvider.tsx
  reports/src/app/NetworkIssues.tsx
  reports/src/app/SessionAndThemeProvider.tsx
  reports/src/app/StoreProvider.tsx
  reports/src/app/api/auth/[...nextauth]/options.ts
  reports/src/app/api/auth/[...nextauth]/route.ts
  reports/src/app/api/generateChart/route.ts
  reports/src/app/error.tsx
  reports/src/app/home/[reportID]/page.tsx
  reports/src/app/home/_sections/ReportForm.tsx
  reports/src/app/home/_sections/SkeletonLoader.tsx
  reports/src/app/home/page.tsx
  reports/src/app/layout.tsx
  reports/src/app/loading.tsx
  reports/src/app/login/page.tsx
  reports/src/app/not-found.tsx
  reports/src/app/page.tsx
  reports/src/app/reports/files/page.tsx
  reports/src/app/settings/page.tsx
  reports/src/assets/styles/globals.scss
  reports/src/components/authForm/index.tsx
  reports/src/components/datePicker/index.tsx
  reports/src/components/header/Header.tsx
  reports/src/components/reportTemplates/graphs/index.tsx
  reports/src/components/reportTemplates/template1/index.tsx
  reports/src/components/sidebar/SideBar.tsx
  reports/src/components/ui/avatar.tsx
  reports/src/components/ui/breadcrumb.tsx
  reports/src/components/ui/button.tsx
  reports/src/components/ui/calendar.tsx
  reports/src/components/ui/card.tsx
  reports/src/components/ui/checkbox.tsx
  reports/src/components/ui/dialog.tsx
  reports/src/components/ui/drawer.tsx
  reports/src/components/ui/dropdown-menu.tsx
  reports/src/components/ui/input.tsx
  reports/src/components/ui/label.tsx
  reports/src/components/ui/popover.tsx
  reports/src/components/ui/select.tsx
  reports/src/components/ui/separator.tsx
  reports/src/components/ui/skeleton.tsx
  reports/src/components/ui/sonner.tsx
  reports/src/components/ui/tooltip.tsx
  reports/src/layout/MainLayout.tsx
  reports/src/lib/reduxSlices/gridSlice.tsx
  reports/src/lib/reduxSlices/reportSlice.tsx
  reports/src/lib/store.tsx
  reports/src/lib/utils.ts
  reports/src/middleware.ts
  reports/src/services/api/index.tsx
  reports/tailwind.config.ts
  reports/tsconfig.json
Labels: enhancement, ready for review
