Repository airqo-platform/AirQo-frontend, pull requests merged in 2024-02, with the labels that each got.

#1834 [WEBSITE] Fixed scroll bug and optimized publications code.
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/Publications/Pagination.js
  website/frontend/src/pages/Publications/Publications.js
Labels: bug, ready for review

#1833 Luganda QA
  mobile/lib/l10n/app_lg.arb
Labels: ready for review

#1826 [platform] Map Implementation First Draft
  platform/package.json
  platform/public/icons/LocationIcon.js
  platform/public/icons/SideBar/world_Icon.js
  platform/public/icons/map/downArrow.js
  platform/public/icons/map/gpsIcon.js
  platform/public/icons/map/homeIcon.js
  platform/public/icons/map/layerIcon.js
  platform/public/icons/map/menuIcon.js
  platform/public/icons/map/minusIcon.js
  platform/public/icons/map/plusIcon.js
  platform/public/icons/map/refreshIcon.js
  platform/public/icons/map/shareIcon.js
  platform/public/icons/map/upArrow.js
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Legend.js
  platform/src/common/components/Map/components/MapControls.js
  platform/src/common/components/Map/components/countries.json
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/styles/global.scss
  platform/src/pages/_document.jsx
  platform/src/pages/map/index.jsx
  platform/yarn.lock
Labels: ready for review, feature

#1835 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  mobile/lib/l10n/app_lg.arb
  platform/package.json
  platform/public/icons/LocationIcon.js
  platform/public/icons/SideBar/world_Icon.js
  platform/public/icons/map/downArrow.js
  platform/public/icons/map/gpsIcon.js
  platform/public/icons/map/homeIcon.js
  platform/public/icons/map/layerIcon.js
  platform/public/icons/map/menuIcon.js
  platform/public/icons/map/minusIcon.js
  platform/public/icons/map/plusIcon.js
  platform/public/icons/map/refreshIcon.js
  platform/public/icons/map/shareIcon.js
  platform/public/icons/map/upArrow.js
  platform/src/common/components/Layout/index.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/Legend.js
  platform/src/common/components/Map/components/MapControls.js
  platform/src/common/components/Map/components/countries.json
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/styles/global.scss
  platform/src/pages/_document.jsx
  platform/src/pages/map/index.jsx
  platform/yarn.lock
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/Publications/Pagination.js
  website/frontend/src/pages/Publications/Publications.js
Labels: ready for review

#1836 Added reset button on export data form
  netmanager/src/views/pages/ExportData/index.js
Labels: ready for review

#1837 move to production
  k8s/platform/values-prod.yaml
  netmanager/src/views/pages/ExportData/index.js
Labels: ready for review

#1704 [WEBSITE] French Translation for all static pages
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/components/CleanAir/CTAs/BottomCTAs.js
  website/frontend/src/components/CleanAir/SecondaryNav/index.js
  website/frontend/src/components/GetInvolvedModal.js
  website/frontend/src/components/LanguageSwitcher.js
  website/frontend/src/components/OurProducts/Header.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/AboutUsPage.js
  website/frontend/src/pages/CareerDetailPage.js
  website/frontend/src/pages/CareerPage.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
  website/frontend/src/pages/CleanAir/EventDetails.js
  website/frontend/src/pages/ContactUs/ContactForm.js
  website/frontend/src/pages/ContactUs/ContactUs.js
  website/frontend/src/pages/ContactUs/Feedback.js
  website/frontend/src/pages/ContactUs/cards.js
  website/frontend/src/pages/ContactUs/index.js
  website/frontend/src/pages/Events/Details.js
  website/frontend/src/pages/Events/EventCard.js
  website/frontend/src/pages/Events/Header.js
  website/frontend/src/pages/Events/Navigation.js
  website/frontend/src/pages/Events/index.js
  website/frontend/src/pages/ExploreData/index.js
  website/frontend/src/pages/OurProducts/AnalyticsPage.js
  website/frontend/src/pages/OurProducts/ApiPage.js
  website/frontend/src/pages/OurProducts/CalibrationPage.js
  website/frontend/src/pages/OurProducts/MobileAppPage.js
  website/frontend/src/pages/OurProducts/MonitorPage.js
  website/frontend/src/pages/OurSolutions/AfricanCitiesPage.js
  website/frontend/src/pages/OurSolutions/CommunityPage.js
  website/frontend/src/pages/OurSolutions/ResearchPage.js
  website/frontend/src/pages/Press/Article.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/src/pages/Publications/CardComponent.js
  website/frontend/src/pages/Publications/Publications.js
  website/frontend/src/pages/Publications/ReportComponent.js
  website/frontend/styles/AfricanCitiesPage.scss
  website/frontend/styles/ResearchPage.scss
Labels: ready for review

#1842 [platform] Overflow issues for small devices
  platform/src/common/components/Map/components/Legend.js
  platform/src/pages/map/index.jsx
Labels: ready for review

#1848 move to production
  inventory/templates/dashboard/index.html
  k8s/inventory/values-prod.yaml
  k8s/platform/values-prod.yaml
Labels: ready for review

#1847 [PLATFORM] Added organisation's cohort verification page
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Account/ProgressComponent.jsx
  platform/src/common/components/Modal/DialogWrapper.jsx
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/apis/Inquiry.js
  platform/src/core/urls/inquiry.js
  platform/src/lib/store/services/deviceRegistry/CohortSlice.js
  platform/src/pages/account/creation/organisation/verify/[id]/[token].jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/token-confirmation.jsx
  platform/tailwind.config.js
Labels: ready for review

#1851 [WEBSITE] Update deploy-frontends-to-staging.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: ready for review

#1852 Update README.md for website to trigger new workflow and SECRETS
  website/README.md
Labels: ready for review

#1853 Update deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-production.yml
Labels: ready for review

#1854 Update deploy-frontends-to-staging.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: ready for review

#1855 [webiste] Update README.md to trigger changes in SECRETS
  website/README.md
Labels: ready for review

#1856 Update README.md
  website/README.md
Labels: ready for review

#1858 Update README.md
  website/README.md
Labels: ready for review

#1850 move to production
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  k8s/inventory/values-prod.yaml
  k8s/inventory/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Account/Layout.jsx
  platform/src/common/components/Account/ProgressComponent.jsx
  platform/src/common/components/Modal/DialogWrapper.jsx
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/apis/Inquiry.js
  platform/src/core/urls/inquiry.js
  platform/src/lib/store/services/deviceRegistry/CohortSlice.js
  platform/src/pages/account/creation/organisation/verify/[id]/[token].jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/details.jsx
  platform/src/pages/account/creation/organisation/verify/[id]/create-org/token-confirmation.jsx
  platform/tailwind.config.js
  website/README.md
Labels: ready for review

#1860 Update deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontend-pr-previews.yml
Labels: ready for review

#1862 Minor Fix for Translation Functionality
  mobile/lib/screens/on_boarding/splash_screen.dart
Labels: ready for review

#1863 [WEBSITE] Content Update for Clean Air Goals
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
Labels: ready for review

#1864 move to production
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
Labels: ready for review

#1868 [Netmanager] Added airqo analytics banner to login page
  netmanager/src/views/pages/SignUp/Login.js
Labels: ready for review

#1866 Increase app versions
  mobile/pubspec.yaml
Labels: ready for review

#1870 move to production
  mobile/pubspec.yaml
  netmanager/src/views/pages/SignUp/Login.js
Labels: ready for review

#1875 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/core/utils/protectedRoute.js
  platform/src/pages/map/index.jsx
Labels: ready for review

#1872 [paltform] Map Functionality (location and country search implemented)
  platform/package.json
  platform/public/images/map/dd1.png
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/LayerModal.js
  platform/src/common/components/Map/components/MapControls.js
  platform/src/common/components/search/SearchField.jsx
  platform/src/common/styles/global.scss
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/urls/deviceRegistry.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/account/UserDefaultsSlice.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/lib/store/services/charts/userDefaultsSlice.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/map/index.jsx
  platform/yarn.lock
Labels: ready for review

#1877 move to production
  platform/package.json
  platform/public/images/map/dd1.png
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/LayerModal.js
  platform/src/common/components/Map/components/MapControls.js
  platform/src/common/components/search/SearchField.jsx
  platform/src/common/styles/global.scss
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/urls/deviceRegistry.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/account/UserDefaultsSlice.js
  platform/src/lib/store/services/charts/ChartSlice.js
  platform/src/lib/store/services/charts/userDefaultsSlice.js
  platform/src/lib/store/services/deviceRegistry/GridsSlice.js
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/map/index.jsx
  platform/yarn.lock
Labels: ready for review

#1879 [platform] Implementation of Map Nodes - Phase 1
  platform/package.json
  platform/public/images/map/GoodAir.png
  platform/public/images/map/Hazardous.png
  platform/public/images/map/Moderate.png
  platform/public/images/map/Unhealthy.png
  platform/public/images/map/UnhealthySG.png
  platform/public/images/map/VeryUnhealthy.png
  platform/src/common/components/Layout/MapLayout.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/SideBar/CollapsedSidebar.jsx
  platform/src/common/styles/global.scss
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/urls/deviceRegistry.js
  platform/src/pages/map/index.jsx
  platform/yarn.lock
Labels: ready for review

#1880 [Hotfix] Update /dashboard route to /
  docs/calibration/airqalibrate.md
  docs/calibration/ml_based_approach.md
Labels: ready for review

#1876 [WEBSITE] QA Feedback addressed
  website/backend/settings.py
  website/frontend/App.js
  website/frontend/reduxStore/CleanAirNetwork/CleanAir.js
  website/frontend/reduxStore/Events/EventSlice.js
  website/frontend/reduxStore/Publications/actions.js
  website/frontend/reduxStore/Publications/operations.js
  website/frontend/reduxStore/Publications/reducers.js
  website/frontend/reduxStore/Publications/selectors.js
  website/frontend/src/assets/img/cleanAir/events.png
  website/frontend/src/assets/img/cleanAir/membership.png
  website/frontend/src/components/CleanAir/CTAs/BottomCTAs.js
  website/frontend/src/components/CleanAir/Sections/Split_Text_section.js
  website/frontend/src/components/CleanAir/index.js
  website/frontend/src/components/CleanAir/pagination/Pagination.js
  website/frontend/src/pages/CareerPage.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
  website/frontend/src/pages/CleanAir/Page.js
  website/frontend/src/pages/Events/Details.js
  website/frontend/src/pages/Events/index.js
  website/frontend/src/pages/Page.js
  website/frontend/src/pages/Partners/index.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/src/pages/Publications/Publications.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1881 move to production
  docs/calibration/airqalibrate.md
  docs/calibration/ml_based_approach.md
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/package.json
  platform/public/images/map/GoodAir.png
  platform/public/images/map/Hazardous.png
  platform/public/images/map/Moderate.png
  platform/public/images/map/Unhealthy.png
  platform/public/images/map/UnhealthySG.png
  platform/public/images/map/VeryUnhealthy.png
  platform/src/common/components/Layout/MapLayout.jsx
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/SideBar/CollapsedSidebar.jsx
  platform/src/common/styles/global.scss
  platform/src/core/apis/DeviceRegistry.js
  platform/src/core/urls/deviceRegistry.js
  platform/src/pages/map/index.jsx
  platform/yarn.lock
  website/backend/settings.py
  website/frontend/App.js
  website/frontend/reduxStore/CleanAirNetwork/CleanAir.js
  website/frontend/reduxStore/Events/EventSlice.js
  website/frontend/reduxStore/Publications/actions.js
  website/frontend/reduxStore/Publications/operations.js
  website/frontend/reduxStore/Publications/reducers.js
  website/frontend/reduxStore/Publications/selectors.js
  website/frontend/src/assets/img/cleanAir/events.png
  website/frontend/src/assets/img/cleanAir/membership.png
  website/frontend/src/components/CleanAir/CTAs/BottomCTAs.js
  website/frontend/src/components/CleanAir/Sections/Split_Text_section.js
  website/frontend/src/components/CleanAir/index.js
  website/frontend/src/components/CleanAir/pagination/Pagination.js
  website/frontend/src/pages/CareerPage.js
  website/frontend/src/pages/CleanAir/CleanAirEvents.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/CleanAir/CleanAirPublications.js
  website/frontend/src/pages/CleanAir/Page.js
  website/frontend/src/pages/Events/Details.js
  website/frontend/src/pages/Events/index.js
  website/frontend/src/pages/Page.js
  website/frontend/src/pages/Partners/index.js
  website/frontend/src/pages/Press/Press.js
  website/frontend/src/pages/Publications/Publications.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1882 Update README.md
  platform/README.md
Labels: ready for review

#1883 move to production
  k8s/calibrate/values-prod.yaml
  k8s/docs/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/README.md
Labels: ready for review
