Repository airqo-platform/AirQo-frontend, pull requests merged in 2024-01, with the labels that each got.

#1786 Automate Deletion of old versions in App Engine
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: ready for review

#1788 [NET] Overlapping map issue and feature enhancements on airqo map
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/index.css
  netmanager/src/views/components/DataDisplay/Map/MapKey.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1789 [NET] UI/UX Improvements on certain views
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/Hosts/HostsTable.js
  netmanager/src/views/components/SIM/SimRegistry.js
  netmanager/src/views/components/Sites/SiteRegistry.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/pages/CandidateList/CandidateList.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
  netmanager/src/views/pages/UserStats/UserStats.js
Labels: ready for review

#1790 [Analytics] Group invite navigation enhancement from email link
  platform/src/pages/account/creation/individual/register.jsx
Labels: ready for review

#1791 [NET] Optimized Map Performance and Implemented Caching for Map Data
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1792 [NET] Error Handling and popup improvements on map
  netmanager/src/index.css
  netmanager/src/views/pages/Dashboard/components/Map/Indicator .js
  netmanager/src/views/pages/Dashboard/components/Map/MapPopup.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1793 [NET] Increased Map node size
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1787 move to production
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/index.css
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/components/DataDisplay/Map/MapKey.js
  netmanager/src/views/components/Hosts/HostsTable.js
  netmanager/src/views/components/SIM/SimRegistry.js
  netmanager/src/views/components/Sites/SiteRegistry.js
  netmanager/src/views/components/Sites/SitesTable.js
  netmanager/src/views/pages/CandidateList/CandidateList.js
  netmanager/src/views/pages/CandidateList/components/CandidatesTable/CandidatesTable.js
  netmanager/src/views/pages/Dashboard/components/Map/Indicator .js
  netmanager/src/views/pages/Dashboard/components/Map/MapPopup.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/UserStats/UserStats.js
  platform/src/pages/account/creation/individual/register.jsx
Labels: work in progress, ready for review

#1795 [NET] updated marker size
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
Labels: ready for review

#1797 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  mobile/lib/constants/api.dart
  mobile/lib/services/rest_api.dart
Labels: ready for review

#1801 [NET] Enhancements to Client Details table and Map Functionality
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/assets/css/overlay-map.css
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/pages/Dashboard/components/Map/MapPopup.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/Settings/components/GenerateToken/GenerateToken.js
Labels: ready for review

#1798 move to production
  Maintenance/.gcloudignore
  Maintenance/app.yaml
  Maintenance/default-app.yaml
  Maintenance/staging-app.yaml
  Maintenance/www/imgs/Logo.svg
  Maintenance/www/imgs/Oops.svg
  Maintenance/www/index.html
  netmanager/package-lock.json
  netmanager/package.json
  netmanager/src/assets/css/overlay-map.css
  netmanager/src/config/urls/analytics.js
  netmanager/src/views/apis/analytics.js
  netmanager/src/views/pages/Dashboard/components/Map/MapPopup.js
  netmanager/src/views/pages/Heatmap/HeatMapOverlay.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/Settings/components/GenerateToken/GenerateToken.js
Labels: ready for review

#1802 [NET] Map Reading Endpoint
  netmanager/src/AppRoutes.js
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/Settings/components/GenerateToken/GenerateToken.js
Labels: ready for review

#1803 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/src/AppRoutes.js
  netmanager/src/config/urls/deviceRegistry.js
  netmanager/src/views/apis/deviceRegistry.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/Map/OverlayMap.js
  netmanager/src/views/pages/Settings/components/GenerateToken/GenerateToken.js
Labels: ready for review

#1806 Inventory Trigger
  inventory/README.md
Labels: ready for review

#1805 [Hotfixes] Analytics dashboard
  netmanager/src/views/pages/Analytics/index.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#1804 Exclude maintenance versions from Being Deleted
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: ready for review

#1807 move to production
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  inventory/README.md
  k8s/inventory/values-stage.yaml
  k8s/netmanager/values-prod.yaml
  netmanager/src/views/pages/Analytics/index.js
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#1809 [WEB] CleanAir about page redesign
  website/frontend/src/assets/img/cleanAir/placeholder.png
  website/frontend/src/assets/img/cleanAir/placeholder2.png
  website/frontend/src/assets/img/cleanAir/placeholder3.png
  website/frontend/src/components/CleanAir/HomePage/Header.js
  website/frontend/src/components/CleanAir/SecondaryNav/index.js
  website/frontend/src/components/CleanAir/Sections/SingleSection.js
  website/frontend/src/components/CleanAir/index.js
  website/frontend/src/components/LanguageSwitcher.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/Page.js
  website/frontend/src/pages/Page.js
  website/frontend/styles/CleanAirPage.scss
  website/frontend/styles/LanguageSwitcher.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/index.scss
Labels: ready for review

#1810 [Hotfix] Resolved collocation application error
  platform/src/common/components/Collocation/AddMonitor/Table/DataTable.jsx
  platform/src/common/components/Collocation/AddMonitor/Table/index.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
Labels: ready for review

#1811 move to production
  k8s/inventory/values-prod.yaml
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Collocation/AddMonitor/Table/DataTable.jsx
  platform/src/common/components/Collocation/AddMonitor/Table/index.jsx
  platform/src/common/components/Collocation/DeviceStatus/Table/DataTable.jsx
  website/frontend/src/assets/img/cleanAir/placeholder.png
  website/frontend/src/assets/img/cleanAir/placeholder2.png
  website/frontend/src/assets/img/cleanAir/placeholder3.png
  website/frontend/src/components/CleanAir/HomePage/Header.js
  website/frontend/src/components/CleanAir/SecondaryNav/index.js
  website/frontend/src/components/CleanAir/Sections/SingleSection.js
  website/frontend/src/components/CleanAir/index.js
  website/frontend/src/components/LanguageSwitcher.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/Page.js
  website/frontend/src/pages/Page.js
  website/frontend/styles/CleanAirPage.scss
  website/frontend/styles/LanguageSwitcher.scss
  website/frontend/styles/TopBar.scss
  website/frontend/styles/index.scss
Labels: ready for review, airqo-website

#1813 [NET] Removing feature to disable developer tools
  netmanager/src/App.js
Labels: ready for review

#1812 Mobile App: Luganda Translations
  mobile/assets/images/uganda_flag.png
  mobile/lib/constants/language_constants.dart
  mobile/lib/l10n/app_lg.arb
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/utils/custom_localisation.dart
Labels: ready for review

#1817 move to production
  k8s/netmanager/values-prod.yaml
  mobile/assets/images/uganda_flag.png
  mobile/lib/constants/language_constants.dart
  mobile/lib/l10n/app_lg.arb
  mobile/lib/main.dart
  mobile/lib/main_common.dart
  mobile/lib/screens/analytics/analytics_widgets.dart
  mobile/lib/screens/profile/profile_widgets.dart
  mobile/lib/utils/custom_localisation.dart
Labels: ready for review

#1819 [NET] Dev tools
  netmanager/src/App.js
Labels: ready for review

#1818 [Hotfix] Cohort dashoard charts and Visibility
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#1820 move to production
  netmanager/src/App.js
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/Dashboard/components/AveragesChart.js
  netmanager/src/views/pages/Dashboard/components/ExceedancesChart/ExceedancesChart.js
Labels: ready for review

#1821 Update README.md
  netmanager/README.md
Labels: ready for review

#1822 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/README.md
Labels: ready for review

#1816 [website] Content Update
  website/frontend/App.js
  website/frontend/src/pages/CleanAir/CleanAirAbout.js
  website/frontend/src/pages/CleanAir/CleanAirPartners.js
  website/frontend/src/pages/Page.js
  website/frontend/styles/CleanAirPage.scss
  website/frontend/styles/index.scss
Labels: ready for review

#1825 [WEBSITE] changed to use grids endpoint and refactored api methods
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/AirQlouds/operations.js
Labels: ready for review

#1828 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/reduxStore/AirQlouds/operations.js
Labels: ready for review

#1830 move to production
  inventory/dashboard/views.py
Labels: ready for review

#1831 Remove scheduled downloads from export and sidebar, added error message
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/ExportData/index.js
Labels: ready for review

#1832 move to production
  k8s/inventory/values-prod.yaml
  k8s/inventory/values-stage.yaml
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
  netmanager/src/views/pages/ExportData/index.js
Labels: ready for review
