Repository airqo-platform/AirQo-frontend, pull requests merged in 2024-04, with the labels that each got.

#1946 [Analytics] Displays location details for clicked map emojis
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/styles/global.scss
  platform/src/core/apis/predict.js
  platform/src/core/urls/predict.js
  platform/src/lib/store/services/map/MapSlice.js
Labels: ready for review

#1923 [Netmanager] added grid and cohort ids to details pages
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
Labels: ready for review

#1919 Fix authentication bug
  mobile/lib/screens/email_authentication/email_verification_screen.dart
Labels: ready for review, mobile-app

#1947 move to production
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  mobile/lib/screens/email_authentication/email_verification_screen.dart
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/styles/global.scss
  platform/src/core/apis/predict.js
  platform/src/core/urls/predict.js
  platform/src/lib/store/services/map/MapSlice.js
Labels: ready for review

#1950 Github Workflows for reports
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
Labels: ready for review

#1952 [platform] Application Intro Tour Modal
  platform/public/images/Home/analytics.png
  platform/public/images/Home/export.png
  platform/public/images/Home/settings.png
  platform/src/common/components/Modal/AppIntro.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/pages/Home/index.jsx
Labels: ready for review

#1953 Setting up K8s for Reports
  k8s/reports/.helmignore
  k8s/reports/Chart.yaml
  k8s/reports/templates/NOTES.txt
  k8s/reports/templates/_helpers.tpl
  k8s/reports/templates/deployment.yaml
  k8s/reports/templates/hpa.yaml
  k8s/reports/templates/service.yaml
  k8s/reports/templates/tests/test-connection.yaml
  k8s/reports/values-dev.yaml
  k8s/reports/values-prod.yaml
  k8s/reports/values-stage.yaml
Labels: ready for review

#1955 Trigger workflow for Reports
  reports/README.md
Labels: ready for review

#1956 [Hotfix] Rename add device button labels
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#1957 REPORT: Exposing right port in dockerfile
  reports/Dockerfile
Labels: ready for review

#1959 Fix ports for reports
  reports/nginx.conf
Labels: ready for review

#1958 Overflow fix when switched to other languages (Link remainder)
  mobile/assets/images/uganda_flag.png
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_fr.arb
  mobile/lib/l10n/app_lg.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
  mobile/lib/screens/profile/profile_edit_page.dart
  mobile/lib/screens/profile/profile_view.dart
  mobile/lib/screens/profile/profile_widgets.dart
Labels: ready for review, mobile-app

#1948 Modification to the FOR YOU section
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_fr.arb
  mobile/lib/l10n/app_lg.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
  mobile/lib/screens/kya/know_your_air_view.dart
  mobile/lib/screens/kya/kya_widgets.dart
  mobile/lib/screens/quiz/quiz_view.dart
Labels: ready for review, mobile-app

#1944 [website] Initial Template Setup for Clean Air Forum Event Site
  website/README.md
  website/backend/cleanair/admin.py
  website/backend/cleanair/migrations/0006_forumevent_engagement_partner_person_program_session_and_more.py
  website/backend/cleanair/migrations/0007_remove_cleanairresource_created_and_more.py
  website/backend/cleanair/migrations/0008_remove_cleanairresource_created_at_and_more.py
  website/backend/cleanair/migrations/0009_forumevent_author_forumevent_updated_by.py
  website/backend/cleanair/migrations/0010_forumevent_event_tag.py
  website/backend/cleanair/migrations/0011_remove_forumevent_event_details_and_more.py
  website/backend/cleanair/migrations/0012_alter_objective_options_objective_order_and_more.py
  website/backend/cleanair/migrations/0013_alter_engagement_forum_event.py
  website/backend/cleanair/migrations/0014_alter_forumevent_end_time_and_more.py
  website/backend/cleanair/migrations/0015_forumevent_introduction_and_more.py
  website/backend/cleanair/migrations/0016_alter_forumevent_title_alter_partner_category_and_more.py
  website/backend/cleanair/migrations/0017_alter_person_biography.py
  website/backend/cleanair/migrations/0018_alter_person_biography.py
  website/backend/cleanair/migrations/0019_alter_person_biography.py
  website/backend/cleanair/migrations/0020_partner_website_link.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/backend/cleanair/views.py
  website/backend/event/admin.py
  website/backend/event/translation.py
  website/backend/urls.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/assets/img/cleanAir/prof.jpg
  website/frontend/src/components/CleanAir/Sections/Split_Text_section.js
  website/frontend/src/components/Profile.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/Page.js
  website/frontend/styles/AboutUsPage.scss
  website/frontend/styles/CleanAirPage.scss
  website/frontend/styles/Modal.scss
  website/frontend/styles/TopBar.scss
Labels: ready for review

#1960 move to production
  k8s/netmanager/values-prod.yaml
  k8s/platform/values-prod.yaml
  k8s/reports/values-prod.yaml
  website/README.md
  website/backend/cleanair/admin.py
  website/backend/cleanair/migrations/0006_forumevent_engagement_partner_person_program_session_and_more.py
  website/backend/cleanair/migrations/0007_remove_cleanairresource_created_and_more.py
  website/backend/cleanair/migrations/0008_remove_cleanairresource_created_at_and_more.py
  website/backend/cleanair/migrations/0009_forumevent_author_forumevent_updated_by.py
  website/backend/cleanair/migrations/0010_forumevent_event_tag.py
  website/backend/cleanair/migrations/0011_remove_forumevent_event_details_and_more.py
  website/backend/cleanair/migrations/0012_alter_objective_options_objective_order_and_more.py
  website/backend/cleanair/migrations/0013_alter_engagement_forum_event.py
  website/backend/cleanair/migrations/0014_alter_forumevent_end_time_and_more.py
  website/backend/cleanair/migrations/0015_forumevent_introduction_and_more.py
  website/backend/cleanair/migrations/0016_alter_forumevent_title_alter_partner_category_and_more.py
  website/backend/cleanair/migrations/0017_alter_person_biography.py
  website/backend/cleanair/migrations/0018_alter_person_biography.py
  website/backend/cleanair/migrations/0019_alter_person_biography.py
  website/backend/cleanair/migrations/0020_partner_website_link.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/backend/cleanair/views.py
  website/backend/event/admin.py
  website/backend/event/translation.py
  website/backend/urls.py
  website/frontend/App.js
  website/frontend/apis/index.js
  website/frontend/config/urls.js
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/assets/img/cleanAir/prof.jpg
  website/frontend/src/components/CleanAir/Sections/Split_Text_section.js
  website/frontend/src/components/Profile.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/Page.js
  website/frontend/styles/AboutUsPage.scss
  website/frontend/styles/CleanAirPage.scss
  website/frontend/styles/Modal.scss
  website/frontend/styles/TopBar.scss
Labels: ready for review

#1961 Trigger FrontEnd Apps
  netmanager/README.md
  platform/README.md
  reports/README.md
Labels: ready for review

#1963 Limiting excess resource utilisation
  k8s/inventory/values-prod.yaml
  k8s/inventory/values-stage.yaml
Labels: ready for review

#1965 move to production
  k8s/inventory/values-prod.yaml
  k8s/inventory/values-stage.yaml
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  k8s/reports/values-prod.yaml
  k8s/reports/values-stage.yaml
Labels: ready for review

#1964 [Website] Clean-Air Forum Site Update
  website/backend/cleanair/migrations/0016_alter_forumevent_title_alter_partner_category_and_more.py
  website/backend/cleanair/migrations/0021_alter_partner_category_alter_person_category.py
  website/backend/cleanair/migrations/0022_alter_person_biography.py
  website/backend/cleanair/migrations/0023_person_bio_alter_person_biography.py
  website/backend/cleanair/migrations/0024_remove_person_biography.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/frontend/App.js
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/components/Profile.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Partners.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Schedule.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Travel.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1966 [reports] Update nginx.conf to include server_name and error_page configuration
  reports/nginx.conf
Labels: ready for review

#1969 [Hotfix] Added pagination to api clients table
  platform/src/common/components/Settings/API/AddClientForm.jsx
  platform/src/common/components/Settings/API/EditClientForm.jsx
  platform/src/common/components/Settings/API/UserClientsTable.jsx
Labels: ready for review

#1967 move to production
  k8s/platform/values-stage.yaml
  k8s/reports/values-stage.yaml
  platform/src/common/components/Modal/AppIntro.jsx
  platform/src/common/components/Modal/Modal.jsx
  platform/src/common/components/Settings/API/AddClientForm.jsx
  platform/src/common/components/Settings/API/AdminClientsTable.jsx
  platform/src/common/components/Settings/API/EditClientForm.jsx
  platform/src/common/components/Settings/API/UserClientsTable.jsx
  platform/src/common/components/Toast/index.jsx
  platform/src/common/components/TopBar/index.jsx
  platform/src/common/styles/global.scss
  platform/src/core/apis/Account.js
  platform/src/core/apis/Settings.js
  platform/src/core/urls/authentication.js
  platform/src/lib/store/index.js
  platform/src/lib/store/services/apiClient/index.js
  platform/src/pages/settings/Tabs/API.jsx
  platform/src/pages/settings/index.jsx
  reports/nginx.conf
  website/backend/cleanair/migrations/0016_alter_forumevent_title_alter_partner_category_and_more.py
  website/backend/cleanair/migrations/0021_alter_partner_category_alter_person_category.py
  website/backend/cleanair/migrations/0022_alter_person_biography.py
  website/backend/cleanair/migrations/0023_person_bio_alter_person_biography.py
  website/backend/cleanair/migrations/0024_remove_person_biography.py
  website/backend/cleanair/migrations/0025_person_section_text_alter_session_end_time.py
  website/backend/cleanair/migrations/0026_remove_person_section_text_and_more.py
  website/backend/cleanair/migrations/0027_alter_session_session_details.py
  website/backend/cleanair/migrations/0028_alter_session_session_details.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/frontend/App.js
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/components/LoadSpinner/SectionLoader.js
  website/frontend/src/components/Profile.js
  website/frontend/src/components/nav/TopBar.js
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/CommitteePage.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Partners.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Schedule.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Travel.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1970 [Analytics] UI feedback fixes
  platform/src/common/components/Settings/API/AdminClientsTable.jsx
  platform/src/common/components/Settings/Teams/table.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/Toast/index.jsx
  platform/src/pages/account/login/index.jsx
  platform/src/pages/settings/Tabs/API.jsx
  platform/src/pages/settings/index.jsx
Labels: ready for review

#1971 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  k8s/reports/values-prod.yaml
  platform/src/common/components/Settings/API/AdminClientsTable.jsx
  platform/src/common/components/Settings/Teams/table.jsx
  platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  platform/src/common/components/Toast/index.jsx
  platform/src/pages/account/login/index.jsx
  platform/src/pages/settings/Tabs/API.jsx
  platform/src/pages/settings/index.jsx
Labels: ready for review

#1972 [Platform] Map Node update
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/styles/global.scss
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/Home/index.jsx
Labels: ready for review

#1974 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  platform/src/common/components/Map/AirQoMap.jsx
  platform/src/common/components/Map/components/MapNodes.js
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/common/styles/global.scss
  platform/src/lib/store/services/map/MapSlice.js
  platform/src/pages/Home/index.jsx
Labels: ready for review

#1973 [website] Update CleanAirResource and models
  website/backend/cleanair/admin.py
  website/backend/cleanair/migrations/0029_alter_forumevent_title_subtext_and_more.py
  website/backend/cleanair/migrations/0030_alter_session_session_details.py
  website/backend/cleanair/migrations/0031_remove_forumevent_event_tag.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/backend/cleanair/views.py
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/components/Profile.js
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/CommitteePage.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Partners.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Schedule.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Travel.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1975 move to production
  k8s/platform/values-prod.yaml
  website/backend/cleanair/admin.py
  website/backend/cleanair/migrations/0029_alter_forumevent_title_subtext_and_more.py
  website/backend/cleanair/migrations/0030_alter_session_session_details.py
  website/backend/cleanair/migrations/0031_remove_forumevent_event_tag.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/backend/cleanair/views.py
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/components/Profile.js
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/CommitteePage.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Partners.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Schedule.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Travel.js
  website/frontend/styles/CleanAirPage.scss
Labels: ready for review

#1977 [website] Website content update and bug fix on session model
  website/backend/cleanair/admin.py
  website/backend/cleanair/migrations/0032_alter_session_session_details.py
  website/backend/cleanair/migrations/0033_alter_person_category.py
  website/backend/cleanair/models.py
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Partners.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
Labels: ready for review

#1976 move to production
  docs/calibration/airqalibrate.md
  website/backend/cleanair/admin.py
  website/backend/cleanair/migrations/0032_alter_session_session_details.py
  website/backend/cleanair/migrations/0033_alter_person_category.py
  website/backend/cleanair/models.py
  website/frontend/locales/en/translation.json
  website/frontend/locales/fr/translation.json
  website/frontend/src/pages/CleanAir/CleanAirForumEvent.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Partners.js
  website/frontend/src/pages/CleanAir/ForumEventsPages/Speakers.js
Labels: ready for review

#1921 [Netmanager] Fault Detection
  netmanager/src/AppRoutes.js
  netmanager/src/__tests__/faultyDevices/ManageFaults.test.js
  netmanager/src/config/urls/predict.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementFaults.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1978 move to production
  netmanager/src/AppRoutes.js
  netmanager/src/__tests__/faultyDevices/ManageFaults.test.js
  netmanager/src/config/urls/predict.js
  netmanager/src/views/apis/predict.js
  netmanager/src/views/components/DataDisplay/DeviceManagement/ManagementFaults.js
  netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#1979 [platform] Session timeout Temporarily removed and updated Sidebar component to display country flags
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/core/utils/protectedRoute.js
Labels: ready for review

#1980 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  platform/src/common/components/Map/components/Sidebar.js
  platform/src/core/utils/protectedRoute.js
Labels: ready for review

#1981 Fix arb formatting errors.
  mobile/lib/l10n/app_en.arb
  mobile/lib/l10n/app_fr.arb
  mobile/lib/l10n/app_lg.arb
  mobile/lib/l10n/app_pt.arb
  mobile/lib/l10n/app_sw.arb
Labels: mobile-app

#1984 [netmanager] URL Updates
  netmanager/.env.sample
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
Labels: ready for review

#1985 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  netmanager/.env.sample
  netmanager/src/views/components/DataDisplay/DeviceView/DeviceOverview/DeviceDetails.js
  netmanager/src/views/pages/CohortsRegistry/CohortDetails.jsx
  netmanager/src/views/pages/GridsRegistry/GridsDetails.js
Labels: ready for review

#1986 [website] Created Sponsorship model for dynamic content upload
  website/backend/cleanair/migrations/0034_forumevent_sponsorship_details.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
Labels: ready for review

#1987 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  website/backend/cleanair/migrations/0034_forumevent_sponsorship_details.py
  website/backend/cleanair/models.py
  website/backend/cleanair/serializers.py
  website/frontend/src/pages/CleanAir/ForumEventsPages/About.js
Labels: ready for review
