Repository airqo-platform/AirQo-frontend, pull requests merged in 2025-03, with the labels that each got.

#2549 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  src/platform/src/common/components/Map/AirQoMap.jsx
  src/platform/src/common/components/Map/components/LayerModal.js
  src/platform/src/common/components/Map/components/MapNodes.js
  src/platform/src/common/components/Map/components/sidebar/components/CountryList.jsx
  src/platform/src/common/components/Map/components/sidebar/components/LocationAlertCard.jsx
  src/platform/src/common/components/Map/components/sidebar/components/LocationCards.jsx
  src/platform/src/common/components/Map/components/sidebar/components/PollutantCard.jsx
  src/platform/src/common/components/Map/components/sidebar/components/Predictions.jsx
  src/platform/src/common/components/Map/components/sidebar/components/SearchResultsSkeleton.jsx
  src/platform/src/common/components/Map/components/sidebar/components/Sections.jsx
  src/platform/src/common/components/Map/components/sidebar/components/SidebarHeader.jsx
  src/platform/src/common/components/Map/components/sidebar/components/TabSelector.jsx
  src/platform/src/common/components/Map/components/sidebar/index.jsx
  src/platform/src/common/components/Map/functions/useLocationBoundaries.jsx
  src/platform/src/common/components/Map/functions/useMapControls.jsx
  src/platform/src/common/components/Map/functions/useMapData.jsx
  src/platform/src/common/components/Modal/dataDownload/components/CustomFields.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/AddLocations.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/SelectMore.jsx
  src/platform/src/common/components/Settings/Teams/InviteForm.jsx
  src/platform/src/common/components/SideBar/AuthenticatedSidebar.jsx
  src/platform/src/common/components/SideBar/SideBarDrawer.jsx
  src/platform/src/core/utils/protectedRoute.js
  src/platform/src/pages/Home/index.jsx
  src/platform/src/pages/settings/Tabs/OrganizationProfile.jsx
  src/platform/src/pages/settings/Tabs/Profile.jsx
  src/platform/src/pages/settings/index.jsx
Labels: ready for review

#2551 [platform] : (Fix) Login Issue for most Users
  src/platform/src/pages/account/login/index.jsx
Labels: ready for review

#2552 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/platform/src/pages/account/login/index.jsx
Labels: ready for review

#2554 Ft analytics event tracking
  src/platform/package.json
  src/platform/src/common/components/GoogleAnalytics.jsx
  src/platform/src/common/components/Modal/dataDownload/components/CustomFields.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/DataDownload.jsx
  src/platform/src/core/hooks/useGoogleAnalytics.js
  src/platform/src/pages/_app.jsx
  src/platform/yarn.lock
Labels: ready for review

#2555 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/platform/package.json
  src/platform/src/common/components/GoogleAnalytics.jsx
  src/platform/src/common/components/Modal/dataDownload/components/CustomFields.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/DataDownload.jsx
  src/platform/src/core/hooks/useGoogleAnalytics.js
  src/platform/src/pages/_app.jsx
  src/platform/yarn.lock
Labels: ready for review

#2553 Website: Enhance imagery content for better visual experience
  src/website2/src/app/(about)/about-us/page.tsx
  src/website2/src/app/(about)/careers/layout.tsx
  src/website2/src/app/(about)/careers/page.tsx
  src/website2/src/app/(about)/events/page.tsx
  src/website2/src/app/(about)/press/page.tsx
  src/website2/src/app/(about)/resources/page.tsx
  src/website2/src/app/clean-air-forum/about/page.tsx
  src/website2/src/app/clean-air-forum/glossary/page.tsx
  src/website2/src/app/clean-air-forum/logistics/page.tsx
  src/website2/src/app/clean-air-forum/partners/page.tsx
  src/website2/src/app/clean-air-forum/program-committee/page.tsx
  src/website2/src/app/clean-air-forum/resources/page.tsx
  src/website2/src/app/clean-air-forum/sessions/page.tsx
  src/website2/src/app/clean-air-forum/speakers/page.tsx
  src/website2/src/app/clean-air-forum/sponsorships/page.tsx
  src/website2/src/app/clean-air-network/about/page.tsx
  src/website2/src/app/clean-air-network/events/page.tsx
  src/website2/src/app/clean-air-network/layout.tsx
  src/website2/src/app/clean-air-network/membership/page.tsx
  src/website2/src/app/clean-air-network/resources/page.tsx
  src/website2/src/app/legal/airqo-data/page.tsx
  src/website2/src/app/legal/layout.tsx
  src/website2/src/app/legal/payment-refund-policy/page.tsx
  src/website2/src/app/legal/privacy-policy/page.tsx
  src/website2/src/app/legal/terms-of-service/page.tsx
  src/website2/src/app/products/analytics/page.tsx
  src/website2/src/app/products/api/page.tsx
  src/website2/src/app/products/calibrate/page.tsx
  src/website2/src/app/products/layout.tsx
  src/website2/src/app/products/mobile-app/page.tsx
  src/website2/src/app/products/monitor/page.tsx
  src/website2/src/app/solutions/african-cities/page.tsx
  src/website2/src/app/solutions/communities/page.tsx
  src/website2/src/app/solutions/layout.tsx
  src/website2/src/app/solutions/research/page.tsx
  src/website2/src/views/products/AnalyticsPage.tsx
  src/website2/src/views/products/ApiPage.tsx
  src/website2/src/views/products/CalibratePage.tsx
  src/website2/src/views/products/MobilePage.tsx
  src/website2/src/views/products/MonitorPage.tsx
Labels: ready for review

#2556 move to production
  k8s/platform/values-prod.yaml
  src/website2/src/app/(about)/about-us/page.tsx
  src/website2/src/app/(about)/careers/layout.tsx
  src/website2/src/app/(about)/careers/page.tsx
  src/website2/src/app/(about)/events/page.tsx
  src/website2/src/app/(about)/press/page.tsx
  src/website2/src/app/(about)/resources/page.tsx
  src/website2/src/app/clean-air-forum/about/page.tsx
  src/website2/src/app/clean-air-forum/glossary/page.tsx
  src/website2/src/app/clean-air-forum/logistics/page.tsx
  src/website2/src/app/clean-air-forum/partners/page.tsx
  src/website2/src/app/clean-air-forum/program-committee/page.tsx
  src/website2/src/app/clean-air-forum/resources/page.tsx
  src/website2/src/app/clean-air-forum/sessions/page.tsx
  src/website2/src/app/clean-air-forum/speakers/page.tsx
  src/website2/src/app/clean-air-forum/sponsorships/page.tsx
  src/website2/src/app/clean-air-network/about/page.tsx
  src/website2/src/app/clean-air-network/events/page.tsx
  src/website2/src/app/clean-air-network/layout.tsx
  src/website2/src/app/clean-air-network/membership/page.tsx
  src/website2/src/app/clean-air-network/resources/page.tsx
  src/website2/src/app/legal/airqo-data/page.tsx
  src/website2/src/app/legal/layout.tsx
  src/website2/src/app/legal/payment-refund-policy/page.tsx
  src/website2/src/app/legal/privacy-policy/page.tsx
  src/website2/src/app/legal/terms-of-service/page.tsx
  src/website2/src/app/products/analytics/page.tsx
  src/website2/src/app/products/api/page.tsx
  src/website2/src/app/products/calibrate/page.tsx
  src/website2/src/app/products/layout.tsx
  src/website2/src/app/products/mobile-app/page.tsx
  src/website2/src/app/products/monitor/page.tsx
  src/website2/src/app/solutions/african-cities/page.tsx
  src/website2/src/app/solutions/communities/page.tsx
  src/website2/src/app/solutions/layout.tsx
  src/website2/src/app/solutions/research/page.tsx
  src/website2/src/views/products/AnalyticsPage.tsx
  src/website2/src/views/products/ApiPage.tsx
  src/website2/src/views/products/CalibratePage.tsx
  src/website2/src/views/products/MobilePage.tsx
  src/website2/src/views/products/MonitorPage.tsx
Labels: ready for review

#2557 Custom map download for the analytics platform
  src/platform/public/icons/map/cameraIcon.jsx
  src/platform/public/icons/map/dotsVerticalIcon.jsx
  src/platform/src/common/components/Map/AirQoMap.jsx
  src/platform/src/common/components/Map/functions/index.jsx
  src/platform/src/common/components/Map/functions/useMapScreenshot.js
Labels: ready for review

#2558 Add autocomplete to register account and login forms in analytics platform
  src/platform/src/pages/account/creation/individual/register.jsx
  src/platform/src/pages/account/login/index.jsx
Labels: ready for review

#2559 move to production
  src/platform/public/icons/map/cameraIcon.jsx
  src/platform/public/icons/map/dotsVerticalIcon.jsx
  src/platform/src/common/components/Map/AirQoMap.jsx
  src/platform/src/common/components/Map/functions/index.jsx
  src/platform/src/common/components/Map/functions/useMapScreenshot.js
  src/platform/src/pages/account/creation/individual/register.jsx
  src/platform/src/pages/account/login/index.jsx
Labels: ready for review

#2562 Website: Update tab LABEL
  src/website2/public/favicon.ico
  src/website2/src/app/Logo.png
  src/website2/src/app/apple-icon.png
  src/website2/src/app/icon.png
  src/website2/src/app/icon.svg
  src/website2/src/app/layout.tsx
  src/website2/src/app/manifest.json
  src/website2/src/views/cleanairforum/TabNavigation.tsx
Labels: ready for review

#2563 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/website2/public/favicon.ico
  src/website2/src/app/Logo.png
  src/website2/src/app/apple-icon.png
  src/website2/src/app/icon.png
  src/website2/src/app/icon.svg
  src/website2/src/app/layout.tsx
  src/website2/src/app/manifest.json
  src/website2/src/views/cleanairforum/TabNavigation.tsx
Labels: ready for review

#2544 [Netmanager-app]improved on the grids hooks
  src/netmanager-app/components/Analytics/analytics-skeleton.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/components/Organization/create-group.tsx
  src/netmanager-app/core/hooks/useGrids.ts
  src/netmanager-app/core/hooks/useGroups.ts
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review, netmanager-app

#2564 move to production
  src/netmanager-app/components/Analytics/analytics-skeleton.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/components/Organization/create-group.tsx
  src/netmanager-app/core/hooks/useGrids.ts
  src/netmanager-app/core/hooks/useGroups.ts
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review

#2569 NETMANAGER >> Update README.md to trigger new ENVs
  src/netmanager/README.md
Labels: ready for review

#2570 move to production
  src/netmanager/README.md
Labels: ready for review

#2571 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  src/mobile-v3/ios/Runner/Info.plist
  src/mobile-v3/lib/core/utils/app_loggy_setup.dart
  src/mobile-v3/lib/main.dart
  src/mobile-v3/lib/src/app/auth/bloc/ForgotPasswordBloc/forgot_password_state.dart
  src/mobile-v3/lib/src/app/auth/pages/password_reset/reset_link_sent.dart
  src/mobile-v3/lib/src/app/auth/pages/welcome_screen.dart
  src/mobile-v3/lib/src/app/auth/repository/auth_repository.dart
  src/mobile-v3/lib/src/app/auth/services/auth_helper.dart
  src/mobile-v3/lib/src/app/auth/services/token_debugger.dart
  src/mobile-v3/lib/src/app/dashboard/bloc/dashboard/dashboard_bloc.dart
  src/mobile-v3/lib/src/app/dashboard/bloc/dashboard/dashboard_event.dart
  src/mobile-v3/lib/src/app/dashboard/bloc/dashboard/dashboard_state.dart
  src/mobile-v3/lib/src/app/dashboard/models/country_model.dart
  src/mobile-v3/lib/src/app/dashboard/models/nearest_places_model.dart
  src/mobile-v3/lib/src/app/dashboard/models/nearest_places_model.g.dart
  src/mobile-v3/lib/src/app/dashboard/models/user_preferences_model.dart
  src/mobile-v3/lib/src/app/dashboard/pages/dashboard_page.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/components/countries_filter.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/components/location_list_view.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/components/location_search_bar.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/components/swipeable_analytics_card.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/location_selection_screen.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/utils/location_helpers.dart
  src/mobile-v3/lib/src/app/dashboard/repository/country_repository.dart
  src/mobile-v3/lib/src/app/dashboard/repository/nearest_places_repository.dart
  src/mobile-v3/lib/src/app/dashboard/repository/user_preferences_repository.dart
  src/mobile-v3/lib/src/app/dashboard/services/location_service_mananger.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/analytics_card.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/analytics_forecast_widget.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/countries_chip.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/dashboard_app_bar.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/dashboard_header.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/google_places_loader.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/location_display_widget.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/measurements_list.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/my_places_view.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/nearby_measurement_card.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/nearby_view.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/nearby_view_empty_state.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/view_selector.dart
  src/mobile-v3/lib/src/app/map/pages/map_page.dart
  src/mobile-v3/lib/src/app/profile/bloc/user_bloc.dart
  src/mobile-v3/lib/src/app/profile/bloc/user_event.dart
  src/mobile-v3/lib/src/app/profile/bloc/user_state.dart
  src/mobile-v3/lib/src/app/profile/pages/edit_profile.dart
  src/mobile-v3/lib/src/app/profile/pages/profile_page.dart
  src/mobile-v3/lib/src/app/profile/pages/widgets/settings_tile.dart
  src/mobile-v3/lib/src/app/profile/pages/widgets/settings_widget.dart
  src/mobile-v3/lib/src/app/profile/repository/user_repository.dart
  src/mobile-v3/lib/src/app/shared/pages/nav_page.dart
  src/mobile-v3/lib/src/app/shared/repository/base_repository.dart
  src/mobile-v3/lib/src/app/shared/repository/base_repository_extension.dart
  src/mobile-v3/lib/src/app/shared/services/notification_manager.dart
  src/mobile-v3/lib/src/app/shared/utils/connectivity_helper.dart
  src/mobile-v3/lib/src/app/shared/widgets/status_notification.dart
  src/mobile-v3/pubspec.lock
  src/mobile-v3/pubspec.yaml
Labels: ready for review

#2573 move to production
  src/website2/src/app/explore-data/page.tsx
  src/website2/src/views/ExplorePage.tsx
  src/website2/src/views/home/AppDownloadSection.tsx
  src/website2/src/views/home/HomePage.tsx
  src/website2/src/views/products/MobilePage.tsx
Labels: ready for review

#2550 [Platform] Data download, Chart Loading and Analytics Card enhancement
  src/platform/Dockerfile
  src/platform/package.json
  src/platform/public/icons/Analytics/deviceIcon.js
  src/platform/src/common/components/AQNumberCard/components/SkeletonCard.jsx
  src/platform/src/common/components/AQNumberCard/components/index.jsx
  src/platform/src/common/components/AQNumberCard/constants/index.jsx
  src/platform/src/common/components/AQNumberCard/index.jsx
  src/platform/src/common/components/Calendar/Calendar.jsx
  src/platform/src/common/components/Calendar/DatePicker.jsx
  src/platform/src/common/components/Charts/ChartContainer.jsx
  src/platform/src/common/components/Charts/MoreInsightsChart.jsx
  src/platform/src/common/components/Charts/components/StandardsMenu.jsx
  src/platform/src/common/components/Map/components/sidebar/index.jsx
  src/platform/src/common/components/Messages/InfoMessage.jsx
  src/platform/src/common/components/Modal/dataDownload/components/CustomFields.jsx
  src/platform/src/common/components/Modal/dataDownload/components/DataTable.jsx
  src/platform/src/common/components/Modal/dataDownload/components/Footer.jsx
  src/platform/src/common/components/Modal/dataDownload/constants/svgs.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/AddLocations.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/DataDownload.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/MoreInsights.jsx
  src/platform/src/common/components/Toast/CustomToast.jsx
  src/platform/src/core/apis/Analytics.js
  src/platform/src/core/apis/DeviceRegistry.js
  src/platform/src/core/hooks/analyticHooks.tsx
  src/platform/src/core/hooks/useFetchAnalyticsData.jsx
  src/platform/src/core/hooks/useResizeObserver.jsx
  src/platform/src/core/hooks/useWindowSize.jsx
  src/platform/src/core/swrConfigs.tsx
  src/platform/src/core/urls/analytics.js
  src/platform/src/core/urls/deviceRegistry.js
  src/platform/src/lib/store/services/charts/ChartData.js
  src/platform/src/lib/store/services/deviceRegistry/RecentMeasurementsSlice.js
  src/platform/src/pages/analytics/_components/OverView.jsx
  src/platform/src/pages/api/proxy/devices.js
  src/platform/src/pages/api/proxy/grids.js
  src/platform/yarn.lock
Labels: ready for review

#2574 move to production
  src/platform/Dockerfile
  src/platform/package.json
  src/platform/public/icons/Analytics/deviceIcon.js
  src/platform/src/common/components/AQNumberCard/components/SkeletonCard.jsx
  src/platform/src/common/components/AQNumberCard/components/index.jsx
  src/platform/src/common/components/AQNumberCard/constants/index.jsx
  src/platform/src/common/components/AQNumberCard/index.jsx
  src/platform/src/common/components/Calendar/Calendar.jsx
  src/platform/src/common/components/Calendar/DatePicker.jsx
  src/platform/src/common/components/Charts/ChartContainer.jsx
  src/platform/src/common/components/Charts/MoreInsightsChart.jsx
  src/platform/src/common/components/Charts/components/StandardsMenu.jsx
  src/platform/src/common/components/Map/components/sidebar/index.jsx
  src/platform/src/common/components/Messages/InfoMessage.jsx
  src/platform/src/common/components/Modal/dataDownload/components/CustomFields.jsx
  src/platform/src/common/components/Modal/dataDownload/components/DataTable.jsx
  src/platform/src/common/components/Modal/dataDownload/components/Footer.jsx
  src/platform/src/common/components/Modal/dataDownload/constants/svgs.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/AddLocations.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/DataDownload.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/MoreInsights.jsx
  src/platform/src/common/components/Toast/CustomToast.jsx
  src/platform/src/core/apis/Analytics.js
  src/platform/src/core/apis/DeviceRegistry.js
  src/platform/src/core/hooks/analyticHooks.tsx
  src/platform/src/core/hooks/useFetchAnalyticsData.jsx
  src/platform/src/core/hooks/useResizeObserver.jsx
  src/platform/src/core/hooks/useWindowSize.jsx
  src/platform/src/core/swrConfigs.tsx
  src/platform/src/core/urls/analytics.js
  src/platform/src/core/urls/deviceRegistry.js
  src/platform/src/lib/store/services/charts/ChartData.js
  src/platform/src/lib/store/services/deviceRegistry/RecentMeasurementsSlice.js
  src/platform/src/pages/analytics/_components/OverView.jsx
  src/platform/src/pages/api/proxy/devices.js
  src/platform/src/pages/api/proxy/grids.js
  src/platform/yarn.lock
Labels: ready for review

#2575 Removed download limit on Sites and fix csv format issue production
  src/platform/src/common/components/Modal/dataDownload/components/SelectionMessage.tsx
  src/platform/src/common/components/Modal/dataDownload/modules/DataDownload.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/MoreInsights.jsx
  src/platform/src/core/hooks/useDataDownload.jsx
Labels: ready for review

#2576 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/platform/src/common/components/Modal/dataDownload/components/SelectionMessage.tsx
  src/platform/src/common/components/Modal/dataDownload/modules/DataDownload.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/MoreInsights.jsx
  src/platform/src/core/hooks/useDataDownload.jsx
Labels: ready for review

#2577 [Hotfix] Update device feeds url
  src/netmanager/src/config/urls/dataManagement.js
  src/netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
Labels: ready for review

#2578 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/netmanager/src/config/urls/dataManagement.js
  src/netmanager/src/views/components/DataDisplay/DeviceView/DeviceDeployStatus.js
Labels: ready for review

#2581 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  src/mobile-v3/assets/images/dashboard/Dark_icon.svg
  src/mobile-v3/assets/images/dashboard/Light_icon.svg
  src/mobile-v3/lib/src/app/auth/pages/password_reset/forgot_password.dart
  src/mobile-v3/lib/src/app/auth/pages/password_reset/password_reset.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/components/location_list_view.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/components/swipeable_analytics_card.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/location_selection_screen.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/analytics_card.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/dashboard_app_bar.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/dashboard_header.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/view_selector.dart
  src/mobile-v3/lib/src/meta/utils/colors.dart
Labels: ready for review

#2582 website: Update data records section
  src/website2/src/views/home/HomeStatsSection.tsx
Labels: ready for review

#2583 move to production
  src/website2/src/views/home/HomeStatsSection.tsx
Labels: ready for review

#2587 [Netmanager-app] Topbar refactor
  src/netmanager-app/components/desktop-sidebar.tsx
  src/netmanager-app/components/topbar.tsx
  src/netmanager-app/components/ui/separator.tsx
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review, frontend, netmanager-app

#2588 move to production
  src/netmanager-app/app/login/page.tsx
  src/netmanager-app/components/desktop-sidebar.tsx
  src/netmanager-app/components/topbar.tsx
  src/netmanager-app/components/ui/separator.tsx
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review
