Repository airqo-platform/AirQo-frontend, pull requests merged in 2025-04, with the labels that each got.

#2579 Fix: Organization dropdown and Map error issue
  src/platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  src/platform/src/common/components/Map/AirQoMap.jsx
  src/platform/src/common/components/Map/functions/useLocationBoundaries.jsx
  src/platform/src/common/components/Map/functions/useMapControls.jsx
  src/platform/src/common/components/Map/functions/useMapData.jsx
  src/platform/src/common/components/Map/functions/useMapScreenshot.js
  src/platform/src/common/components/Modal/dataDownload/components/CustomFields.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/DataDownload.jsx
  src/platform/src/core/hooks/index.jsx
  src/platform/src/core/hooks/useDebounce.jsx
  src/platform/src/core/hooks/useSitesSummary.jsx
  src/platform/src/pages/account/login/index.jsx
Labels: ready for review

#2589 move to production
  k8s/platform/values-stage.yaml
  src/platform/src/common/components/Dropdowns/OrganizationDropdown.jsx
  src/platform/src/common/components/Map/AirQoMap.jsx
  src/platform/src/common/components/Map/functions/useLocationBoundaries.jsx
  src/platform/src/common/components/Map/functions/useMapControls.jsx
  src/platform/src/common/components/Map/functions/useMapData.jsx
  src/platform/src/common/components/Map/functions/useMapScreenshot.js
  src/platform/src/common/components/Modal/dataDownload/components/CustomFields.jsx
  src/platform/src/common/components/Modal/dataDownload/modules/DataDownload.jsx
  src/platform/src/core/hooks/index.jsx
  src/platform/src/core/hooks/useDebounce.jsx
  src/platform/src/core/hooks/useSitesSummary.jsx
  src/platform/src/pages/account/login/index.jsx
Labels: ready for review

#2591 move to production
  k8s/platform/values-prod.yaml
  src/mobile-v3/lib/src/app/auth/pages/login_page.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/components/swipeable_analytics_card.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/analytics_card.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/analytics_forecast_widget.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/dashboard_header.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/measurements_list.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/my_places_view.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/view_selector.dart
  src/mobile-v3/lib/src/app/shared/pages/nav_page.dart
Labels: ready for review

#2592 Website: content updates
  src/website2/src/views/about/AboutPage.tsx
  src/website2/src/views/products/MobilePage.tsx
  src/website2/src/views/products/MonitorPage.tsx
  src/website2/src/views/solutions/communities/CommunityPage.tsx
Labels: ready for review

#2594 move to production
  src/website2/src/views/about/AboutPage.tsx
  src/website2/src/views/products/MobilePage.tsx
  src/website2/src/views/products/MonitorPage.tsx
  src/website2/src/views/solutions/communities/CommunityPage.tsx
Labels: ready for review

#2597 [Hotfixes] Type error fixes for new netmanager app
  src/netmanager-app/app/(authenticated)/sites/[id]/page.tsx
  src/netmanager-app/app/(authenticated)/sites/create-site-form.tsx
  src/netmanager-app/app/(authenticated)/sites/page.tsx
  src/netmanager-app/app/forgot-password/page.tsx
  src/netmanager-app/app/types/clients.ts
  src/netmanager-app/components/Analytics/ExceedanceLine.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/components/Organization/List.tsx
  src/netmanager-app/components/Organization/create-group.tsx
  src/netmanager-app/components/Organization/organization-roles.tsx
  src/netmanager-app/components/Settings/ApiTokens.tsx
  src/netmanager-app/components/Settings/ClientTableRow.tsx
  src/netmanager-app/components/Settings/Clients.tsx
  src/netmanager-app/components/Settings/CreateClientForm.tsx
  src/netmanager-app/components/Settings/EditClientForm.tsx
  src/netmanager-app/components/Settings/MyProfile.tsx
  src/netmanager-app/components/export-data/ExportForm.tsx
  src/netmanager-app/components/grids/create-grid.tsx
  src/netmanager-app/components/grids/polymap.tsx
  src/netmanager-app/core/apis/analytics.ts
Labels: ready for review

#2598 move to production
  src/netmanager-app/app/(authenticated)/sites/[id]/page.tsx
  src/netmanager-app/app/(authenticated)/sites/create-site-form.tsx
  src/netmanager-app/app/(authenticated)/sites/page.tsx
  src/netmanager-app/app/forgot-password/page.tsx
  src/netmanager-app/app/types/clients.ts
  src/netmanager-app/components/Analytics/ExceedanceLine.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/components/Organization/List.tsx
  src/netmanager-app/components/Organization/create-group.tsx
  src/netmanager-app/components/Organization/organization-roles.tsx
  src/netmanager-app/components/Settings/ApiTokens.tsx
  src/netmanager-app/components/Settings/ClientTableRow.tsx
  src/netmanager-app/components/Settings/Clients.tsx
  src/netmanager-app/components/Settings/CreateClientForm.tsx
  src/netmanager-app/components/Settings/EditClientForm.tsx
  src/netmanager-app/components/Settings/MyProfile.tsx
  src/netmanager-app/components/export-data/ExportForm.tsx
  src/netmanager-app/components/grids/create-grid.tsx
  src/netmanager-app/components/grids/polymap.tsx
  src/netmanager-app/core/apis/analytics.ts
Labels: ready for review

#2600 move to production
  src/mobile-v3/lib/src/app/dashboard/models/user_preferences_model.dart
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/location_selection_screen.dart
  src/mobile-v3/lib/src/app/dashboard/repository/user_preferences_repository.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/my_places_view.dart
Labels: ready for review

#2599 Newnwetmanager app deployment
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/netmanager-app/.helmignore
  k8s/netmanager-app/Chart.yaml
  k8s/netmanager-app/templates/NOTES.txt
  k8s/netmanager-app/templates/_helpers.tpl
  k8s/netmanager-app/templates/deployment.yaml
  k8s/netmanager-app/templates/hpa.yaml
  k8s/netmanager-app/templates/service.yaml
  k8s/netmanager-app/templates/tests/test-connection.yaml
  k8s/netmanager-app/values-prod.yaml
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/.dockerignore
  src/netmanager-app/Dockerfile
  src/netmanager-app/app/(authenticated)/grids/page.tsx
  src/netmanager-app/app/(authenticated)/sites/[id]/page.tsx
  src/netmanager-app/app/(authenticated)/sites/create-site-form.tsx
  src/netmanager-app/components/Analytics/CohortsDashboard.tsx
  src/netmanager-app/components/Analytics/ExceedanceLine.tsx
  src/netmanager-app/components/Analytics/GridDashboard.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/components/Organization/organization-profile.tsx
  src/netmanager-app/components/Organization/team-members.tsx
  src/netmanager-app/components/Settings/PasswordEdit.tsx
  src/netmanager-app/components/grids/polymap.tsx
  src/netmanager-app/core/hooks/useAirqlouds.ts
  src/netmanager-app/core/hooks/useClients.ts
  src/netmanager-app/core/hooks/useCohorts.ts
  src/netmanager-app/core/hooks/useGrids.ts
  src/netmanager-app/core/hooks/useGroups.ts
  src/netmanager-app/core/hooks/useRoles.ts
  src/netmanager-app/core/hooks/useSites.ts
  src/netmanager-app/core/hooks/useUserClients.ts
  src/netmanager-app/core/redux/slices/analyticsSlice.ts
  src/netmanager-app/lib/utils.ts
Labels: ready for review

#2601 move to production
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-staging.yml
  .github/workflows/remove-deploy-previews.yml
  k8s/netmanager-app/.helmignore
  k8s/netmanager-app/Chart.yaml
  k8s/netmanager-app/templates/NOTES.txt
  k8s/netmanager-app/templates/_helpers.tpl
  k8s/netmanager-app/templates/deployment.yaml
  k8s/netmanager-app/templates/hpa.yaml
  k8s/netmanager-app/templates/service.yaml
  k8s/netmanager-app/templates/tests/test-connection.yaml
  k8s/netmanager-app/values-prod.yaml
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/.dockerignore
  src/netmanager-app/Dockerfile
  src/netmanager-app/app/(authenticated)/grids/page.tsx
  src/netmanager-app/app/(authenticated)/sites/[id]/page.tsx
  src/netmanager-app/app/(authenticated)/sites/create-site-form.tsx
  src/netmanager-app/components/Analytics/CohortsDashboard.tsx
  src/netmanager-app/components/Analytics/ExceedanceLine.tsx
  src/netmanager-app/components/Analytics/GridDashboard.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/components/Organization/organization-profile.tsx
  src/netmanager-app/components/Organization/team-members.tsx
  src/netmanager-app/components/Settings/PasswordEdit.tsx
  src/netmanager-app/components/grids/polymap.tsx
  src/netmanager-app/core/hooks/useAirqlouds.ts
  src/netmanager-app/core/hooks/useClients.ts
  src/netmanager-app/core/hooks/useCohorts.ts
  src/netmanager-app/core/hooks/useGrids.ts
  src/netmanager-app/core/hooks/useGroups.ts
  src/netmanager-app/core/hooks/useRoles.ts
  src/netmanager-app/core/hooks/useSites.ts
  src/netmanager-app/core/hooks/useUserClients.ts
  src/netmanager-app/core/redux/slices/analyticsSlice.ts
  src/netmanager-app/lib/utils.ts
Labels: ready for review

#2602 edited notes.txt
  k8s/netmanager-app/templates/NOTES.txt
Labels: ready for review

#2603 move to production
  k8s/netmanager-app/templates/NOTES.txt
  k8s/netmanager-app/values-stage.yaml
Labels: ready for review

#2604 readme trigger for new netmanager
  src/netmanager-app/README.md
Labels: ready for review

#2605 move to production
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/README.md
Labels: ready for review

#2606 edited value file for new netmanager
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/README.md
Labels: ready for review

#2584 Organization Setup Refactor
  src/netmanager-app/app/(authenticated)/organizations/[id]/page.tsx
  src/netmanager-app/app/(authenticated)/organizations/page.tsx
  src/netmanager-app/components/Organization/List.tsx
  src/netmanager-app/components/Organization/assign-resources-button.tsx
  src/netmanager-app/components/Organization/create-group.tsx
  src/netmanager-app/components/Organization/create-organization-dialog.tsx
  src/netmanager-app/components/Organization/organization-profile.tsx
  src/netmanager-app/components/Organization/organization-roles.tsx
  src/netmanager-app/components/Organization/organization-setup-card.tsx
  src/netmanager-app/components/Organization/resource-assignment-modal.tsx
  src/netmanager-app/components/desktop-sidebar.tsx
  src/netmanager-app/components/ui/empty-state.tsx
  src/netmanager-app/components/ui/scroll-area.tsx
  src/netmanager-app/core/apis/devices.ts
  src/netmanager-app/core/apis/organizations.ts
  src/netmanager-app/core/apis/sites.ts
  src/netmanager-app/core/hooks/useGrids.ts
  src/netmanager-app/core/hooks/useGroupResources.ts
  src/netmanager-app/core/hooks/useGroups.ts
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review, frontend, netmanager-app

#2608 move to production
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/app/(authenticated)/organizations/[id]/page.tsx
  src/netmanager-app/app/(authenticated)/organizations/page.tsx
  src/netmanager-app/components/Organization/List.tsx
  src/netmanager-app/components/Organization/assign-resources-button.tsx
  src/netmanager-app/components/Organization/create-group.tsx
  src/netmanager-app/components/Organization/create-organization-dialog.tsx
  src/netmanager-app/components/Organization/organization-profile.tsx
  src/netmanager-app/components/Organization/organization-roles.tsx
  src/netmanager-app/components/Organization/organization-setup-card.tsx
  src/netmanager-app/components/Organization/resource-assignment-modal.tsx
  src/netmanager-app/components/desktop-sidebar.tsx
  src/netmanager-app/components/ui/empty-state.tsx
  src/netmanager-app/components/ui/scroll-area.tsx
  src/netmanager-app/core/apis/devices.ts
  src/netmanager-app/core/apis/organizations.ts
  src/netmanager-app/core/apis/sites.ts
  src/netmanager-app/core/hooks/useGrids.ts
  src/netmanager-app/core/hooks/useGroupResources.ts
  src/netmanager-app/core/hooks/useGroups.ts
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review

#2610 edited app name for new-netmanager
  k8s/netmanager-app/Chart.yaml
  k8s/netmanager-app/templates/NOTES.txt
  k8s/netmanager-app/templates/_helpers.tpl
  k8s/netmanager-app/templates/tests/test-connection.yaml
  k8s/netmanager-app/values-prod.yaml
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/README.md
Labels: work in progress

#2611 move to production
  k8s/netmanager-app/Chart.yaml
  k8s/netmanager-app/templates/NOTES.txt
  k8s/netmanager-app/templates/_helpers.tpl
  k8s/netmanager-app/templates/tests/test-connection.yaml
  k8s/netmanager-app/values-prod.yaml
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/README.md
Labels: ready for review

#2612 edited port name
  k8s/netmanager-app/values-prod.yaml
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/README.md
Labels: ready for review

#2613 move to production
  k8s/netmanager-app/values-prod.yaml
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/README.md
Labels: ready for review

#2614 Newnetmanager k8s deployment files edit
  k8s/netmanager-app/Chart.yaml
  k8s/netmanager-app/templates/NOTES.txt
  k8s/netmanager-app/templates/_helpers.tpl
  k8s/netmanager-app/templates/tests/test-connection.yaml
  k8s/netmanager-app/values-prod.yaml
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/README.md
Labels: work in progress

#2615 move to production
  k8s/netmanager-app/Chart.yaml
  k8s/netmanager-app/templates/NOTES.txt
  k8s/netmanager-app/templates/_helpers.tpl
  k8s/netmanager-app/templates/tests/test-connection.yaml
  k8s/netmanager-app/values-prod.yaml
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/README.md
Labels: ready for review

#2621 move to production
  src/mobile-v3/assets/images/shared/language_icon.svg
  src/mobile-v3/assets/lang/en.json
  src/mobile-v3/assets/lang/fr.json
  src/mobile-v3/assets/lang/lg.json
  src/mobile-v3/assets/lang/pt.json
  src/mobile-v3/assets/lang/sw.json
  src/mobile-v3/lib/main.dart
  src/mobile-v3/lib/src/app/other/language/bloc/language_bloc.dart
  src/mobile-v3/lib/src/app/other/language/bloc/language_event.dart
  src/mobile-v3/lib/src/app/other/language/bloc/language_state.dart
  src/mobile-v3/lib/src/app/other/language/services/app_localizations.dart
  src/mobile-v3/lib/src/app/other/language/utils/translate_x.dart
  src/mobile-v3/lib/src/app/profile/pages/edit_profile.dart
  src/mobile-v3/lib/src/app/profile/pages/languages/select_language_page.dart
  src/mobile-v3/lib/src/app/profile/pages/widgets/settings_tile.dart
  src/mobile-v3/lib/src/app/profile/pages/widgets/settings_widget.dart
  src/mobile-v3/pubspec.lock
  src/mobile-v3/pubspec.yaml
Labels: ready for review

#2618 Network map for netmanager app
  src/netmanager-app/app/(authenticated)/layout.tsx
  src/netmanager-app/app/(authenticated)/network-map/layout.tsx
  src/netmanager-app/app/(authenticated)/network-map/page.tsx
  src/netmanager-app/app/(authenticated)/profile/page.tsx
  src/netmanager-app/app/layout.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/components/Settings/ApiTokens.tsx
  src/netmanager-app/components/Settings/Clients.tsx
  src/netmanager-app/components/desktop-sidebar.tsx
  src/netmanager-app/components/layout.tsx
  src/netmanager-app/components/network-map/map-legend.tsx
  src/netmanager-app/components/network-map/network-map.tsx
  src/netmanager-app/components/network-map/status-summary.tsx
  src/netmanager-app/components/topbar.tsx
  src/netmanager-app/core/apis/devices.ts
  src/netmanager-app/core/hooks/useDevices.ts
  src/netmanager-app/core/redux/slices/devicesSlice.ts
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review

#2622 move to production
  src/netmanager-app/app/(authenticated)/layout.tsx
  src/netmanager-app/app/(authenticated)/network-map/layout.tsx
  src/netmanager-app/app/(authenticated)/network-map/page.tsx
  src/netmanager-app/app/(authenticated)/profile/page.tsx
  src/netmanager-app/app/layout.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/components/Settings/ApiTokens.tsx
  src/netmanager-app/components/Settings/Clients.tsx
  src/netmanager-app/components/desktop-sidebar.tsx
  src/netmanager-app/components/layout.tsx
  src/netmanager-app/components/network-map/map-legend.tsx
  src/netmanager-app/components/network-map/network-map.tsx
  src/netmanager-app/components/network-map/status-summary.tsx
  src/netmanager-app/components/topbar.tsx
  src/netmanager-app/core/apis/devices.ts
  src/netmanager-app/core/hooks/useDevices.ts
  src/netmanager-app/core/redux/slices/devicesSlice.ts
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review

#2624 Site details page enhancement in netmanager app
  src/netmanager-app/app/(authenticated)/sites/[id]/devices.tsx
  src/netmanager-app/app/(authenticated)/sites/[id]/page.tsx
  src/netmanager-app/app/(authenticated)/sites/create-site-form.tsx
  src/netmanager-app/app/(authenticated)/sites/page.tsx
  src/netmanager-app/app/(authenticated)/sites/site-form.tsx
  src/netmanager-app/app/types/sites.ts
  src/netmanager-app/components/desktop-sidebar.tsx
  src/netmanager-app/components/topbar.tsx
  src/netmanager-app/core/apis/sites.ts
  src/netmanager-app/core/hooks/useSites.ts
Labels: ready for review

#2623 [Netmanager-App] Perfecting the Organisation Role module
  src/netmanager-app/app/login/page.tsx
  src/netmanager-app/app/types/roles.ts
  src/netmanager-app/components/Organization/assign-resources-button.tsx
  src/netmanager-app/components/Organization/create-organization-dialog.tsx
  src/netmanager-app/components/Organization/organization-profile.tsx
  src/netmanager-app/components/Organization/organization-roles.tsx
  src/netmanager-app/components/Organization/organization-setup-card.tsx
  src/netmanager-app/components/Organization/resource-assignment-modal.tsx
  src/netmanager-app/components/Organization/team-members.tsx
  src/netmanager-app/core/apis/users.ts
  src/netmanager-app/core/hooks/useGroupResources.ts
  src/netmanager-app/core/hooks/usePermission.ts
  src/netmanager-app/core/urls.tsx
Labels: ready for review, frontend, netmanager-app

#2625 move to production
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/app/(authenticated)/sites/[id]/devices.tsx
  src/netmanager-app/app/(authenticated)/sites/[id]/page.tsx
  src/netmanager-app/app/(authenticated)/sites/create-site-form.tsx
  src/netmanager-app/app/(authenticated)/sites/page.tsx
  src/netmanager-app/app/(authenticated)/sites/site-form.tsx
  src/netmanager-app/app/login/page.tsx
  src/netmanager-app/app/types/roles.ts
  src/netmanager-app/app/types/sites.ts
  src/netmanager-app/components/Organization/assign-resources-button.tsx
  src/netmanager-app/components/Organization/create-organization-dialog.tsx
  src/netmanager-app/components/Organization/organization-profile.tsx
  src/netmanager-app/components/Organization/organization-roles.tsx
  src/netmanager-app/components/Organization/organization-setup-card.tsx
  src/netmanager-app/components/Organization/resource-assignment-modal.tsx
  src/netmanager-app/components/Organization/team-members.tsx
  src/netmanager-app/components/desktop-sidebar.tsx
  src/netmanager-app/components/topbar.tsx
  src/netmanager-app/core/apis/sites.ts
  src/netmanager-app/core/apis/users.ts
  src/netmanager-app/core/hooks/useGroupResources.ts
  src/netmanager-app/core/hooks/usePermission.ts
  src/netmanager-app/core/hooks/useSites.ts
  src/netmanager-app/core/urls.tsx
Labels: ready for review

#2630 Analytics Map Improvements
  src/platform/src/common/components/Calendar/DatePicker.jsx
  src/platform/src/common/features/airQuality-map/components/LoadingOverlay.js
  src/platform/src/common/features/airQuality-map/components/sidebar/components/SidebarHeader.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/common/features/airQuality-map/index.jsx
  src/platform/src/common/features/download-insights-locations/components/datadownload/DataContent.js
  src/platform/src/common/features/download-insights-locations/components/datadownload/SettingsSidebar.js
  src/platform/src/common/features/download-insights-locations/constants/index.jsx
  src/platform/src/common/features/download-insights-locations/hooks/useLocationSelection.js
  src/platform/src/common/features/download-insights-locations/index.jsx
  src/platform/src/common/features/download-insights-locations/modules/AddLocations.jsx
  src/platform/src/common/features/download-insights-locations/modules/DataDownload.jsx
  src/platform/src/common/features/download-insights-locations/utils/index.js
  src/platform/src/lib/store/services/map/MapSlice.js
  src/platform/src/pages/analytics/_components/OverView.jsx
Labels: ready for review

#2631 move to production
  k8s/platform/values-prod.yaml
  src/platform/src/common/components/Calendar/DatePicker.jsx
  src/platform/src/common/features/airQuality-map/components/LoadingOverlay.js
  src/platform/src/common/features/airQuality-map/components/sidebar/components/SidebarHeader.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/common/features/airQuality-map/index.jsx
  src/platform/src/common/features/download-insights-locations/components/datadownload/DataContent.js
  src/platform/src/common/features/download-insights-locations/components/datadownload/SettingsSidebar.js
  src/platform/src/common/features/download-insights-locations/constants/index.jsx
  src/platform/src/common/features/download-insights-locations/hooks/useLocationSelection.js
  src/platform/src/common/features/download-insights-locations/index.jsx
  src/platform/src/common/features/download-insights-locations/modules/AddLocations.jsx
  src/platform/src/common/features/download-insights-locations/modules/DataDownload.jsx
  src/platform/src/common/features/download-insights-locations/utils/index.js
  src/platform/src/lib/store/services/map/MapSlice.js
  src/platform/src/pages/analytics/_components/OverView.jsx
Labels: ready for review

#2632 Netmanager App >> Update README.md
  src/netmanager-app/README.md
Labels: ready for review

#2633 Analytics: Feedback updates and Responsiveness fix
  src/platform/src/common/components/Layout/index.jsx
  src/platform/src/common/features/airQuality-map/components/Legend.js
  src/platform/src/common/features/airQuality-map/components/sidebar/components/LocationCards.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/components/SidebarHeader.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/common/features/airQuality-map/constants/constants.js
  src/platform/src/common/features/airQuality-map/hooks/index.jsx
  src/platform/src/common/features/airQuality-map/hooks/useMapControls.jsx
  src/platform/src/common/features/airQuality-map/index.jsx
  src/platform/src/common/features/download-insights-locations/components/AirQualityCard.jsx
  src/platform/src/common/features/download-insights-locations/components/DataTable.jsx
  src/platform/src/common/features/download-insights-locations/components/datadownload/SettingsSidebar.js
  src/platform/src/common/features/download-insights-locations/modules/DataDownload.jsx
  src/platform/src/common/features/download-insights-locations/modules/MoreInsights.jsx
  src/platform/src/common/features/theme-customizer/utils/themeUtils.jsx
  src/platform/src/lib/store/services/map/MapSlice.js
  src/platform/src/pages/analytics/_components/OverView.jsx
  src/platform/src/pages/map/index.jsx
  src/platform/src/pages/settings/Tabs/OrganizationProfile.jsx
  src/platform/src/pages/settings/Tabs/Password.jsx
  src/platform/src/pages/settings/Tabs/Profile.jsx
  src/platform/src/pages/settings/Tabs/Team.jsx
  src/platform/yarn.lock
Labels: ready for review, analytics

#2634 move to production
  k8s/netmanager-app/values-stage.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/netmanager-app/README.md
  src/platform/src/common/components/Layout/index.jsx
  src/platform/src/common/features/airQuality-map/components/Legend.js
  src/platform/src/common/features/airQuality-map/components/sidebar/components/LocationCards.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/components/SidebarHeader.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/common/features/airQuality-map/constants/constants.js
  src/platform/src/common/features/airQuality-map/hooks/index.jsx
  src/platform/src/common/features/airQuality-map/hooks/useMapControls.jsx
  src/platform/src/common/features/airQuality-map/index.jsx
  src/platform/src/common/features/download-insights-locations/components/AirQualityCard.jsx
  src/platform/src/common/features/download-insights-locations/components/DataTable.jsx
  src/platform/src/common/features/download-insights-locations/components/datadownload/SettingsSidebar.js
  src/platform/src/common/features/download-insights-locations/modules/DataDownload.jsx
  src/platform/src/common/features/download-insights-locations/modules/MoreInsights.jsx
  src/platform/src/common/features/theme-customizer/utils/themeUtils.jsx
  src/platform/src/lib/store/services/map/MapSlice.js
  src/platform/src/pages/analytics/_components/OverView.jsx
  src/platform/src/pages/map/index.jsx
  src/platform/src/pages/settings/Tabs/OrganizationProfile.jsx
  src/platform/src/pages/settings/Tabs/Password.jsx
  src/platform/src/pages/settings/Tabs/Profile.jsx
  src/platform/src/pages/settings/Tabs/Team.jsx
  src/platform/yarn.lock
Labels: ready for review

#2627 [Netmanager-app] User Statistics page
  src/netmanager-app/app/(authenticated)/user-management/page.tsx
  src/netmanager-app/app/types/userStats.ts
  src/netmanager-app/components/Analytics/analytics-skeleton.tsx
  src/netmanager-app/components/userstats/stats-cards.tsx
  src/netmanager-app/components/userstats/user-distribution-chart.tsx
  src/netmanager-app/components/userstats/user-search.tsx
  src/netmanager-app/components/userstats/user-stats-dashboard.tsx
  src/netmanager-app/components/userstats/user-table.tsx
  src/netmanager-app/core/hooks/useUserStats.ts
Labels: ready for review, frontend, netmanager-app

#2635 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/netmanager-app/app/(authenticated)/user-management/page.tsx
  src/netmanager-app/app/types/userStats.ts
  src/netmanager-app/components/Analytics/analytics-skeleton.tsx
  src/netmanager-app/components/userstats/stats-cards.tsx
  src/netmanager-app/components/userstats/user-distribution-chart.tsx
  src/netmanager-app/components/userstats/user-search.tsx
  src/netmanager-app/components/userstats/user-stats-dashboard.tsx
  src/netmanager-app/components/userstats/user-table.tsx
  src/netmanager-app/core/hooks/useUserStats.ts
Labels: ready for review

#2628 [Netmanager-app] Analytic Page
  src/netmanager-app/.env.example
  src/netmanager-app/components/Analytics/CohortsDashboard.tsx
  src/netmanager-app/components/Analytics/ExceedanceLine.tsx
  src/netmanager-app/components/Analytics/GridDashboard.tsx
  src/netmanager-app/components/Analytics/PollutantCategory.tsx
  src/netmanager-app/components/Analytics/averages-chart.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/core/urls.tsx
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review, frontend, netmanager-app

#2636 move to production
  k8s/netmanager-app/values-stage.yaml
  src/netmanager-app/.env.example
  src/netmanager-app/components/Analytics/CohortsDashboard.tsx
  src/netmanager-app/components/Analytics/ExceedanceLine.tsx
  src/netmanager-app/components/Analytics/GridDashboard.tsx
  src/netmanager-app/components/Analytics/PollutantCategory.tsx
  src/netmanager-app/components/Analytics/averages-chart.tsx
  src/netmanager-app/components/Analytics/index.tsx
  src/netmanager-app/core/urls.tsx
  src/netmanager-app/package-lock.json
  src/netmanager-app/package.json
Labels: ready for review

#2641 Analytics: Wrong AQI indexing on chart (fix)
  src/platform/src/common/components/Toast/CustomToast.jsx
  src/platform/src/common/features/airQuality-charts/MoreInsightsChart.jsx
  src/platform/src/common/features/airQuality-charts/components/index.jsx
  src/platform/src/common/features/download-insights-locations/modules/MoreInsights.jsx
Labels: ready for review

#2642 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/platform/src/common/components/Toast/CustomToast.jsx
  src/platform/src/common/features/airQuality-charts/MoreInsightsChart.jsx
  src/platform/src/common/features/airQuality-charts/components/index.jsx
  src/platform/src/common/features/download-insights-locations/modules/MoreInsights.jsx
Labels: ready for review

#2619 website: New guide link updated and Updates For CLEAN-Air Forum 2025
  src/website2/src/app/layout.tsx
  src/website2/src/components/ExternalLinkDecorator.tsx
  src/website2/src/components/sections/ReversibleContentSection.tsx
  src/website2/src/views/cleanairforum/speakers/SpeakersPage.tsx
  src/website2/src/views/home/HomePage.tsx
  src/website2/src/views/products/MonitorPage.tsx
Labels: ready for review

#2643 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/website2/src/app/layout.tsx
  src/website2/src/components/ExternalLinkDecorator.tsx
  src/website2/src/components/sections/ReversibleContentSection.tsx
  src/website2/src/views/cleanairforum/speakers/SpeakersPage.tsx
  src/website2/src/views/home/HomePage.tsx
  src/website2/src/views/products/MonitorPage.tsx
Labels: ready for review

#2645 move to production
  src/mobile-v3/lib/src/app/dashboard/widgets/my_places_view.dart
Labels: ready for review

#2648 Analytics: Data download fix
  src/platform/src/common/features/download-insights-locations/modules/DataDownload.jsx
  src/platform/yarn.lock
Labels: ready for review

#2649 move to production
  src/platform/src/common/features/download-insights-locations/modules/DataDownload.jsx
  src/platform/yarn.lock
Labels: ready for review

#2651 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/mobile-v3/lib/core/utils/app_loggy_setup.dart
  src/mobile-v3/lib/core/utils/slack_logger.dart
  src/mobile-v3/lib/main.dart
  src/mobile-v3/lib/src/app/debug/slack_logger_test_screen.dart
  src/mobile-v3/lib/src/app/profile/pages/widgets/settings_widget.dart
Labels: ready for review

#2652 Analytics: Remove 404 from slack response and fix for missing site_ids
  src/platform/src/common/components/Toast/CustomToast.jsx
  src/platform/src/common/features/airQuality-cards/index.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/lib/logger/index.js
Labels: ready for review

#2653 move to production
  src/platform/src/common/components/Toast/CustomToast.jsx
  src/platform/src/common/features/airQuality-cards/index.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/lib/logger/index.js
Labels: ready for review

#2658 move to production
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/components/location_list_view.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/analytics_card.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/nearby_measurement_card.dart
Labels: ready for review

#2654 Analytics: Response message Update based on status
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/common/features/download-insights-locations/modules/MoreInsights.jsx
  src/platform/src/core/hooks/useDataDownload.jsx
Labels: ready for review

#2659 move to production
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/common/features/download-insights-locations/modules/MoreInsights.jsx
  src/platform/src/core/hooks/useDataDownload.jsx
Labels: ready for review

#2663 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/mobile-v3/assets/images/shared/airquality_indicators/unhealthy-sensitive.svg
  src/mobile-v3/assets/images/shared/airquality_indicators/unhealthy.svg
  src/mobile-v3/lib/src/app/dashboard/pages/dashboard_page.dart
  src/mobile-v3/lib/src/app/dashboard/repository/nearest_places_repository.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/nearby_view.dart
  src/mobile-v3/lib/src/app/profile/pages/edit_profile.dart
  src/mobile-v3/lib/src/app/shared/repository/base_repository.dart
  src/mobile-v3/lib/src/app/shared/repository/base_repository_extension.dart
Labels: ready for review

#2664 Analytics: Enhancements to code
  src/platform/next.config.js
  src/platform/src/common/components/search/SearchField.jsx
  src/platform/src/common/features/Checklist/components/Checklist.js
  src/platform/src/common/features/Checklist/hooks/useChecklistSteps.js
  src/platform/src/common/features/Checklist/utils/steps.js
  src/platform/src/common/features/airQuality-charts/MoreInsightsChart.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/components/CountryList.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/components/LocationCards.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/common/features/airQuality-map/index.jsx
  src/platform/src/common/features/download-insights-locations/modules/AddLocations.jsx
  src/platform/src/lib/logger/index.js
  src/platform/src/pages/Home/index.jsx
  src/platform/src/pages/settings/Tabs/Profile.jsx
Labels: enhancement, ready for review

#2665 move to production
  src/platform/next.config.js
  src/platform/src/common/components/search/SearchField.jsx
  src/platform/src/common/features/Checklist/components/Checklist.js
  src/platform/src/common/features/Checklist/hooks/useChecklistSteps.js
  src/platform/src/common/features/Checklist/utils/steps.js
  src/platform/src/common/features/airQuality-charts/MoreInsightsChart.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/components/CountryList.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/components/LocationCards.jsx
  src/platform/src/common/features/airQuality-map/components/sidebar/index.jsx
  src/platform/src/common/features/airQuality-map/index.jsx
  src/platform/src/common/features/download-insights-locations/modules/AddLocations.jsx
  src/platform/src/lib/logger/index.js
  src/platform/src/pages/Home/index.jsx
  src/platform/src/pages/settings/Tabs/Profile.jsx
Labels: ready for review

#2667 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/mobile-v3/lib/src/app/dashboard/widgets/nearby_view.dart
Labels: ready for review

#2669 move to production
  src/mobile-v3/lib/src/meta/utils/api_utils.dart
Labels: ready for review

#2672 move to production
  src/mobile-v3/lib/core/utils/hive_box_setup.dart
  src/mobile-v3/lib/main.dart
  src/mobile-v3/lib/src/app/auth/services/auth_helper.dart
  src/mobile-v3/lib/src/app/dashboard/bloc/forecast/forecast_bloc.dart
  src/mobile-v3/lib/src/app/dashboard/bloc/forecast/forecast_event.dart
  src/mobile-v3/lib/src/app/dashboard/bloc/forecast/forecast_state.dart
  src/mobile-v3/lib/src/app/dashboard/repository/forecast_repository.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/analytics_forecast_widget.dart
  src/mobile-v3/lib/src/app/shared/repository/hive_repository.dart
  src/mobile-v3/pubspec.lock
  src/mobile-v3/pubspec.yaml
Labels: ready for review

#2670 Wesbite: Enabled Website Link redirect on partner logo click (CLEAN-air forum)
  src/website2/.dockerignore
  src/website2/next.config.mjs
  src/website2/src/views/cleanAirNetwork/PaginatedSection.tsx
  src/website2/src/views/cleanairforum/partners/PartnersPage.tsx
Labels: ready for review

#2673 move to production
  src/website2/.dockerignore
  src/website2/next.config.mjs
  src/website2/src/views/cleanAirNetwork/PaginatedSection.tsx
  src/website2/src/views/cleanairforum/partners/PartnersPage.tsx
Labels: ready for review
