Repository airqo-platform/AirQo-frontend, pull requests merged in 2025-09, with the labels that each got.

#2881 Website: Enhancing Site Metadata for Better SEO and Social Sharing
  src/website2/.env.sample
  src/website2/jest.config.js
  src/website2/next.config.mjs
  src/website2/package-lock.json
  src/website2/package.json
  src/website2/src/app/(about)/about-us/page.tsx
  src/website2/src/app/(about)/careers/page.tsx
  src/website2/src/app/(about)/events/page.tsx
  src/website2/src/app/(about)/press/page.tsx
  src/website2/src/app/(about)/resources/page.tsx
  src/website2/src/app/api/proxy/route.ts
  src/website2/src/app/clean-air-forum/about/page.tsx
  src/website2/src/app/clean-air-network/about/page.tsx
  src/website2/src/app/contact/page.tsx
  src/website2/src/app/explore-data/page.tsx
  src/website2/src/app/home/page.tsx
  src/website2/src/app/layout.tsx
  src/website2/src/app/legal/airqo-data/page.tsx
  src/website2/src/app/legal/payment-refund-policy/page.tsx
  src/website2/src/app/legal/privacy-policy/page.tsx
  src/website2/src/app/legal/terms-of-service/page.tsx
  src/website2/src/app/page.tsx
  src/website2/src/app/products/analytics/page.tsx
  src/website2/src/app/products/api/page.tsx
  src/website2/src/app/products/calibrate/page.tsx
  src/website2/src/app/products/layout.tsx
  src/website2/src/app/products/mobile-app/page.tsx
  src/website2/src/app/products/monitor/page.tsx
  src/website2/src/app/robots.txt/route.ts
  src/website2/src/app/sitemap.ts
  src/website2/src/app/sitemap.xml/route.ts
  src/website2/src/app/solutions/african-cities/page.tsx
  src/website2/src/app/solutions/communities/page.tsx
  src/website2/src/app/solutions/research/page.tsx
  src/website2/src/components/PerformanceMonitor.client.tsx
  src/website2/src/components/ui/LazyImage.tsx
  src/website2/src/components/ui/OptimizedImage.tsx
  src/website2/src/lib/metadata.ts
  src/website2/src/lib/performance-monitor.ts
  src/website2/src/lib/performance.tsx
  src/website2/src/services/externalService/index.tsx
  src/website2/tsconfig.json
Labels: ready for review

#2885 Analytics: Correct Bug on CustomDropdown component
  src/platform/src/common/features/download-insights-locations/data-download/components/CustomFields.jsx
  src/platform/src/common/features/download-insights-locations/data-download/components/SettingsSidebar.js
  src/platform/src/common/layouts/components/UserProfileDropdown.jsx
Labels: ready for review

#2886 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  k8s/vertex/values-prod.yaml
  src/platform/src/common/features/download-insights-locations/data-download/components/CustomFields.jsx
  src/platform/src/common/features/download-insights-locations/data-download/components/SettingsSidebar.js
  src/platform/src/common/layouts/components/UserProfileDropdown.jsx
Labels: ready for review

#2867 Update cohorts table to use api data in vertex app
  src/vertex/app/(authenticated)/cohorts/[id]/page.tsx
  src/vertex/app/(authenticated)/cohorts/page.tsx
  src/vertex/app/(authenticated)/devices/my-devices/page.tsx
  src/vertex/app/(authenticated)/devices/overview/[id]/page.tsx
  src/vertex/app/(authenticated)/devices/overview/page.tsx
  src/vertex/app/(authenticated)/grids/page.tsx
  src/vertex/app/(authenticated)/sites/page.tsx
  src/vertex/app/providers.tsx
  src/vertex/app/types/cohorts.ts
  src/vertex/app/types/devices.ts
  src/vertex/components/features/cohorts/assign-cohort-devices.tsx
  src/vertex/components/features/cohorts/cohort-detail-card.tsx
  src/vertex/components/features/cohorts/create-cohort.tsx
  src/vertex/components/features/cohorts/edit-cohort-details-modal.tsx
  src/vertex/components/features/devices/device-details-card.tsx
  src/vertex/components/features/devices/device-list-table.tsx
  src/vertex/components/features/devices/device-location-card.tsx
  src/vertex/components/features/devices/maintenance-status-card.tsx
  src/vertex/components/features/devices/online-status-card.tsx
  src/vertex/components/features/devices/run-device-test-card.tsx
  src/vertex/components/features/org-picker/organization-picker.tsx
  src/vertex/components/features/sites/sites-list-table.tsx
  src/vertex/components/shared/table/ReusableTable.tsx
  src/vertex/components/ui/combobox.tsx
  src/vertex/components/ui/command.tsx
  src/vertex/components/ui/multi-select.tsx
  src/vertex/components/ui/popover.tsx
  src/vertex/core/apis/cohorts.ts
  src/vertex/core/apis/devices.ts
  src/vertex/core/apis/sites.ts
  src/vertex/core/hooks/useCohorts.ts
  src/vertex/core/hooks/useDevices.ts
Labels: work in progress

#2893 move to production
  k8s/beacon/values-prod.yaml
  k8s/vertex/values-prod.yaml
  k8s/vertex/values-stage.yaml
  src/website2/.env.sample
  src/website2/next.config.mjs
  src/website2/package-lock.json
  src/website2/package.json
  src/website2/src/app/(about)/careers/[id]/page.tsx
  src/website2/src/app/MaintenancePage.tsx
  src/website2/src/app/api/proxy/route.ts
  src/website2/src/app/clean-air-forum/about/page.tsx
  src/website2/src/app/clean-air-forum/layout.tsx
  src/website2/src/app/layout.tsx
  src/website2/src/app/manifest.json
  src/website2/src/components/PerformanceMonitor.client.tsx
  src/website2/src/components/sections/footer/CountrySelectorDialog.tsx
  src/website2/src/components/ui/ErrorBoundary.tsx
  src/website2/src/components/ui/ForumLoading.tsx
  src/website2/src/components/ui/index.ts
  src/website2/src/context/ForumDataContext.tsx
  src/website2/src/hooks/swrConfig.ts
  src/website2/src/hooks/useApiHooks.tsx
  src/website2/src/lib/maintenance.ts
  src/website2/src/lib/metadata.ts
  src/website2/src/lib/performance-monitor.ts
  src/website2/src/lib/performance.tsx
  src/website2/src/services/apiService/index.tsx
  src/website2/src/services/externalService/index.tsx
  src/website2/src/utils/logger.ts
  src/website2/src/utils/quillUtils.ts
  src/website2/src/views/about/AboutPage.tsx
  src/website2/src/views/cleanairforum/BannerSection.tsx
  src/website2/src/views/cleanairforum/about/AboutPage.tsx
  src/website2/src/views/home/HomePage.tsx
Labels: ready for review

#2894 move to production
  src/mobile-v3/lib/src/app/auth/bloc/auth_state.dart
  src/mobile-v3/lib/src/app/auth/repository/auth_repository.dart
Labels: ready for review

#2898 Website: Docker workflow optimization and compression from 0.9GB to 303MB for faster builds below the 2GB memory increase
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  src/website2/.dockerignore
  src/website2/.env.sample
  src/website2/.gitignore
  src/website2/Dockerfile
  src/website2/README.md
  src/website2/docker-compose.yml
  src/website2/next.config.mjs
  src/website2/package-lock.json
  src/website2/package.json
  src/website2/public/assets/svgs/ImpactNumbers/Community.svg
  src/website2/public/assets/svgs/ImpactNumbers/Monitor.svg
  src/website2/public/assets/svgs/ImpactNumbers/Network.svg
  src/website2/public/assets/svgs/ImpactNumbers/Partners.svg
  src/website2/public/assets/svgs/ImpactNumbers/Publications.svg
  src/website2/public/assets/svgs/ImpactNumbers/Records.svg
  src/website2/src/app/api/geocode/route.ts
  src/website2/src/app/api/log/route.ts
  src/website2/src/app/api/proxy/route.ts
  src/website2/src/app/clean-air-forum/layout.tsx
  src/website2/src/app/clean-air-forum/speakers/page.tsx
  src/website2/src/components/layouts/Footer.tsx
  src/website2/src/components/sections/footer/CountrySelectorDialog.tsx
  src/website2/src/services/apiService/index.tsx
  src/website2/src/services/externalService/index.tsx
  src/website2/src/utils/logger.ts
  src/website2/src/views/cleanairforum/about/AboutPage.tsx
  src/website2/src/views/home/HomeStatsSection.tsx
  src/website2/src/views/home/data.ts
  src/website2/wait-for-it.sh
Labels: ready for review

#2900 website trigger
  src/website2/README.md
Labels: ready for review

#2904 Updated analytics login api, and response check
  src/platform/src/app/api/auth/[...nextauth]/options.js
  src/platform/src/core/urls/authentication.js
Labels: ready for review

#2905 move to production
  k8s/platform/values-stage.yaml
  src/platform/src/app/api/auth/[...nextauth]/options.js
  src/platform/src/core/urls/authentication.js
Labels: ready for review

#2913 fix: resolve mobile user registration API compatibility issues
  src/mobile-v3/.gitignore
  src/mobile-v3/lib/src/app/auth/pages/register_page.dart
  src/mobile-v3/lib/src/app/auth/repository/auth_repository.dart
Labels: mobile-app

#2923 chore: upgrade jwt-decode to version 4.0.0 and refactor imports
  src/platform/package.json
  src/platform/src/app/(individual)/user/(auth)/login/page.jsx
  src/platform/src/app/api/auth/[...nextauth]/options.js
  src/platform/src/app/api/auth/[...nextauth]/route.js
  src/platform/src/common/features/tours/utils/tourStorage.js
  src/platform/src/core/utils/googleLoginFromCookie.js
  src/platform/src/core/utils/optimizedApiClient.js
  src/platform/src/core/utils/proxyClient.js
  src/platform/src/lib/sessionWatcher.js
  src/platform/yarn.lock
Labels: ready for review

#2924 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/platform/package.json
  src/platform/src/app/(individual)/user/(auth)/login/page.jsx
  src/platform/src/app/api/auth/[...nextauth]/options.js
  src/platform/src/app/api/auth/[...nextauth]/route.js
  src/platform/src/common/features/tours/utils/tourStorage.js
  src/platform/src/core/utils/googleLoginFromCookie.js
  src/platform/src/core/utils/optimizedApiClient.js
  src/platform/src/core/utils/proxyClient.js
  src/platform/src/lib/sessionWatcher.js
  src/platform/yarn.lock
Labels: ready for review

#2925 Website: Add New Page (FAQs)
  src/website2/src/app/(about)/faqs/page.tsx
  src/website2/src/app/clean-air-forum/layout.tsx
  src/website2/src/app/layout.tsx
  src/website2/src/components/layouts/Navbar.tsx
  src/website2/src/components/ui/Accordion.tsx
  src/website2/src/hooks/useApiHooks.tsx
  src/website2/src/lib/metadata.ts
  src/website2/src/services/apiService/index.tsx
  src/website2/src/types/index.ts
  src/website2/src/utils/logger.ts
  src/website2/src/views/cleanairforum/about/AboutPage.tsx
  src/website2/src/views/faqs/FAQPage.tsx
  src/website2/src/views/faqs/index.ts
Labels: ready for review

#2926 move to production
  k8s/platform/values-prod.yaml
  src/mobile-v3/android/app/src/main/kotlin/com/airqo/airqo/MainActivity.kt
  src/mobile-v3/android/app/src/main/kotlin/com/airqo/app/MainActivity.kt
  src/mobile-v3/ios/Flutter/Debug.xcconfig
  src/mobile-v3/ios/Flutter/Release.xcconfig
  src/mobile-v3/ios/Runner.xcodeproj/project.pbxproj
  src/mobile-v3/ios/Runner/AppDelegate.swift
  src/mobile-v3/ios/Runner/Info.plist
  src/mobile-v3/lib/src/app/dashboard/pages/location_selection/components/location_list_view.dart
  src/mobile-v3/lib/src/app/dashboard/widgets/analytics_card.dart
  src/mobile-v3/test/app/dashboard/widgets/nearby_view_test.dart
  src/mobile-v3/test/widget_test.dart
  src/website2/src/app/(about)/faqs/page.tsx
  src/website2/src/app/clean-air-forum/layout.tsx
  src/website2/src/app/layout.tsx
  src/website2/src/components/layouts/Navbar.tsx
  src/website2/src/components/ui/Accordion.tsx
  src/website2/src/hooks/useApiHooks.tsx
  src/website2/src/lib/metadata.ts
  src/website2/src/services/apiService/index.tsx
  src/website2/src/types/index.ts
  src/website2/src/utils/logger.ts
  src/website2/src/views/cleanairforum/about/AboutPage.tsx
  src/website2/src/views/faqs/FAQPage.tsx
  src/website2/src/views/faqs/index.ts
Labels: ready for review

#2931 move to production
  src/platform/next.config.js
  src/platform/src/app/(individual)/user/(pages)/(layout-1)/Home/page.jsx
  src/platform/src/app/providers/UnifiedGroupProvider.jsx
  src/platform/src/common/features/airQuality-map/utils/mapConfig.js
  src/platform/src/common/features/video-players/Intro-video-modal.jsx
  src/platform/src/core/utils/secureApiProxyClient.js
Labels: ready for review

#2932 Update login logic, added organization display enhancements in vertex
  src/vertex/app/api/auth/[...nextauth]/options.ts
  src/vertex/app/login/page.tsx
  src/vertex/app/page.tsx
  src/vertex/app/providers.tsx
  src/vertex/components/features/devices/device-assignment-modal.tsx
  src/vertex/components/features/org-picker/organization-modal.tsx
  src/vertex/components/features/org-picker/organization-picker.tsx
  src/vertex/components/layout/layout.tsx
  src/vertex/components/layout/topbar.tsx
  src/vertex/components/shared/ErrorBoundary.tsx
  src/vertex/core/apis/axiosConfig.ts
  src/vertex/core/apis/users.ts
  src/vertex/core/auth/authProvider.tsx
  src/vertex/core/hooks/users.ts
  src/vertex/core/redux/slices/userSlice.ts
  src/vertex/core/utils/getApiErrorMessage.ts
  src/vertex/core/utils/secureApiProxyClient.ts
  src/vertex/core/utils/sessionManager.ts
  src/vertex/lib/envConstants.ts
  src/vertex/lib/utils.ts
  src/vertex/next.config.mjs
  src/vertex/package-lock.json
  src/vertex/package.json
Labels: ready for review

#2934 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  k8s/vertex/values-stage.yaml
  src/vertex/app/api/auth/[...nextauth]/options.ts
  src/vertex/app/login/page.tsx
  src/vertex/app/page.tsx
  src/vertex/app/providers.tsx
  src/vertex/components/features/devices/device-assignment-modal.tsx
  src/vertex/components/features/org-picker/organization-modal.tsx
  src/vertex/components/features/org-picker/organization-picker.tsx
  src/vertex/components/layout/layout.tsx
  src/vertex/components/layout/topbar.tsx
  src/vertex/components/shared/ErrorBoundary.tsx
  src/vertex/core/apis/axiosConfig.ts
  src/vertex/core/apis/users.ts
  src/vertex/core/auth/authProvider.tsx
  src/vertex/core/hooks/users.ts
  src/vertex/core/redux/slices/userSlice.ts
  src/vertex/core/utils/getApiErrorMessage.ts
  src/vertex/core/utils/secureApiProxyClient.ts
  src/vertex/core/utils/sessionManager.ts
  src/vertex/lib/envConstants.ts
  src/vertex/lib/utils.ts
  src/vertex/next.config.mjs
  src/vertex/package-lock.json
  src/vertex/package.json
Labels: ready for review

#2935 Enhance session loading experience in vertex
  src/vertex/app/(authenticated)/home/page.tsx
  src/vertex/app/login/page.tsx
  src/vertex/components/features/org-picker/organization-picker.tsx
  src/vertex/components/layout/secondary-sidebar.tsx
  src/vertex/components/layout/topbar.tsx
  src/vertex/core/auth/authProvider.tsx
  src/vertex/core/hooks/users.ts
  src/vertex/core/redux/slices/userSlice.ts
  src/vertex/core/utils/sessionManager.ts
Labels: ready for review

#2938 Analytics: Map redirect fix
  src/platform/src/core/HOC/withSessionAuth.js
  src/platform/src/core/hooks/useApiHooks.js
  src/platform/src/core/utils/loginSetup.js
  src/platform/src/core/utils/statusText.js
Labels: ready for review

#2939 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/platform/src/core/HOC/withSessionAuth.js
  src/platform/src/core/hooks/useApiHooks.js
  src/platform/src/core/utils/loginSetup.js
  src/platform/src/core/utils/statusText.js
Labels: ready for review

#2943 move to production
  k8s/vertex/values-prod.yaml
  k8s/vertex/values-stage.yaml
  src/vertex/app/(authenticated)/grids/page.tsx
  src/vertex/components/features/devices/device-list-table.tsx
  src/vertex/components/shared/table/ReusableTable.tsx
Labels: ready for review

#2953 Fix import error in analytics
  src/platform/src/app/api/auth/[...nextauth]/options.js
  src/platform/src/core/HOC/withSessionAuth.js
  src/platform/src/core/utils/googleLoginFromCookie.js
  src/platform/src/lib/sessionWatcher.js
Labels: ready for review

#2954 move to production
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  src/platform/src/app/api/auth/[...nextauth]/options.js
  src/platform/src/core/HOC/withSessionAuth.js
  src/platform/src/core/utils/googleLoginFromCookie.js
  src/platform/src/lib/sessionWatcher.js
Labels: ready for review

#2965 Added remove device from cohort, network status indicator, more enhancements in vertex
  src/vertex/app/(authenticated)/cohorts/[id]/page.tsx
  src/vertex/app/(authenticated)/cohorts/page.tsx
  src/vertex/app/(authenticated)/sites/[id]/page.tsx
  src/vertex/app/providers.tsx
  src/vertex/components/features/cohorts/assign-cohort-devices.tsx
  src/vertex/components/features/cohorts/assign-cohorts-to-group.tsx
  src/vertex/components/features/cohorts/cohort-detail-card.tsx
  src/vertex/components/features/cohorts/create-cohort.tsx
  src/vertex/components/features/cohorts/unassign-cohort-devices.tsx
  src/vertex/components/features/devices/client-paginated-devices-table.tsx
  src/vertex/components/features/devices/device-list-table.tsx
  src/vertex/components/features/devices/device-location-card.tsx
  src/vertex/components/features/devices/maintenance-status-card.tsx
  src/vertex/components/features/devices/utils/table-columns.tsx
  src/vertex/components/features/network-status-banner/index.tsx
  src/vertex/components/features/sites/client-paginated-sites-table.tsx
  src/vertex/components/features/sites/sites-list-table.tsx
  src/vertex/components/layout/secondary-sidebar.tsx
  src/vertex/components/shared/table/ReusableTable.tsx
  src/vertex/core/apis/cohorts.ts
  src/vertex/core/hooks/useCohorts.ts
  src/vertex/core/urls.tsx
  src/vertex/core/utils/proxyClient.ts
Labels: ready for review

#2966 move to production
  k8s/vertex/values-prod.yaml
  k8s/vertex/values-stage.yaml
  src/vertex/app/(authenticated)/cohorts/[id]/page.tsx
  src/vertex/app/(authenticated)/cohorts/page.tsx
  src/vertex/app/(authenticated)/sites/[id]/page.tsx
  src/vertex/app/providers.tsx
  src/vertex/components/features/cohorts/assign-cohort-devices.tsx
  src/vertex/components/features/cohorts/assign-cohorts-to-group.tsx
  src/vertex/components/features/cohorts/cohort-detail-card.tsx
  src/vertex/components/features/cohorts/create-cohort.tsx
  src/vertex/components/features/cohorts/unassign-cohort-devices.tsx
  src/vertex/components/features/devices/client-paginated-devices-table.tsx
  src/vertex/components/features/devices/device-list-table.tsx
  src/vertex/components/features/devices/device-location-card.tsx
  src/vertex/components/features/devices/maintenance-status-card.tsx
  src/vertex/components/features/devices/utils/table-columns.tsx
  src/vertex/components/features/network-status-banner/index.tsx
  src/vertex/components/features/sites/client-paginated-sites-table.tsx
  src/vertex/components/features/sites/sites-list-table.tsx
  src/vertex/components/layout/secondary-sidebar.tsx
  src/vertex/components/shared/table/ReusableTable.tsx
  src/vertex/core/apis/cohorts.ts
  src/vertex/core/hooks/useCohorts.ts
  src/vertex/core/urls.tsx
  src/vertex/core/utils/proxyClient.ts
Labels: ready for review
