Repository airqo-platform/AirQo-frontend, pull requests merged in 2025-02, with the labels that each got.

#2435 [Netmanager] Added serial number field to create device and soft create device, fix network bug
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/layouts/Main.js
Labels: ready for review

#2436 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/src/views/components/DataDisplay/Devices.js
  netmanager/src/views/layouts/Main.js
Labels: ready for review

#2437 Website: Clean Air Forum 2025
  website2/src/views/Forum/AboutPage.tsx
Labels: ready for review

#2438 Remove serial number field from create device
  netmanager/src/views/components/DataDisplay/Devices.js
Labels: ready for review

#2439 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  netmanager/src/views/components/DataDisplay/Devices.js
  website2/src/views/Forum/AboutPage.tsx
Labels: ready for review

#2440 website content update feedback
  website2/package-lock.json
  website2/package.json
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/app/clean-air-forum/layout.tsx
  website2/src/app/clean-air-forum/logistics/page.tsx
  website2/src/app/clean-air-forum/partners/page.tsx
  website2/src/app/clean-air-forum/program-committee/page.tsx
  website2/src/app/clean-air-forum/schedule/page.tsx
  website2/src/app/clean-air-forum/speakers/page.tsx
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/store/index.ts
  website2/src/store/slices/forumSlice.ts
  website2/src/views/Forum/AboutPage.tsx
  website2/src/views/Forum/TabNavigation.tsx
  website2/src/views/about/AboutPage.tsx
  website2/src/views/cleanairforum/PaginatedSection.tsx
Labels: ready for review

#2441 move to production
  k8s/netmanager/values-prod.yaml
  k8s/netmanager/values-stage.yaml
  website2/package-lock.json
  website2/package.json
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/app/clean-air-forum/layout.tsx
  website2/src/app/clean-air-forum/logistics/page.tsx
  website2/src/app/clean-air-forum/partners/page.tsx
  website2/src/app/clean-air-forum/program-committee/page.tsx
  website2/src/app/clean-air-forum/schedule/page.tsx
  website2/src/app/clean-air-forum/speakers/page.tsx
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/store/index.ts
  website2/src/store/slices/forumSlice.ts
  website2/src/views/Forum/AboutPage.tsx
  website2/src/views/Forum/TabNavigation.tsx
  website2/src/views/about/AboutPage.tsx
  website2/src/views/cleanairforum/PaginatedSection.tsx
Labels: ready for review

#2401 [Netmanager]: Profile Settings Page
  netmanager-app/app/(authenticated)/clients/page.tsx
  netmanager-app/app/(authenticated)/profile/page.tsx
  netmanager-app/app/types/clients.ts
  netmanager-app/components/Settings/ApiTokens.tsx
  netmanager-app/components/Settings/ClientTableRow.tsx
  netmanager-app/components/Settings/Clients.tsx
  netmanager-app/components/Settings/CreateClientForm.tsx
  netmanager-app/components/Settings/DialogWrapper.tsx
  netmanager-app/components/Settings/EditClientForm.tsx
  netmanager-app/components/Settings/MyProfile.tsx
  netmanager-app/components/Settings/PasswordEdit.tsx
  netmanager-app/components/Settings/ProfileTabs.tsx
  netmanager-app/components/sidebar.tsx
  netmanager-app/components/ui/progress.tsx
  netmanager-app/components/ui/textarea.tsx
  netmanager-app/components/ui/toast.tsx
  netmanager-app/components/ui/toaster.tsx
  netmanager-app/core/apis/cloudinary.ts
  netmanager-app/core/apis/settings.ts
  netmanager-app/core/hooks/useClients.ts
  netmanager-app/core/hooks/useUserClients.ts
  netmanager-app/core/redux/slices/clientsSlice.ts
  netmanager-app/core/redux/store.ts
  netmanager-app/hooks/use-toast.ts
  netmanager-app/package-lock.json
  netmanager-app/package.json
  netmanager-app/utils/countries.ts
  netmanager-app/utils/timezones.ts
Labels: ready for review, netmanager

#2442 Minor resource changes for Caliberate and docs
  k8s/calibrate/values-stage.yaml
  k8s/docs/values-stage.yaml
Labels: ready for review

#2443 move to production
  k8s/calibrate/values-stage.yaml
  k8s/docs/values-stage.yaml
  netmanager-app/app/(authenticated)/clients/page.tsx
  netmanager-app/app/(authenticated)/profile/page.tsx
  netmanager-app/app/types/clients.ts
  netmanager-app/components/Settings/ApiTokens.tsx
  netmanager-app/components/Settings/ClientTableRow.tsx
  netmanager-app/components/Settings/Clients.tsx
  netmanager-app/components/Settings/CreateClientForm.tsx
  netmanager-app/components/Settings/DialogWrapper.tsx
  netmanager-app/components/Settings/EditClientForm.tsx
  netmanager-app/components/Settings/MyProfile.tsx
  netmanager-app/components/Settings/PasswordEdit.tsx
  netmanager-app/components/Settings/ProfileTabs.tsx
  netmanager-app/components/sidebar.tsx
  netmanager-app/components/ui/progress.tsx
  netmanager-app/components/ui/textarea.tsx
  netmanager-app/components/ui/toast.tsx
  netmanager-app/components/ui/toaster.tsx
  netmanager-app/core/apis/cloudinary.ts
  netmanager-app/core/apis/settings.ts
  netmanager-app/core/hooks/useClients.ts
  netmanager-app/core/hooks/useUserClients.ts
  netmanager-app/core/redux/slices/clientsSlice.ts
  netmanager-app/core/redux/store.ts
  netmanager-app/hooks/use-toast.ts
  netmanager-app/package-lock.json
  netmanager-app/package.json
  netmanager-app/utils/countries.ts
  netmanager-app/utils/timezones.ts
Labels: ready for review

#2444 Link updates for clean air forum
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/views/cleanairforum/PaginatedSection.tsx
Labels: ready for review

#2445 move to production
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/views/cleanairforum/PaginatedSection.tsx
Labels: ready for review

#2447 [Netmanager]: Resolving some API issues in the profile setting Page
  netmanager-app/app/types/users.ts
  netmanager-app/components/Settings/ApiTokens.tsx
  netmanager-app/components/Settings/Clients.tsx
  netmanager-app/components/Settings/CreateClientForm.tsx
  netmanager-app/components/Settings/MyProfile.tsx
  netmanager-app/core/apis/settings.ts
  netmanager-app/core/hooks/useUserClients.ts
  netmanager-app/core/hooks/users.ts
  netmanager-app/core/redux/slices/clientsSlice.ts
Labels: ready for review, netmanager

#2448 move to production
  netmanager-app/app/types/users.ts
  netmanager-app/components/Settings/ApiTokens.tsx
  netmanager-app/components/Settings/Clients.tsx
  netmanager-app/components/Settings/CreateClientForm.tsx
  netmanager-app/components/Settings/MyProfile.tsx
  netmanager-app/core/apis/settings.ts
  netmanager-app/core/hooks/useUserClients.ts
  netmanager-app/core/hooks/users.ts
  netmanager-app/core/redux/slices/clientsSlice.ts
Labels: ready for review

#2449 [Analytics] Trigger New Build to update expired token >> Update README.md
  platform/README.md
Labels: ready for review

#2450 move to production
  platform/README.md
Labels: ready for review

#2418 [Netmanager] Grids UI functionality
  netmanager-app/.env.example
  netmanager-app/app/(authenticated)/cohorts/[id]/page.tsx
  netmanager-app/app/(authenticated)/cohorts/page.tsx
  netmanager-app/app/(authenticated)/devices/overview/page.tsx
  netmanager-app/app/(authenticated)/grids/[id]/page.tsx
  netmanager-app/app/(authenticated)/grids/page.tsx
  netmanager-app/app/(authenticated)/sites/create-site-form.tsx
  netmanager-app/app/types/grids.ts
  netmanager-app/components/Analytics/index.tsx
  netmanager-app/components/Settings/MyProfile.tsx
  netmanager-app/components/cohorts/assign-cohort-devices.tsx
  netmanager-app/components/cohorts/create-cohort.tsx
  netmanager-app/components/export-data/ExportForm.tsx
  netmanager-app/components/grids/create-grid.tsx
  netmanager-app/components/grids/date-range-picker.tsx
  netmanager-app/components/grids/grid-sites.tsx
  netmanager-app/components/grids/polymap.tsx
  netmanager-app/components/ui/textarea.tsx
  netmanager-app/core/apis/grids.ts
  netmanager-app/core/hooks/useDevices.ts
  netmanager-app/core/hooks/useGrids.ts
  netmanager-app/core/redux/slices/gridsSlice.ts
  netmanager-app/package-lock.json
  netmanager-app/package.json
Labels: ready for review

#2455 Move resource optimisation changes to production
  k8s/calibrate/values-prod.yaml
  k8s/docs/values-prod.yaml
  k8s/inventory/values-prod.yaml
  k8s/netmanager/values-prod.yaml
  k8s/platform/values-prod.yaml
  k8s/reports/values-prod.yaml
Labels: ready for review

#2457 move to production
  k8s/calibrate/values-prod.yaml
  k8s/docs/values-prod.yaml
  k8s/inventory/values-prod.yaml
  k8s/netmanager/values-prod.yaml
  k8s/platform/values-prod.yaml
  k8s/platform/values-stage.yaml
  k8s/reports/values-prod.yaml
  netmanager-app/.env.example
  netmanager-app/app/(authenticated)/cohorts/[id]/page.tsx
  netmanager-app/app/(authenticated)/cohorts/page.tsx
  netmanager-app/app/(authenticated)/devices/overview/page.tsx
  netmanager-app/app/(authenticated)/grids/[id]/page.tsx
  netmanager-app/app/(authenticated)/grids/page.tsx
  netmanager-app/app/(authenticated)/sites/create-site-form.tsx
  netmanager-app/app/types/grids.ts
  netmanager-app/components/Analytics/index.tsx
  netmanager-app/components/Settings/MyProfile.tsx
  netmanager-app/components/cohorts/assign-cohort-devices.tsx
  netmanager-app/components/cohorts/create-cohort.tsx
  netmanager-app/components/export-data/ExportForm.tsx
  netmanager-app/components/grids/create-grid.tsx
  netmanager-app/components/grids/date-range-picker.tsx
  netmanager-app/components/grids/grid-sites.tsx
  netmanager-app/components/grids/polymap.tsx
  netmanager-app/components/ui/textarea.tsx
  netmanager-app/core/apis/grids.ts
  netmanager-app/core/hooks/useDevices.ts
  netmanager-app/core/hooks/useGrids.ts
  netmanager-app/core/redux/slices/gridsSlice.ts
  netmanager-app/package-lock.json
  netmanager-app/package.json
Labels: ready for review

#2458 Website clean air Forum site
  website2/src/app/clean-air-forum/about/page.tsx
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/app/clean-air-forum/logistics/page.tsx
  website2/src/app/clean-air-forum/partners/page.tsx
  website2/src/app/clean-air-forum/program-committee/page.tsx
  website2/src/app/clean-air-forum/schedule/page.tsx
  website2/src/app/clean-air-forum/sessions/page.tsx
  website2/src/app/clean-air-forum/speakers/page.tsx
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/components/layouts/Navbar.tsx
  website2/src/store/slices/forumSlice.ts
  website2/src/views/Forum/SectionDisplay.tsx
  website2/src/views/Forum/TabNavigation.tsx
Labels: ready for review

#2460 updates UI website
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/app/clean-air-forum/logistics/page.tsx
  website2/src/app/clean-air-forum/partners/page.tsx
  website2/src/app/clean-air-forum/program-committee/page.tsx
  website2/src/app/clean-air-forum/sessions/page.tsx
  website2/src/app/clean-air-forum/speakers/page.tsx
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/utils/glossaryValidator.ts
  website2/src/utils/htmlValidator.ts
Labels: ready for review

#2461 move to production
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/app/clean-air-forum/logistics/page.tsx
  website2/src/app/clean-air-forum/partners/page.tsx
  website2/src/app/clean-air-forum/program-committee/page.tsx
  website2/src/app/clean-air-forum/sessions/page.tsx
  website2/src/app/clean-air-forum/speakers/page.tsx
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/utils/glossaryValidator.ts
  website2/src/utils/htmlValidator.ts
Labels: ready for review

#2463 Clean Air Forum Updates
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/views/Forum/SectionDisplay.tsx
Labels: ready for review

#2464 move to production
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/views/Forum/SectionDisplay.tsx
Labels: ready for review

#2462 [Netmanager-app] Deploy device UI
  netmanager-app/app/(authenticated)/devices/deploy/page.tsx
  netmanager-app/components/ui/checkbox.tsx
  netmanager-app/components/ui/stepper.tsx
  netmanager-app/package-lock.json
  netmanager-app/package.json
Labels: ready for review

#2465 move to production
  netmanager-app/app/(authenticated)/devices/deploy/page.tsx
  netmanager-app/components/ui/checkbox.tsx
  netmanager-app/components/ui/stepper.tsx
  netmanager-app/package-lock.json
  netmanager-app/package.json
Labels: ready for review

#2467 Website clean air Forum Updates
  website2/package-lock.json
  website2/package.json
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/app/clean-air-forum/logistics/page.tsx
  website2/src/app/clean-air-forum/partners/page.tsx
  website2/src/app/clean-air-forum/program-committee/page.tsx
  website2/src/app/clean-air-forum/resources/page.tsx
  website2/src/app/clean-air-forum/sessions/page.tsx
  website2/src/app/clean-air-forum/speakers/page.tsx
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/components/ui/MemberCard.tsx
  website2/src/views/Forum/AboutPage.tsx
  website2/src/views/Forum/SectionDisplay.tsx
  website2/src/views/Forum/TabNavigation.tsx
  website2/src/views/cleanairforum/PaginatedSection.tsx
  website2/src/views/cleanairforum/events/SingleEvent.tsx
  website2/src/views/events/SingleEvent.tsx
  website2/tailwind.config.ts
Labels: ready for review

#2468 move to production
  website2/package-lock.json
  website2/package.json
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/app/clean-air-forum/logistics/page.tsx
  website2/src/app/clean-air-forum/partners/page.tsx
  website2/src/app/clean-air-forum/program-committee/page.tsx
  website2/src/app/clean-air-forum/resources/page.tsx
  website2/src/app/clean-air-forum/sessions/page.tsx
  website2/src/app/clean-air-forum/speakers/page.tsx
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/components/ui/MemberCard.tsx
  website2/src/views/Forum/AboutPage.tsx
  website2/src/views/Forum/SectionDisplay.tsx
  website2/src/views/Forum/TabNavigation.tsx
  website2/src/views/cleanairforum/PaginatedSection.tsx
  website2/src/views/cleanairforum/events/SingleEvent.tsx
  website2/src/views/events/SingleEvent.tsx
  website2/tailwind.config.ts
Labels: ready for review

#2469 Fix: Broken URL link redirects
  website2/next.config.mjs
  website2/src/app/clean-air-forum/layout.tsx
  website2/src/views/Forum/BannerSection.tsx
Labels: ready for review

#2470 move to production
  website2/next.config.mjs
  website2/src/app/clean-air-forum/layout.tsx
  website2/src/views/Forum/BannerSection.tsx
Labels: ready for review

#2471 move to production
  mobile-v3/assets/images/shared/Frame 128.svg
  mobile-v3/lib/main.dart
  mobile-v3/lib/src/app/auth/bloc/auth_bloc.dart
  mobile-v3/lib/src/app/auth/bloc/auth_event.dart
  mobile-v3/lib/src/app/auth/repository/auth_repository.dart
  mobile-v3/lib/src/app/profile/pages/guest_profile page.dart
  mobile-v3/lib/src/app/shared/repository/hive_repository.dart
  mobile-v3/lib/src/meta/utils/colors.dart
Labels: ready for review

#2472 Fix: Clean air forum 2024
  website2/next.config.mjs
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/app/clean-air-forum/layout.tsx
  website2/src/app/clean-air-forum/logistics/page.tsx
  website2/src/app/clean-air-forum/partners/page.tsx
  website2/src/app/clean-air-forum/program-committee/page.tsx
  website2/src/app/clean-air-forum/resources/page.tsx
  website2/src/app/clean-air-forum/sessions/page.tsx
  website2/src/app/clean-air-forum/speakers/page.tsx
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/context/ForumDataContext.tsx
  website2/src/hooks/useApiHooks.tsx
  website2/src/services/apiService/index.tsx
  website2/src/store/slices/forumSlice.ts
  website2/src/types/forum.tsx
  website2/src/views/Forum/AboutPage.tsx
  website2/src/views/Forum/SectionDisplay.tsx
  website2/src/views/Forum/TabNavigation.tsx
Labels: ready for review

#2474 move to production
  website2/next.config.mjs
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/app/clean-air-forum/layout.tsx
  website2/src/app/clean-air-forum/logistics/page.tsx
  website2/src/app/clean-air-forum/partners/page.tsx
  website2/src/app/clean-air-forum/program-committee/page.tsx
  website2/src/app/clean-air-forum/resources/page.tsx
  website2/src/app/clean-air-forum/sessions/page.tsx
  website2/src/app/clean-air-forum/speakers/page.tsx
  website2/src/app/clean-air-forum/sponsorships/page.tsx
  website2/src/context/ForumDataContext.tsx
  website2/src/hooks/useApiHooks.tsx
  website2/src/services/apiService/index.tsx
  website2/src/store/slices/forumSlice.ts
  website2/src/types/forum.tsx
  website2/src/views/Forum/AboutPage.tsx
  website2/src/views/Forum/SectionDisplay.tsx
  website2/src/views/Forum/TabNavigation.tsx
Labels: ready for review

#2477 Website: Remove glossary duplicate data
  website2/src/app/clean-air-forum/glossary/page.tsx
Labels: ready for review

#2478 move to production
  website2/src/app/clean-air-forum/glossary/page.tsx
  website2/src/components/dialogs/EngagementDialog.tsx
Labels: ready for review

#2484 move to production
  mobile-v3/android/app/build.gradle
  mobile-v3/android/app/src/main/AndroidManifest.xml
  mobile-v3/lib/src/app/auth/bloc/auth_bloc.dart
  mobile-v3/lib/src/app/auth/bloc/auth_event.dart
  mobile-v3/lib/src/app/dashboard/pages/dashboard_page.dart
  mobile-v3/lib/src/app/learn/pages/lesson_finished.dart
  mobile-v3/lib/src/app/profile/pages/widgets/settings_widget.dart
Labels: ready for review

#2486 move to production
  mobile-v3/android/app/build.gradle
  mobile-v3/android/app/src/main/AndroidManifest.xml
Labels: ready for review

#2489 move to production
  mobile-v3/android/app/build.gradle
  mobile-v3/android/app/src/main/AndroidManifest.xml
  mobile-v3/android/local.defaults.properties
Labels: ready for review

#2493 move to production
  mobile-v3/.gitignore
  mobile-v3/.metadata
  mobile-v3/analysis_options.yaml
  mobile-v3/android/app/build.gradle.kts
  mobile-v3/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
  mobile-v3/android/app/src/main/kotlin/com/airqo/airqo/MainActivity.kt
  mobile-v3/android/gradle/wrapper/gradle-wrapper.jar
  mobile-v3/android/gradlew
  mobile-v3/android/gradlew.bat
  mobile-v3/android/settings.gradle.kts
  mobile-v3/ios/Flutter/Generated.xcconfig
  mobile-v3/ios/Flutter/flutter_export_environment.sh
  mobile-v3/ios/Podfile
  mobile-v3/ios/Podfile.lock
  mobile-v3/ios/Runner.xcodeproj/project.pbxproj
  mobile-v3/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  mobile-v3/ios/Runner/AppDelegate.swift
  mobile-v3/ios/Runner/Assets.xcassets/LaunchBackground.imageset/Contents.json
  mobile-v3/ios/Runner/Assets.xcassets/LaunchBackground.imageset/background.png
  mobile-v3/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json
  mobile-v3/ios/Runner/GeneratedPluginRegistrant.h
  mobile-v3/ios/Runner/GeneratedPluginRegistrant.m
  mobile-v3/ios/Runner/Info.plist
  mobile-v3/pubspec.lock
  mobile-v3/test/widget_test.dart
Labels: ready for review

#2495 (website2 deployment) Removed min - max instances on the .yml file
  .github/workflows/deploy-frontend-pr-previews.yml
Labels: ready for review

#2496 move to production
  .github/workflows/deploy-frontend-pr-previews.yml
Labels: ready for review

#2494 Website: Integrate Google Analytics and dynamic sitemap.xml setup
  website2/.env.sample
  website2/src/app/layout.tsx
  website2/src/app/robots.txt/route.ts
  website2/src/app/sitemap.xml/route.ts
  website2/src/components/GoogleAnalytics.tsx
  website2/src/components/layouts/NewsLetter.tsx
  website2/src/views/careers/CareerPage.tsx
  website2/src/views/solutions/AfricanCities/AfricanCities.tsx
  website2/src/views/solutions/communities/CommunityPage.tsx
Labels: ready for review

#2497 move to production
  website2/.env.sample
  website2/src/app/layout.tsx
  website2/src/app/robots.txt/route.ts
  website2/src/app/sitemap.xml/route.ts
  website2/src/components/GoogleAnalytics.tsx
  website2/src/components/layouts/NewsLetter.tsx
  website2/src/views/careers/CareerPage.tsx
  website2/src/views/solutions/AfricanCities/AfricanCities.tsx
  website2/src/views/solutions/communities/CommunityPage.tsx
Labels: ready for review

#2498 website: Included Lazy load on For GTag manager script
  website2/src/components/GoogleAnalytics.tsx
Labels: ready for review

#2499 move to production
  website2/src/components/GoogleAnalytics.tsx
Labels: ready for review

#2500 Website: Enhancements to the GA implementations
  website2/src/app/layout.tsx
  website2/src/components/GoogleAnalytics.tsx
  website2/src/components/layouts/Navbar.tsx
  website2/src/components/layouts/NotificationBanner.tsx
  website2/src/views/home/HomePlayerSection.tsx
Labels: ready for review

#2501 move to production
  website2/src/app/layout.tsx
  website2/src/components/GoogleAnalytics.tsx
  website2/src/components/layouts/Navbar.tsx
  website2/src/components/layouts/NotificationBanner.tsx
  website2/src/views/home/HomePlayerSection.tsx
Labels: ready for review

#2502 move to production
  mobile-v3/lib/main.dart
  mobile-v3/lib/src/app/auth/bloc/auth_bloc.dart
  mobile-v3/lib/src/app/dashboard/pages/dashboard_page.dart
Labels: ready for review

#2454 [Netmanager-App] Organization Settings Page
  netmanager-app/app/(authenticated)/layout.tsx
  netmanager-app/app/(authenticated)/organizations/[id]/page.tsx
  netmanager-app/app/(authenticated)/organizations/page.tsx
  netmanager-app/app/layout.tsx
  netmanager-app/app/types/groups.ts
  netmanager-app/app/types/roles.ts
  netmanager-app/components/Organization/List.tsx
  netmanager-app/components/Organization/create-group.tsx
  netmanager-app/components/Organization/organization-profile.tsx
  netmanager-app/components/Organization/organization-roles.tsx
  netmanager-app/components/Organization/team-members.tsx
  netmanager-app/components/Settings/ApiTokens.tsx
  netmanager-app/components/Settings/MyProfile.tsx
  netmanager-app/components/Settings/PasswordEdit.tsx
  netmanager-app/components/ui/switch.tsx
  netmanager-app/core/apis/organizations.ts
  netmanager-app/core/apis/permissions.ts
  netmanager-app/core/apis/roles.ts
  netmanager-app/core/hooks/useGroups.ts
  netmanager-app/core/hooks/useRoles.ts
  netmanager-app/core/hooks/useUserClients.ts
  netmanager-app/core/redux/slices/groupDetailsSlice.ts
  netmanager-app/core/redux/slices/groupsSlice.ts
  netmanager-app/core/redux/slices/rolesSlice.ts
  netmanager-app/core/redux/slices/teamSlice.ts
  netmanager-app/core/redux/store.ts
  netmanager-app/package-lock.json
  netmanager-app/package.json
Labels: ready for review, netmanager-app

#2475 Netmanager-app Sidebar Collapsible and Responsive for Mobile Devices
  netmanager-app/.gitignore
  netmanager-app/components/desktop-sidebar.tsx
  netmanager-app/components/layout.tsx
  netmanager-app/components/mobile-sidebar.tsx
  netmanager-app/components/sidebar.tsx
  netmanager-app/components/topbar.tsx
  netmanager-app/package-lock.json
  netmanager-app/package.json
  netmanager-app/public/images/airqo_logo.svg
Labels: ready for review

#2503 Fix Deployment Website
  .github/workflows/deploy-frontends-to-production.yml
Labels: ready for review

#2507 move to production
  .github/workflows/deploy-frontends-to-production.yml
Labels: ready for review

#2508 Website: Fix for styling issue
  website2/src/app/layout.tsx
  website2/src/components/GoogleAnalytics.tsx
  website2/src/components/layouts/Navbar.tsx
  website2/src/components/layouts/NotificationBanner.tsx
  website2/src/views/home/HomePlayerSection.tsx
Labels: ready for review

#2509 move to production
  website2/src/app/layout.tsx
  website2/src/components/GoogleAnalytics.tsx
  website2/src/components/layouts/Navbar.tsx
  website2/src/components/layouts/NotificationBanner.tsx
  website2/src/views/home/HomePlayerSection.tsx
Labels: ready for review

#2513 Fix deploy preview
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
Labels: ready for review

#2514 move to production
  .github/workflows/deploy-frontend-pr-previews.yml
  .github/workflows/deploy-frontends-to-production.yml
  .github/workflows/deploy-frontends-to-staging.yml
  k8s/calibrate/values-stage.yaml
  k8s/docs/values-stage.yaml
  k8s/inventory/values-stage.yaml
  k8s/netmanager/values-stage.yaml
  k8s/platform/values-stage.yaml
  k8s/reports/values-stage.yaml
Labels: ready for review

#2515 move to production
  README.md
Labels: ready for review

#2512 Website: Resolved Change exclusions
  src/website2/README.md
  src/website2/src/app/robots.txt/route.ts
  src/website2/src/app/sitemap.xml/route.ts
  src/website2/src/components/GoogleAnalytics.tsx
Labels: ready for review

#2519 move to production
  src/website2/README.md
  src/website2/src/app/robots.txt/route.ts
  src/website2/src/app/sitemap.xml/route.ts
  src/website2/src/components/GoogleAnalytics.tsx
Labels: ready for review

#2520 [Analaytics] Organise files
  src/netmanager-app/app/(authenticated)/organizations/[id]/page.tsx
  src/netmanager-app/app/(authenticated)/organizations/page.tsx
  src/netmanager-app/public/images/airqo_logo.svg
Labels: ready for review

#2523 Update README.md
  README.md
Labels: ready for review

#2524 move to production
  README.md
Labels: ready for review

#2522 Website: updated readme and footer component
  src/website2/README.md
  src/website2/src/app/layout.tsx
  src/website2/src/components/GoogleAnalytics.tsx
  src/website2/src/components/sections/footer/CountrySelectorDialog.tsx
Labels: ready for review

#2528 Google analytics functionality for analytics platform
  src/platform/package.json
  src/platform/src/pages/Home/index.jsx
  src/platform/src/pages/account/login/index.jsx
  src/platform/yarn.lock
Labels: work in progress

#2530 Move redirect check to protected route file in analytics platform
  src/platform/src/core/utils/protectedRoute.js
  src/platform/src/pages/Home/index.jsx
Labels: ready for review

#2532 Undo file changes in analytics platform
  src/platform/src/core/utils/protectedRoute.js
  src/platform/src/pages/Home/index.jsx
  src/platform/src/pages/account/login/index.jsx
Labels: ready for review

#2529 [work in progress] move to production
  k8s/platform/values-stage.yaml
  src/platform/package.json
  src/platform/yarn.lock
Labels: ready for review

#2534 Website: Added More event triggers to website
  src/website2/src/components/dialogs/EngagementDialog.tsx
  src/website2/src/components/layouts/Navbar.tsx
  src/website2/src/components/layouts/NewsLetter.tsx
  src/website2/src/components/sections/footer/CountrySelectorDialog.tsx
  src/website2/src/views/home/HomePlayerSection.tsx
Labels: ready for review

#2535 move to production
  src/website2/src/components/dialogs/EngagementDialog.tsx
  src/website2/src/components/layouts/Navbar.tsx
  src/website2/src/components/layouts/NewsLetter.tsx
  src/website2/src/components/sections/footer/CountrySelectorDialog.tsx
  src/website2/src/views/home/HomePlayerSection.tsx
Labels: ready for review

#2536 website: Add GA tag to header for google search console indexing
  src/website2/src/app/layout.tsx
Labels: ready for review

#2537 move to production
  src/website2/src/app/layout.tsx
Labels: ready for review

#2542 move to production
  src/platform/src/pages/account/creation/index.jsx
Labels: ready for review
