Repository airqo-platform/AirQo-frontend, pull requests merged in 2025-07, with the labels that each got.

#2785 Airqo website
  src/website2/public/web-app-manifest-192x192.png
  src/website2/public/web-app-manifest-512x512.png
  src/website2/src/app/(about)/careers/[id]/page.tsx
  src/website2/src/app/(about)/careers/page.tsx
  src/website2/src/app/(about)/events/[id]/page.tsx
  src/website2/src/app/(about)/events/page.tsx
  src/website2/src/app/(about)/layout.tsx
  src/website2/src/app/(about)/press/page.tsx
  src/website2/src/app/(about)/resources/page.tsx
  src/website2/src/app/Logo.png
  src/website2/src/app/apple-icon.png
  src/website2/src/app/clean-air-forum/about/page.tsx
  src/website2/src/app/clean-air-forum/speakers/page.tsx
  src/website2/src/app/clean-air-network/about/page.tsx
  src/website2/src/app/contact/form/page.tsx
  src/website2/src/app/contact/page.tsx
  src/website2/src/app/contact/success/page.tsx
  src/website2/src/app/explore-data/page.tsx
  src/website2/src/app/favicon.ico
  src/website2/src/app/home/page.tsx
  src/website2/src/app/icon.png
  src/website2/src/app/icon.svg
  src/website2/src/app/layout.tsx
  src/website2/src/app/legal/privacy-policy/page.tsx
  src/website2/src/app/legal/terms-of-service/page.tsx
  src/website2/src/app/manifest.json
  src/website2/src/app/page.tsx
  src/website2/src/app/products/analytics/page.tsx
  src/website2/src/app/products/api/page.tsx
  src/website2/src/app/products/calibrate/page.tsx
  src/website2/src/app/products/mobile-app/page.tsx
  src/website2/src/app/solutions/african-cities/page.tsx
  src/website2/src/app/solutions/communities/page.tsx
  src/website2/src/app/solutions/research/page.tsx
  src/website2/src/components/layouts/MainLayout.tsx
  src/website2/src/components/layouts/NotificationBanner.tsx
  src/website2/src/components/sections/ReversibleContentSection.tsx
  src/website2/src/views/home/HomePage.tsx
Labels: ready for review

#2786 move to production
  src/website2/public/web-app-manifest-192x192.png
  src/website2/public/web-app-manifest-512x512.png
  src/website2/src/app/(about)/careers/[id]/page.tsx
  src/website2/src/app/(about)/careers/page.tsx
  src/website2/src/app/(about)/events/[id]/page.tsx
  src/website2/src/app/(about)/events/page.tsx
  src/website2/src/app/(about)/layout.tsx
  src/website2/src/app/(about)/press/page.tsx
  src/website2/src/app/(about)/resources/page.tsx
  src/website2/src/app/Logo.png
  src/website2/src/app/apple-icon.png
  src/website2/src/app/clean-air-forum/about/page.tsx
  src/website2/src/app/clean-air-forum/speakers/page.tsx
  src/website2/src/app/clean-air-network/about/page.tsx
  src/website2/src/app/contact/form/page.tsx
  src/website2/src/app/contact/page.tsx
  src/website2/src/app/contact/success/page.tsx
  src/website2/src/app/explore-data/page.tsx
  src/website2/src/app/favicon.ico
  src/website2/src/app/home/page.tsx
  src/website2/src/app/icon.png
  src/website2/src/app/icon.svg
  src/website2/src/app/layout.tsx
  src/website2/src/app/legal/privacy-policy/page.tsx
  src/website2/src/app/legal/terms-of-service/page.tsx
  src/website2/src/app/manifest.json
  src/website2/src/app/page.tsx
  src/website2/src/app/products/analytics/page.tsx
  src/website2/src/app/products/api/page.tsx
  src/website2/src/app/products/calibrate/page.tsx
  src/website2/src/app/products/mobile-app/page.tsx
  src/website2/src/app/solutions/african-cities/page.tsx
  src/website2/src/app/solutions/communities/page.tsx
  src/website2/src/app/solutions/research/page.tsx
  src/website2/src/components/layouts/MainLayout.tsx
  src/website2/src/components/layouts/NotificationBanner.tsx
  src/website2/src/components/sections/ReversibleContentSection.tsx
  src/website2/src/views/home/HomePage.tsx
Labels: ready for review

#2787 Update installation guide link in MonitorPage component
  src/website2/src/views/products/MonitorPage.tsx
Labels: ready for review

#2790 move to production
  src/mobile-v3/android/app/build.gradle
Labels: ready for review

#2792 move to production
  docs/AIRQO_ROLE-BASED_ACCESS_CONTROL.md
Labels: ready for review

#2795 Forgot password fixes
  src/mobile-v3/lib/src/app/auth/bloc/ForgotPasswordBloc/forgot_password_bloc.dart
  src/mobile-v3/lib/src/app/auth/bloc/ForgotPasswordBloc/forgot_password_state.dart
  src/mobile-v3/lib/src/app/auth/pages/login_page.dart
  src/mobile-v3/lib/src/app/auth/pages/password_reset/forgot_password.dart
  src/mobile-v3/lib/src/app/auth/pages/password_reset/password_reset.dart
  src/mobile-v3/lib/src/app/auth/pages/password_reset/reset_link_sent.dart
  src/mobile-v3/lib/src/app/auth/pages/register_page.dart
  src/mobile-v3/lib/src/app/auth/repository/auth_repository.dart
  src/mobile-v3/lib/src/app/shared/widgets/form_field.dart
Labels: mobile-app

#2794 Analytics : Enhancements to codebase
  src/platform/public/icons/Errors/OopsIcon.jsx
  src/platform/src/app/(individual)/user/(pages)/(layout-1)/Home/page.jsx
  src/platform/src/app/(organization)/org/[org_slug]/(auth)/forgotPwd/page.jsx
  src/platform/src/app/(organization)/org/[org_slug]/(auth)/forgotPwd/reset/page.jsx
  src/platform/src/app/(organization)/org/[org_slug]/(auth)/login/page.jsx
  src/platform/src/app/(organization)/org/[org_slug]/(auth)/register/page.jsx
  src/platform/src/app/(organization)/org/[org_slug]/(pages)/(layout-1)/dashboard/page.jsx
  src/platform/src/app/(organization)/org/[org_slug]/(pages)/(layout-1)/members/page.jsx
  src/platform/src/app/(organization)/org/[org_slug]/(pages)/(layout-1)/settings/page.jsx
  src/platform/src/app/create-organization/layout.jsx
  src/platform/src/app/create-organization/page.jsx
  src/platform/src/app/not-found.jsx
  src/platform/src/app/permission-denied/page.jsx
  src/platform/src/common/components/Button/CustomDropdown.jsx
  src/platform/src/common/components/Button/index.jsx
  src/platform/src/common/components/PermissionDenied/index.jsx
  src/platform/src/common/components/Skeleton/DashboardPageSkeleton.jsx
  src/platform/src/common/features/Checklist/components/Checklist.js
  src/platform/src/common/features/airQuality-charts/ChartContainer.jsx
  src/platform/src/common/features/create-organization/components/CreateOrganizationForm.jsx
  src/platform/src/common/features/user-settings/tabs/Password.jsx
  src/platform/src/common/features/user-settings/tabs/Profile.jsx
  src/platform/src/common/layouts/GlobalTopbar/index.jsx
  src/platform/src/common/layouts/SideBar/UnifiedSideBarDrawer.jsx
  src/platform/src/common/layouts/pages/MapLayout.jsx
  src/platform/src/common/layouts/pages/UnifiedPagesLayout.jsx
  src/platform/src/core/HOC/LogoutUser.jsx
Labels: enhancement, ready for review

#2797 Downgrade react and react dom version in beacon
  src/beacon/README.md
  src/beacon/app/layout.tsx
  src/beacon/app/login/page.tsx
  src/beacon/middleware.ts
  src/beacon/next.config.mjs
  src/beacon/package-lock.json
  src/beacon/package.json
  src/beacon/public/icons/airqo_logo.svg
  src/beacon/public/icons/favicon-16x16.png
  src/beacon/public/icons/favicon-32x32.png
  src/beacon/public/icons/favicon.ico
  src/beacon/public/placeholder-logo.png
  src/beacon/public/placeholder-logo.svg
  src/beacon/public/placeholder-user.jpg
  src/beacon/public/placeholder.jpg
  src/beacon/public/placeholder.svg
Labels: ready for review

#2805 Analytics: User Feedback Fixes
  src/platform/src/app/(individual)/user/(auth)/creation/individual/register/page.jsx
  src/platform/src/app/admin/layout.jsx
  src/platform/src/app/create-organization/layout.jsx
  src/platform/src/app/providers/UnifiedGroupProvider.jsx
  src/platform/src/common/components/Calendar/components/CalendarHeader.jsx
  src/platform/src/common/components/CardWrapper/index.jsx
  src/platform/src/common/components/Organization/OrganizationSwitchLoader.jsx
  src/platform/src/common/components/Skeleton/HomeSkeleton.jsx
  src/platform/src/common/components/Table/ReusableTable.jsx
  src/platform/src/common/components/Toast/CustomToast.jsx
  src/platform/src/common/features/Checklist/components/Checklist.js
  src/platform/src/common/features/Checklist/components/ChecklistSkeleton.js
  src/platform/src/common/features/airQuality-cards/index.jsx
  src/platform/src/common/features/airQuality-charts/ChartContainer/index.jsx
  src/platform/src/common/features/analytics-overview/components/AnalyticsChartsGrid.jsx
  src/platform/src/common/features/analytics-overview/components/AnalyticsControls.jsx
  src/platform/src/common/features/download-insights-locations/components/DataTable.jsx
  src/platform/src/common/features/download-insights-locations/components/TopBarSearch.jsx
  src/platform/src/common/layouts/GlobalTopbar/index.jsx
  src/platform/src/common/layouts/SideBar/AuthenticatedSidebar.jsx
  src/platform/src/common/layouts/SideBar/UnifiedSideBarDrawer.jsx
  src/platform/src/common/layouts/SideBar/sidebarConfig.js
  src/platform/src/common/layouts/components/MobileBottomNavigation.jsx
  src/platform/src/common/layouts/components/TopbarOrganizationDropdown/OrganizationSelectModal.jsx
  src/platform/src/common/layouts/pages/MapLayout.jsx
  src/platform/src/common/layouts/pages/UnifiedPagesLayout.jsx
Labels: ready for review

#2809 Hotfix netmanager permissions
  src/netmanager/src/components/PermissionGuard/PermissionGuard.jsx
  src/netmanager/src/components/PermissionGuard/index.js
  src/netmanager/src/constants/permissions.js
  src/netmanager/src/utils/customHooks/usePermissions.js
  src/netmanager/src/utils/permissions.js
  src/netmanager/src/views/containers/PageAccess.js
  src/netmanager/src/views/layouts/common/Sidebar/Sidebar.js
Labels: ready for review

#2811 Added assign device to group modal and enhance error message display in netmanager
  src/netmanager/src/config/urls/analytics.js
  src/netmanager/src/config/urls/deviceRegistry.js
  src/netmanager/src/redux/DeviceRegistry/actions.js
  src/netmanager/src/redux/DeviceRegistry/operations.js
  src/netmanager/src/redux/DeviceRegistry/reducers/device.js
  src/netmanager/src/views/apis/analytics.js
  src/netmanager/src/views/apis/deviceRegistry.js
  src/netmanager/src/views/components/DataDisplay/DeviceView/AssignGroupModal.js
  src/netmanager/src/views/components/DataDisplay/DeviceView/DeviceEdit.js
  src/netmanager/src/views/components/Sites/SiteView.js
  src/netmanager/src/views/components/Sites/SitesTable.js
Labels: ready for review

#2815 Analytics: Added CHANGELOGs, Fix for all frontend notifs errors and download limit notice added
  src/platform/CHANGELOG.md
  src/platform/package.json
  src/platform/src/app/providers/ClientProviders.jsx
  src/platform/src/app/providers/UnifiedGroupProvider.jsx
  src/platform/src/common/features/airQuality-map/components/AirQoMap.jsx
  src/platform/src/common/features/airQuality-map/components/LayerModal.js
  src/platform/src/common/features/airQuality-map/constants/mapConstants.js
  src/platform/src/common/features/airQuality-map/hooks/useMapData.jsx
  src/platform/src/common/features/download-insights-locations/data-download/DataDownload.jsx
  src/platform/src/common/features/download-insights-locations/data-download/components/SettingsSidebar.js
  src/platform/src/core/utils/loginSetup.js
Labels: ready for review
